SUBROUTINE VERDER_SINGLEBLOCK (KPROMA, KST, KEND, KLEVIN, KLEVOUT, PDERI, PIN, POUT, LDACC)

IMPLICIT NONE

INTEGER, PARAMETER :: JPIM = 4, JPRB = 8, JPRD = 8

INTEGER (KIND=JPIM), INTENT (IN)::KPROMA
INTEGER (KIND=JPIM), INTENT (IN)::KLEVIN
INTEGER (KIND=JPIM), INTENT (IN)::KLEVOUT
INTEGER (KIND=JPIM), INTENT (IN)::KST
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRD), INTENT (IN)::PDERI (KLEVOUT, KLEVIN)
REAL (KIND=JPRB), INTENT (IN), TARGET::PIN (KPROMA, KLEVIN)
REAL (KIND=JPRB), INTENT (OUT), TARGET::POUT (KPROMA, KLEVOUT)
LOGICAL, INTENT (IN) :: LDACC
LOGICAL, PARAMETER::LLDOUBLE=JPRB==JPRD
INTEGER (KIND=JPIM)::JLEVOUT
INTEGER (KIND=JPIM)::JLEVIN
INTEGER (KIND=JPIM)::JROF
INTEGER (KIND=JPIM)::JLEV
REAL (KIND=JPRD), POINTER::ZIN (:,:)
REAL (KIND=JPRD), POINTER::ZOUT (:,:)
REAL (KIND=JPRD), TARGET::ZIN0 (KPROMA, MERGE (KLEVIN, 0,.NOT.LLDOUBLE))
REAL (KIND=JPRD), TARGET::ZOUT0 (KPROMA, MERGE (KLEVOUT, 0,.NOT.LLDOUBLE))

!$OMP TARGET DATA  &
!$OMP&MAP(ALLOC:ZIN0, ZOUT0) &
!$OMP&IF (LDACC) &
!$OMP&MAP(PRESENT:PIN, POUT) 

IF (LLDOUBLE) THEN
ELSE

  ZIN=>ZIN0
  ZOUT=>ZOUT0
  
  !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO SIMD &
  !$OMP&IF (LDACC) &
  !$OMP&MAP(PRESENT:ZIN) &
  !$OMP&PRIVATE (JLEV, JROF) 

  DO JROF = KST, KEND
    DO JLEV=1, KLEVIN
      ZIN (JROF, JLEV)=REAL (PIN (JROF, JLEV), KIND=JPRD)
    ENDDO
  ENDDO

ENDIF

!$OMP END TARGET DATA

END SUBROUTINE VERDER_SINGLEBLOCK
