SUBROUTINE CPTEND_NEW_MANYBLOCKS (YDCST, YDMODEL, KLON, KIDIA, KFDIA, KFLEV, PGNORDL, PGNORDM,&
& PDIFCQ, PDIFCQI, PDIFCQL, PDIFCS, PDIFEXT, PDIFTQ, PDIFTQI, PDIFTQL, PDIFTS, PFCCQL, PFCCQN,&
& PFCSQL, PFCSQN, PFPLSL, PFPLSN, PFPLSG, PFPLCL, PFPLCN, PFPLCG, PFESL, PFESN, PFESG, PFECL, PFECN&
&, PFECG, PFASL, PFASN, PFASG, PFACL, PFACN, PFCQLNG, PFCQING, PFCQRNG, PFCQSNG, PFCQGNG, PFCQNG&
&, PFRMH, PFRMQ, PFCHQ, PFRSO, PFRTH, PSTRCU, PSTRCV, PSTRDU, PSTRDV, PSTRTU, PSTRTV, PSTRMU, PSTRMV&
&, PDIFCQLC, PDIFCQIC, PFIMCC, PFEDQLC, PFEDQIC, PFEDQRC, PFEDQSC, PFCNEGQLC, PFCNEGQIC, PFCNEGQRC&
&, PFCNEGQSC, PFTKE, PFTKEI, PFEFB1, PFEFB2, PFEFB3, PDELP, PRDELP, PAPHIF, PCP, PU, PV, PT, PQ&
&, PQI, PQL, PQLCONV, PQICONV, PQRCONV, PQSCONV, PQR, PQS, PQG, PCPS, PTS, PFHSCL, PFHSCN, PFHSSL&
&, PFHSSN, PFHSSG, PFHPCL, PFHPCN, PFHPCG, PFHPSL, PFHPSN, PFHPSG, PFHP, PFP, PFEPFP, PFCMPCQ,&
& PFCMPSN, PFCMPSL, PTENDU, PTENDV, PTENDU_ZDEC, PTENDV_ZDEC, PTENDH, PTENDQ, PTENDQI, PTENDQL&
&, PTENDQLCONV, PTENDQICONV, PTENDQRCONV, PTENDQSCONV, PTENDQR, PTENDQS, PTENDQG, PTENDTKE, PTENDEFB1&
&, PTENDEFB2, PTENDEFB3, PTENDEXT, LDACC, KGPBLKS)
USE TYPE_MODEL,ONLY:MODEL
USE PARKIND1,ONLY:JPIM, JPRB, JPRD
USE YOMCST,ONLY:TCST

IMPLICIT NONE



TYPE (TCST), INTENT (IN)::YDCST
TYPE (MODEL), INTENT (IN)::YDMODEL
INTEGER (KIND=JPIM), INTENT (IN)::KLON
INTEGER (KIND=JPIM), INTENT (IN)::KIDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFDIA
INTEGER (KIND=JPIM), INTENT (IN)::KFLEV
REAL (KIND=JPRB), INTENT (IN)::PGNORDL (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PGNORDM (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQ (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQI (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCS (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFEXT (:, 0:, 1:, :) ! (KLON, 0:KFLEV, 1:YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQ (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQI (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTQL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFTS (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCCQL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCCQN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCSQL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCSQN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLSL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLSN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLSG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLCL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLCN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFPLCG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFESL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFESN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFESG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFECG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFASL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFASN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFASG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFACL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFACN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCQLNG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCQING (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCQRNG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCQSNG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCQGNG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCQNG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFRMH (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFRMQ (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCHQ (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFRSO (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFRTH (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRCU (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRCV (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRDU (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRDV (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRTU (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRTV (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRMU (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PSTRMV (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQLC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDIFCQIC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFIMCC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEDQLC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEDQIC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEDQRC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEDQSC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCNEGQLC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCNEGQIC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCNEGQRC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFCNEGQSC (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFTKE (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFTKEI (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEFB1 (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEFB2 (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PFEFB3 (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PDELP (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PRDELP (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PAPHIF (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PCP (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PU (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PT (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQ (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQI (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQL (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQLCONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQICONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQRCONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQSCONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQR (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQS (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PQG (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (IN)::PCPS (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (IN)::PTS (:, :) ! (KLON)
REAL (KIND=JPRB), INTENT (OUT)::PFHSCL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHSCN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHSSL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHSSN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHSSG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHPCL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHPCN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHPCG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHPSL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHPSN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHPSG (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFHP (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFP (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFEPFP (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFCMPCQ (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFCMPSN (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PFCMPSL (:, 0:, :) ! (KLON, 0:KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDU (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDU_ZDEC (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDV_ZDEC (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDH (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQ (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQI (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQL (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQLCONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQICONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQRCONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQSCONV (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQR (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQS (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDQG (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDTKE (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDEFB1 (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDEFB2 (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDEFB3 (:, :, :) ! (KLON, KFLEV)
REAL (KIND=JPRB), INTENT (OUT)::PTENDEXT (:, :, :, :) ! (KLON, KFLEV, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT)
INTEGER, INTENT (IN) :: KGPBLKS
LOGICAL, INTENT (IN) :: LDACC
REAL (KIND=JPRB)::ZGSDP (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZJTOT (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFHSENS (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFHDPSFI (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZTI (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQH (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQLH (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQIH (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQRH (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQSH (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQGH (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZCHAT (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZLIFT (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPL (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPN (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPLSL (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPLSN (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPLSG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPLCL (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPLCN (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFPLCG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZFHIMCC (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZTMPVAR (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZTMPFLUX (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZSTTVG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZSTTUG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZSTCVG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZSTCUG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZSTDVG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZSTDUG (KLON, 0:KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZTNDKKD (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZTNDKKC (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZKENE (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZTNDKKT (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZVMGEO (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZUZGEO (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQ2 (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZQ1 (KLON, KFLEV,KGPBLKS)
REAL (KIND=JPRB)::ZCPH
INTEGER (KIND=JPIM)::JGFL
INTEGER (KIND=JPIM)::JLON
INTEGER (KIND=JPIM)::JLEV
LOGICAL::LLDPSFI
#include "fcttrm.func.h"
INTEGER :: JBLK

!$OMP TARGET DATA  &
!$OMP&MAP(ALLOC:ZCHAT, ZFHDPSFI, ZFHIMCC, ZFHSENS, ZFPG, ZFPL, ZFPLCG, ZFPLCL, ZFPLCN, &
!$OMP&        ZFPLSG, ZFPLSL, ZFPLSN, ZFPN, ZGSDP, ZJTOT, ZKENE, ZLIFT, ZQ1, ZQ2, ZQGH, &
!$OMP&        ZQH, ZQIH, ZQLH, ZQRH, ZQSH, ZSTCUG, ZSTCVG, ZSTDUG, ZSTDVG, ZSTTUG, ZSTTVG, &
!$OMP&        ZTI, ZTMPFLUX, ZTMPVAR, ZTNDKKC, ZTNDKKD, ZTNDKKT, ZUZGEO, ZVMGEO) &
!$OMP&IF (LDACC) &
!$OMP&MAP(PRESENT:PAPHIF, PCP, PCPS, PDELP, PDIFCQ, PDIFCQI, PDIFCQIC, PDIFCQL, PDIFCQLC, &
!$OMP&         PDIFCS, PDIFEXT, PDIFTQ, PDIFTQI, PDIFTQL, PDIFTS, PFACL, PFACN, PFASG, &
!$OMP&         PFASL, PFASN, PFCCQL, PFCCQN, PFCHQ, PFCMPCQ, PFCMPSL, PFCMPSN, PFCNEGQIC, &
!$OMP&         PFCNEGQLC, PFCNEGQRC, PFCNEGQSC, PFCQGNG, PFCQING, PFCQLNG, PFCQNG, &
!$OMP&         PFCQRNG, PFCQSNG, PFCSQL, PFCSQN, PFECG, PFECL, PFECN, PFEDQIC, PFEDQLC, &
!$OMP&         PFEDQRC, PFEDQSC, PFEFB1, PFEFB2, PFEFB3, PFEPFP, PFESG, PFESL, PFESN, &
!$OMP&         PFHP, PFHPCG, PFHPCL, PFHPCN, PFHPSG, PFHPSL, PFHPSN, PFHSCL, PFHSCN, &
!$OMP&         PFHSSG, PFHSSL, PFHSSN, PFIMCC, PFP, PFPLCG, PFPLCL, PFPLCN, PFPLSG, &
!$OMP&         PFPLSL, PFPLSN, PFRMH, PFRMQ, PFRSO, PFRTH, PFTKE, PFTKEI, PGNORDL, PGNORDM, &
!$OMP&         PQ, PQG, PQI, PQICONV, PQL, PQLCONV, PQR, PQRCONV, PQS, PQSCONV, PRDELP, &
!$OMP&         PSTRCU, PSTRCV, PSTRDU, PSTRDV, PSTRMU, PSTRMV, PSTRTU, PSTRTV, PT, PTENDEFB1, &
!$OMP&         PTENDEFB2, PTENDEFB3, PTENDEXT, PTENDH, PTENDQ, PTENDQG, PTENDQI, &
!$OMP&         PTENDQICONV, PTENDQL, PTENDQLCONV, PTENDQR, PTENDQRCONV, PTENDQS, &
!$OMP&         PTENDQSCONV, PTENDTKE, PTENDU, PTENDU_ZDEC, PTENDV, PTENDV_ZDEC, &
!$OMP&         PTS, PU, PV, YDCST, YDMODEL) 

LLDPSFI=(YDMODEL%YRML_PHY_MF%YRPHY%NDPSFI==1)

!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&IF (LDACC) &
!$OMP&PRIVATE (JBLK) &
!$OMP&THREAD_LIMIT (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD &
  !$OMP&PRIVATE (JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
    ZLIFT(JLON,:, JBLK)=0.0_JPRB
    ZCHAT(JLON,:, JBLK)=0.0_JPRB
  ENDDO

ENDDO



IF (YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
      
      ZFHIMCC (JLON, 0, JBLK)=0._JPRB

      

      DO JLEV=1, KFLEV
        
        ZFHIMCC (JLON, JLEV, JBLK)=ZFHIMCC (JLON, JLEV-1, JBLK)+(PFIMCC (JLON, JLEV&
        &, JBLK)-PFIMCC (JLON, JLEV-1, JBLK))*(YDCST%RLVZER-YDCST%RLSZER)
      
      ENDDO

    ENDDO

  ENDDO

  
ELSE
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
      ZFHIMCC (JLON,:, JBLK)=0._JPRB
    ENDDO

  ENDDO

ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%LPHSPSH) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
      
      ZTI (JLON, 0, JBLK)=PT (JLON, 1, JBLK)
      ZTI (JLON, KFLEV, JBLK)=PT (JLON, KFLEV, JBLK)
    
    ENDDO

  ENDDO

ELSE
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
      
      ZTI (JLON, 0, JBLK)=PT (JLON, 1, JBLK)
      ZTI (JLON, KFLEV, JBLK)=PTS (JLON, JBLK)
    
    ENDDO

  ENDDO

ENDIF


!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&IF (LDACC) &
!$OMP&PRIVATE (JBLK) &
!$OMP&THREAD_LIMIT (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD &
  !$OMP&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=1, KFLEV-1
      
      ZTI (JLON, JLEV, JBLK)=(PT (JLON, JLEV, JBLK)+PT (JLON, JLEV+1, JBLK))*0.5_JPRB
    
    ENDDO

  ENDDO

ENDDO


IF (LLDPSFI) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
      
      ZQH (JLON, 0, JBLK)=0.0_JPRB
      ZQLH (JLON, 0, JBLK)=0.0_JPRB
      ZQIH (JLON, 0, JBLK)=0.0_JPRB
      ZQRH (JLON, 0, JBLK)=0.0_JPRB
      ZQSH (JLON, 0, JBLK)=0.0_JPRB
      ZQH (JLON, KFLEV, JBLK)=PQ (JLON, KFLEV, JBLK)
      ZQLH (JLON, KFLEV, JBLK)=PQL (JLON, KFLEV, JBLK)
      ZQIH (JLON, KFLEV, JBLK)=PQI (JLON, KFLEV, JBLK)
      ZQRH (JLON, KFLEV, JBLK)=PQR (JLON, KFLEV, JBLK)
      ZQSH (JLON, KFLEV, JBLK)=PQS (JLON, KFLEV, JBLK)
    
    ENDDO

  ENDDO

  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV-1
        
        ZQH (JLON, JLEV, JBLK)=(PQ (JLON, JLEV, JBLK)+PQ (JLON, JLEV+1, JBLK))*0.5_JPRB
        ZQLH (JLON, JLEV, JBLK)=(PQL (JLON, JLEV, JBLK)+PQL (JLON, JLEV+1, JBLK))*0.5_JPRB
        ZQIH (JLON, JLEV, JBLK)=(PQI (JLON, JLEV, JBLK)+PQI (JLON, JLEV+1, JBLK))*0.5_JPRB
        ZQRH (JLON, JLEV, JBLK)=(PQR (JLON, JLEV, JBLK)+PQR (JLON, JLEV+1, JBLK))*0.5_JPRB
        ZQSH (JLON, JLEV, JBLK)=(PQS (JLON, JLEV, JBLK)+PQS (JLON, JLEV+1, JBLK))*0.5_JPRB
      
      ENDDO

    ENDDO

  ENDDO


  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
        
        ZQGH (JLON, 0, JBLK)=0.0_JPRB
        ZQGH (JLON, KFLEV, JBLK)=PQG (JLON, KFLEV, JBLK)

        

        DO JLEV=1, KFLEV-1
          
          ZQGH (JLON, JLEV, JBLK)=(PQG (JLON, JLEV, JBLK)+PQG (JLON, JLEV+1, JBLK))*0.5_JPRB
        
        ENDDO

      ENDDO

    ENDDO

  
  ENDIF

ENDIF


IF (LLDPSFI) THEN

  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON, ZCPH) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=0, KFLEV
          
          ZFPL (JLON, JLEV, JBLK)=(1.0_JPRB-ZQRH (JLON, JLEV, JBLK))*PFPLSL (JLON, JLEV, JBLK&
          &)-ZQRH (JLON, JLEV, JBLK)*(PFPLSN (JLON, JLEV, JBLK)+PFPLSG (JLON, JLEV, JBLK))
          ZFPN (JLON, JLEV, JBLK)=(1.0_JPRB-ZQSH (JLON, JLEV, JBLK))*PFPLSN (JLON, JLEV, JBLK&
          &)-ZQSH (JLON, JLEV, JBLK)*(PFPLSL (JLON, JLEV, JBLK)+PFPLSG (JLON, JLEV, JBLK))
          ZFPG (JLON, JLEV, JBLK)=(1.0_JPRB-ZQGH (JLON, JLEV, JBLK))*PFPLSG (JLON, JLEV, JBLK&
          &)-ZQGH (JLON, JLEV, JBLK)*(PFPLSL (JLON, JLEV, JBLK)+PFPLSN (JLON, JLEV, JBLK))
          ZFPLSL (JLON, JLEV, JBLK)=ZFPL (JLON, JLEV, JBLK)
          ZFPLSN (JLON, JLEV, JBLK)=ZFPN (JLON, JLEV, JBLK)
          ZFPLSG (JLON, JLEV, JBLK)=ZFPG (JLON, JLEV, JBLK)
          ZFPL (JLON, JLEV, JBLK)=(1.0_JPRB-ZQRH (JLON, JLEV, JBLK))*PFPLCL (JLON&
          &, JLEV, JBLK)-ZQRH (JLON, JLEV, JBLK)*(PFPLCN (JLON, JLEV, JBLK))
          ZFPN (JLON, JLEV, JBLK)=(1.0_JPRB-ZQSH (JLON, JLEV, JBLK))*PFPLCN (JLON&
          &, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK)*(PFPLCL (JLON, JLEV, JBLK))
          ZFPG (JLON, JLEV, JBLK)=(1.0_JPRB-ZQGH (JLON, JLEV, JBLK))*PFPLCG (JLON&
          &, JLEV, JBLK)-ZQGH (JLON, JLEV, JBLK)*(PFPLCG (JLON, JLEV, JBLK))
          ZFPLCL (JLON, JLEV, JBLK)=ZFPL (JLON, JLEV, JBLK)
          ZFPLCN (JLON, JLEV, JBLK)=ZFPN (JLON, JLEV, JBLK)
          ZFPLCG (JLON, JLEV, JBLK)=ZFPG (JLON, JLEV, JBLK)
          ZFPL (JLON, JLEV, JBLK)=ZFPLSL (JLON, JLEV, JBLK)+ZFPLCL (JLON, JLEV, JBLK)
          ZFPN (JLON, JLEV, JBLK)=ZFPLSN (JLON, JLEV, JBLK)+ZFPLCN (JLON, JLEV, JBLK)
          ZFPG (JLON, JLEV, JBLK)=ZFPLSG (JLON, JLEV, JBLK)+ZFPLCG (JLON, JLEV, JBLK)
          ZCPH=YDCST%RCPD+(YDCST%RCPV-YDCST%RCPD)*ZQH (JLON, JLEV, JBLK)+(YDCST%RCW-YDCST&
          &%RCPD)*(ZQLH (JLON, JLEV, JBLK)+ZQRH (JLON, JLEV, JBLK))+(YDCST%RCS-YDCST%RCPD&
          &)*(ZQIH (JLON, JLEV, JBLK)+ZQSH (JLON, JLEV, JBLK)+ZQGH (JLON, JLEV, JBLK))
          ZCHAT (JLON, JLEV, JBLK)=(ZCPH-YDCST%RCW*ZQRH (JLON, JLEV, JBLK)-YDCST%RCS&
          &*(ZQSH (JLON, JLEV, JBLK)+ZQGH (JLON, JLEV, JBLK)))/(1.0_JPRB-ZQRH (JLON&
          &, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK)-ZQGH (JLON, JLEV, JBLK))
          ZLIFT (JLON, JLEV, JBLK)=(ZFPL (JLON, JLEV, JBLK)+ZFPN (JLON, JLEV, JBLK)+ZFPG (JLON, JLEV, JBLK&
          &))/(1.0_JPRB-ZQRH (JLON, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK)-ZQGH (JLON, JLEV, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ELSE
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON, ZCPH) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=0, KFLEV
          
          ZFPL (JLON, JLEV, JBLK)=(1.0_JPRB-ZQRH (JLON, JLEV, JBLK))*PFPLSL (JLON&
          &, JLEV, JBLK)-ZQRH (JLON, JLEV, JBLK)*PFPLSN (JLON, JLEV, JBLK)
          ZFPN (JLON, JLEV, JBLK)=(1.0_JPRB-ZQSH (JLON, JLEV, JBLK))*PFPLSN (JLON&
          &, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK)*PFPLSL (JLON, JLEV, JBLK)
          ZFPLSL (JLON, JLEV, JBLK)=ZFPL (JLON, JLEV, JBLK)
          ZFPLSN (JLON, JLEV, JBLK)=ZFPN (JLON, JLEV, JBLK)
          ZFPL (JLON, JLEV, JBLK)=(1.0_JPRB-ZQRH (JLON, JLEV, JBLK))*PFPLCL (JLON&
          &, JLEV, JBLK)-ZQRH (JLON, JLEV, JBLK)*PFPLCN (JLON, JLEV, JBLK)
          ZFPN (JLON, JLEV, JBLK)=(1.0_JPRB-ZQSH (JLON, JLEV, JBLK))*PFPLCN (JLON&
          &, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK)*PFPLCL (JLON, JLEV, JBLK)
          ZFPLCL (JLON, JLEV, JBLK)=ZFPL (JLON, JLEV, JBLK)
          ZFPLCN (JLON, JLEV, JBLK)=ZFPN (JLON, JLEV, JBLK)
          ZFPL (JLON, JLEV, JBLK)=ZFPLSL (JLON, JLEV, JBLK)+ZFPLCL (JLON, JLEV, JBLK)
          ZFPN (JLON, JLEV, JBLK)=ZFPLSN (JLON, JLEV, JBLK)+ZFPLCN (JLON, JLEV, JBLK)
          ZCPH=YDCST%RCPD+(YDCST%RCPV-YDCST%RCPD)*ZQH (JLON, JLEV, JBLK)+(YDCST%RCW&
          &-YDCST%RCPD)*(ZQLH (JLON, JLEV, JBLK)+ZQRH (JLON, JLEV, JBLK))+(YDCST%RCS&
          &-YDCST%RCPD)*(ZQIH (JLON, JLEV, JBLK)+ZQSH (JLON, JLEV, JBLK))
          ZCHAT (JLON, JLEV, JBLK)=(ZCPH-YDCST%RCW*ZQRH (JLON, JLEV, JBLK)-YDCST%RCS*ZQSH (JLON&
          &, JLEV, JBLK))/(1.0_JPRB-ZQRH (JLON, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK))
          ZLIFT (JLON, JLEV, JBLK)=(ZFPL (JLON, JLEV, JBLK)+ZFPN (JLON, JLEV, JBLK&
          &))/(1.0_JPRB-ZQRH (JLON, JLEV, JBLK)-ZQSH (JLON, JLEV, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ELSE
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=0, KFLEV
        
        ZFPL (JLON, JLEV, JBLK)=PFPLSL (JLON, JLEV, JBLK)+PFPLCL (JLON, JLEV, JBLK)
        ZFPN (JLON, JLEV, JBLK)=PFPLSN (JLON, JLEV, JBLK)+PFPLCN (JLON, JLEV, JBLK)
      
      ENDDO

    ENDDO

  ENDDO


  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=0, KFLEV
          
          ZFPG (JLON, JLEV, JBLK)=PFPLSG (JLON, JLEV, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ENDIF


!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&IF (LDACC) &
!$OMP&PRIVATE (JBLK) &
!$OMP&THREAD_LIMIT (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD &
  !$OMP&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=0, KFLEV

      

      IF (LLDPSFI) THEN
        PFHSCL (JLON, JLEV, JBLK)=ZFPLCL (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*YDCST%RCW
        PFHSCN (JLON, JLEV, JBLK)=ZFPLCN (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*YDCST%RCS
        PFHSSL (JLON, JLEV, JBLK)=ZFPLSL (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*YDCST%RCW
        PFHSSN (JLON, JLEV, JBLK)=ZFPLSN (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*YDCST%RCS

        IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
          PFHSSG (JLON, JLEV, JBLK)=ZFPLSG (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*YDCST%RCS
        ELSE
          PFHSSG (JLON, JLEV, JBLK)=0._JPRB
        ENDIF

      ELSE
        PFHSCL (JLON, JLEV, JBLK)=PFPLCL (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*(YDCST%RCW-YDCST%RCPD)
        PFHSCN (JLON, JLEV, JBLK)=PFPLCN (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*(YDCST%RCS-YDCST%RCPD)
        PFHSSL (JLON, JLEV, JBLK)=PFPLSL (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*(YDCST%RCW-YDCST%RCPD)
        PFHSSN (JLON, JLEV, JBLK)=PFPLSN (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*(YDCST%RCS-YDCST%RCPD)

        IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
          PFHSSG (JLON, JLEV, JBLK)=PFPLSG (JLON, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*(YDCST%RCS-YDCST%RCPD)
        ELSE
          PFHSSG (JLON, JLEV, JBLK)=0._JPRB
        ENDIF

      ENDIF

      PFHPCL (JLON, JLEV, JBLK)=-YDCST%RLVZER*(PFCCQL (JLON, JLEV, JBLK)-PFECL (JLON, JLEV, JBLK))
      PFHPCN (JLON, JLEV, JBLK)=-YDCST%RLSZER*(PFCCQN (JLON, JLEV, JBLK)-PFECN (JLON, JLEV, JBLK))
      PFHPSL (JLON, JLEV, JBLK)=-YDCST%RLVZER*(PFCSQL (JLON, JLEV, JBLK)-PFESL (JLON, JLEV, JBLK))
      PFHPSN (JLON, JLEV, JBLK)=-YDCST%RLSZER*(PFCSQN (JLON, JLEV, JBLK)-PFESN (JLON, JLEV, JBLK))
      PFP (JLON, JLEV, JBLK)=ZFPL (JLON, JLEV, JBLK)+ZFPN (JLON, JLEV, JBLK)

      IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
        PFHPSG (JLON, JLEV, JBLK)=-YDCST%RLSZER*(-PFESG (JLON, JLEV, JBLK))
        PFHPCG (JLON, JLEV, JBLK)=-YDCST%RLSZER*(-PFECG (JLON, JLEV, JBLK))
        PFP (JLON, JLEV, JBLK)=PFP (JLON, JLEV, JBLK)+ZFPG (JLON, JLEV, JBLK)
      ELSE
        PFHPSG (JLON, JLEV, JBLK)=0._JPRB
        PFHPCG (JLON, JLEV, JBLK)=0._JPRB
      ENDIF

      PFEPFP (JLON, JLEV, JBLK)=-YDMODEL%YRML_PHY_MF%YRPHY%NDPSFI*ZCHAT (JLON&
      &, JLEV, JBLK)*ZTI (JLON, JLEV, JBLK)*PFP (JLON, JLEV, JBLK)
      PFHP (JLON, JLEV, JBLK)=PFHSCL (JLON, JLEV, JBLK)+PFHSCN (JLON, JLEV, JBLK)+PFHSSL (JLON&
      &, JLEV, JBLK)+PFHSSN (JLON, JLEV, JBLK)+PFHPCL (JLON, JLEV, JBLK)+PFHPCN (JLON, JLEV, JBLK&
      &)+PFHPSL (JLON, JLEV, JBLK)+PFHPSN (JLON, JLEV, JBLK)+PFEPFP (JLON, JLEV, JBLK)

      IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
        PFHP (JLON, JLEV, JBLK)=PFHP (JLON, JLEV, JBLK)+PFHSSG (JLON, JLEV&
        &, JBLK)+PFHPSG (JLON, JLEV, JBLK)+PFHPCG (JLON, JLEV, JBLK)
      ENDIF

    
    ENDDO

  ENDDO

ENDDO


!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&IF (LDACC) &
!$OMP&PRIVATE (JBLK) &
!$OMP&THREAD_LIMIT (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD &
  !$OMP&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=0, KFLEV
      
      ZJTOT (JLON, JLEV, JBLK)=PFRSO (JLON, JLEV, JBLK)+PFRTH (JLON, JLEV, JBLK)+PFRMH (JLON, JLEV, JBLK&
      &)+PDIFTS (JLON, JLEV, JBLK)+PDIFCS (JLON, JLEV, JBLK)+(YDCST%RCW-YDCST%RCPD)*ZFPL (JLON, JLEV&
      &, JBLK)*ZTI (JLON, JLEV, JBLK)+(YDCST%RCS-YDCST%RCPD)*ZFPN (JLON, JLEV, JBLK)*ZTI (JLON, JLEV&
      &, JBLK)-YDCST%RLVZER*(PFCCQL (JLON, JLEV, JBLK)+PFCSQL (JLON, JLEV, JBLK)-PFESL (JLON, JLEV, JBLK&
      &)-PFECL (JLON, JLEV, JBLK))-YDCST%RLSZER*(PFCCQN (JLON, JLEV, JBLK)+PFCSQN (JLON, JLEV, JBLK)&
      &-PFESN (JLON, JLEV, JBLK)-PFECN (JLON, JLEV, JBLK))+ZFHIMCC (JLON, JLEV, JBLK)
    
    ENDDO

  ENDDO

ENDDO


IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=0, KFLEV
        
        ZJTOT (JLON, JLEV, JBLK)=ZJTOT (JLON, JLEV, JBLK)+(YDCST%RCS-YDCST%RCPD)*ZFPG (JLON, JLEV, JBLK&
        &)*ZTI (JLON, JLEV, JBLK)+YDCST%RLSZER*(PFESG (JLON, JLEV, JBLK)+PFECG (JLON, JLEV, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (LLDPSFI) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=0, KFLEV
        
        ZFHDPSFI (JLON, JLEV, JBLK)=-(ZCHAT (JLON, JLEV, JBLK)-YDCST%RCPD)*ZTI &
        &(JLON, JLEV, JBLK)*(ZFPL (JLON, JLEV, JBLK)+ZFPN (JLON, JLEV, JBLK))

        IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
          ZFHDPSFI (JLON, JLEV, JBLK)=ZFHDPSFI (JLON, JLEV, JBLK)-(ZCHAT (JLON, JLEV&
          &, JBLK)-YDCST%RCPD)*ZTI (JLON, JLEV, JBLK)*ZFPG (JLON, JLEV, JBLK)
        ENDIF

        ZJTOT (JLON, JLEV, JBLK)=ZJTOT (JLON, JLEV, JBLK)+ZFHDPSFI (JLON, JLEV, JBLK)
      
      ENDDO

    ENDDO

  ENDDO

ELSE
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)
      ZFHDPSFI (JLON, 0:KFLEV, JBLK)=0.
    ENDDO

  ENDDO

ENDIF


!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&IF (LDACC) &
!$OMP&PRIVATE (JBLK) &
!$OMP&THREAD_LIMIT (KLON) 


DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD &
  !$OMP&PRIVATE (JLEV, JLON) 

  

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=1, KFLEV
      
      ZGSDP (JLON, JLEV, JBLK)=YDCST%RG*PRDELP (JLON, JLEV, JBLK)
      PTENDU (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PSTRCU (JLON, JLEV-1, JBLK)-PSTRCU (JLON,&
      & JLEV, JBLK))+(PSTRDU (JLON, JLEV-1, JBLK)-PSTRDU (JLON, JLEV, JBLK))+(PSTRMU (JLON, JLEV-1, JBLK&
      &)-PSTRMU (JLON, JLEV, JBLK))+(PSTRTU (JLON, JLEV-1, JBLK)-PSTRTU (JLON, JLEV, JBLK)))
      PTENDV (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PSTRCV (JLON, JLEV-1, JBLK)-PSTRCV (JLON,&
      & JLEV, JBLK))+(PSTRDV (JLON, JLEV-1, JBLK)-PSTRDV (JLON, JLEV, JBLK))+(PSTRMV (JLON, JLEV-1, JBLK&
      &)-PSTRMV (JLON, JLEV, JBLK))+(PSTRTV (JLON, JLEV-1, JBLK)-PSTRTV (JLON, JLEV, JBLK)))

      IF (YDMODEL%YRML_PHY_MF%YRPHY%LCVTDK) THEN
        PTENDU_ZDEC (JLON, JLEV, JBLK)=0.0_JPRB
        PTENDV_ZDEC (JLON, JLEV, JBLK)=0.0_JPRB
      ELSE
        PTENDU_ZDEC (JLON, JLEV, JBLK)=PTENDU (JLON, JLEV, JBLK)
        PTENDV_ZDEC (JLON, JLEV, JBLK)=PTENDV (JLON, JLEV, JBLK)
      ENDIF

      PTENDQ (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PDIFTQ (JLON, JLEV-1, JBLK)-PDIFTQ (JLON, JLEV&
      &, JBLK))+(PDIFCQ (JLON, JLEV-1, JBLK)-PDIFCQ (JLON, JLEV, JBLK))+(PFRMQ (JLON, JLEV-1, JBLK)-PFRMQ&
      & (JLON, JLEV, JBLK))+(PFCHQ (JLON, JLEV-1, JBLK)-PFCHQ (JLON, JLEV, JBLK))+(PFCCQL (JLON, JLEV-1,&
      & JBLK)-PFCCQL (JLON, JLEV, JBLK))+(PFCCQN (JLON, JLEV-1, JBLK)-PFCCQN (JLON, JLEV, JBLK))+(PFCSQL&
      & (JLON, JLEV-1, JBLK)-PFCSQL (JLON, JLEV, JBLK))+(PFCSQN (JLON, JLEV-1, JBLK)-PFCSQN (JLON, JLEV,&
      & JBLK))+(PFCQNG (JLON, JLEV-1, JBLK)-PFCQNG (JLON, JLEV, JBLK))-(PFECL (JLON, JLEV-1, JBLK)-PFECL&
      & (JLON, JLEV, JBLK))-(PFESL (JLON, JLEV-1, JBLK)-PFESL (JLON, JLEV, JBLK))-(PFECN (JLON, JLEV-1, JBLK&
      &)-PFECN (JLON, JLEV, JBLK))-(PFESN (JLON, JLEV-1, JBLK)-PFESN (JLON, JLEV, JBLK)))
      PTENDH (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(ZJTOT&
      & (JLON, JLEV-1, JBLK)-ZJTOT (JLON, JLEV, JBLK))
    
    ENDDO

  ENDDO

ENDDO


IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDQ (JLON, JLEV, JBLK)=PTENDQ (JLON, JLEV, JBLK)+ZGSDP (JLON, JLEV, JBLK)*(-(PFESG (JLON, JLEV&
        &-1, JBLK)-PFESG (JLON, JLEV, JBLK))-(PFECG (JLON, JLEV-1, JBLK)-PFECG (JLON, JLEV, JBLK)))
      
      ENDDO

    ENDDO

  ENDDO

ENDIF



IF (YDMODEL%YRML_PHY_MF%YRPHY%LCONDWT.AND..NOT.YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDQL (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PDIFTQL (JLON, JLEV-1, JBLK)-PDIFTQL &
        &(JLON, JLEV, JBLK))+(PDIFCQL (JLON, JLEV-1, JBLK)-PDIFCQL (JLON, JLEV, JBLK))+(PFCQLNG (JLON&
        &, JLEV-1, JBLK)-PFCQLNG (JLON, JLEV, JBLK))+(PFACL (JLON, JLEV-1, JBLK)-PFACL (JLON, JLEV,&
        & JBLK))+(PFASL (JLON, JLEV-1, JBLK)-PFASL (JLON, JLEV, JBLK))-(PFCSQL (JLON, JLEV-1, JBLK)&
        &-PFCSQL (JLON, JLEV, JBLK))-(PFCCQL (JLON, JLEV-1, JBLK)-PFCCQL (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQI (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PDIFTQI (JLON, JLEV-1, JBLK)-PDIFTQI &
        &(JLON, JLEV, JBLK))+(PDIFCQI (JLON, JLEV-1, JBLK)-PDIFCQI (JLON, JLEV, JBLK))+(PFCQING (JLON&
        &, JLEV-1, JBLK)-PFCQING (JLON, JLEV, JBLK))+(PFACN (JLON, JLEV-1, JBLK)-PFACN (JLON, JLEV,&
        & JBLK))+(PFASN (JLON, JLEV-1, JBLK)-PFASN (JLON, JLEV, JBLK))-(PFCSQN (JLON, JLEV-1, JBLK)&
        &-PFCSQN (JLON, JLEV, JBLK))-(PFCCQN (JLON, JLEV-1, JBLK)-PFCCQN (JLON, JLEV, JBLK)))
      
      ENDDO

    ENDDO

  ENDDO


  

  

  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=1, KFLEV
          
          PTENDQI (JLON, JLEV, JBLK)=PTENDQI (JLON, JLEV, JBLK)+ZGSDP (JLON, JLEV&
          &, JBLK)*(PFASG (JLON, JLEV-1, JBLK)-PFASG (JLON, JLEV, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

  
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDQR (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PFESL (JLON, JLEV-1, JBLK)-PFESL (JLON, JLEV&
        &, JBLK))+(PFECL (JLON, JLEV-1, JBLK)-PFECL (JLON, JLEV, JBLK))+(PFCQRNG (JLON, JLEV-1, JBLK)-PFCQRNG&
        & (JLON, JLEV, JBLK))+(ZFPL (JLON, JLEV-1, JBLK)-ZFPL (JLON, JLEV, JBLK))-(PFACL (JLON, JLEV-1, JBLK&
        &)-PFACL (JLON, JLEV, JBLK))-(PFASL (JLON, JLEV-1, JBLK)-PFASL (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQS (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PFESN (JLON, JLEV-1, JBLK)-PFESN (JLON, JLEV&
        &, JBLK))+(PFECN (JLON, JLEV-1, JBLK)-PFECN (JLON, JLEV, JBLK))+(PFCQSNG (JLON, JLEV-1, JBLK)-PFCQSNG&
        & (JLON, JLEV, JBLK))+(ZFPN (JLON, JLEV-1, JBLK)-ZFPN (JLON, JLEV, JBLK))-(PFACN (JLON, JLEV-1, JBLK&
        &)-PFACN (JLON, JLEV, JBLK))-(PFASN (JLON, JLEV-1, JBLK)-PFASN (JLON, JLEV, JBLK)))
      
      ENDDO

    ENDDO

  ENDDO


  

  

  

  IF (YDMODEL%YRML_PHY_MF%YRPHY%LGRAPRO) THEN
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=1, KFLEV
          
          PTENDQG (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PFESG (JLON, JLEV-1, JBLK)-PFESG&
          & (JLON, JLEV, JBLK))+(PFECG (JLON, JLEV-1, JBLK)-PFECG (JLON, JLEV, JBLK))+(PFCQGNG&
          & (JLON, JLEV-1, JBLK)-PFCQGNG (JLON, JLEV, JBLK))+(ZFPG (JLON, JLEV-1, JBLK)-ZFPG &
          &(JLON, JLEV, JBLK))-(PFASG (JLON, JLEV-1, JBLK)-PFASG (JLON, JLEV, JBLK)))
        
        ENDDO

      ENDDO

    ENDDO

  
  ENDIF

ELSEIF (YDMODEL%YRML_PHY_MF%YRPHY%LCONDWT.AND.YDMODEL%YRML_PHY_MF%YRPHY%LGPCMT) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDQL (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PDIFTQL (JLON, JLEV-1, JBLK)-PDIFTQL (JLON, JLEV&
        &, JBLK))+(PDIFCQL (JLON, JLEV-1, JBLK)-PDIFCQL (JLON, JLEV, JBLK))+(PFCQLNG (JLON, JLEV-1, JBLK)-PFCQLNG&
        & (JLON, JLEV, JBLK))-(PFEDQLC (JLON, JLEV-1, JBLK)-PFEDQLC (JLON, JLEV, JBLK))+(PFASL (JLON, JLEV-1&
        &, JBLK)-PFASL (JLON, JLEV, JBLK))-(PFCSQL (JLON, JLEV-1, JBLK)-PFCSQL (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQI (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PDIFTQI (JLON, JLEV-1, JBLK)-PDIFTQI (JLON, JLEV&
        &, JBLK))+(PDIFCQI (JLON, JLEV-1, JBLK)-PDIFCQI (JLON, JLEV, JBLK))+(PFCQING (JLON, JLEV-1, JBLK)-PFCQING&
        & (JLON, JLEV, JBLK))-(PFEDQIC (JLON, JLEV-1, JBLK)-PFEDQIC (JLON, JLEV, JBLK))+(PFASN (JLON, JLEV-1&
        &, JBLK)-PFASN (JLON, JLEV, JBLK))-(PFCSQN (JLON, JLEV-1, JBLK)-PFCSQN (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQR (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PFESL (JLON, JLEV-1, JBLK)-PFESL&
        & (JLON, JLEV, JBLK))+(PFCQRNG (JLON, JLEV-1, JBLK)-PFCQRNG (JLON, JLEV, JBLK))-(PFEDQRC&
        & (JLON, JLEV-1, JBLK)-PFEDQRC (JLON, JLEV, JBLK))+(PFPLSL (JLON, JLEV-1, JBLK)-PFPLSL&
        & (JLON, JLEV, JBLK))-(PFASL (JLON, JLEV-1, JBLK)-PFASL (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQS (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*((PFESN (JLON, JLEV-1, JBLK)-PFESN&
        & (JLON, JLEV, JBLK))+(PFCQSNG (JLON, JLEV-1, JBLK)-PFCQSNG (JLON, JLEV, JBLK))-(PFEDQSC&
        & (JLON, JLEV-1, JBLK)-PFEDQSC (JLON, JLEV, JBLK))+(PFPLSN (JLON, JLEV-1, JBLK)-PFPLSN&
        & (JLON, JLEV, JBLK))-(PFASN (JLON, JLEV-1, JBLK)-PFASN (JLON, JLEV, JBLK)))
      
      ENDDO

    ENDDO

  ENDDO

  
  
  
  
  
  
  
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDQLCONV (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(+(PFCNEGQLC (JLON, JLEV-1&
        &, JBLK)-PFCNEGQLC (JLON, JLEV, JBLK))+(PDIFCQLC (JLON, JLEV-1, JBLK)-PDIFCQLC (JLON&
        &, JLEV, JBLK))+(PFEDQLC (JLON, JLEV-1, JBLK)-PFEDQLC (JLON, JLEV, JBLK))+(PFIMCC &
        &(JLON, JLEV-1, JBLK)-PFIMCC (JLON, JLEV, JBLK))-(PFCCQL (JLON, JLEV-1, JBLK)-PFCCQL&
        & (JLON, JLEV, JBLK))+(PFACL (JLON, JLEV-1, JBLK)-PFACL (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQICONV (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(+(PFCNEGQIC (JLON, JLEV-1&
        &, JBLK)-PFCNEGQIC (JLON, JLEV, JBLK))+(PDIFCQIC (JLON, JLEV-1, JBLK)-PDIFCQIC (JLON&
        &, JLEV, JBLK))+(PFEDQIC (JLON, JLEV-1, JBLK)-PFEDQIC (JLON, JLEV, JBLK))-(PFIMCC &
        &(JLON, JLEV-1, JBLK)-PFIMCC (JLON, JLEV, JBLK))-(PFCCQN (JLON, JLEV-1, JBLK)-PFCCQN&
        & (JLON, JLEV, JBLK))+(PFACN (JLON, JLEV-1, JBLK)-PFACN (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQRCONV (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(+(PFCNEGQRC (JLON, JLEV-1, JBLK&
        &)-PFCNEGQRC (JLON, JLEV, JBLK))+(PFPLCL (JLON, JLEV-1, JBLK)-PFPLCL (JLON, JLEV, JBLK)&
        &)+(PFEDQRC (JLON, JLEV-1, JBLK)-PFEDQRC (JLON, JLEV, JBLK))-(PFACL (JLON, JLEV-1, JBLK&
        &)-PFACL (JLON, JLEV, JBLK))+(PFECL (JLON, JLEV-1, JBLK)-PFECL (JLON, JLEV, JBLK)))
      
      ENDDO


      DO JLEV=1, KFLEV
        
        PTENDQSCONV (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(+(PFCNEGQSC (JLON, JLEV-1, JBLK&
        &)-PFCNEGQSC (JLON, JLEV, JBLK))+(PFPLCN (JLON, JLEV-1, JBLK)-PFPLCN (JLON, JLEV, JBLK)&
        &)+(PFEDQSC (JLON, JLEV-1, JBLK)-PFEDQSC (JLON, JLEV, JBLK))-(PFACN (JLON, JLEV-1, JBLK&
        &)-PFACN (JLON, JLEV, JBLK))+(PFECN (JLON, JLEV-1, JBLK)-PFECN (JLON, JLEV, JBLK)))
      
      ENDDO

    ENDDO

  ENDDO

  
  
  
  
  
  
  
ENDIF



IF (LLDPSFI) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDQ (JLON, JLEV, JBLK)=PTENDQ (JLON, JLEV, JBLK)-ZGSDP (JLON, JLEV, JBLK)*(ZQH (JLON, JLEV&
        &-1, JBLK)*ZLIFT (JLON, JLEV-1, JBLK)-ZQH (JLON, JLEV, JBLK)*ZLIFT (JLON, JLEV, JBLK))

        IF (YDMODEL%YRML_PHY_MF%YRPHY%LCONDWT) THEN
          PTENDQI (JLON, JLEV, JBLK)=PTENDQI (JLON, JLEV, JBLK)-ZGSDP (JLON, JLEV, JBLK)*(ZQIH (JLON, JLEV&
          &-1, JBLK)*ZLIFT (JLON, JLEV-1, JBLK)-ZQIH (JLON, JLEV, JBLK)*ZLIFT (JLON, JLEV, JBLK))
          PTENDQL (JLON, JLEV, JBLK)=PTENDQL (JLON, JLEV, JBLK)-ZGSDP (JLON, JLEV, JBLK)*(ZQLH (JLON, JLEV&
          &-1, JBLK)*ZLIFT (JLON, JLEV-1, JBLK)-ZQLH (JLON, JLEV, JBLK)*ZLIFT (JLON, JLEV, JBLK))
        ENDIF

      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%LECT) THEN

  IF (JPRD==JPRB) THEN
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=1, KFLEV
          
          PTENDTKE (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(PFTKE&
          & (JLON, JLEV-1, JBLK)-PFTKE (JLON, JLEV, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ELSE
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=1, KFLEV
          
          PTENDTKE (JLON, JLEV, JBLK)=PFTKEI (JLON, JLEV, JBLK)
        
        ENDDO

      ENDDO

    ENDDO

  ENDIF

ENDIF


IF (YDMODEL%YRML_PHY_MF%YRPHY%LEFB) THEN
  
  !$OMP TARGET TEAMS DISTRIBUTE &
  !$OMP&IF (LDACC) &
  !$OMP&PRIVATE (JBLK) &
  !$OMP&THREAD_LIMIT (KLON) 

  

  DO JBLK = 1, KGPBLKS
    
    !$OMP PARALLEL DO SIMD &
    !$OMP&PRIVATE (JLEV, JLON) 

    

    DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

      DO JLEV=1, KFLEV
        
        PTENDEFB1 (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(PFEFB1&
        & (JLON, JLEV-1, JBLK)-PFEFB1 (JLON, JLEV, JBLK))
        PTENDEFB2 (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(PFEFB2&
        & (JLON, JLEV-1, JBLK)-PFEFB2 (JLON, JLEV, JBLK))
        PTENDEFB3 (JLON, JLEV, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(PFEFB3&
        & (JLON, JLEV-1, JBLK)-PFEFB3 (JLON, JLEV, JBLK))
      
      ENDDO

    ENDDO

  ENDDO

ENDIF


IF (YDMODEL%YRML_PHY_MF%YRARPHY%LMDUST.AND.(YDMODEL%YRML_GCONF%YGFL%NGFL_EXT/=0)) THEN

  DO JGFL=1, YDMODEL%YRML_GCONF%YGFL%NGFL_EXT
    
    !$OMP TARGET TEAMS DISTRIBUTE &
    !$OMP&IF (LDACC) &
    !$OMP&PRIVATE (JBLK) &
    !$OMP&THREAD_LIMIT (KLON) 

    

    DO JBLK = 1, KGPBLKS
      
      !$OMP PARALLEL DO SIMD &
      !$OMP&PRIVATE (JLEV, JLON) 

      

      DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

        DO JLEV=1, KFLEV
          
          PTENDEXT (JLON, JLEV, JGFL, JBLK)=ZGSDP (JLON, JLEV, JBLK)*(PDIFEXT&
          & (JLON, JLEV-1, JGFL, JBLK)-PDIFEXT (JLON, JLEV, JGFL, JBLK))
        
        ENDDO

      ENDDO

    ENDDO

  ENDDO

ENDIF





!$OMP END TARGET DATA

END SUBROUTINE CPTEND_NEW_MANYBLOCKS
