!mod$ v1 sum:b25571bc4daf472d
!need$ 1a95e331e288a574 n field_constants_module
!need$ 6d1a91c03e08cb34 n field_abort_module
!need$ fe3180dd7f22d4c1 n parkind1
!need$ 920192381ddd6d57 i omp_lib
!need$ 0bde2ac47243ead2 i iso_c_binding
module field_1rm_data_module
use parkind1,only:jprm
use parkind1,only:jprd
use parkind1,only:jplm
use field_constants_module,only:jpim
use field_constants_module,only:ndevfresh
use field_constants_module,only:int
use field_constants_module,only:nhstfresh
use field_constants_module,only:unallocated
use field_constants_module,only:uninitialized
use field_constants_module,only:nh2d
use field_constants_module,only:nd2h
use field_constants_module,only:nrd
use field_constants_module,only:nwr
use field_constants_module,only:nf2l
use field_constants_module,only:nl2f
use field_abort_module,only:field_abort_func
use field_abort_module,only:field_abort
use,intrinsic::iso_c_binding,only:c_associated
use,intrinsic::iso_c_binding,only:c_funloc
use,intrinsic::iso_c_binding,only:c_funptr
use,intrinsic::iso_c_binding,only:c_f_pointer
use,intrinsic::iso_c_binding,only:c_loc
use,intrinsic::iso_c_binding,only:c_null_funptr
use,intrinsic::iso_c_binding,only:c_null_ptr
use,intrinsic::iso_c_binding,only:c_ptr
use,intrinsic::iso_c_binding,only:c_sizeof
use,intrinsic::iso_c_binding,only:operator(==)
use,intrinsic::iso_c_binding,only:operator(/=)
use,intrinsic::iso_c_binding,only:c_int8_t
use,intrinsic::iso_c_binding,only:c_int16_t
use,intrinsic::iso_c_binding,only:c_int32_t
use,intrinsic::iso_c_binding,only:c_int64_t
use,intrinsic::iso_c_binding,only:c_int128_t
use,intrinsic::iso_c_binding,only:c_int
use,intrinsic::iso_c_binding,only:c_short
use,intrinsic::iso_c_binding,only:c_long
use,intrinsic::iso_c_binding,only:c_long_long
use,intrinsic::iso_c_binding,only:c_signed_char
use,intrinsic::iso_c_binding,only:c_size_t
use,intrinsic::iso_c_binding,only:c_intmax_t
use,intrinsic::iso_c_binding,only:c_intptr_t
use,intrinsic::iso_c_binding,only:c_ptrdiff_t
use,intrinsic::iso_c_binding,only:c_int_least8_t
use,intrinsic::iso_c_binding,only:c_int_fast8_t
use,intrinsic::iso_c_binding,only:c_int_least16_t
use,intrinsic::iso_c_binding,only:c_int_fast16_t
use,intrinsic::iso_c_binding,only:c_int_least32_t
use,intrinsic::iso_c_binding,only:c_int_fast32_t
use,intrinsic::iso_c_binding,only:c_int_least64_t
use,intrinsic::iso_c_binding,only:c_int_fast64_t
use,intrinsic::iso_c_binding,only:c_int_least128_t
use,intrinsic::iso_c_binding,only:c_int_fast128_t
use,intrinsic::iso_c_binding,only:c_float
use,intrinsic::iso_c_binding,only:c_double
use,intrinsic::iso_c_binding,only:c_long_double
use,intrinsic::iso_c_binding,only:c_float_complex
use,intrinsic::iso_c_binding,only:c_double_complex
use,intrinsic::iso_c_binding,only:c_long_double_complex
use,intrinsic::iso_c_binding,only:c_bool
use,intrinsic::iso_c_binding,only:c_char
use,intrinsic::iso_c_binding,only:c_null_char
use,intrinsic::iso_c_binding,only:c_alert
use,intrinsic::iso_c_binding,only:c_backspace
use,intrinsic::iso_c_binding,only:c_form_feed
use,intrinsic::iso_c_binding,only:c_new_line
use,intrinsic::iso_c_binding,only:c_carriage_return
use,intrinsic::iso_c_binding,only:c_horizontal_tab
use,intrinsic::iso_c_binding,only:c_vertical_tab
use,intrinsic::iso_c_binding,only:c_float128
use,intrinsic::iso_c_binding,only:c_float128_complex
use,intrinsic::iso_c_binding,only:c_uint8_t
use,intrinsic::iso_c_binding,only:c_uint16_t
use,intrinsic::iso_c_binding,only:c_uint32_t
use,intrinsic::iso_c_binding,only:c_uint64_t
use,intrinsic::iso_c_binding,only:c_uint128_t
use,intrinsic::iso_c_binding,only:c_unsigned_char
use,intrinsic::iso_c_binding,only:c_unsigned_short
use,intrinsic::iso_c_binding,only:c_unsigned
use,intrinsic::iso_c_binding,only:c_unsigned_long
use,intrinsic::iso_c_binding,only:c_unsigned_long_long
use,intrinsic::iso_c_binding,only:c_uintmax_t
use,intrinsic::iso_c_binding,only:c_uint_fast8_t
use,intrinsic::iso_c_binding,only:c_uint_fast16_t
use,intrinsic::iso_c_binding,only:c_uint_fast32_t
use,intrinsic::iso_c_binding,only:c_uint_fast64_t
use,intrinsic::iso_c_binding,only:c_uint_fast128_t
use,intrinsic::iso_c_binding,only:c_uint_least8_t
use,intrinsic::iso_c_binding,only:c_uint_least16_t
use,intrinsic::iso_c_binding,only:c_uint_least32_t
use,intrinsic::iso_c_binding,only:c_uint_least64_t
use,intrinsic::iso_c_binding,only:c_uint_least128_t
use,intrinsic::iso_c_binding,only:c_f_procpointer
use,intrinsic::omp_lib,only:omp_integer_kind
use,intrinsic::omp_lib,only:omp_logical_kind
use,intrinsic::omp_lib,only:omp_real_kind
use,intrinsic::omp_lib,only:kmp_double_kind
use,intrinsic::omp_lib,only:omp_lock_kind
use,intrinsic::omp_lib,only:omp_nest_lock_kind
use,intrinsic::omp_lib,only:omp_sched_kind
use,intrinsic::omp_lib,only:omp_proc_bind_kind
use,intrinsic::omp_lib,only:kmp_pointer_kind
use,intrinsic::omp_lib,only:kmp_size_t_kind
use,intrinsic::omp_lib,only:kmp_affinity_mask_kind
use,intrinsic::omp_lib,only:kmp_cancel_kind
use,intrinsic::omp_lib,only:omp_sync_hint_kind
use,intrinsic::omp_lib,only:omp_lock_hint_kind
use,intrinsic::omp_lib,only:omp_control_tool_kind
use,intrinsic::omp_lib,only:omp_control_tool_result_kind
use,intrinsic::omp_lib,only:omp_allocator_handle_kind
use,intrinsic::omp_lib,only:omp_memspace_handle_kind
use,intrinsic::omp_lib,only:omp_alloctrait_key_kind
use,intrinsic::omp_lib,only:omp_alloctrait_val_kind
use,intrinsic::omp_lib,only:omp_interop_kind
use,intrinsic::omp_lib,only:omp_interop_fr_kind
use,intrinsic::omp_lib,only:omp_alloctrait
use,intrinsic::omp_lib,only:omp_pause_resource_kind
use,intrinsic::omp_lib,only:omp_depend_kind
use,intrinsic::omp_lib,only:omp_event_handle_kind
use,intrinsic::omp_lib,only:openmp_version
use,intrinsic::omp_lib,only:kmp_version_major
use,intrinsic::omp_lib,only:kmp_version_minor
use,intrinsic::omp_lib,only:kmp_version_build
use,intrinsic::omp_lib,only:omp_sched_static
use,intrinsic::omp_lib,only:omp_sched_dynamic
use,intrinsic::omp_lib,only:omp_sched_guided
use,intrinsic::omp_lib,only:omp_sched_auto
use,intrinsic::omp_lib,only:omp_sched_monotonic
use,intrinsic::omp_lib,only:omp_proc_bind_false
use,intrinsic::omp_lib,only:omp_proc_bind_true
use,intrinsic::omp_lib,only:omp_proc_bind_master
use,intrinsic::omp_lib,only:omp_proc_bind_close
use,intrinsic::omp_lib,only:omp_proc_bind_spread
use,intrinsic::omp_lib,only:kmp_cancel_parallel
use,intrinsic::omp_lib,only:kmp_cancel_loop
use,intrinsic::omp_lib,only:kmp_cancel_sections
use,intrinsic::omp_lib,only:kmp_cancel_taskgroup
use,intrinsic::omp_lib,only:omp_sync_hint_none
use,intrinsic::omp_lib,only:omp_sync_hint_uncontended
use,intrinsic::omp_lib,only:omp_sync_hint_contended
use,intrinsic::omp_lib,only:omp_sync_hint_nonspeculative
use,intrinsic::omp_lib,only:omp_sync_hint_speculative
use,intrinsic::omp_lib,only:omp_lock_hint_none
use,intrinsic::omp_lib,only:omp_lock_hint_uncontended
use,intrinsic::omp_lib,only:omp_lock_hint_contended
use,intrinsic::omp_lib,only:omp_lock_hint_nonspeculative
use,intrinsic::omp_lib,only:omp_lock_hint_speculative
use,intrinsic::omp_lib,only:kmp_lock_hint_hle
use,intrinsic::omp_lib,only:kmp_lock_hint_rtm
use,intrinsic::omp_lib,only:kmp_lock_hint_adaptive
use,intrinsic::omp_lib,only:omp_control_tool_start
use,intrinsic::omp_lib,only:omp_control_tool_pause
use,intrinsic::omp_lib,only:omp_control_tool_flush
use,intrinsic::omp_lib,only:omp_control_tool_end
use,intrinsic::omp_lib,only:omp_control_tool_notool
use,intrinsic::omp_lib,only:omp_control_tool_nocallback
use,intrinsic::omp_lib,only:omp_control_tool_success
use,intrinsic::omp_lib,only:omp_control_tool_ignored
use,intrinsic::omp_lib,only:omp_atk_sync_hint
use,intrinsic::omp_lib,only:omp_atk_alignment
use,intrinsic::omp_lib,only:omp_atk_access
use,intrinsic::omp_lib,only:omp_atk_pool_size
use,intrinsic::omp_lib,only:omp_atk_fallback
use,intrinsic::omp_lib,only:omp_atk_fb_data
use,intrinsic::omp_lib,only:omp_atk_pinned
use,intrinsic::omp_lib,only:omp_atk_partition
use,intrinsic::omp_lib,only:omp_atk_pin_device
use,intrinsic::omp_lib,only:omp_atk_preferred_device
use,intrinsic::omp_lib,only:omp_atk_device_access
use,intrinsic::omp_lib,only:omp_atk_target_access
use,intrinsic::omp_lib,only:omp_atk_atomic_scope
use,intrinsic::omp_lib,only:omp_atk_part_size
use,intrinsic::omp_lib,only:omp_atv_default
use,intrinsic::omp_lib,only:omp_atv_false
use,intrinsic::omp_lib,only:omp_atv_true
use,intrinsic::omp_lib,only:omp_atv_contended
use,intrinsic::omp_lib,only:omp_atv_uncontended
use,intrinsic::omp_lib,only:omp_atv_serialized
use,intrinsic::omp_lib,only:omp_atv_sequential
use,intrinsic::omp_lib,only:omp_atv_private
use,intrinsic::omp_lib,only:omp_atv_device
use,intrinsic::omp_lib,only:omp_atv_thread
use,intrinsic::omp_lib,only:omp_atv_pteam
use,intrinsic::omp_lib,only:omp_atv_cgroup
use,intrinsic::omp_lib,only:omp_atv_default_mem_fb
use,intrinsic::omp_lib,only:omp_atv_null_fb
use,intrinsic::omp_lib,only:omp_atv_abort_fb
use,intrinsic::omp_lib,only:omp_atv_allocator_fb
use,intrinsic::omp_lib,only:omp_atv_environment
use,intrinsic::omp_lib,only:omp_atv_nearest
use,intrinsic::omp_lib,only:omp_atv_blocked
use,intrinsic::omp_lib,only:omp_atv_interleaved
use,intrinsic::omp_lib,only:omp_atv_all
use,intrinsic::omp_lib,only:omp_atv_single
use,intrinsic::omp_lib,only:omp_atv_multiple
use,intrinsic::omp_lib,only:omp_atv_memspace
use,intrinsic::omp_lib,only:omp_null_allocator
use,intrinsic::omp_lib,only:omp_default_mem_alloc
use,intrinsic::omp_lib,only:omp_large_cap_mem_alloc
use,intrinsic::omp_lib,only:omp_const_mem_alloc
use,intrinsic::omp_lib,only:omp_high_bw_mem_alloc
use,intrinsic::omp_lib,only:omp_low_lat_mem_alloc
use,intrinsic::omp_lib,only:omp_cgroup_mem_alloc
use,intrinsic::omp_lib,only:omp_pteam_mem_alloc
use,intrinsic::omp_lib,only:omp_thread_mem_alloc
use,intrinsic::omp_lib,only:llvm_omp_target_host_mem_alloc
use,intrinsic::omp_lib,only:llvm_omp_target_shared_mem_alloc
use,intrinsic::omp_lib,only:llvm_omp_target_device_mem_alloc
use,intrinsic::omp_lib,only:omp_null_mem_space
use,intrinsic::omp_lib,only:omp_default_mem_space
use,intrinsic::omp_lib,only:omp_large_cap_mem_space
use,intrinsic::omp_lib,only:omp_const_mem_space
use,intrinsic::omp_lib,only:omp_high_bw_mem_space
use,intrinsic::omp_lib,only:omp_low_lat_mem_space
use,intrinsic::omp_lib,only:llvm_omp_target_host_mem_space
use,intrinsic::omp_lib,only:llvm_omp_target_shared_mem_space
use,intrinsic::omp_lib,only:llvm_omp_target_device_mem_space
use,intrinsic::omp_lib,only:omp_pause_resume
use,intrinsic::omp_lib,only:omp_pause_soft
use,intrinsic::omp_lib,only:omp_pause_hard
use,intrinsic::omp_lib,only:omp_pause_stop_tool
use,intrinsic::omp_lib,only:omp_ifr_cuda
use,intrinsic::omp_lib,only:omp_ifr_cuda_driver
use,intrinsic::omp_lib,only:omp_ifr_opencl
use,intrinsic::omp_lib,only:omp_ifr_sycl
use,intrinsic::omp_lib,only:omp_ifr_hip
use,intrinsic::omp_lib,only:omp_ifr_level_zero
use,intrinsic::omp_lib,only:omp_ifr_last
use,intrinsic::omp_lib,only:omp_interop_none
use,intrinsic::omp_lib,only:omp_set_num_threads
use,intrinsic::omp_lib,only:omp_set_dynamic
use,intrinsic::omp_lib,only:omp_set_nested
use,intrinsic::omp_lib,only:omp_get_num_threads
use,intrinsic::omp_lib,only:omp_get_max_threads
use,intrinsic::omp_lib,only:omp_get_thread_num
use,intrinsic::omp_lib,only:omp_get_num_procs
use,intrinsic::omp_lib,only:omp_in_parallel
use,intrinsic::omp_lib,only:omp_in_final
use,intrinsic::omp_lib,only:omp_get_dynamic
use,intrinsic::omp_lib,only:omp_get_nested
use,intrinsic::omp_lib,only:omp_get_thread_limit
use,intrinsic::omp_lib,only:omp_set_max_active_levels
use,intrinsic::omp_lib,only:omp_get_max_active_levels
use,intrinsic::omp_lib,only:omp_get_level
use,intrinsic::omp_lib,only:omp_get_active_level
use,intrinsic::omp_lib,only:omp_get_ancestor_thread_num
use,intrinsic::omp_lib,only:omp_get_team_size
use,intrinsic::omp_lib,only:omp_set_schedule
use,intrinsic::omp_lib,only:omp_get_schedule
use,intrinsic::omp_lib,only:omp_get_proc_bind
use,intrinsic::omp_lib,only:omp_get_num_places
use,intrinsic::omp_lib,only:omp_get_place_num_procs
use,intrinsic::omp_lib,only:omp_get_place_proc_ids
use,intrinsic::omp_lib,only:omp_get_place_num
use,intrinsic::omp_lib,only:omp_get_partition_num_places
use,intrinsic::omp_lib,only:omp_get_partition_place_nums
use,intrinsic::omp_lib,only:omp_get_wtime
use,intrinsic::omp_lib,only:omp_get_wtick
use,intrinsic::omp_lib,only:omp_get_default_device
use,intrinsic::omp_lib,only:omp_set_default_device
use,intrinsic::omp_lib,only:omp_get_num_devices
use,intrinsic::omp_lib,only:omp_get_num_teams
use,intrinsic::omp_lib,only:omp_get_team_num
use,intrinsic::omp_lib,only:omp_get_cancellation
use,intrinsic::omp_lib,only:omp_is_initial_device
use,intrinsic::omp_lib,only:omp_get_initial_device
use,intrinsic::omp_lib,only:omp_get_device_num
use,intrinsic::omp_lib,only:omp_pause_resource
use,intrinsic::omp_lib,only:omp_pause_resource_all
use,intrinsic::omp_lib,only:omp_get_supported_active_levels
use,intrinsic::omp_lib,only:omp_fulfill_event
use,intrinsic::omp_lib,only:omp_init_lock
use,intrinsic::omp_lib,only:omp_destroy_lock
use,intrinsic::omp_lib,only:omp_set_lock
use,intrinsic::omp_lib,only:omp_unset_lock
use,intrinsic::omp_lib,only:omp_test_lock
use,intrinsic::omp_lib,only:omp_init_nest_lock
use,intrinsic::omp_lib,only:omp_destroy_nest_lock
use,intrinsic::omp_lib,only:omp_set_nest_lock
use,intrinsic::omp_lib,only:omp_unset_nest_lock
use,intrinsic::omp_lib,only:omp_test_nest_lock
use,intrinsic::omp_lib,only:omp_get_max_task_priority
use,intrinsic::omp_lib,only:omp_init_lock_with_hint
use,intrinsic::omp_lib,only:omp_init_nest_lock_with_hint
use,intrinsic::omp_lib,only:omp_control_tool
use,intrinsic::omp_lib,only:omp_init_allocator
use,intrinsic::omp_lib,only:omp_destroy_allocator
use,intrinsic::omp_lib,only:omp_set_default_allocator
use,intrinsic::omp_lib,only:omp_get_default_allocator
use,intrinsic::omp_lib,only:omp_set_affinity_format
use,intrinsic::omp_lib,only:omp_get_affinity_format
use,intrinsic::omp_lib,only:omp_display_affinity
use,intrinsic::omp_lib,only:omp_capture_affinity
use,intrinsic::omp_lib,only:omp_set_num_teams
use,intrinsic::omp_lib,only:omp_get_max_teams
use,intrinsic::omp_lib,only:omp_set_teams_thread_limit
use,intrinsic::omp_lib,only:omp_get_teams_thread_limit
use,intrinsic::omp_lib,only:omp_display_env
use,intrinsic::omp_lib,only:omp_target_alloc
use,intrinsic::omp_lib,only:omp_target_free
use,intrinsic::omp_lib,only:omp_target_is_present
use,intrinsic::omp_lib,only:omp_target_memcpy
use,intrinsic::omp_lib,only:omp_target_memcpy_rect
use,intrinsic::omp_lib,only:omp_target_memcpy_async
use,intrinsic::omp_lib,only:omp_target_memcpy_rect_async
use,intrinsic::omp_lib,only:omp_target_memset
use,intrinsic::omp_lib,only:omp_target_memset_async
use,intrinsic::omp_lib,only:omp_target_associate_ptr
use,intrinsic::omp_lib,only:omp_get_mapped_ptr
use,intrinsic::omp_lib,only:omp_target_disassociate_ptr
use,intrinsic::omp_lib,only:omp_target_is_accessible
use,intrinsic::omp_lib,only:omp_alloc
use,intrinsic::omp_lib,only:omp_aligned_alloc
use,intrinsic::omp_lib,only:omp_calloc
use,intrinsic::omp_lib,only:omp_aligned_calloc
use,intrinsic::omp_lib,only:omp_realloc
use,intrinsic::omp_lib,only:omp_free
use,intrinsic::omp_lib,only:omp_in_explicit_task
use,intrinsic::omp_lib,only:kmp_set_stacksize
use,intrinsic::omp_lib,only:kmp_set_stacksize_s
use,intrinsic::omp_lib,only:kmp_set_blocktime
use,intrinsic::omp_lib,only:kmp_set_library_serial
use,intrinsic::omp_lib,only:kmp_set_library_turnaround
use,intrinsic::omp_lib,only:kmp_set_library_throughput
use,intrinsic::omp_lib,only:kmp_set_library
use,intrinsic::omp_lib,only:kmp_set_defaults
use,intrinsic::omp_lib,only:kmp_get_stacksize
use,intrinsic::omp_lib,only:kmp_get_stacksize_s
use,intrinsic::omp_lib,only:kmp_get_blocktime
use,intrinsic::omp_lib,only:kmp_get_library
use,intrinsic::omp_lib,only:kmp_set_disp_num_buffers
use,intrinsic::omp_lib,only:kmp_set_affinity
use,intrinsic::omp_lib,only:kmp_get_affinity
use,intrinsic::omp_lib,only:kmp_get_affinity_max_proc
use,intrinsic::omp_lib,only:kmp_create_affinity_mask
use,intrinsic::omp_lib,only:kmp_destroy_affinity_mask
use,intrinsic::omp_lib,only:kmp_set_affinity_mask_proc
use,intrinsic::omp_lib,only:kmp_unset_affinity_mask_proc
use,intrinsic::omp_lib,only:kmp_get_affinity_mask_proc
use,intrinsic::omp_lib,only:kmp_malloc
use,intrinsic::omp_lib,only:kmp_aligned_malloc
use,intrinsic::omp_lib,only:kmp_calloc
use,intrinsic::omp_lib,only:kmp_realloc
use,intrinsic::omp_lib,only:kmp_free
use,intrinsic::omp_lib,only:kmp_set_warnings_on
use,intrinsic::omp_lib,only:kmp_set_warnings_off
use,intrinsic::omp_lib,only:kmp_get_cancellation_status
private::jprm
private::jprd
private::jplm
private::jpim
private::ndevfresh
private::int
private::nhstfresh
private::unallocated
private::uninitialized
private::nh2d
private::nd2h
private::nrd
private::nwr
private::nf2l
private::nl2f
private::field_abort_func
private::field_abort
private::c_associated
private::c_funloc
private::c_funptr
private::c_f_pointer
private::c_loc
private::c_null_funptr
private::c_null_ptr
private::c_ptr
private::c_sizeof
private::operator(==)
private::operator(/=)
private::c_int8_t
private::c_int16_t
private::c_int32_t
private::c_int64_t
private::c_int128_t
private::c_int
private::c_short
private::c_long
private::c_long_long
private::c_signed_char
private::c_size_t
private::c_intmax_t
private::c_intptr_t
private::c_ptrdiff_t
private::c_int_least8_t
private::c_int_fast8_t
private::c_int_least16_t
private::c_int_fast16_t
private::c_int_least32_t
private::c_int_fast32_t
private::c_int_least64_t
private::c_int_fast64_t
private::c_int_least128_t
private::c_int_fast128_t
private::c_float
private::c_double
private::c_long_double
private::c_float_complex
private::c_double_complex
private::c_long_double_complex
private::c_bool
private::c_char
private::c_null_char
private::c_alert
private::c_backspace
private::c_form_feed
private::c_new_line
private::c_carriage_return
private::c_horizontal_tab
private::c_vertical_tab
private::c_float128
private::c_float128_complex
private::c_uint8_t
private::c_uint16_t
private::c_uint32_t
private::c_uint64_t
private::c_uint128_t
private::c_unsigned_char
private::c_unsigned_short
private::c_unsigned
private::c_unsigned_long
private::c_unsigned_long_long
private::c_uintmax_t
private::c_uint_fast8_t
private::c_uint_fast16_t
private::c_uint_fast32_t
private::c_uint_fast64_t
private::c_uint_fast128_t
private::c_uint_least8_t
private::c_uint_least16_t
private::c_uint_least32_t
private::c_uint_least64_t
private::c_uint_least128_t
private::c_f_procpointer
private::omp_integer_kind
private::omp_logical_kind
private::omp_real_kind
private::kmp_double_kind
private::omp_lock_kind
private::omp_nest_lock_kind
private::omp_sched_kind
private::omp_proc_bind_kind
private::kmp_pointer_kind
private::kmp_size_t_kind
private::kmp_affinity_mask_kind
private::kmp_cancel_kind
private::omp_sync_hint_kind
private::omp_lock_hint_kind
private::omp_control_tool_kind
private::omp_control_tool_result_kind
private::omp_allocator_handle_kind
private::omp_memspace_handle_kind
private::omp_alloctrait_key_kind
private::omp_alloctrait_val_kind
private::omp_interop_kind
private::omp_interop_fr_kind
private::omp_alloctrait
private::omp_pause_resource_kind
private::omp_depend_kind
private::omp_event_handle_kind
private::openmp_version
private::kmp_version_major
private::kmp_version_minor
private::kmp_version_build
private::omp_sched_static
private::omp_sched_dynamic
private::omp_sched_guided
private::omp_sched_auto
private::omp_sched_monotonic
private::omp_proc_bind_false
private::omp_proc_bind_true
private::omp_proc_bind_master
private::omp_proc_bind_close
private::omp_proc_bind_spread
private::kmp_cancel_parallel
private::kmp_cancel_loop
private::kmp_cancel_sections
private::kmp_cancel_taskgroup
private::omp_sync_hint_none
private::omp_sync_hint_uncontended
private::omp_sync_hint_contended
private::omp_sync_hint_nonspeculative
private::omp_sync_hint_speculative
private::omp_lock_hint_none
private::omp_lock_hint_uncontended
private::omp_lock_hint_contended
private::omp_lock_hint_nonspeculative
private::omp_lock_hint_speculative
private::kmp_lock_hint_hle
private::kmp_lock_hint_rtm
private::kmp_lock_hint_adaptive
private::omp_control_tool_start
private::omp_control_tool_pause
private::omp_control_tool_flush
private::omp_control_tool_end
private::omp_control_tool_notool
private::omp_control_tool_nocallback
private::omp_control_tool_success
private::omp_control_tool_ignored
private::omp_atk_sync_hint
private::omp_atk_alignment
private::omp_atk_access
private::omp_atk_pool_size
private::omp_atk_fallback
private::omp_atk_fb_data
private::omp_atk_pinned
private::omp_atk_partition
private::omp_atk_pin_device
private::omp_atk_preferred_device
private::omp_atk_device_access
private::omp_atk_target_access
private::omp_atk_atomic_scope
private::omp_atk_part_size
private::omp_atv_default
private::omp_atv_false
private::omp_atv_true
private::omp_atv_contended
private::omp_atv_uncontended
private::omp_atv_serialized
private::omp_atv_sequential
private::omp_atv_private
private::omp_atv_device
private::omp_atv_thread
private::omp_atv_pteam
private::omp_atv_cgroup
private::omp_atv_default_mem_fb
private::omp_atv_null_fb
private::omp_atv_abort_fb
private::omp_atv_allocator_fb
private::omp_atv_environment
private::omp_atv_nearest
private::omp_atv_blocked
private::omp_atv_interleaved
private::omp_atv_all
private::omp_atv_single
private::omp_atv_multiple
private::omp_atv_memspace
private::omp_null_allocator
private::omp_default_mem_alloc
private::omp_large_cap_mem_alloc
private::omp_const_mem_alloc
private::omp_high_bw_mem_alloc
private::omp_low_lat_mem_alloc
private::omp_cgroup_mem_alloc
private::omp_pteam_mem_alloc
private::omp_thread_mem_alloc
private::llvm_omp_target_host_mem_alloc
private::llvm_omp_target_shared_mem_alloc
private::llvm_omp_target_device_mem_alloc
private::omp_null_mem_space
private::omp_default_mem_space
private::omp_large_cap_mem_space
private::omp_const_mem_space
private::omp_high_bw_mem_space
private::omp_low_lat_mem_space
private::llvm_omp_target_host_mem_space
private::llvm_omp_target_shared_mem_space
private::llvm_omp_target_device_mem_space
private::omp_pause_resume
private::omp_pause_soft
private::omp_pause_hard
private::omp_pause_stop_tool
private::omp_ifr_cuda
private::omp_ifr_cuda_driver
private::omp_ifr_opencl
private::omp_ifr_sycl
private::omp_ifr_hip
private::omp_ifr_level_zero
private::omp_ifr_last
private::omp_interop_none
private::omp_set_num_threads
private::omp_set_dynamic
private::omp_set_nested
private::omp_get_num_threads
private::omp_get_max_threads
private::omp_get_thread_num
private::omp_get_num_procs
private::omp_in_parallel
private::omp_in_final
private::omp_get_dynamic
private::omp_get_nested
private::omp_get_thread_limit
private::omp_set_max_active_levels
private::omp_get_max_active_levels
private::omp_get_level
private::omp_get_active_level
private::omp_get_ancestor_thread_num
private::omp_get_team_size
private::omp_set_schedule
private::omp_get_schedule
private::omp_get_proc_bind
private::omp_get_num_places
private::omp_get_place_num_procs
private::omp_get_place_proc_ids
private::omp_get_place_num
private::omp_get_partition_num_places
private::omp_get_partition_place_nums
private::omp_get_wtime
private::omp_get_wtick
private::omp_get_default_device
private::omp_set_default_device
private::omp_get_num_devices
private::omp_get_num_teams
private::omp_get_team_num
private::omp_get_cancellation
private::omp_is_initial_device
private::omp_get_initial_device
private::omp_get_device_num
private::omp_pause_resource
private::omp_pause_resource_all
private::omp_get_supported_active_levels
private::omp_fulfill_event
private::omp_init_lock
private::omp_destroy_lock
private::omp_set_lock
private::omp_unset_lock
private::omp_test_lock
private::omp_init_nest_lock
private::omp_destroy_nest_lock
private::omp_set_nest_lock
private::omp_unset_nest_lock
private::omp_test_nest_lock
private::omp_get_max_task_priority
private::omp_init_lock_with_hint
private::omp_init_nest_lock_with_hint
private::omp_control_tool
private::omp_init_allocator
private::omp_destroy_allocator
private::omp_set_default_allocator
private::omp_get_default_allocator
private::omp_set_affinity_format
private::omp_get_affinity_format
private::omp_display_affinity
private::omp_capture_affinity
private::omp_set_num_teams
private::omp_get_max_teams
private::omp_set_teams_thread_limit
private::omp_get_teams_thread_limit
private::omp_display_env
private::omp_target_alloc
private::omp_target_free
private::omp_target_is_present
private::omp_target_memcpy
private::omp_target_memcpy_rect
private::omp_target_memcpy_async
private::omp_target_memcpy_rect_async
private::omp_target_memset
private::omp_target_memset_async
private::omp_target_associate_ptr
private::omp_get_mapped_ptr
private::omp_target_disassociate_ptr
private::omp_target_is_accessible
private::omp_alloc
private::omp_aligned_alloc
private::omp_calloc
private::omp_aligned_calloc
private::omp_realloc
private::omp_free
private::omp_in_explicit_task
private::kmp_set_stacksize
private::kmp_set_stacksize_s
private::kmp_set_blocktime
private::kmp_set_library_serial
private::kmp_set_library_turnaround
private::kmp_set_library_throughput
private::kmp_set_library
private::kmp_set_defaults
private::kmp_get_stacksize
private::kmp_get_stacksize_s
private::kmp_get_blocktime
private::kmp_get_library
private::kmp_set_disp_num_buffers
private::kmp_set_affinity
private::kmp_get_affinity
private::kmp_get_affinity_max_proc
private::kmp_create_affinity_mask
private::kmp_destroy_affinity_mask
private::kmp_set_affinity_mask_proc
private::kmp_unset_affinity_mask_proc
private::kmp_get_affinity_mask_proc
private::kmp_malloc
private::kmp_aligned_malloc
private::kmp_calloc
private::kmp_realloc
private::kmp_free
private::kmp_set_warnings_on
private::kmp_set_warnings_off
private::kmp_get_cancellation_status
abstract interface
subroutine field_1rm_copy_intf(hst,dev,map_devptr,kdir,queue)
real(4),pointer::hst(:)
real(4),pointer::dev(:)
logical(4),intent(in)::map_devptr
integer(4),intent(in)::kdir
integer(4),intent(in),optional::queue
end
end interface
private::field_1rm_copy_dim0_contiguous
private::field_1rm_copy_dim1_contiguous
private::field_1rm_get_last_contiguous_dimension
contains
function field_1rm_copy_func(hst,dev) result(func)
real(4),optional,pointer::hst(:)
real(4),optional,pointer::dev(:)
procedure(field_1rm_copy_intf),pointer::func
end
subroutine field_1rm_copy(hst,dev,map_devptr,kdir,queue)
real(4),pointer::hst(:)
real(4),pointer::dev(:)
logical(4),intent(in)::map_devptr
integer(4),intent(in)::kdir
integer(4),intent(in),optional::queue
end
subroutine field_1rm_copy_dim0_contiguous(hst,dev,map_devptr,kdir,queue)
real(4),pointer::hst(:)
real(4),pointer::dev(:)
logical(4),intent(in)::map_devptr
integer(4),intent(in)::kdir
integer(4),intent(in),optional::queue
end
subroutine field_1rm_copy_dim1_contiguous(hst,dev,map_devptr,kdir,queue)
real(4),pointer::hst(:)
real(4),pointer::dev(:)
logical(4),intent(in)::map_devptr
integer(4),intent(in)::kdir
integer(4),intent(in),optional::queue
end
function field_1rm_get_last_contiguous_dimension(ptr,after) result(jdim)
real(4),pointer::ptr(:)
integer(4)::after
integer(4)::jdim
end
end
