!mod$ v1 sum:5df798c736e3cb58
!need$ 25b02d753545073c n modd_parameters
module modd_elec_descr
use modd_parameters,only:jpsvnamelgtmax
logical(4)::locg
logical(4)::lelec_field
logical(4)::lfw_helfa
logical(4)::lcosmic_approx
logical(4)::lion_attach
character(3_4,1)::cdrift
logical(4)::lrelax2fw_ion
logical(4)::lflash_geom
logical(4)::lsave_coord
integer(4)::nflash_write
logical(4)::linductive
logical(4)::llnox_explicit
logical(4)::lseries_elec
integer(4)::ntsave_series
character(5_4,1)::cni_charging
real(8)::xqtc
real(8)::xlim_ni_is
real(8)::xlim_ni_ig
real(8)::xlim_ni_sg
character(5_4,1)::clsol
integer(4)::nlapitr_elec
real(8)::xrelax_elec
real(8)::xetrig
real(8)::xebalance
real(8)::xeprop
real(8)::xqexces
real(8)::xqneut
real(8)::xdfrac_eclair
real(8)::xdfrac_l
real(8)::xwang_a
real(8)::xwang_b
real(8),allocatable,save::xqtmin(:)
real(8),allocatable::xrtmin_elec(:)
real(8)::xepsilon
real(8),save::xlbdar_maxe
real(8),save::xlbdas_maxe
real(8),save::xlbdag_maxe
real(8),save::xlbdah_maxe
real(8)::xalphacq
real(8)::xnucq
real(8)::xlbdacq
real(8)::xe_0
real(8)::xkef
real(8),save::xe0_hf
real(8),save::xa1_hf
real(8),save::xb1_hf
real(8),save::xa2_hf
real(8),save::xb2_hf
real(8),save::xa3_hf
real(8),save::xb3_hf
real(8),save::xioncomb
real(8),save::xf_pos
real(8),save::xf_neg
real(8),save::xexpmob
real(8),save::xfcorona
real(8),save::xecorona
real(8),save::xjcurr_fw
integer(4)::nmax_cell
integer(4)::nbranch_max
integer(4)::nleader_max
real(8)::xe_thresh
integer(4),parameter::nlghtmax=5000_4
integer(4),parameter::nsegmax=500_4
integer(4)::nnblight
real(8),allocatable::xneut_pos(:)
real(8),allocatable::xneut_neg(:)
integer(4)::nnb_cg
integer(4)::nnb_cg_pos
real(8)::xalt_cg
character(10_4,1)::celecnames(1_8:8_8)
real(8)::xlnox_eclair
real(8),allocatable::xepotfw_top(:,:)
logical(4)::liaggs_latham
type::elec_descr_t
real(8)::xfc
real(8)::xfr
real(8)::xfi
real(8)::xfs
real(8)::xfg
real(8)::xfh
real(8)::xcxr
real(8)::xecharge
logical(4)::lsedim_beard=.false._4
end type
type(elec_descr_t),target::elec_descr
real(8),pointer::xfc
intrinsic::null
real(8),pointer::xfr
real(8),pointer::xfi
real(8),pointer::xfs
real(8),pointer::xfg
real(8),pointer::xfh
real(8),pointer::xcxr
real(8),pointer::xecharge
logical(4),pointer::lsedim_beard
contains
subroutine elec_descr_associate()
end
end
