!mod$ v1 sum:0b09809203dac56a
!need$ 25b02d753545073c n modd_parameters
module modd_rain_ice_descr_n
use modd_parameters,only:jpmodelmax
type::rain_ice_descr_t
real(8)::xcexvt
real(8)::xac
real(8)::xbc
real(8)::xcc
real(8)::xdc
real(8)::xar
real(8)::xbr
real(8)::xcr
real(8)::xdr
real(8)::xccr
real(8)::xf0r
real(8)::xf1r
real(8)::xc1r
real(8)::xai
real(8)::xbi
real(8)::xc_i
real(8)::xdi
real(8)::xf0i
real(8)::xf2i
real(8)::xc1i
real(8)::xas
real(8)::xbs
real(8)::xcs
real(8)::xds
real(8)::xccs
real(8)::xcxs
real(8)::xf0s
real(8)::xf1s
real(8)::xc1s
real(8)::xag
real(8)::xbg
real(8)::xcg
real(8)::xdg
real(8)::xccg
real(8)::xcxg
real(8)::xf0g
real(8)::xf1g
real(8)::xc1g
real(8)::xah
real(8)::xbh
real(8)::xch
real(8)::xdh
real(8)::xcch
real(8)::xcxh
real(8)::xf0h
real(8)::xf1h
real(8)::xc1h
real(8)::xalphac
real(8)::xnuc
real(8)::xalphac2
real(8)::xnuc2
real(8)::xlbexc
real(8)::xlbc(1_8:2_8)
real(8)::xalphar
real(8)::xnur
real(8)::xlbexr
real(8)::xlbr
real(8)::xalphai
real(8)::xnui
real(8)::xlbexi
real(8)::xlbi
real(8)::xalphas
real(8)::xnus
real(8)::xlbexs
real(8)::xlbs
real(8)::xns
real(8)::xalphag
real(8)::xnug
real(8)::xlbexg
real(8)::xlbg
real(8)::xalphah
real(8)::xnuh
real(8)::xlbexh
real(8)::xlbh
real(8)::xfvelos
real(8)::xtrans_mp_gammas
real(8)::xlbdar_max
real(8)::xlbdas_min
real(8)::xlbdas_max
real(8)::xlbdag_max
real(8),allocatable::xrtmin(:)
real(8)::xconc_sea
real(8)::xconc_land
real(8)::xconc_urban
end type
type(rain_ice_descr_t),save,target::rain_ice_descr_model(1_8:8_8)
type(rain_ice_descr_t),pointer,save::rain_ice_descrn
intrinsic::null
real(8),pointer::xlbc(:)
real(8),pointer::xrtmin(:)
real(8),pointer::xcexvt
real(8),pointer::xac
real(8),pointer::xbc
real(8),pointer::xcc
real(8),pointer::xdc
real(8),pointer::xar
real(8),pointer::xbr
real(8),pointer::xcr
real(8),pointer::xdr
real(8),pointer::xccr
real(8),pointer::xf0r
real(8),pointer::xf1r
real(8),pointer::xc1r
real(8),pointer::xai
real(8),pointer::xbi
real(8),pointer::xc_i
real(8),pointer::xdi
real(8),pointer::xf0i
real(8),pointer::xf2i
real(8),pointer::xc1i
real(8),pointer::xas
real(8),pointer::xbs
real(8),pointer::xcs
real(8),pointer::xds
real(8),pointer::xccs
real(8),pointer::xcxs
real(8),pointer::xf0s
real(8),pointer::xf1s
real(8),pointer::xc1s
real(8),pointer::xag
real(8),pointer::xbg
real(8),pointer::xcg
real(8),pointer::xdg
real(8),pointer::xccg
real(8),pointer::xcxg
real(8),pointer::xf0g
real(8),pointer::xf1g
real(8),pointer::xc1g
real(8),pointer::xah
real(8),pointer::xbh
real(8),pointer::xch
real(8),pointer::xdh
real(8),pointer::xcch
real(8),pointer::xcxh
real(8),pointer::xf0h
real(8),pointer::xf1h
real(8),pointer::xc1h
real(8),pointer::xalphac
real(8),pointer::xnuc
real(8),pointer::xalphac2
real(8),pointer::xnuc2
real(8),pointer::xlbexc
real(8),pointer::xalphar
real(8),pointer::xnur
real(8),pointer::xlbexr
real(8),pointer::xlbr
real(8),pointer::xalphai
real(8),pointer::xnui
real(8),pointer::xlbexi
real(8),pointer::xlbi
real(8),pointer::xalphas
real(8),pointer::xnus
real(8),pointer::xns
real(8),pointer::xlbexs
real(8),pointer::xlbs
real(8),pointer::xalphag
real(8),pointer::xnug
real(8),pointer::xlbexg
real(8),pointer::xlbg
real(8),pointer::xalphah
real(8),pointer::xnuh
real(8),pointer::xlbexh
real(8),pointer::xlbh
real(8),pointer::xlbdar_max
real(8),pointer::xlbdas_max
real(8),pointer::xlbdag_max
real(8),pointer::xconc_sea
real(8),pointer::xconc_land
real(8),pointer::xconc_urban
real(8),pointer::xfvelos
real(8),pointer::xtrans_mp_gammas
real(8),pointer::xlbdas_min
contains
subroutine rain_ice_descr_goto_model(kfrom,kto)
integer(4),intent(in)::kfrom
integer(4),intent(in)::kto
end
subroutine rain_ice_descr_allocate(krr)
integer(4),intent(in)::krr
end
subroutine rain_ice_descr_deallocate()
end
end
