!mod$ v1 sum:0888039919d409d3
module modd_param_lima_mixed
type::param_lima_mixed_t
real(8)::xag
real(8)::xbg
real(8)::xcg
real(8)::xdg
real(8)::xccg
real(8)::xcxg
real(8)::xf0g
real(8)::xf1g
real(8)::xc1g
real(8)::xlbexg
real(8)::xlbg
real(8)::xng
real(8)::xlbdag_max
real(8)::xah
real(8)::xbh
real(8)::xch
real(8)::xdh
real(8)::xcch
real(8)::xcxh
real(8)::xf0h
real(8)::xf1h
real(8)::xc1h
real(8)::xalphah
real(8)::xnuh
real(8)::xlbexh
real(8)::xlbh
real(8)::xdcslim_cibu_min
real(8)::xdcslim_cibu_max
real(8)::xdcglim_cibu_min
real(8)::xgaminc_bound_cibu_smin
real(8)::xgaminc_bound_cibu_smax
real(8)::xgaminc_bound_cibu_gmin
real(8)::xgaminc_bound_cibu_gmax
real(8)::xcibuintp_s
real(8)::xcibuintp1_s
real(8)::xcibuintp2_s
real(8)::xcibuintp_g
real(8)::xcibuintp1_g
real(8)::xfactor_cibu_ni
real(8)::xfactor_cibu_ri
real(8)::xmomgg_cibu_1
real(8)::xmomgg_cibu_2
real(8)::xmomgs_cibu_1
real(8)::xmomgs_cibu_2
real(8)::xmomgs_cibu_3
real(8),allocatable::xgaminc_cibu_s(:,:)
real(8),allocatable::xgaminc_cibu_g(:,:)
real(8)::xdcrlim_rdsf_min
real(8)::xgaminc_bound_rdsf_rmin
real(8)::xgaminc_bound_rdsf_rmax
real(8)::xrdsfintp_r
real(8)::xrdsfintp1_r
real(8)::xfactor_rdsf_ni
real(8)::xmomgr_rdsf
real(8)::xtm_psh
real(8)::xsig_psh
real(8),allocatable::xgaminc_rdsf_r(:)
real(8)::xfsedg
real(8)::xexsedg
real(8)::xfsedrg
real(8)::xfsedcg
real(8)::x0depg
real(8)::x1depg
real(8)::xex0depg
real(8)::xex1depg
real(8)::xhmtmin
real(8)::xhmtmax
real(8)::xhm1
real(8)::xhm2
real(8)::xhm_yield
real(8)::xhm_collcs
real(8)::xhm_facts
real(8)::xhm_collcg
real(8)::xhm_factg
real(8)::xgaminc_hmc_bound_min
real(8)::xgaminc_hmc_bound_max
real(8)::xhmsintp1
real(8)::xhmsintp2
real(8)::xhmlintp1
real(8)::xhmlintp2
real(8)::xdcslim
real(8)::xcolcs
real(8)::xexcrimss
real(8)::xcrimss
real(8)::xexcrimsg
real(8)::xcrimsg
real(8)::xexsrimcg
real(8)::xsrimcg
real(8)::xsrimcg2
real(8)::xsrimcg3
real(8)::xexsrimcg2
real(8)::xgaminc_bound_min
real(8)::xgaminc_bound_max
real(8)::xrimintp1
real(8)::xrimintp2
integer(4)::ngaminc
real(8),allocatable::xgaminc_rim1(:)
real(8),allocatable::xgaminc_rim2(:)
real(8),allocatable::xgaminc_rim4(:)
real(8),allocatable::xgaminc_hmc(:)
real(8)::xfraccss
real(8)::xfnraccss
real(8)::xlbraccs1
real(8)::xlbraccs2
real(8)::xlbraccs3
real(8)::xlbnraccs1
real(8)::xlbnraccs2
real(8)::xlbnraccs3
real(8)::xfsaccrg
real(8)::xfnsaccrg
real(8)::xlbsaccr1
real(8)::xlbsaccr2
real(8)::xlbsaccr3
real(8)::xlbnsaccr1
real(8)::xlbnsaccr2
real(8)::xlbnsaccr3
real(8)::xsclbdas_min
real(8)::xsclbdas_max
real(8)::xacclbdas_min
real(8)::xacclbdas_max
real(8)::xacclbdar_min
real(8)::xacclbdar_max
real(8)::xaccintp1s
real(8)::xaccintp2s
real(8)::xaccintp1r
real(8)::xaccintp2r
integer(4)::nacclbdas
integer(4)::nacclbdar
real(8),allocatable::xker_raccss(:,:)
real(8),allocatable::xker_raccs(:,:)
real(8),allocatable::xker_saccrg(:,:)
real(8),allocatable::xker_n_raccss(:,:)
real(8),allocatable::xker_n_raccs(:,:)
real(8),allocatable::xker_n_saccrg(:,:)
real(8)::xfscvmg
real(8)::xcolir
real(8)::xexrcfri
real(8)::xrcfri
real(8)::xexicfrr
real(8)::xicfrr
real(8)::xfcdryg
real(8)::xcolcg
real(8)::xcolig
real(8)::xcolexig
real(8)::xfidryg
real(8)::xcolsg
real(8)::xcolexsg
real(8)::xfsdryg
real(8)::xfnsdryg
real(8)::xlbsdryg1
real(8)::xlbsdryg2
real(8)::xlbsdryg3
real(8)::xlbnsdryg1
real(8)::xlbnsdryg2
real(8)::xlbnsdryg3
real(8)::xfrdryg
real(8)::xfnrdryg
real(8)::xlbrdryg1
real(8)::xlbrdryg2
real(8)::xlbrdryg3
real(8)::xlbnrdryg1
real(8)::xlbnrdryg2
real(8)::xlbnrdryg3
real(8)::xdrylbdar_min
real(8)::xdrylbdar_max
real(8)::xdrylbdas_min
real(8)::xdrylbdas_max
real(8)::xdrylbdag_min
real(8)::xdrylbdag_max
real(8)::xdryintp1r
real(8)::xdryintp2r
real(8)::xdryintp1s
real(8)::xdryintp2s
real(8)::xdryintp1g
real(8)::xdryintp2g
real(8)::xmindg
real(8)::xmaxlbdg
integer(4)::ndrylbdar
integer(4)::ndrylbdas
integer(4)::ndrylbdag
real(8),allocatable::xker_sdryg(:,:)
real(8),allocatable::xker_rdryg(:,:)
real(8),allocatable::xker_n_sdryg(:,:)
real(8),allocatable::xker_n_rdryg(:,:)
real(8)::xfsedh
real(8)::xexsedh
real(8)::xfsedrh
real(8)::xfsedch
real(8)::x0deph
real(8)::x1deph
real(8)::xex0deph
real(8)::xex1deph
real(8)::xfweth
real(8)::xfsweth
real(8)::xfnsweth
real(8)::xlbsweth1
real(8)::xlbsweth2
real(8)::xlbsweth3
real(8)::xlbnsweth1
real(8)::xlbnsweth2
real(8)::xlbnsweth3
real(8)::xfgweth
real(8)::xfngweth
real(8)::xlbgweth1
real(8)::xlbgweth2
real(8)::xlbgweth3
real(8)::xlbngweth1
real(8)::xlbngweth2
real(8)::xlbngweth3
real(8)::xwetlbdas_min
real(8)::xwetlbdas_max
real(8)::xwetlbdag_min
real(8)::xwetlbdag_max
real(8)::xwetlbdah_min
real(8)::xwetlbdah_max
real(8)::xwetintp1s
real(8)::xwetintp2s
real(8)::xwetintp1g
real(8)::xwetintp2g
real(8)::xwetintp1h
real(8)::xwetintp2h
integer(4)::nwetlbdas
integer(4)::nwetlbdag
integer(4)::nwetlbdah
real(8),allocatable::xker_sweth(:,:)
real(8),allocatable::xker_gweth(:,:)
real(8),allocatable::xker_n_sweth(:,:)
real(8),allocatable::xker_n_gweth(:,:)
end type
type(param_lima_mixed_t),target::param_lima_mixed
real(8),pointer::xag
intrinsic::null
real(8),pointer::xbg
real(8),pointer::xcg
real(8),pointer::xdg
real(8),pointer::xccg
real(8),pointer::xcxg
real(8),pointer::xf0g
real(8),pointer::xf1g
real(8),pointer::xc1g
real(8),pointer::xlbexg
real(8),pointer::xlbg
real(8),pointer::xng
real(8),pointer::xlbdag_max
real(8),pointer::xah
real(8),pointer::xbh
real(8),pointer::xch
real(8),pointer::xdh
real(8),pointer::xcch
real(8),pointer::xcxh
real(8),pointer::xf0h
real(8),pointer::xf1h
real(8),pointer::xc1h
real(8),pointer::xalphah
real(8),pointer::xnuh
real(8),pointer::xlbexh
real(8),pointer::xlbh
real(8),pointer::xdcslim_cibu_min
real(8),pointer::xdcslim_cibu_max
real(8),pointer::xdcglim_cibu_min
real(8),pointer::xgaminc_bound_cibu_smin
real(8),pointer::xgaminc_bound_cibu_smax
real(8),pointer::xgaminc_bound_cibu_gmin
real(8),pointer::xgaminc_bound_cibu_gmax
real(8),pointer::xcibuintp_s
real(8),pointer::xcibuintp1_s
real(8),pointer::xcibuintp2_s
real(8),pointer::xcibuintp_g
real(8),pointer::xcibuintp1_g
real(8),pointer::xfactor_cibu_ni
real(8),pointer::xfactor_cibu_ri
real(8),pointer::xmomgg_cibu_1
real(8),pointer::xmomgg_cibu_2
real(8),pointer::xmomgs_cibu_1
real(8),pointer::xmomgs_cibu_2
real(8),pointer::xmomgs_cibu_3
real(8),pointer::xdcrlim_rdsf_min
real(8),pointer::xgaminc_bound_rdsf_rmin
real(8),pointer::xgaminc_bound_rdsf_rmax
real(8),pointer::xrdsfintp_r
real(8),pointer::xrdsfintp1_r
real(8),pointer::xfactor_rdsf_ni
real(8),pointer::xmomgr_rdsf
real(8),pointer::xtm_psh
real(8),pointer::xsig_psh
real(8),pointer::xfsedg
real(8),pointer::xexsedg
real(8),pointer::xfsedrg
real(8),pointer::xfsedcg
real(8),pointer::x0depg
real(8),pointer::x1depg
real(8),pointer::xex0depg
real(8),pointer::xex1depg
real(8),pointer::xhmtmin
real(8),pointer::xhmtmax
real(8),pointer::xhm1
real(8),pointer::xhm2
real(8),pointer::xhm_yield
real(8),pointer::xhm_collcs
real(8),pointer::xhm_facts
real(8),pointer::xhm_collcg
real(8),pointer::xhm_factg
real(8),pointer::xgaminc_hmc_bound_min
real(8),pointer::xgaminc_hmc_bound_max
real(8),pointer::xhmsintp1
real(8),pointer::xhmsintp2
real(8),pointer::xhmlintp1
real(8),pointer::xhmlintp2
real(8),pointer::xdcslim
real(8),pointer::xcolcs
real(8),pointer::xexcrimss
real(8),pointer::xcrimss
real(8),pointer::xexcrimsg
real(8),pointer::xcrimsg
real(8),pointer::xexsrimcg
real(8),pointer::xsrimcg
real(8),pointer::xsrimcg2
real(8),pointer::xsrimcg3
real(8),pointer::xexsrimcg2
real(8),pointer::xgaminc_bound_min
real(8),pointer::xgaminc_bound_max
real(8),pointer::xrimintp1
real(8),pointer::xrimintp2
real(8),pointer::xfraccss
real(8),pointer::xfnraccss
real(8),pointer::xlbraccs1
real(8),pointer::xlbraccs2
real(8),pointer::xlbraccs3
real(8),pointer::xlbnraccs1
real(8),pointer::xlbnraccs2
real(8),pointer::xlbnraccs3
real(8),pointer::xfsaccrg
real(8),pointer::xfnsaccrg
real(8),pointer::xlbsaccr1
real(8),pointer::xlbsaccr2
real(8),pointer::xlbsaccr3
real(8),pointer::xlbnsaccr1
real(8),pointer::xlbnsaccr2
real(8),pointer::xlbnsaccr3
real(8),pointer::xsclbdas_min
real(8),pointer::xsclbdas_max
real(8),pointer::xacclbdas_min
real(8),pointer::xacclbdas_max
real(8),pointer::xacclbdar_min
real(8),pointer::xacclbdar_max
real(8),pointer::xaccintp1s
real(8),pointer::xaccintp2s
real(8),pointer::xaccintp1r
real(8),pointer::xaccintp2r
real(8),pointer::xfscvmg
real(8),pointer::xcolir
real(8),pointer::xexrcfri
real(8),pointer::xrcfri
real(8),pointer::xexicfrr
real(8),pointer::xicfrr
real(8),pointer::xfcdryg
real(8),pointer::xcolcg
real(8),pointer::xcolig
real(8),pointer::xcolexig
real(8),pointer::xfidryg
real(8),pointer::xcolsg
real(8),pointer::xcolexsg
real(8),pointer::xfsdryg
real(8),pointer::xfnsdryg
real(8),pointer::xlbsdryg1
real(8),pointer::xlbsdryg2
real(8),pointer::xlbsdryg3
real(8),pointer::xlbnsdryg1
real(8),pointer::xlbnsdryg2
real(8),pointer::xlbnsdryg3
real(8),pointer::xfrdryg
real(8),pointer::xfnrdryg
real(8),pointer::xlbrdryg1
real(8),pointer::xlbrdryg2
real(8),pointer::xlbrdryg3
real(8),pointer::xlbnrdryg1
real(8),pointer::xlbnrdryg2
real(8),pointer::xlbnrdryg3
real(8),pointer::xdrylbdar_min
real(8),pointer::xdrylbdar_max
real(8),pointer::xdrylbdas_min
real(8),pointer::xdrylbdas_max
real(8),pointer::xdrylbdag_min
real(8),pointer::xdrylbdag_max
real(8),pointer::xdryintp1r
real(8),pointer::xdryintp2r
real(8),pointer::xdryintp1s
real(8),pointer::xdryintp2s
real(8),pointer::xdryintp1g
real(8),pointer::xdryintp2g
real(8),pointer::xfsedh
real(8),pointer::xexsedh
real(8),pointer::xfsedrh
real(8),pointer::xfsedch
real(8),pointer::x0deph
real(8),pointer::x1deph
real(8),pointer::xex0deph
real(8),pointer::xex1deph
real(8),pointer::xfweth
real(8),pointer::xfsweth
real(8),pointer::xfnsweth
real(8),pointer::xlbsweth1
real(8),pointer::xlbsweth2
real(8),pointer::xlbsweth3
real(8),pointer::xlbnsweth1
real(8),pointer::xlbnsweth2
real(8),pointer::xlbnsweth3
real(8),pointer::xfgweth
real(8),pointer::xfngweth
real(8),pointer::xlbgweth1
real(8),pointer::xlbgweth2
real(8),pointer::xlbgweth3
real(8),pointer::xlbngweth1
real(8),pointer::xlbngweth2
real(8),pointer::xlbngweth3
real(8),pointer::xwetlbdas_min
real(8),pointer::xwetlbdas_max
real(8),pointer::xwetlbdag_min
real(8),pointer::xwetlbdag_max
real(8),pointer::xwetlbdah_min
real(8),pointer::xwetlbdah_max
real(8),pointer::xwetintp1s
real(8),pointer::xwetintp2s
real(8),pointer::xwetintp1g
real(8),pointer::xwetintp2g
real(8),pointer::xwetintp1h
real(8),pointer::xwetintp2h
real(8),pointer::xmindg
real(8),pointer::xmaxlbdg
integer(4),pointer::ngaminc
integer(4),pointer::nacclbdas
integer(4),pointer::nacclbdar
integer(4),pointer::ndrylbdar
integer(4),pointer::ndrylbdas
integer(4),pointer::ndrylbdag
integer(4),pointer::nwetlbdas
integer(4),pointer::nwetlbdag
integer(4),pointer::nwetlbdah
real(8),pointer::xgaminc_rdsf_r(:)
real(8),pointer::xgaminc_rim1(:)
real(8),pointer::xgaminc_rim2(:)
real(8),pointer::xgaminc_rim4(:)
real(8),pointer::xgaminc_hmc(:)
real(8),pointer::xgaminc_cibu_s(:,:)
real(8),pointer::xgaminc_cibu_g(:,:)
real(8),pointer::xker_raccss(:,:)
real(8),pointer::xker_raccs(:,:)
real(8),pointer::xker_saccrg(:,:)
real(8),pointer::xker_n_raccss(:,:)
real(8),pointer::xker_n_raccs(:,:)
real(8),pointer::xker_n_saccrg(:,:)
real(8),pointer::xker_sdryg(:,:)
real(8),pointer::xker_rdryg(:,:)
real(8),pointer::xker_n_sdryg(:,:)
real(8),pointer::xker_n_rdryg(:,:)
real(8),pointer::xker_sweth(:,:)
real(8),pointer::xker_gweth(:,:)
real(8),pointer::xker_n_sweth(:,:)
real(8),pointer::xker_n_gweth(:,:)
contains
subroutine param_lima_mixed_associate()
end
subroutine param_lima_mixed_allocate(hname,kdim1,kdim2)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in),optional::kdim2
end
end
