!mod$ v1 sum:ca95dcf298f8bbcf
!need$ 25b02d753545073c n modd_parameters
module modd_param_mfshall_n
use modd_parameters,only:jpmodelmax
type::param_mfshall_t
real(8)::ximpl_mf
character(4_4,1)::cmf_updraft
character(4_4,1)::cmf_cloud
character(4_4,1)::cwet_mixing
character(4_4,1)::ckic_compute
character(4_4,1)::cdetr_dry_lup
logical(4)::lmixuv
logical(4)::lmixtke
logical(4)::lmf_flx
real(8)::xalp_pert
real(8)::xabuo
real(8)::xbentr
real(8)::xbdetr
real(8)::xcmf
real(8)::xentr_mf
real(8)::xcrad_mf
real(8)::xentr_dry
real(8)::xdetr_dry
real(8)::xdetr_lup
real(8)::xkcf_mf
real(8)::xkrc_mf
real(8)::xtausigmf
real(8)::xpres_uv
real(8)::xalpha_mf
real(8)::xsigma_mf
real(8)::xsigma_env
real(8)::xfrac_up_max
real(8)::xa1
real(8)::xb
real(8)::xc
real(8)::xbeta1
real(8)::xr
logical(4)::lgz
real(8)::xgz
logical(4)::lthetas_mf
real(8)::xlambda_mf
logical(4)::lverlimup
logical(4)::lpz_exp_log
real(8)::xbrio
real(8)::xaadvec
logical(4)::lrelax_alpha_mf
end type
type(param_mfshall_t),save,target::param_mfshall_model(1_8:8_8)
type(param_mfshall_t),pointer,save::param_mfshalln
intrinsic::null
real(8),pointer::ximpl_mf
character(4_4,1),pointer::cmf_updraft
character(4_4,1),pointer::cmf_cloud
character(4_4,1),pointer::cwet_mixing
character(4_4,1),pointer::ckic_compute
character(4_4,1),pointer::cdetr_dry_lup
logical(4),pointer::lmixuv
logical(4),pointer::lmixtke
logical(4),pointer::lmf_flx
real(8),pointer::xalp_pert
real(8),pointer::xabuo
real(8),pointer::xbentr
real(8),pointer::xbdetr
real(8),pointer::xcmf
real(8),pointer::xentr_mf
real(8),pointer::xcrad_mf
real(8),pointer::xentr_dry
real(8),pointer::xdetr_dry
real(8),pointer::xdetr_lup
real(8),pointer::xkcf_mf
real(8),pointer::xkrc_mf
real(8),pointer::xtausigmf
real(8),pointer::xpres_uv
real(8),pointer::xalpha_mf
real(8),pointer::xsigma_mf
real(8),pointer::xsigma_env
real(8),pointer::xfrac_up_max
real(8),pointer::xa1
real(8),pointer::xb
real(8),pointer::xc
real(8),pointer::xbeta1
real(8),pointer::xr
logical(4),pointer::lthetas_mf
real(8),pointer::xlambda_mf
logical(4),pointer::lgz
real(8),pointer::xgz
logical(4),pointer::lverlimup
logical(4),pointer::lpz_exp_log
real(8),pointer::xbrio
real(8),pointer::xaadvec
logical(4),pointer::lrelax_alpha_mf
namelist/nam_param_mfshalln/ximpl_mf,cmf_updraft,cmf_cloud,cwet_mixing,lmixuv,lmixtke,lmf_flx,xalp_pert,xabuo,xbentr,xbdetr,xcmf,xentr_mf,xcrad_mf,xentr_dry,xdetr_dry,xdetr_lup,xkcf_mf,xkrc_mf,xtausigmf,xpres_uv,xalpha_mf,xsigma_mf,xsigma_env,xfrac_up_max,xa1,xb,xc,xbeta1,xr,lthetas_mf,lgz,xgz,lverlimup,lpz_exp_log,ckic_compute,cdetr_dry_lup,xbrio,xaadvec,lrelax_alpha_mf
contains
subroutine param_mfshall_goto_model(kfrom,kto)
integer(4),intent(in)::kfrom
integer(4),intent(in)::kto
end
subroutine param_mfshalln_init(hprogram,tfilenam,ldneednam,kluout,lddefaultval,ldreadnam,ldcheck,kprint)
use modd_io,only:tfiledata
character(6_4,1),intent(in)::hprogram
type(tfiledata),intent(in)::tfilenam
logical(4),intent(in)::ldneednam
integer(4),intent(in)::kluout
logical(4),intent(in),optional::lddefaultval
logical(4),intent(in),optional::ldreadnam
logical(4),intent(in),optional::ldcheck
integer(4),intent(in),optional::kprint
end
end
