!mod$ v1 sum:e13df4e7c0f096e5
!need$ 25b02d753545073c n modd_parameters
module modd_turb_n
use modd_parameters,only:jpmodelmax
type::turb_t
real(8)::ximpl
real(8)::xtkemin
real(8)::xced
real(8)::xctp
real(8)::xcshf
real(8)::xchf
real(8)::xctv
real(8)::xchv
real(8)::xcht1
real(8)::xcht2
real(8)::xcpr1
real(8)::xcadap
character(4_4,1)::cturblen
character(4_4,1)::cturbdim
logical(4)::lturb_flx
logical(4)::lturb_diag
logical(4)::lsig_conv
logical(4)::lharat
logical(4)::lbl89top
logical(4)::lbl89exp
logical(4)::lrmc01
character(4_4,1)::ctom
real(8),pointer::xdyp(:,:,:)=>NULL()
real(8),pointer::xthp(:,:,:)=>NULL()
real(8),pointer::xtr(:,:,:)=>NULL()
real(8),pointer::xdiss(:,:,:)=>NULL()
real(8),pointer::xlem(:,:,:)=>NULL()
real(8),pointer::xssufl_c(:,:,:)=>NULL()
real(8),pointer::xssvfl_c(:,:,:)=>NULL()
real(8),pointer::xsstfl_c(:,:,:)=>NULL()
real(8),pointer::xssrfl_c(:,:,:)=>NULL()
logical(4)::lleonard
real(8)::xcoefhgradthl
real(8)::xcoefhgradrm
real(8)::xalthgrad
logical(4)::lgoger
real(8)::xsmag
real(8)::xcldthold
real(8)::xlini
logical(4)::lrotate_wind
logical(4)::ltkeminturb
logical(4)::lprojqiturb
logical(4)::lsmooth_prandtl
real(8)::xminsigs
real(8)::xbl89exp
real(8)::xusrbl89
integer(4)::nturbsplit
logical(4)::lcloudmodiflm
character(4_4,1)::cturblen_cloud
real(8)::xcoef_ampl_sat
real(8)::xcei_min
real(8)::xcei_max
real(8),pointer::xcei(:,:,:)
logical(4)::lturb_precip
logical(4)::ldynmf
logical(4)::lthermmf
end type
intrinsic::null
type(turb_t),save,target::turb_model(1_8:8_8)
type(turb_t),pointer,save::turbn
real(8),pointer::ximpl
real(8),pointer::xtkemin
real(8),pointer::xced
real(8),pointer::xctp
real(8),pointer::xcshf
real(8),pointer::xchf
real(8),pointer::xctv
real(8),pointer::xchv
real(8),pointer::xcht1
real(8),pointer::xcht2
real(8),pointer::xcpr1
real(8),pointer::xcadap
character(4_4,1),pointer::cturblen
character(4_4,1),pointer::cturbdim
logical(4),pointer::lturb_flx
logical(4),pointer::lturb_diag
logical(4),pointer::lsig_conv
logical(4),pointer::lrmc01
logical(4),pointer::lharat
logical(4),pointer::lbl89top
logical(4),pointer::lbl89exp
character(4_4,1),pointer::ctom
real(8),pointer::xbl_depth(:,:)
real(8),pointer::xsbl_depth(:,:)
real(8),pointer::xwthvmf(:,:,:)
real(8),pointer::xwumf(:,:,:)
real(8),pointer::xwvmf(:,:,:)
real(8),pointer::xdyp(:,:,:)
real(8),pointer::xthp(:,:,:)
real(8),pointer::xtr(:,:,:)
real(8),pointer::xdiss(:,:,:)
real(8),pointer::xlem(:,:,:)
real(8),pointer::xssufl_c(:,:,:)
real(8),pointer::xssvfl_c(:,:,:)
real(8),pointer::xsstfl_c(:,:,:)
real(8),pointer::xssrfl_c(:,:,:)
logical(4),pointer::lleonard
real(8),pointer::xcoefhgradthl
real(8),pointer::xcoefhgradrm
real(8),pointer::xalthgrad
logical(4),pointer::lgoger
real(8),pointer::xsmag
real(8),pointer::xcldthold
real(8),pointer::xlini
logical(4),pointer::lrotate_wind
logical(4),pointer::ltkeminturb
logical(4),pointer::lprojqiturb
logical(4),pointer::lsmooth_prandtl
real(8),pointer::xminsigs
real(8),pointer::xbl89exp
real(8),pointer::xusrbl89
integer(4),pointer::nturbsplit
logical(4),pointer::lcloudmodiflm
character(4_4,1),pointer::cturblen_cloud
real(8),pointer::xcoef_ampl_sat
real(8),pointer::xcei_min
real(8),pointer::xcei_max
real(8),pointer::xcei(:,:,:)
logical(4),pointer::lturb_precip
logical(4),pointer::ldynmf
logical(4),pointer::lthermmf
namelist/nam_turbn/ximpl,cturblen,cturbdim,lturb_flx,lturb_diag,lsig_conv,lrmc01,ctom,xtkemin,xced,xctp,xcadap,lleonard,xcoefhgradthl,xcoefhgradrm,xalthgrad,lgoger,xsmag,xcldthold,xlini,lharat,lprojqiturb,lsmooth_prandtl,xminsigs,nturbsplit,lcloudmodiflm,cturblen_cloud,xcoef_ampl_sat,xcei_min,xcei_max,lturb_precip,ldynmf,lthermmf,lbl89top,lbl89exp
contains
subroutine turb_goto_model(kfrom,kto)
integer(4),intent(in)::kfrom
integer(4),intent(in)::kto
end
subroutine turbn_init(hprogram,tfilenam,ldneednam,kluout,lddefaultval,ldreadnam,ldcheck,kprint)
use modd_io,only:tfiledata
character(6_4,1),intent(in)::hprogram
type(tfiledata),intent(in)::tfilenam
logical(4),intent(in)::ldneednam
integer(4),intent(in)::kluout
logical(4),intent(in),optional::lddefaultval
logical(4),intent(in),optional::ldreadnam
logical(4),intent(in),optional::ldcheck
integer(4),intent(in),optional::kprint
end
end
