!mod$ v1 sum:2957080609654ec2
!need$ 25b02d753545073c n modd_parameters
module modd_param_lima_cold
use modd_parameters,only:jpsvnamelgtmax
type::param_lima_cold_t
real(8)::xlbexi
real(8)::xlbi
real(8)::xlbexs
real(8)::xlbs
real(8)::xns
real(8)::xai
real(8)::xbi
real(8)::xc_i
real(8)::xdi
real(8)::xf0i
real(8)::xf2i
real(8)::xc1i
real(8)::xf0is
real(8)::xf1is
real(8)::xdeltai
real(8)::xgammai
real(8)::xas
real(8)::xbs
real(8)::xcs
real(8)::xds
real(8)::xccs
real(8)::xcxs
real(8)::xf0s
real(8)::xf1s
real(8)::xc1s
real(8)::xlbdas_min
real(8)::xlbdas_max
real(8)::xfvelos
real(8)::xtrans_mp_gammas
real(8)::xreffi
real(8),allocatable::xlbexi_shape(:)
real(8),allocatable::xlbi_shape(:)
real(8),allocatable::xai_shape(:)
real(8),allocatable::xbi_shape(:)
real(8),allocatable::xc_i_shape(:)
real(8),allocatable::xdi_shape(:)
real(8),allocatable::xgammai_shape(:)
real(8),allocatable::xdeltai_shape(:)
real(8),allocatable::xc1i_shape(:)
real(8)::xfsedri
real(8)::xfsedci
real(8)::xfsedrs
real(8)::xfsedcs
real(8)::xfseds
real(8)::xexseds
real(8)::xnuc_dep
real(8)::xexsi_dep
real(8)::xex_dep
real(8)::xnuc_con
real(8)::xextt_con
real(8)::xex_con
real(8)::xmnu0
real(8)::xrhoi_honh
real(8)::xcexp_difvap_honh
real(8)::xcoef_difvap_honh
real(8)::xrcoef_honh
real(8)::xcritsat1_honh
real(8)::xcritsat2_honh
real(8)::xtmin_honh
real(8)::xtmax_honh
real(8)::xdlnjodt1_honh
real(8)::xdlnjodt2_honh
real(8)::xc1_honh
real(8)::xc2_honh
real(8)::xc3_honh
real(8)::xc_honc
real(8)::xr_honc
real(8)::xtexp1_honc
real(8)::xtexp2_honc
real(8)::xtexp3_honc
real(8)::xtexp4_honc
real(8)::xtexp5_honc
real(8)::xcscnvi_max
real(8)::xlbdascnvi_max
real(8)::xrhorsmin
real(8)::xdscnvi_lim
real(8)::xlbdascnvi_lim
real(8)::xc0depsi
real(8)::xc1depsi
real(8)::xr0depsi
real(8)::xr1depsi
real(8)::xscfac
real(8)::x0depi
real(8)::x2depi
real(8)::x0deps
real(8)::x1deps
real(8)::xex0deps
real(8)::xex1deps
real(8)::xdicnvs_lim
real(8)::xlbdaicnvs_lim
real(8)::xc0depis
real(8)::xc1depis
real(8)::xr0depis
real(8)::xr1depis
real(8)::xcolexis
real(8)::xaggs_clarge1
real(8)::xaggs_clarge2
real(8)::xaggs_rlarge1
real(8)::xaggs_rlarge2
real(8)::xfiaggs
real(8)::xexiaggs
real(8)::xaccs1
real(8)::xsponbuds1
real(8)::xsponbuds2
real(8)::xsponbuds3
real(8)::xsponcoefs2
real(8)::xker_zrnic_a1
real(8)::xker_zrnic_a2
real(8),allocatable::xker_n_sscs(:,:)
real(8)::xcolss
real(8)::xcolexss
real(8)::xfnsscs
real(8)::xlbnsscs1
real(8)::xlbnsscs2
real(8)::xscintp1s
real(8)::xscintp2s
integer(4)::nsclbdas
real(8),allocatable::xker_n_isci(:,:)
real(8)::xselfi
real(8)::xcolii
real(8)::xcolexii
real(8)::xfnisci
real(8)::xlbnisci1
real(8)::xlbnisci2
real(8)::xscintp1i
real(8)::xscintp2i
real(8)::xsclbdai_min
real(8)::xsclbdai_max
real(8),allocatable::xfiscs(:)
real(8),allocatable::xlbiscs1(:)
real(8),allocatable::xlbiscs2(:)
real(8),allocatable::xlbiscs3(:)
real(8),allocatable::xker_r_isci_shape(:,:,:)
real(8),allocatable::xker_n_isci_shape(:,:,:,:)
integer(4)::nsclbdai
real(8)::xauto3
real(8)::xauto4
real(8)::xlauts
real(8)::xlauts_threshold
real(8)::xitauts
real(8)::xitauts_threshold
real(8)::xtexauti
real(8)::xconci_max
real(8)::xfreffi
real(8)::xalpha1
real(8)::xalpha2
real(8)::xbeta1
real(8)::xbeta2
real(8)::xnu10
real(8)::xnu20
real(8),allocatable::xfsedci_shape(:)
real(8),allocatable::xfsedri_shape(:)
real(8),allocatable::xfsedri_tot_shape(:)
real(8),allocatable::xc0depsi_shape(:)
real(8),allocatable::xc1depsi_shape(:)
real(8),allocatable::xr0depsi_shape(:)
real(8),allocatable::xr1depsi_shape(:)
real(8),allocatable::x0depi_shape(:)
real(8),allocatable::x2depi_shape(:)
real(8),allocatable::xc0depis_shape(:)
real(8),allocatable::xc1depis_shape(:)
real(8),allocatable::xr0depis_shape(:)
real(8),allocatable::xr1depis_shape(:)
real(8),allocatable::xaggs_rlarge1_shape(:)
real(8),allocatable::xaggs_rlarge2_shape(:)
real(8),allocatable::xfreffi_shape(:)
end type
type(param_lima_cold_t),save,target::param_lima_cold
real(8),pointer::xlbexi
intrinsic::null
real(8),pointer::xlbi
real(8),pointer::xlbexs
real(8),pointer::xlbs
real(8),pointer::xns
real(8),pointer::xai
real(8),pointer::xbi
real(8),pointer::xgammai
real(8),pointer::xdeltai
real(8),pointer::xc_i
real(8),pointer::xdi
real(8),pointer::xf0i
real(8),pointer::xf2i
real(8),pointer::xc1i
real(8),pointer::xf0is
real(8),pointer::xf1is
real(8),pointer::xas
real(8),pointer::xbs
real(8),pointer::xcs
real(8),pointer::xds
real(8),pointer::xccs
real(8),pointer::xcxs
real(8),pointer::xf0s
real(8),pointer::xf1s
real(8),pointer::xc1s
real(8),pointer::xlbdas_min
real(8),pointer::xlbdas_max
real(8),pointer::xfvelos
real(8),pointer::xtrans_mp_gammas
real(8),pointer::xreffi
real(8),pointer::xfsedri
real(8),pointer::xfsedci
real(8),pointer::xfsedrs
real(8),pointer::xfsedcs
real(8),pointer::xfseds
real(8),pointer::xexseds
real(8),pointer::xnuc_dep
real(8),pointer::xexsi_dep
real(8),pointer::xex_dep
real(8),pointer::xnuc_con
real(8),pointer::xextt_con
real(8),pointer::xex_con
real(8),pointer::xmnu0
real(8),pointer::xrhoi_honh
real(8),pointer::xcexp_difvap_honh
real(8),pointer::xcoef_difvap_honh
real(8),pointer::xrcoef_honh
real(8),pointer::xcritsat1_honh
real(8),pointer::xcritsat2_honh
real(8),pointer::xtmin_honh
real(8),pointer::xtmax_honh
real(8),pointer::xdlnjodt1_honh
real(8),pointer::xdlnjodt2_honh
real(8),pointer::xc1_honh
real(8),pointer::xc2_honh
real(8),pointer::xc3_honh
real(8),pointer::xc_honc
real(8),pointer::xr_honc
real(8),pointer::xtexp1_honc
real(8),pointer::xtexp2_honc
real(8),pointer::xtexp3_honc
real(8),pointer::xtexp4_honc
real(8),pointer::xtexp5_honc
real(8),pointer::xcscnvi_max
real(8),pointer::xlbdascnvi_max
real(8),pointer::xrhorsmin
real(8),pointer::xdscnvi_lim
real(8),pointer::xlbdascnvi_lim
real(8),pointer::xc0depsi
real(8),pointer::xc1depsi
real(8),pointer::xr0depsi
real(8),pointer::xr1depsi
real(8),pointer::xscfac
real(8),pointer::x0depi
real(8),pointer::x2depi
real(8),pointer::x0deps
real(8),pointer::x1deps
real(8),pointer::xex0deps
real(8),pointer::xex1deps
real(8),pointer::xdicnvs_lim
real(8),pointer::xlbdaicnvs_lim
real(8),pointer::xc0depis
real(8),pointer::xc1depis
real(8),pointer::xr0depis
real(8),pointer::xr1depis
real(8),pointer::xcolexis
real(8),pointer::xaggs_clarge1
real(8),pointer::xaggs_clarge2
real(8),pointer::xaggs_rlarge1
real(8),pointer::xaggs_rlarge2
real(8),pointer::xfiaggs
real(8),pointer::xexiaggs
real(8),pointer::xaccs1
real(8),pointer::xsponbuds1
real(8),pointer::xsponbuds2
real(8),pointer::xsponbuds3
real(8),pointer::xsponcoefs2
real(8),pointer::xker_zrnic_a1
real(8),pointer::xker_zrnic_a2
real(8),pointer::xselfi
real(8),pointer::xcolss
real(8),pointer::xcolexss
real(8),pointer::xfnsscs
real(8),pointer::xlbnsscs1
real(8),pointer::xlbnsscs2
real(8),pointer::xscintp1s
real(8),pointer::xscintp2s
real(8),pointer::xcolii
real(8),pointer::xcolexii
real(8),pointer::xfnisci
real(8),pointer::xlbnisci1
real(8),pointer::xlbnisci2
real(8),pointer::xscintp1i
real(8),pointer::xscintp2i
real(8),pointer::xsclbdai_min
real(8),pointer::xsclbdai_max
real(8),pointer::xauto3
real(8),pointer::xauto4
real(8),pointer::xlauts
real(8),pointer::xlauts_threshold
real(8),pointer::xitauts
real(8),pointer::xitauts_threshold
real(8),pointer::xtexauti
real(8),pointer::xconci_max
real(8),pointer::xfreffi
real(8),pointer::xalpha1
real(8),pointer::xalpha2
real(8),pointer::xbeta1
real(8),pointer::xbeta2
real(8),pointer::xnu10
real(8),pointer::xnu20
integer(4),pointer::nsclbdas
real(8),pointer::xker_n_sscs(:,:)
integer(4),pointer::nsclbdai
real(8),pointer::xker_n_isci(:,:)
real(8),pointer::xlbiscs1(:)
real(8),pointer::xlbiscs2(:)
real(8),pointer::xlbiscs3(:)
real(8),pointer::xfiscs(:)
real(8),pointer::xker_r_isci_shape(:,:,:)
real(8),pointer::xker_n_isci_shape(:,:,:,:)
real(8),pointer::xlbexi_shape(:)
real(8),pointer::xlbi_shape(:)
real(8),pointer::xai_shape(:)
real(8),pointer::xbi_shape(:)
real(8),pointer::xc_i_shape(:)
real(8),pointer::xdi_shape(:)
real(8),pointer::xgammai_shape(:)
real(8),pointer::xdeltai_shape(:)
real(8),pointer::xc1i_shape(:)
real(8),pointer::xfsedci_shape(:)
real(8),pointer::xfsedri_shape(:)
real(8),pointer::xfsedri_tot_shape(:)
real(8),pointer::xc0depsi_shape(:)
real(8),pointer::xc1depsi_shape(:)
real(8),pointer::xr0depsi_shape(:)
real(8),pointer::xr1depsi_shape(:)
real(8),pointer::x0depi_shape(:)
real(8),pointer::x2depi_shape(:)
real(8),pointer::xc0depis_shape(:)
real(8),pointer::xc1depis_shape(:)
real(8),pointer::xr0depis_shape(:)
real(8),pointer::xr1depis_shape(:)
real(8),pointer::xaggs_rlarge1_shape(:)
real(8),pointer::xaggs_rlarge2_shape(:)
real(8),pointer::xfreffi_shape(:)
character(10_4,1),parameter::clima_cold_names(1_8:8_8)=[CHARACTER(KIND=1,LEN=10)::"CICE      ","CSNOW     ","CGRAUPEL  ","CHAIL     ","CIFNFREE  ","CIFNNUCL  ","CCNINIMM  ","CCCNNUCL  "]
character(10_4,1),parameter::clima_cold_conc(1_8:8_8)=[CHARACTER(KIND=1,LEN=10)::"NI        ","NS        ","NG        ","NH        ","NIF       ","NIN       ","NNI       ","NNH       "]
character(10_4,1),parameter::clima_shape_names(1_8:4_8)=[CHARACTER(KIND=1,LEN=10)::"CICE      ","CICE2     ","CICE3     ","CICE4     "]
character(5_4,1),parameter::clima_shape_conc(1_8:4_8)=[CHARACTER(KIND=1,LEN=5)::"N_001","N_002","N_003","N_004"]
contains
subroutine param_lima_cold_associate()
end
subroutine param_lima_cold_allocate(hname,kdim1,kdim2)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in)::kdim2
end
subroutine param_lima_cold_allocate_1d(hname,kdim1)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
end
subroutine param_lima_cold_allocate_3d(hname,kdim1,kdim2,kdim3)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in)::kdim2
integer(4),intent(in)::kdim3
end
subroutine param_lima_cold_allocate_4d(hname,kdim1,kdim2,kdim3,kdim4)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in)::kdim2
integer(4),intent(in)::kdim3
integer(4),intent(in)::kdim4
end
end
