!mod$ v1 sum:541798f82b757715
!need$ 25b02d753545073c n modd_parameters
module modd_param_ice_n
use modd_parameters,only:jpmodelmax
type::param_ice_t
logical(4)::lwarm
logical(4)::lsedic
logical(4)::ldeposc
real(8)::xvdeposc
character(4_4,1)::cpristine_ice
character(4_4,1)::csedim
logical(4)::lred
logical(4)::lfeedbackt
logical(4)::levlimit
logical(4)::lnullwetg
logical(4)::lwetgpost
logical(4)::lnullweth
logical(4)::lwethpost
character(4_4,1)::csnowriming
real(8)::xfracm90
integer(4)::nmaxiter_micro
real(8)::xmrstep
logical(4)::lconvhg
logical(4)::lcrflimit
real(8)::xtstep_ts
character(80_4,1)::csubg_rc_rr_accr
character(80_4,1)::csubg_rr_evap
character(80_4,1)::csubg_pr_pdf
character(4_4,1)::csubg_aucv_rc
character(80_4,1)::csubg_aucv_ri
character(80_4,1)::csubg_mf_pdf
logical(4)::ladj_before
logical(4)::ladj_after
logical(4)::lsedim_after
real(8)::xsplit_maxcfl
logical(4)::lsnow_t
logical(4)::lpack_interp
logical(4)::lpack_micro
integer(4)::npromicro
logical(4)::lcriauti
real(8)::xcriauti_nam
real(8)::xt0criauti_nam
real(8)::xbcriauti_nam
real(8)::xacriauti_nam
real(8)::xcriautc_nam
real(8)::xrdepsred_nam
real(8)::xrdepgred_nam
logical(4)::locnd2
logical(4)::lkogan
logical(4)::lmodicedep
logical(4)::lexcldrop
real(8)::xfrmin_nam(1_8:40_8)
end type
type(param_ice_t),save,target::param_ice_model(1_8:8_8)
type(param_ice_t),pointer,save::param_icen
intrinsic::null
logical(4),pointer::lwarm
logical(4),pointer::lsedic
logical(4),pointer::ldeposc
logical(4),pointer::lred
logical(4),pointer::lfeedbackt
logical(4),pointer::levlimit
logical(4),pointer::lnullwetg
logical(4),pointer::lwetgpost
logical(4),pointer::lnullweth
logical(4),pointer::lwethpost
logical(4),pointer::lconvhg
logical(4),pointer::lcrflimit
logical(4),pointer::ladj_before
logical(4),pointer::ladj_after
logical(4),pointer::lsedim_after
logical(4),pointer::lsnow_t
logical(4),pointer::lpack_interp
logical(4),pointer::lpack_micro
logical(4),pointer::lcriauti
logical(4),pointer::locnd2
logical(4),pointer::lkogan
logical(4),pointer::lmodicedep
logical(4),pointer::lexcldrop
real(8),pointer::xvdeposc
real(8),pointer::xfracm90
real(8),pointer::xmrstep
real(8),pointer::xtstep_ts
real(8),pointer::xsplit_maxcfl
real(8),pointer::xcriauti_nam
real(8),pointer::xt0criauti_nam
real(8),pointer::xbcriauti_nam
real(8),pointer::xacriauti_nam
real(8),pointer::xcriautc_nam
real(8),pointer::xrdepsred_nam
real(8),pointer::xrdepgred_nam
real(8),pointer::xfrmin_nam(:)
integer(4),pointer::nmaxiter_micro
integer(4),pointer::npromicro
character(4_4,1),pointer::cpristine_ice
character(4_4,1),pointer::csedim
character(4_4,1),pointer::csnowriming
character(80_4,1),pointer::csubg_rc_rr_accr
character(80_4,1),pointer::csubg_rr_evap
character(80_4,1),pointer::csubg_pr_pdf
character(4_4,1),pointer::csubg_aucv_rc
character(80_4,1),pointer::csubg_aucv_ri
character(80_4,1),pointer::csubg_mf_pdf
namelist/nam_param_icen/lwarm,lsedic,lconvhg,cpristine_ice,csedim,ldeposc,xvdeposc,lred,lfeedbackt,levlimit,lnullwetg,lwetgpost,lnullweth,lwethpost,csnowriming,xfracm90,nmaxiter_micro,xmrstep,xtstep_ts,ladj_before,ladj_after,lcrflimit,xsplit_maxcfl,lsedim_after,lsnow_t,lpack_interp,lpack_micro,npromicro,csubg_rc_rr_accr,csubg_rr_evap,csubg_pr_pdf,csubg_aucv_rc,csubg_aucv_ri,lcriauti,xcriauti_nam,xt0criauti_nam,xbcriauti_nam,xacriauti_nam,xcriautc_nam,xrdepsred_nam,xrdepgred_nam,locnd2,lkogan,lmodicedep,lexcldrop,xfrmin_nam,csubg_mf_pdf
contains
subroutine param_ice_goto_model(kfrom,kto)
integer(4),intent(in)::kfrom
integer(4),intent(in)::kto
end
subroutine param_icen_init(hprogram,tfilenam,ldneednam,kluout,lddefaultval,ldreadnam,ldcheck,kprint)
use modd_io,only:tfiledata
character(6_4,1),intent(in)::hprogram
type(tfiledata),intent(in)::tfilenam
logical(4),intent(in)::ldneednam
integer(4),intent(in)::kluout
logical(4),intent(in),optional::lddefaultval
logical(4),intent(in),optional::ldreadnam
logical(4),intent(in),optional::ldcheck
integer(4),intent(in),optional::kprint
end
end
