!mod$ v1 sum:293086545750eba9
!need$ 25b02d753545073c n modd_parameters
!need$ 38b69ded9c912757 n modd_tiwmx
module modd_rain_ice_param_n
use modd_parameters,only:jpmodelmax
use modd_tiwmx,only:tiwmx_t
type::rain_ice_param_t
real(8)::xfsedc(1_8:2_8)
real(8)::xfsedr
real(8)::xexsedr
real(8)::xfsedi
real(8)::xexcsedi
real(8)::xexrsedi
real(8)::xfseds
real(8)::xexseds
real(8)::xfsedg
real(8)::xexsedg
real(8)::xnu10
real(8)::xalpha1
real(8)::xbeta1
real(8)::xnu20
real(8)::xalpha2
real(8)::xbeta2
real(8)::xmnu0
real(8)::xalpha3
real(8)::xbeta3
real(8)::xhon
real(8)::xscfac
real(8)::x0evar
real(8)::x1evar
real(8)::xex0evar
real(8)::xex1evar
real(8)::x0depi
real(8)::x2depi
real(8)::x0deps
real(8)::x1deps
real(8)::xex0deps
real(8)::xex1deps
real(8)::xrdepsred
real(8)::x0depg
real(8)::x1depg
real(8)::xex0depg
real(8)::xex1depg
real(8)::xrdepgred
real(8)::xtimauti
real(8)::xtexauti
real(8)::xcriauti
real(8)::xt0criauti
real(8)::xacriauti
real(8)::xbcriauti
real(8)::xcolis
real(8)::xcolexis
real(8)::xfiaggs
real(8)::xexiaggs
real(8)::xtimautc
real(8)::xcriautc
real(8)::xfcaccr
real(8)::xexcaccr
real(8)::xdcslim
real(8)::xcolcs
real(8)::xexcrimss
real(8)::xcrimss
real(8)::xexcrimsg
real(8)::xcrimsg
real(8)::xexsrimcg
real(8)::xsrimcg
real(8)::xexsrimcg2
real(8)::xsrimcg2
real(8)::xsrimcg3
real(8)::xgaminc_bound_min
real(8)::xgaminc_bound_max
real(8)::xrimintp1
real(8)::xrimintp2
integer(4)::ngaminc
real(8),allocatable::xgaminc_rim1(:)
real(8),allocatable::xgaminc_rim2(:)
real(8),allocatable::xgaminc_rim4(:)
real(8)::xfraccss
real(8)::xlbraccs1
real(8)::xlbraccs2
real(8)::xlbraccs3
real(8)::xfsaccrg
real(8)::xlbsaccr1
real(8)::xlbsaccr2
real(8)::xlbsaccr3
real(8)::xacclbdas_min
real(8)::xacclbdas_max
real(8)::xacclbdar_min
real(8)::xacclbdar_max
real(8)::xaccintp1s
real(8)::xaccintp2s
real(8)::xaccintp1r
real(8)::xaccintp2r
integer(4)::nacclbdas
integer(4)::nacclbdar
real(8),allocatable::xker_raccss(:,:)
real(8),allocatable::xker_raccs(:,:)
real(8),allocatable::xker_saccrg(:,:)
real(8)::xfscvmg
real(8)::xcolir
real(8)::xexrcfri
real(8)::xrcfri
real(8)::xexicfrr
real(8)::xicfrr
real(8)::xfcdryg
real(8)::xcolig
real(8)::xcolexig
real(8)::xfidryg
real(8)::xfidryg2
real(8)::xexfidryg
real(8)::xcolsg
real(8)::xcolexsg
real(8)::xfsdryg
real(8)::xlbsdryg1
real(8)::xlbsdryg2
real(8)::xlbsdryg3
real(8)::xfrdryg
real(8)::xlbrdryg1
real(8)::xlbrdryg2
real(8)::xlbrdryg3
real(8)::xdrylbdar_min
real(8)::xdrylbdar_max
real(8)::xdrylbdas_min
real(8)::xdrylbdas_max
real(8)::xdrylbdag_min
real(8)::xdrylbdag_max
real(8)::xdryintp1r
real(8)::xdryintp2r
real(8)::xdryintp1s
real(8)::xdryintp2s
real(8)::xdryintp1g
real(8)::xdryintp2g
integer(4)::ndrylbdar
integer(4)::ndrylbdas
integer(4)::ndrylbdag
real(8),allocatable::xker_sdryg(:,:)
real(8),allocatable::xker_rdryg(:,:)
real(8)::xfsedh
real(8)::xexsedh
real(8)::x0deph
real(8)::x1deph
real(8)::xex0deph
real(8)::xex1deph
real(8)::xcolih
real(8)::xcolexih
real(8)::xcolsh
real(8)::xcolexsh
real(8)::xcolgh
real(8)::xcolexgh
real(8)::xfweth
real(8)::xfsweth
real(8)::xlbsweth1
real(8)::xlbsweth2
real(8)::xlbsweth3
real(8)::xfgweth
real(8)::xlbgweth1
real(8)::xlbgweth2
real(8)::xlbgweth3
real(8)::xfrweth
real(8)::xlbrweth1
real(8)::xlbrweth2
real(8)::xlbrweth3
real(8)::xwetlbdas_min
real(8)::xwetlbdas_max
real(8)::xwetlbdag_min
real(8)::xwetlbdag_max
real(8)::xwetlbdar_min
real(8)::xwetlbdar_max
real(8)::xwetlbdah_min
real(8)::xwetlbdah_max
real(8)::xwetintp1s
real(8)::xwetintp2s
real(8)::xwetintp1g
real(8)::xwetintp2g
real(8)::xwetintp1r
real(8)::xwetintp2r
real(8)::xwetintp1h
real(8)::xwetintp2h
integer(4)::nwetlbdas
integer(4)::nwetlbdag
integer(4)::nwetlbdar
integer(4)::nwetlbdah
real(8),allocatable::xker_sweth(:,:)
real(8),allocatable::xker_gweth(:,:)
real(8),allocatable::xker_rweth(:,:)
real(8)::xfrmin(1_8:40_8)
type(tiwmx_t),pointer::tiwmx
logical(4)::lnewcoeff
end type
type(rain_ice_param_t),save,target::rain_ice_param_model(1_8:8_8)
type(rain_ice_param_t),pointer,save::rain_ice_paramn
intrinsic::null
real(8),pointer::xfsedc(:)
real(8),pointer::xfrmin(:)
real(8),pointer::xfsedr
real(8),pointer::xexsedr
real(8),pointer::xfsedi
real(8),pointer::xexcsedi
real(8),pointer::xexrsedi
real(8),pointer::xfseds
real(8),pointer::xexseds
real(8),pointer::xfsedg
real(8),pointer::xexsedg
real(8),pointer::xnu10
real(8),pointer::xalpha1
real(8),pointer::xbeta1
real(8),pointer::xnu20
real(8),pointer::xalpha2
real(8),pointer::xbeta2
real(8),pointer::xmnu0
real(8),pointer::xalpha3
real(8),pointer::xbeta3
real(8),pointer::xhon
real(8),pointer::xscfac
real(8),pointer::x0evar
real(8),pointer::x1evar
real(8),pointer::xex0evar
real(8),pointer::xex1evar
real(8),pointer::x0depi
real(8),pointer::x2depi
real(8),pointer::x0deps
real(8),pointer::x1deps
real(8),pointer::xex0deps
real(8),pointer::xex1deps
real(8),pointer::xrdepsred
real(8),pointer::x0depg
real(8),pointer::x1depg
real(8),pointer::xex0depg
real(8),pointer::xex1depg
real(8),pointer::xrdepgred
real(8),pointer::xtimauti
real(8),pointer::xtexauti
real(8),pointer::xcriauti
real(8),pointer::xt0criauti
real(8),pointer::xacriauti
real(8),pointer::xbcriauti
real(8),pointer::xcolis
real(8),pointer::xcolexis
real(8),pointer::xfiaggs
real(8),pointer::xexiaggs
real(8),pointer::xtimautc
real(8),pointer::xcriautc
real(8),pointer::xfcaccr
real(8),pointer::xexcaccr
real(8),pointer::xdcslim
real(8),pointer::xcolcs
real(8),pointer::xexcrimss
real(8),pointer::xcrimss
real(8),pointer::xexcrimsg
real(8),pointer::xcrimsg
real(8),pointer::xexsrimcg
real(8),pointer::xsrimcg
real(8),pointer::xexsrimcg2
real(8),pointer::xsrimcg2
real(8),pointer::xsrimcg3
real(8),pointer::xgaminc_bound_min
real(8),pointer::xgaminc_bound_max
real(8),pointer::xrimintp1
real(8),pointer::xrimintp2
real(8),pointer::xfraccss
real(8),pointer::xlbraccs1
real(8),pointer::xlbraccs2
real(8),pointer::xlbraccs3
real(8),pointer::xfsaccrg
real(8),pointer::xlbsaccr1
real(8),pointer::xlbsaccr2
real(8),pointer::xlbsaccr3
real(8),pointer::xacclbdas_min
real(8),pointer::xacclbdas_max
real(8),pointer::xacclbdar_min
real(8),pointer::xacclbdar_max
real(8),pointer::xaccintp1s
real(8),pointer::xaccintp2s
real(8),pointer::xaccintp1r
real(8),pointer::xaccintp2r
real(8),pointer::xfscvmg
real(8),pointer::xcolir
real(8),pointer::xexrcfri
real(8),pointer::xrcfri
real(8),pointer::xexicfrr
real(8),pointer::xicfrr
real(8),pointer::xfcdryg
real(8),pointer::xcolig
real(8),pointer::xcolexig
real(8),pointer::xfidryg
real(8),pointer::xfidryg2
real(8),pointer::xexfidryg
real(8),pointer::xcolsg
real(8),pointer::xcolexsg
real(8),pointer::xfsdryg
real(8),pointer::xlbsdryg1
real(8),pointer::xlbsdryg2
real(8),pointer::xlbsdryg3
real(8),pointer::xfrdryg
real(8),pointer::xlbrdryg1
real(8),pointer::xlbrdryg2
real(8),pointer::xlbrdryg3
real(8),pointer::xdrylbdar_min
real(8),pointer::xdrylbdar_max
real(8),pointer::xdrylbdas_min
real(8),pointer::xdrylbdas_max
real(8),pointer::xdrylbdag_min
real(8),pointer::xdrylbdag_max
real(8),pointer::xdryintp1r
real(8),pointer::xdryintp2r
real(8),pointer::xdryintp1s
real(8),pointer::xdryintp2s
real(8),pointer::xdryintp1g
real(8),pointer::xdryintp2g
real(8),pointer::xfsedh
real(8),pointer::xexsedh
real(8),pointer::x0deph
real(8),pointer::x1deph
real(8),pointer::xex0deph
real(8),pointer::xex1deph
real(8),pointer::xcolih
real(8),pointer::xcolexih
real(8),pointer::xcolsh
real(8),pointer::xcolexsh
real(8),pointer::xcolgh
real(8),pointer::xcolexgh
real(8),pointer::xfweth
real(8),pointer::xfsweth
real(8),pointer::xlbsweth1
real(8),pointer::xlbsweth2
real(8),pointer::xlbsweth3
real(8),pointer::xfgweth
real(8),pointer::xlbgweth1
real(8),pointer::xlbgweth2
real(8),pointer::xlbgweth3
real(8),pointer::xfrweth
real(8),pointer::xlbrweth1
real(8),pointer::xlbrweth2
real(8),pointer::xlbrweth3
real(8),pointer::xwetlbdas_min
real(8),pointer::xwetlbdas_max
real(8),pointer::xwetlbdag_min
real(8),pointer::xwetlbdag_max
real(8),pointer::xwetlbdar_min
real(8),pointer::xwetlbdar_max
real(8),pointer::xwetlbdah_min
real(8),pointer::xwetlbdah_max
real(8),pointer::xwetintp1s
real(8),pointer::xwetintp2s
real(8),pointer::xwetintp1g
real(8),pointer::xwetintp2g
real(8),pointer::xwetintp1r
real(8),pointer::xwetintp2r
real(8),pointer::xwetintp1h
real(8),pointer::xwetintp2h
integer(4),pointer::ngaminc
integer(4),pointer::nacclbdas
integer(4),pointer::nacclbdar
integer(4),pointer::ndrylbdar
integer(4),pointer::ndrylbdas
integer(4),pointer::ndrylbdag
integer(4),pointer::nwetlbdas
integer(4),pointer::nwetlbdag
integer(4),pointer::nwetlbdar
integer(4),pointer::nwetlbdah
real(8),pointer::xgaminc_rim1(:)
real(8),pointer::xgaminc_rim2(:)
real(8),pointer::xgaminc_rim4(:)
real(8),pointer::xker_raccss(:,:)
real(8),pointer::xker_raccs(:,:)
real(8),pointer::xker_saccrg(:,:)
real(8),pointer::xker_sdryg(:,:)
real(8),pointer::xker_rdryg(:,:)
real(8),pointer::xker_sweth(:,:)
real(8),pointer::xker_gweth(:,:)
real(8),pointer::xker_rweth(:,:)
logical(4),pointer::lnewcoeff
contains
subroutine rain_ice_param_goto_model(kfrom,kto)
integer(4),intent(in)::kfrom
integer(4),intent(in)::kto
end
subroutine helper1(xpt,xarr)
real(8),intent(inout),pointer::xpt(:)
real(8),allocatable,intent(inout),target::xarr(:)
end
subroutine helper2(xpt,xarr)
real(8),intent(inout),pointer::xpt(:,:)
real(8),allocatable,intent(inout),target::xarr(:,:)
end
subroutine rain_ice_param_allocate(hname,kdim1,kdim2)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in),optional::kdim2
end
subroutine rain_ice_param_deallocate()
end
end
