!mod$ v1 sum:ae0737809c65fa28
!need$ 25b02d753545073c n modd_parameters
module modd_param_lima_warm
use modd_parameters,only:jpsvnamelgtmax
type::param_lima_warm_t
real(8)::xlbc
real(8)::xlbexc
real(8)::xlbr
real(8)::xlbexr
real(8)::xnr
real(8)::xar
real(8)::xbr
real(8)::xcr
real(8)::xdr
real(8)::xf0r
real(8)::xf1r
real(8)::xccr
real(8)::xcxr
real(8)::xac
real(8)::xbc
real(8)::xcc
real(8)::xdc
real(8)::xf0c
real(8)::xf2c
real(8)::xc1c
real(8)::xfsedrr
real(8)::xfsedcr
real(8)::xfsedrc
real(8)::xfsedcc
real(8)::xgcc
real(8)::xdiva
real(8)::xthco
real(8)::xwmin
real(8)::xtmin
real(8)::xcsthen
real(8)::xcstdcrit
integer(4)::nhyp
real(8)::xhypintp1
real(8)::xhypintp2
real(8),allocatable::xhypf12(:,:)
real(8),allocatable::xhypf32(:,:)
integer(4)::nahen
real(8)::xahenintp1
real(8)::xahenintp2
real(8),allocatable::xaheng(:)
real(8),allocatable::xaheng2(:)
real(8),allocatable::xaheng3(:)
real(8),allocatable::xpsi1(:)
real(8),allocatable::xpsi3(:)
real(8),allocatable::xahenf(:)
real(8),allocatable::xaheny(:)
real(8)::xwcoef_f1
real(8)::xwcoef_f2
real(8)::xwcoef_f3
real(8)::xwcoef_y1
real(8)::xwcoef_y2
real(8)::xwcoef_y3
real(8)::xkera1
real(8)::xkera2
real(8)::xselfc
real(8)::xauto1
real(8)::xauto2
real(8)::xcautr
real(8)::xlautr
real(8)::xlautr_threshold
real(8)::xitautr
real(8)::xitautr_threshold
real(8)::xr0
real(8)::xaccr1
real(8)::xaccr2
real(8)::xaccr3
real(8)::xaccr4
real(8)::xaccr5
real(8)::xaccr6
real(8)::xaccr_clarge1
real(8)::xaccr_clarge2
real(8)::xaccr_rlarge1
real(8)::xaccr_rlarge2
real(8)::xaccr_csmall1
real(8)::xaccr_csmall2
real(8)::xaccr_rsmall1
real(8)::xaccr_rsmall2
real(8)::xfcaccr
real(8)::xexcaccr
real(8)::xscbu2
real(8)::xscbu3
real(8)::xscbu_eff1
real(8)::xscbu_eff2
real(8)::xscbuexp1
real(8)::xsponbud1
real(8)::xsponbud2
real(8)::xsponbud3
real(8)::xsponcoef2
real(8)::x0evar
real(8)::x1evar
real(8)::xex0evar
real(8)::xex1evar
real(8)::xex2evar
real(8)::xcevap
real(8),allocatable::xconcc_ini(:,:,:,:)
real(8)::xconcr_param_ini
real(8)::x0cndc
real(8)::x2cndc
real(8)::xfreffc
real(8)::xfreffr
real(8)::xcrec
real(8)::xcrer
end type
type(param_lima_warm_t),save,target::param_lima_warm
real(8),pointer::xlbc
intrinsic::null
real(8),pointer::xlbexc
real(8),pointer::xlbr
real(8),pointer::xlbexr
real(8),pointer::xnr
real(8),pointer::xar
real(8),pointer::xbr
real(8),pointer::xcr
real(8),pointer::xdr
real(8),pointer::xf0r
real(8),pointer::xf1r
real(8),pointer::xccr
real(8),pointer::xcxr
real(8),pointer::xac
real(8),pointer::xbc
real(8),pointer::xcc
real(8),pointer::xdc
real(8),pointer::xf0c
real(8),pointer::xf2c
real(8),pointer::xc1c
real(8),pointer::xfsedrr
real(8),pointer::xfsedcr
real(8),pointer::xfsedrc
real(8),pointer::xfsedcc
real(8),pointer::xgcc
real(8),pointer::xdiva
real(8),pointer::xthco
real(8),pointer::xwmin
real(8),pointer::xtmin
real(8),pointer::xcsthen
real(8),pointer::xcstdcrit
real(8),pointer::xhypintp1
real(8),pointer::xhypintp2
real(8),pointer::xahenintp1
real(8),pointer::xahenintp2
real(8),pointer::xwcoef_f1
real(8),pointer::xwcoef_f2
real(8),pointer::xwcoef_f3
real(8),pointer::xwcoef_y1
real(8),pointer::xwcoef_y2
real(8),pointer::xwcoef_y3
real(8),pointer::xkera1
real(8),pointer::xkera2
real(8),pointer::xselfc
real(8),pointer::xauto1
real(8),pointer::xauto2
real(8),pointer::xcautr
real(8),pointer::xlautr
real(8),pointer::xlautr_threshold
real(8),pointer::xitautr
real(8),pointer::xitautr_threshold
real(8),pointer::xr0
real(8),pointer::xaccr1
real(8),pointer::xaccr2
real(8),pointer::xaccr3
real(8),pointer::xaccr4
real(8),pointer::xaccr5
real(8),pointer::xaccr6
real(8),pointer::xaccr_clarge1
real(8),pointer::xaccr_clarge2
real(8),pointer::xaccr_rlarge1
real(8),pointer::xaccr_rlarge2
real(8),pointer::xaccr_csmall1
real(8),pointer::xaccr_csmall2
real(8),pointer::xaccr_rsmall1
real(8),pointer::xaccr_rsmall2
real(8),pointer::xfcaccr
real(8),pointer::xexcaccr
real(8),pointer::xscbu2
real(8),pointer::xscbu3
real(8),pointer::xscbu_eff1
real(8),pointer::xscbu_eff2
real(8),pointer::xscbuexp1
real(8),pointer::xsponbud1
real(8),pointer::xsponbud2
real(8),pointer::xsponbud3
real(8),pointer::xsponcoef2
real(8),pointer::x0evar
real(8),pointer::x1evar
real(8),pointer::xex0evar
real(8),pointer::xex1evar
real(8),pointer::xex2evar
real(8),pointer::xcevap
real(8),pointer::xconcr_param_ini
real(8),pointer::x0cndc
real(8),pointer::x2cndc
real(8),pointer::xfreffc
real(8),pointer::xfreffr
real(8),pointer::xcrec
real(8),pointer::xcrer
integer(4),pointer::nhyp
integer(4),pointer::nahen
real(8),pointer::xhypf12(:,:)
real(8),pointer::xhypf32(:,:)
real(8),pointer::xaheng(:)
real(8),pointer::xaheng2(:)
real(8),pointer::xaheng3(:)
real(8),pointer::xpsi1(:)
real(8),pointer::xpsi3(:)
real(8),pointer::xahenf(:)
real(8),pointer::xaheny(:)
real(8),pointer::xconcc_ini(:,:,:,:)
character(10_4,1),parameter::clima_warm_names(1_8:5_8)=[CHARACTER(KIND=1,LEN=10)::"CCLOUD    ","CRAIN     ","CCCNFREE  ","CCCNACTI  ","SPRO      "]
character(10_4,1),parameter::clima_warm_conc(1_8:5_8)=[CHARACTER(KIND=1,LEN=10)::"NC        ","NR        ","NFREE     ","NCCN      ","SS        "]
character(10_4,1),parameter::caero_mass(1_8:2_8)=[CHARACTER(KIND=1,LEN=10)::"MASSAP    ","MAP       "]
contains
subroutine param_lima_warm_associate()
end
subroutine param_lima_warm_allocate(hname,kdim1,kdim2,kdim3,kdim4)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in),optional::kdim2
integer(4),intent(in),optional::kdim3
integer(4),intent(in),optional::kdim4
end
end
