!mod$ v1 sum:9206eb5ddd5977fb
!need$ 25b02d753545073c n modd_parameters
module modd_param_lima
use modd_parameters,only:jplimaccnmax
use modd_parameters,only:jplimaifnmax
use modd_parameters,only:nnbcrystalmax
type::param_lima_t
logical(4)::llima_diag
logical(4)::lptsplit
logical(4)::lfeedbackt
integer(4)::nmaxiter
real(8)::xmrstep
real(8)::xtstep_ts
logical(4)::lnucl
logical(4)::lsedi
logical(4)::lhhoni
logical(4)::lmeyers
logical(4)::lcibu
logical(4)::lrdsf
logical(4)::lcrystal_shape
logical(4)::lice_isc
integer(4)::nmom_i
integer(4)::nmom_s
integer(4)::nmom_g
integer(4)::nmom_h
integer(4)::nmod_ifn
real(8)::xifn_conc(1_8:10_8)
logical(4)::lifn_hom
character(8_4,1)::cifn_species
character(8_4,1)::cint_mixing
integer(4)::nmod_imm
integer(4)::nind_specie
integer(4),allocatable::nimm(:)
integer(4),allocatable::nindice_ccn_imm(:)
integer(4)::nspecie
real(8),allocatable::xmdiam_ifn(:)
real(8),allocatable::xsigma_ifn(:)
real(8),allocatable::xrho_ifn(:)
real(8),allocatable::xfrac(:,:)
real(8),allocatable::xfrac_ref(:)
real(8),allocatable::xginc_ifn(:)
logical(4)::lsnow_t
logical(4)::lmurakami
character(4_4,1)::cpristine_ice_lima
character(4_4,1)::chevrimed_ice_lima
real(8)::xalphai
real(8)::xnui
real(8)::xalphas
real(8)::xnus
real(8)::xalphag
real(8)::xnug
integer(4)::nnb_crystal_shape
character(4_4,1)::htype_crystal_shape(1_8:4_8)
logical(4)::lsigmoide_g
logical(4)::lsigmoide_ng
real(8)::xsigmoide_g
real(8)::xmvdmin_g
integer(4)::nphillips
real(8)::xt0(1_8:4_8)
real(8)::xdt0(1_8:4_8)
real(8)::xdsi0(1_8:4_8)
real(8)::xsw0
real(8)::xrho_cfdc
real(8)::xh(1_8:4_8)
real(8)::xarea1(1_8:4_8)
real(8)::xgamma
real(8)::xtx1(1_8:4_8)
real(8)::xtx2(1_8:4_8)
real(8),allocatable::xabsciss(:)
real(8),allocatable::xweight(:)
integer(4)::ndiam
real(8)::xfactnuc_dep
real(8)::xfactnuc_con
real(8)::xndebris_cibu
real(8)::xpsh_max_rdsf
logical(4)::lacti
logical(4)::lsedc
logical(4)::lactit
logical(4)::ldepoc
logical(4)::lacttke
logical(4)::ladj
logical(4)::lspro
logical(4)::lkhko
logical(4)::lkesslerac
integer(4)::nmom_c
integer(4)::nmom_r
integer(4)::nmod_ccn
real(8)::xccn_conc(1_8:10_8)
logical(4)::lccn_hom
character(8_4,1)::cccn_modes
real(8),allocatable::xr_mean_ccn(:)
real(8),allocatable::xlogsig_ccn(:)
real(8),allocatable::xrho_ccn(:)
real(8),allocatable::xkhen_multi(:)
real(8),allocatable::xmuhen_multi(:)
real(8),allocatable::xbetahen_multi(:)
real(8),allocatable::xgmulti(:)
real(8),allocatable::xconc_ccn_tot(:,:,:)
real(8),allocatable::xlimit_factor(:)
real(8)::xalphar
real(8)::xnur
real(8)::xalphac
real(8)::xnuc
character(3_4,1)::hparam_ccn="CPB"
character(3_4,1)::hini_ccn
character(10_4,1)::htype_ccn(1_8:10_8)
real(8)::xfsolub_ccn
real(8)::xactemp_ccn
real(8)::xaerdiff
real(8)::xaerheight
real(8)::xvdepoc
logical(4)::lscav
logical(4)::laero_mass
integer(4)::ndiamr=20_4
integer(4)::ndiamp=20_4
real(8)::xt0scav=2.931499999999999772626324556767940521240234375e2_8
real(8)::xtref=2.731499999999999772626324556767940521240234375e2_8
real(8)::xndo=8.e6_8
real(8)::xmua0=1.711000000000000050687752606304314895169227384030818939208984375e-5_8
real(8)::xt_suth_a=1.10400000000000005684341886080801486968994140625e2_8
real(8)::xmfpa0=6.59999999999999954251886044066799374974152669892646372318267822265625e-8_8
real(8)::xviscw=1.000000000000000020816681711721685132943093776702880859375e-3_8
real(8)::xrho00=1.204099999999999948130380289512686431407928466796875_8
real(8)::xcexvt
real(8),allocatable::xrtmin(:)
real(8),allocatable::xctmin(:)
integer(4)::nsplitsed(1_8:7_8)
real(8)::xlb(1_8:7_8)
real(8)::xlbex(1_8:7_8)
real(8)::xd(1_8:7_8)
real(8)::xfsedr(1_8:7_8)
real(8)::xfsedc(1_8:7_8)
end type
type(param_lima_t),save,target::param_lima
logical(4),pointer::llima_diag
intrinsic::null
logical(4),pointer::lptsplit
logical(4),pointer::lfeedbackt
logical(4),pointer::lnucl
logical(4),pointer::lsedi
logical(4),pointer::lhhoni
logical(4),pointer::lmeyers
logical(4),pointer::lcibu
logical(4),pointer::lrdsf
logical(4),pointer::lcrystal_shape
logical(4),pointer::lice_isc
logical(4),pointer::lifn_hom
logical(4),pointer::lsnow_t
logical(4),pointer::lmurakami
logical(4),pointer::lacti
logical(4),pointer::lsedc
logical(4),pointer::lactit
logical(4),pointer::ldepoc
logical(4),pointer::lacttke
logical(4),pointer::ladj
logical(4),pointer::lspro
logical(4),pointer::lkhko
logical(4),pointer::lkesslerac
logical(4),pointer::lccn_hom
logical(4),pointer::lscav
logical(4),pointer::laero_mass
logical(4),pointer::lsigmoide_g
logical(4),pointer::lsigmoide_ng
integer(4),pointer::nmaxiter
integer(4),pointer::nmom_i
integer(4),pointer::nmom_s
integer(4),pointer::nmom_g
integer(4),pointer::nmom_h
integer(4),pointer::nnb_crystal_shape
integer(4),pointer::nmod_ifn
integer(4),pointer::nmod_imm
integer(4),pointer::nind_specie
integer(4),pointer::nspecie
integer(4),pointer::nphillips
integer(4),pointer::ndiam
integer(4),pointer::nmom_c
integer(4),pointer::nmom_r
integer(4),pointer::nmod_ccn
integer(4),pointer::ndiamr
integer(4),pointer::ndiamp
character(4_4,1),pointer::htype_crystal_shape(:)
real(8),pointer::xmrstep
real(8),pointer::xtstep_ts
real(8),pointer::xalphai
real(8),pointer::xnui
real(8),pointer::xalphas
real(8),pointer::xnus
real(8),pointer::xalphag
real(8),pointer::xnug
real(8),pointer::xsw0
real(8),pointer::xrho_cfdc
real(8),pointer::xgamma
real(8),pointer::xfactnuc_dep
real(8),pointer::xfactnuc_con
real(8),pointer::xndebris_cibu
real(8),pointer::xpsh_max_rdsf
real(8),pointer::xalphar
real(8),pointer::xnur
real(8),pointer::xalphac
real(8),pointer::xnuc
real(8),pointer::xfsolub_ccn
real(8),pointer::xactemp_ccn
real(8),pointer::xaerdiff
real(8),pointer::xaerheight
real(8),pointer::xvdepoc
real(8),pointer::xt0scav
real(8),pointer::xtref
real(8),pointer::xndo
real(8),pointer::xmua0
real(8),pointer::xt_suth_a
real(8),pointer::xmfpa0
real(8),pointer::xviscw
real(8),pointer::xrho00
real(8),pointer::xcexvt
real(8),pointer::xsigmoide_g
real(8),pointer::xmvdmin_g
real(8),pointer::xifn_conc(:)
real(8),pointer::xmdiam_ifn(:)
real(8),pointer::xsigma_ifn(:)
real(8),pointer::xginc_ifn(:)
real(8),pointer::xrho_ifn(:)
real(8),pointer::xfrac_ref(:)
real(8),pointer::xt0(:)
real(8),pointer::xdt0(:)
real(8),pointer::xdsi0(:)
real(8),pointer::xh(:)
real(8),pointer::xarea1(:)
real(8),pointer::xtx1(:)
real(8),pointer::xtx2(:)
real(8),pointer::xabsciss(:)
real(8),pointer::xweight(:)
real(8),pointer::xccn_conc(:)
real(8),pointer::xr_mean_ccn(:)
real(8),pointer::xlogsig_ccn(:)
real(8),pointer::xrho_ccn(:)
real(8),pointer::xkhen_multi(:)
real(8),pointer::xmuhen_multi(:)
real(8),pointer::xbetahen_multi(:)
real(8),pointer::xlimit_factor(:)
real(8),pointer::xgmulti(:)
real(8),pointer::xrtmin(:)
real(8),pointer::xctmin(:)
real(8),pointer::xlb(:)
real(8),pointer::xlbex(:)
real(8),pointer::xd(:)
real(8),pointer::xfsedr(:)
real(8),pointer::xfsedc(:)
real(8),pointer::xfrac(:,:)
real(8),pointer::xconc_ccn_tot(:,:,:)
integer(4),pointer::nimm(:)
integer(4),pointer::nindice_ccn_imm(:)
integer(4),pointer::nsplitsed(:)
character(8_4,1),pointer::cifn_species
character(8_4,1),pointer::cint_mixing
character(4_4,1),pointer::cpristine_ice_lima
character(4_4,1),pointer::chevrimed_ice_lima
character(8_4,1),pointer::cccn_modes
character(3_4,1),pointer::hparam_ccn
character(3_4,1),pointer::hini_ccn
character(10_4,1),pointer::htype_ccn(:)
namelist/nam_param_lima/lnucl,lsedi,lhhoni,lmeyers,nmom_i,nmom_s,nmom_g,nmom_h,nmod_ifn,xifn_conc,lifn_hom,cifn_species,cint_mixing,nmod_imm,nind_specie,lsnow_t,cpristine_ice_lima,chevrimed_ice_lima,xfactnuc_dep,xfactnuc_con,nphillips,lcibu,xndebris_cibu,lrdsf,xpsh_max_rdsf,lmurakami,lcrystal_shape,nnb_crystal_shape,htype_crystal_shape,lice_isc,lacti,lsedc,lactit,lspro,ladj,lkhko,lkesslerac,nmom_c,nmom_r,nmod_ccn,xccn_conc,lccn_hom,cccn_modes,hini_ccn,htype_ccn,xalphac,xnuc,xalphar,xnur,xfsolub_ccn,xactemp_ccn,xaerdiff,xaerheight,lscav,laero_mass,ldepoc,xvdepoc,lacttke,lptsplit,lfeedbackt,nmaxiter,xmrstep,xtstep_ts,lsigmoide_ng,lsigmoide_g,xsigmoide_g,xmvdmin_g
contains
subroutine param_lima_associate()
end
subroutine param_lima_deallocate(hname)
character(*,1),intent(in)::hname
end
subroutine param_lima_allocate(hname,kdim1,kdim2,kdim3)
character(*,1),intent(in)::hname
integer(4),intent(in)::kdim1
integer(4),intent(in),optional::kdim2
integer(4),intent(in),optional::kdim3
end
subroutine param_lima_init(hprogram,tfilenam,odneednam,kluout,oddefaultval,odreadnam,odcheck,kprint)
use modd_io,only:tfiledata
character(6_4,1),intent(in)::hprogram
type(tfiledata),intent(in)::tfilenam
logical(4),intent(in)::odneednam
integer(4),intent(in)::kluout
logical(4),intent(in),optional::oddefaultval
logical(4),intent(in),optional::odreadnam
logical(4),intent(in),optional::odcheck
integer(4),intent(in),optional::kprint
end
end
