!mod$ v1 sum:f6813cfbdf20d0e1
!need$ 25b02d753545073c n modd_parameters
module modd_elec_param
use modd_parameters,only:jpmodelmax
real(8)::xcoef_rq_v
real(8)::xcoef_rq_c
real(8)::xcoef_rq_r
real(8)::xcoef_rq_i
real(8)::xcoef_rq_s
real(8)::xcoef_rq_g
real(8)::xcoef_rq_h
real(8)::xqhon
real(8)::xfqupdnci
real(8)::xqsrimcg
real(8)::xexqsrimcg
real(8),allocatable::xgaminc_rim3(:)
real(8)::xqrcfrig
real(8)::xexqrcfrig
real(8)::xfqraccs
real(8)::xfqiaggsbh
real(8)::xfqiaggsbg
real(8)::xexfqiaggsbg
real(8)::xfqiaggsbs
real(8)::xfqiaggsbt1
real(8)::xfqiaggsbt2
real(8)::xfqiaggsbt3
real(8)::xlbqraccs1
real(8)::xlbqraccs2
real(8)::xlbqraccs3
real(8)::xlbqsaccrg1
real(8)::xlbqsaccrg2
real(8)::xlbqsaccrg3
real(8),allocatable::xker_q_raccs(:,:)
real(8),allocatable::xker_q_raccss(:,:)
real(8),allocatable::xker_q_saccrg(:,:)
real(8)::xfqsdryg
real(8)::xfqsdrygb
real(8)::xfqrdryg
real(8),allocatable::xker_q_limsg(:,:)
real(8),allocatable::xker_q_sdrygb(:,:)
real(8),allocatable::xker_q_sdrygb1(:,:)
real(8),allocatable::xker_q_sdrygb2(:,:)
real(8)::xhidryg
real(8)::xhsdryg
real(8)::xlbqsdrygb4h
real(8)::xlbqsdrygb5h
real(8)::xlbqsdrygb6h
real(8)::xfqsdrygbh
real(8)::xlwcc
real(8)::xfqidrygbg
real(8)::xlbqidrygbg
real(8)::xfqsdrygbg
real(8)::xlbqsdrygb4g
real(8)::xlbqsdrygb5g
real(8)::xlbqsdrygb6g
real(8)::ximp
real(8)::xinp
real(8)::xikp
real(8)::ximn
real(8)::xinn
real(8)::xikn
real(8)::xsmp
real(8)::xsnp
real(8)::xskp
real(8)::xsmn
real(8)::xsnn
real(8)::xskn
real(8)::xfqiaggsp
real(8)::xfqiaggsn
real(8)::xfqidrygbsp
real(8)::xfqidrygbsn
real(8)::xlbqsdrygb1sp
real(8)::xlbqsdrygb1sn
real(8)::xlbqsdrygb2sp
real(8)::xlbqsdrygb2sn
real(8)::xlbqsdrygb3sp
real(8)::xlbqsdrygb3sn
real(8)::xaigammabi
real(8)::xikp_tak
real(8)::xikn_tak
real(8)::xskp_tak
real(8)::xskn_tak
real(8)::xfqiaggsp_tak
real(8)::xfqiaggsn_tak
real(8)::xfqidrygbsp_tak
real(8)::xfqidrygbsn_tak
real(8)::xvscoef
real(8)::xvgcoef
real(8)::xfqidrygbs
real(8)::xlbqidrygbs
real(8)::xfqsdrygbs
real(8)::xlbqsdrygb1s
real(8)::xlbqsdrygb2s
integer(4)::nind_temp
integer(4)::nind_lwc
real(8),allocatable::xmansell(:,:)
real(8),allocatable::xsaunder(:,:)
real(8),allocatable::xtaka_tm(:,:)
real(8)::xfqidrygbt1
real(8)::xfqidrygbt2
real(8)::xfqidrygbt3
real(8)::xfqsdrygbt1
real(8)::xfqsdrygbt2
real(8)::xfqsdrygbt3
real(8)::xfqsdrygbt4
real(8)::xfqsdrygbt5
real(8)::xfqsdrygbt6
real(8)::xfqsdrygbt7
real(8)::xfqsdrygbt8
real(8)::xfqsdrygbt9
real(8)::xfqsdrygbt10
real(8)::xfqsdrygbt11
real(8)::xfqsdrygbt12
real(8)::xlbqrdryg1
real(8)::xlbqrdryg2
real(8)::xlbqrdryg3
real(8)::xlbqsdryg1
real(8)::xlbqsdryg2
real(8)::xlbqsdryg3
real(8),allocatable::xker_q_sdryg(:,:)
real(8),allocatable::xker_q_rdryg(:,:)
real(8)::xqrevav1
real(8)::xqrevav2
real(8)::xaux_lim
real(8)::xaux_lim1
real(8)::xaux_lim2
real(8)::xaux_lim3
real(8)::xcolcg_ind
real(8)::xebound
real(8)::xalpha_ind
real(8)::xcos_theta
real(8)::xind1
real(8)::xind2
real(8)::xind3
real(8)::xfqlightc
real(8)::xfqlightr
real(8)::xfqlighti
real(8)::xfqlights
real(8)::xfqlightg
real(8)::xfqlighth
real(8)::xexqlightr
real(8)::xexqlighti
real(8)::xexqlights
real(8)::xexqlightg
real(8)::xexqlighth
type::elec_param_t
real(8)::xfci
real(8)::xfqsedc
real(8)::xexqsedc
real(8)::xfqsedr
real(8)::xexqsedr
real(8)::xfqsedi
real(8)::xexqsedi
real(8)::xfqseds
real(8)::xexqseds
real(8)::xfqsedg
real(8)::xexqsedg
real(8)::xfqsedh
real(8)::xexqsedh
real(8)::xegmin
real(8)::xegmax
real(8)::xesmin
real(8)::xesmax
real(8)::xeimin
real(8)::xeimax
real(8)::xecmin
real(8)::xecmax
real(8)::xermin
real(8)::xermax
real(8)::xehmin
real(8)::xehmax
real(8)::xfqupdc
real(8)::xfqupdr
real(8)::xfqupdi
real(8)::xexfqupdi
real(8)::xfqupds
real(8)::xfqupdg
real(8)::xfqupdh
real(8)::xfqsed(1_8:7_8)
real(8)::xdq(1_8:7_8)
end type
type(elec_param_t),target::elec_param
real(8),pointer::xfci
intrinsic::null
real(8),pointer::xfqsedc
real(8),pointer::xexqsedc
real(8),pointer::xfqsedr
real(8),pointer::xexqsedr
real(8),pointer::xfqsedi
real(8),pointer::xexqsedi
real(8),pointer::xfqseds
real(8),pointer::xexqseds
real(8),pointer::xfqsedg
real(8),pointer::xexqsedg
real(8),pointer::xfqsedh
real(8),pointer::xexqsedh
real(8),pointer::xegmin
real(8),pointer::xegmax
real(8),pointer::xesmin
real(8),pointer::xesmax
real(8),pointer::xeimin
real(8),pointer::xeimax
real(8),pointer::xecmin
real(8),pointer::xecmax
real(8),pointer::xermin
real(8),pointer::xermax
real(8),pointer::xehmin
real(8),pointer::xehmax
real(8),pointer::xfqupdc
real(8),pointer::xfqupdr
real(8),pointer::xfqupdi
real(8),pointer::xexfqupdi
real(8),pointer::xfqupds
real(8),pointer::xfqupdg
real(8),pointer::xfqupdh
real(8),pointer::xfqsed(:)
real(8),pointer::xdq(:)
contains
subroutine elec_param_associate()
end
end
