!mod$ v1 sum:e15bb8637dc8f8af
!need$ fe3180dd7f22d4c1 n parkind1
module model_physics_forcing_mod
use parkind1,only:jpim
use parkind1,only:jprb
type::model_physics_forcing_type
logical(4)::lgeost_uv_frc
real(8)::rcorio_forc
real(8)::rz0_forc
real(8)::ralb_forc
real(8)::remis_forc
integer(4),allocatable::ngeost_uv_time(:)
integer(4)::ngeost_uv_freq
integer(4)::ngeost_u_deb
integer(4)::ngeost_u_num
integer(4)::ngeost_v_deb
integer(4)::ngeost_v_num
logical(4)::luv_adv_frc
integer(4),allocatable::nuv_adv_time(:)
integer(4)::nuv_adv_freq
integer(4)::nu_adv_deb
integer(4)::nu_adv_num
integer(4)::nv_adv_deb
integer(4)::nv_adv_num
logical(4)::lt_adv_frc
integer(4),allocatable::nt_adv_time(:)
integer(4)::nt_adv_freq
integer(4)::nt_adv_deb
integer(4)::nt_adv_num
logical(4)::lqv_adv_frc
integer(4),allocatable::nqv_adv_time(:)
integer(4)::nqv_adv_freq
integer(4)::nqv_adv_deb
integer(4)::nqv_adv_num
logical(4)::lsw_frc
integer(4),allocatable::nlsw_time(:)
integer(4)::nlsw_freq
integer(4)::nlsw_deb
integer(4)::nlsw_num
logical(4)::lsomega_frc
integer(4),allocatable::nlsomega_time(:)
integer(4)::nlsomega_freq
integer(4)::nlsomega_deb
integer(4)::nlsomega_num
logical(4)::lt_nudg
logical(4)::lqv_nudg
logical(4)::luv_nudg
integer(4),allocatable::nt_nudg_time(:)
integer(4),allocatable::nqv_nudg_time(:)
integer(4),allocatable::nuv_nudg_time(:)
real(8)::relax_taut
real(8)::relax_tauq
real(8)::relax_tauu
integer(4)::nt_nudg
integer(4)::nqv_nudg
integer(4)::nu_nudg
integer(4)::nv_nudg
integer(4),allocatable::nt_sh_adv_time(:)
integer(4)::nsh_forc_deb
integer(4)::nsh_forc_num
integer(4),allocatable::nt_lh_adv_time(:)
integer(4)::nlh_forc_deb
integer(4)::nlh_forc_num
integer(4),allocatable::nt_ts_adv_time(:)
integer(4)::nts_forc_deb
integer(4)::nts_forc_num
integer(4),allocatable::nt_us_adv_time(:)
integer(4)::nus_forc_deb
integer(4)::nus_forc_num
logical(4)::lmusclfa
integer(4)::nmusclfa
integer(4)::nt_nudg_freq
integer(4)::nqv_nudg_freq
integer(4)::nuv_nudg_freq
integer(4)::nt_nudg_deb
integer(4)::nqv_nudg_deb
integer(4)::nu_nudg_deb
integer(4)::nv_nudg_deb
integer(4)::nt_nudg_num
integer(4)::nqv_nudg_num
integer(4)::nuv_nudg_num
logical(4)::lsps_frc
contains
procedure::dealloc_forcing
end type
contains
subroutine dealloc_forcing(self)
class(model_physics_forcing_type),intent(inout)::self
end
end
