!mod$ v1 sum:6df3a4026c28925a
!need$ 0bde2ac47243ead2 i iso_c_binding
module netcdf_nc_data
use,intrinsic::iso_c_binding,only:c_associated
use,intrinsic::iso_c_binding,only:c_funloc
use,intrinsic::iso_c_binding,only:c_funptr
use,intrinsic::iso_c_binding,only:c_f_pointer
use,intrinsic::iso_c_binding,only:c_loc
use,intrinsic::iso_c_binding,only:c_null_funptr
use,intrinsic::iso_c_binding,only:c_null_ptr
use,intrinsic::iso_c_binding,only:c_ptr
use,intrinsic::iso_c_binding,only:c_sizeof
use,intrinsic::iso_c_binding,only:operator(==)
use,intrinsic::iso_c_binding,only:operator(/=)
use,intrinsic::iso_c_binding,only:c_int8_t
use,intrinsic::iso_c_binding,only:c_int16_t
use,intrinsic::iso_c_binding,only:c_int32_t
use,intrinsic::iso_c_binding,only:c_int64_t
use,intrinsic::iso_c_binding,only:c_int128_t
use,intrinsic::iso_c_binding,only:c_int
use,intrinsic::iso_c_binding,only:c_short
use,intrinsic::iso_c_binding,only:c_long
use,intrinsic::iso_c_binding,only:c_long_long
use,intrinsic::iso_c_binding,only:c_signed_char
use,intrinsic::iso_c_binding,only:c_size_t
use,intrinsic::iso_c_binding,only:c_intmax_t
use,intrinsic::iso_c_binding,only:c_intptr_t
use,intrinsic::iso_c_binding,only:c_ptrdiff_t
use,intrinsic::iso_c_binding,only:c_int_least8_t
use,intrinsic::iso_c_binding,only:c_int_fast8_t
use,intrinsic::iso_c_binding,only:c_int_least16_t
use,intrinsic::iso_c_binding,only:c_int_fast16_t
use,intrinsic::iso_c_binding,only:c_int_least32_t
use,intrinsic::iso_c_binding,only:c_int_fast32_t
use,intrinsic::iso_c_binding,only:c_int_least64_t
use,intrinsic::iso_c_binding,only:c_int_fast64_t
use,intrinsic::iso_c_binding,only:c_int_least128_t
use,intrinsic::iso_c_binding,only:c_int_fast128_t
use,intrinsic::iso_c_binding,only:c_float
use,intrinsic::iso_c_binding,only:c_double
use,intrinsic::iso_c_binding,only:c_long_double
use,intrinsic::iso_c_binding,only:c_float_complex
use,intrinsic::iso_c_binding,only:c_double_complex
use,intrinsic::iso_c_binding,only:c_long_double_complex
use,intrinsic::iso_c_binding,only:c_bool
use,intrinsic::iso_c_binding,only:c_char
use,intrinsic::iso_c_binding,only:c_null_char
use,intrinsic::iso_c_binding,only:c_alert
use,intrinsic::iso_c_binding,only:c_backspace
use,intrinsic::iso_c_binding,only:c_form_feed
use,intrinsic::iso_c_binding,only:c_new_line
use,intrinsic::iso_c_binding,only:c_carriage_return
use,intrinsic::iso_c_binding,only:c_horizontal_tab
use,intrinsic::iso_c_binding,only:c_vertical_tab
use,intrinsic::iso_c_binding,only:c_float128
use,intrinsic::iso_c_binding,only:c_float128_complex
use,intrinsic::iso_c_binding,only:c_uint8_t
use,intrinsic::iso_c_binding,only:c_uint16_t
use,intrinsic::iso_c_binding,only:c_uint32_t
use,intrinsic::iso_c_binding,only:c_uint64_t
use,intrinsic::iso_c_binding,only:c_uint128_t
use,intrinsic::iso_c_binding,only:c_unsigned_char
use,intrinsic::iso_c_binding,only:c_unsigned_short
use,intrinsic::iso_c_binding,only:c_unsigned
use,intrinsic::iso_c_binding,only:c_unsigned_long
use,intrinsic::iso_c_binding,only:c_unsigned_long_long
use,intrinsic::iso_c_binding,only:c_uintmax_t
use,intrinsic::iso_c_binding,only:c_uint_fast8_t
use,intrinsic::iso_c_binding,only:c_uint_fast16_t
use,intrinsic::iso_c_binding,only:c_uint_fast32_t
use,intrinsic::iso_c_binding,only:c_uint_fast64_t
use,intrinsic::iso_c_binding,only:c_uint_fast128_t
use,intrinsic::iso_c_binding,only:c_uint_least8_t
use,intrinsic::iso_c_binding,only:c_uint_least16_t
use,intrinsic::iso_c_binding,only:c_uint_least32_t
use,intrinsic::iso_c_binding,only:c_uint_least64_t
use,intrinsic::iso_c_binding,only:c_uint_least128_t
use,intrinsic::iso_c_binding,only:c_f_procpointer
integer(4),parameter,private::real32=4_4
intrinsic::selected_real_kind
integer(4),parameter,private::real64=8_4
integer(4),parameter,private::int8=1_4
intrinsic::selected_int_kind
integer(4),parameter,private::int16=2_4
integer(4),parameter,private::int32=4_4
integer(4),parameter,private::int64=8_4
integer(4),parameter::rk4=4_4
integer(4),parameter::rk8=8_4
integer(4),parameter::ik1=1_4
integer(4),parameter::ik2=2_4
integer(4),parameter::ik4=4_4
integer(4),parameter::ik8=8_4
integer(4),parameter::cint1=1_4
integer(4),parameter::nfint1=1_4
integer(4),parameter::cint2=2_4
integer(4),parameter::nfint2=2_4
integer(4),parameter::cint=4_4
integer(4),parameter::nfint=4_4
integer(4),parameter::cint8=8_4
integer(4),parameter::nfint8=8_4
integer(4),parameter::nfreal=4_4
integer(4),parameter,private::dummy=0_4
integer(4),parameter::c_enum=4_4
intrinsic::kind
integer(4),parameter::nc_nat=0_4
integer(4),parameter::nc_byte=1_4
integer(4),parameter::nc_char=2_4
integer(4),parameter::nc_short=3_4
integer(4),parameter::nc_int=4_4
integer(4),parameter::nc_float=5_4
integer(4),parameter::nc_double=6_4
character(1_8,1),parameter::nc_fill_char="\000"
integer(1),parameter::nc_fill_byte=-127_1
integer(2),parameter::nc_fill_short=-32767_2
integer(4),parameter::nc_fill_int=-2147483647_4
real(4),parameter::nc_fill_float=9.96920996838686904677855295210258432e36_4
real(8),parameter::nc_fill_double=9.96920996838686904677855295210258432e36_8
integer(4),parameter::nc_nowrite=0_4
integer(4),parameter::nc_write=1_4
integer(4),parameter::nc_clobber=0_4
integer(4),parameter::nc_noclobber=4_4
integer(4),parameter::nc_fill=0_4
integer(4),parameter::nc_nofill=256_4
integer(4),parameter::nc_lock=1024_4
integer(4),parameter::nc_share=2048_4
integer(4),parameter::nc_strict_nc3=8_4
integer(4),parameter::nc_64bit_offset=512_4
integer(4),parameter::nc_64bit_data=32_4
integer(4),parameter::nc_cdf5=32_4
integer(4),parameter::nc_sizehint_default=0_4
integer(4),parameter::nc_align_chunk=-1_4
integer(4),parameter::nc_format_classic=1_4
integer(4),parameter::nc_format_64bit=2_4
integer(4),parameter::nc_format_64bit_offset=2_4
integer(4),parameter::nc_format_64bit_data=5_4
integer(4),parameter::nc_format_cdf5=5_4
integer(4),parameter::nc_diskless=8_4
integer(4),parameter::nc_mmap=16_4
integer(4),parameter::nc_inmemory=32768_4
integer(4),parameter::nc_unlimited=0_4
integer(4),parameter::nc_global=0_4
integer(4),parameter::nc_max_dims=1024_4
integer(4),parameter::nc_max_attrs=8192_4
integer(4),parameter::nc_max_vars=8192_4
integer(4),parameter::nc_max_name=256_4
integer(4),parameter::nc_max_var_dims=1024_4
integer(4),parameter::nc_noerr=0_4
integer(4),parameter::nc2_err=-1_4
integer(4),parameter::nc_syserr=-31_4
integer(4),parameter::nc_exdr=-32_4
integer(4),parameter::nc_ebadid=-33_4
integer(4),parameter::nc_ebfile=-34_4
integer(4),parameter::nc_eexist=-35_4
integer(4),parameter::nc_einval=-36_4
integer(4),parameter::nc_eperm=-37_4
integer(4),parameter::nc_enotindefine=-38_4
integer(4),parameter::nc_eindefine=-39_4
integer(4),parameter::nc_einvalcoords=-40_4
integer(4),parameter::nc_emaxdims=-41_4
integer(4),parameter::nc_enameinuse=-42_4
integer(4),parameter::nc_enotatt=-43_4
integer(4),parameter::nc_emaxatts=-44_4
integer(4),parameter::nc_ebadtype=-45_4
integer(4),parameter::nc_ebaddim=-46_4
integer(4),parameter::nc_eunlimpos=-47_4
integer(4),parameter::nc_emaxvars=-48_4
integer(4),parameter::nc_enotvar=-49_4
integer(4),parameter::nc_eglobal=-50_4
integer(4),parameter::nc_enotnc=-51_4
integer(4),parameter::nc_ests=-52_4
integer(4),parameter::nc_emaxname=-53_4
integer(4),parameter::nc_eunlimit=-54_4
integer(4),parameter::nc_enorecvars=-55_4
integer(4),parameter::nc_echar=-56_4
integer(4),parameter::nc_eedge=-57_4
integer(4),parameter::nc_estride=-58_4
integer(4),parameter::nc_ebadname=-59_4
integer(4),parameter::nc_erange=-60_4
integer(4),parameter::nc_enomem=-61_4
integer(4),parameter::nc_evarsize=-62_4
integer(4),parameter::nc_edimsize=-63_4
integer(4),parameter::nc_etrunc=-64_4
integer(4),parameter::nc_eaxistype=-65_4
integer(4),parameter::nc_edap=-66_4
integer(4),parameter::nc_ecurl=-67_4
integer(4),parameter::nc_eio=-68_4
integer(4),parameter::nc_enodata=-69_4
integer(4),parameter::nc_edapsvc=-70_4
integer(4),parameter::nc_edas=-71_4
integer(4),parameter::nc_edds=-72_4
integer(4),parameter::nc_edatadds=-73_4
integer(4),parameter::nc_edapurl=-74_4
integer(4),parameter::nc_edapconstraint=-75_4
integer(4),parameter::nc_etranslation=-76_4
integer(4),parameter::nc_fatal=1_4
integer(4),parameter::nc_verbose=2_4
integer(4),parameter::nc_format_netcdf4=3_4
integer(4),parameter::nc_format_netcdf4_classic=4_4
integer(4),parameter::nc_netcdf4=4096_4
integer(4),parameter::nc_classic_model=256_4
integer(4),parameter::nc_long=4_4
integer(4),parameter::nc_ubyte=7_4
integer(4),parameter::nc_ushort=8_4
integer(4),parameter::nc_uint=9_4
integer(4),parameter::nc_int64=10_4
integer(4),parameter::nc_uint64=11_4
integer(4),parameter::nc_string=12_4
integer(4),parameter::nc_vlen=13_4
integer(4),parameter::nc_opaque=14_4
integer(4),parameter::nc_enum=15_4
integer(4),parameter::nc_compound=16_4
integer(4),parameter::nc_fill_ubyte=255_4
integer(4),parameter::nc_fill_ushort=65535_4
integer(8),parameter::nc_fill_uint=4294967295_8
integer(8),parameter::nc_fill_int64=-9223372036854775806_8
integer(4),parameter::nc_chunk_seq=0_4
integer(4),parameter::nc_chunk_sub=1_4
integer(4),parameter::nc_chunk_sizes=2_4
integer(4),parameter::nc_endian_native=0_4
integer(4),parameter::nc_endian_little=1_4
integer(4),parameter::nc_endian_big=2_4
integer(4),parameter::nc_chunked=0_4
integer(4),parameter::nc_notcontiguous=0_4
integer(4),parameter::nc_contiguous=1_4
integer(4),parameter::nc_nochecksum=0_4
integer(4),parameter::nc_fletcher32=1_4
integer(4),parameter::nc_noshuffle=0_4
integer(4),parameter::nc_shuffle=1_4
integer(4),parameter::nc_independent=0_4
integer(4),parameter::nc_collective=1_4
integer(4),parameter::nc_mpiio=8192_4
integer(4),parameter::nc_mpiposix=16384_4
integer(4),parameter::nc_pnetcdf=8192_4
integer(4),parameter::nc_szip_ec_option_mask=4_4
integer(4),parameter::nc_szip_nn_option_mask=32_4
integer(4),parameter::nc_ehdferr=-101_4
integer(4),parameter::nc_ecantread=-102_4
integer(4),parameter::nc_ecantwrite=-103_4
integer(4),parameter::nc_ecantcreate=-104_4
integer(4),parameter::nc_efilemeta=-105_4
integer(4),parameter::nc_edimmeta=-106_4
integer(4),parameter::nc_eattmeta=-107_4
integer(4),parameter::nc_evarmeta=-108_4
integer(4),parameter::nc_enocompound=-109_4
integer(4),parameter::nc_eattexists=-110_4
integer(4),parameter::nc_enotnc4=-111_4
integer(4),parameter::nc_estrictnc3=-112_4
integer(4),parameter::nc_enotnc3=-113_4
integer(4),parameter::nc_enopar=-114_4
integer(4),parameter::nc_eparinit=-115_4
integer(4),parameter::nc_ebadgrpid=-116_4
integer(4),parameter::nc_ebadtypid=-117_4
integer(4),parameter::nc_etypdefined=-118_4
integer(4),parameter::nc_ebadfield=-119_4
integer(4),parameter::nc_ebadclass=-120_4
integer(4),parameter::nc_emaptype=-121_4
integer(4),parameter::nc_elatefill=-122_4
integer(4),parameter::nc_elatedef=-123_4
integer(4),parameter::nc_edimscale=-124_4
integer(4),parameter::nc_enogrp=-125_4
integer(4),parameter::nc_estorage=-126_4
integer(4),parameter::nc_ebadchunk=-127_4
integer(4),parameter::nc_enotbuilt=-128_4
integer(4),parameter::nc_ediskless=-129_4
integer(4),parameter::nc_ecantextend=-130_4
integer(4),parameter::nc_empi=-131_4
integer(4),parameter::nc_efilter=-132_4
integer(4),parameter::nc_ercfile=-133_4
integer(4),parameter::nc_enullpad=-134_4
integer(4),parameter::nc_einmemory=-135_4
integer(4),parameter::nc_enofilter=-136_4
integer(4),parameter::nc_enczarr=-137_4
integer(4),parameter::nc_es3=-138_4
integer(4),parameter::nc_eempty=-139_4
integer(4),parameter::nc_eobject=-140_4
integer(4),parameter::nc_enoobject=-141_4
integer(4),parameter::nc_eplugin=-142_4
integer(4),parameter::nc_noquantize=0_4
integer(4),parameter::nc_quantize_bitgroom=1_4
end
