!mod$ v1 sum:5e3d67c12d5538aa
!need$ c0b7901dfd247b37 n netcdf_nf_data
!need$ 36400f10d6274402 n netcdf_nf_interfaces
!need$ 8319d370c4cee9ee n netcdf4_nf_interfaces
module netcdf4_f03
use netcdf_nf_data,only:c_associated
use netcdf_nf_data,only:c_funloc
use netcdf_nf_data,only:c_funptr
use netcdf_nf_data,only:c_f_pointer
use netcdf_nf_data,only:c_loc
use netcdf_nf_data,only:c_null_funptr
use netcdf_nf_data,only:c_null_ptr
use netcdf_nf_data,only:c_ptr
use netcdf_nf_data,only:c_sizeof
use netcdf_nf_data,only:operator(==)
use netcdf_nf_data,only:operator(/=)
use netcdf_nf_data,only:c_int8_t
use netcdf_nf_data,only:c_int16_t
use netcdf_nf_data,only:c_int32_t
use netcdf_nf_data,only:c_int64_t
use netcdf_nf_data,only:c_int128_t
use netcdf_nf_data,only:c_int
use netcdf_nf_data,only:c_short
use netcdf_nf_data,only:c_long
use netcdf_nf_data,only:c_long_long
use netcdf_nf_data,only:c_signed_char
use netcdf_nf_data,only:c_size_t
use netcdf_nf_data,only:c_intmax_t
use netcdf_nf_data,only:c_intptr_t
use netcdf_nf_data,only:c_ptrdiff_t
use netcdf_nf_data,only:c_int_least8_t
use netcdf_nf_data,only:c_int_fast8_t
use netcdf_nf_data,only:c_int_least16_t
use netcdf_nf_data,only:c_int_fast16_t
use netcdf_nf_data,only:c_int_least32_t
use netcdf_nf_data,only:c_int_fast32_t
use netcdf_nf_data,only:c_int_least64_t
use netcdf_nf_data,only:c_int_fast64_t
use netcdf_nf_data,only:c_int_least128_t
use netcdf_nf_data,only:c_int_fast128_t
use netcdf_nf_data,only:c_float
use netcdf_nf_data,only:c_double
use netcdf_nf_data,only:c_long_double
use netcdf_nf_data,only:c_float_complex
use netcdf_nf_data,only:c_double_complex
use netcdf_nf_data,only:c_long_double_complex
use netcdf_nf_data,only:c_bool
use netcdf_nf_data,only:c_char
use netcdf_nf_data,only:c_null_char
use netcdf_nf_data,only:c_alert
use netcdf_nf_data,only:c_backspace
use netcdf_nf_data,only:c_form_feed
use netcdf_nf_data,only:c_new_line
use netcdf_nf_data,only:c_carriage_return
use netcdf_nf_data,only:c_horizontal_tab
use netcdf_nf_data,only:c_vertical_tab
use netcdf_nf_data,only:c_float128
use netcdf_nf_data,only:c_float128_complex
use netcdf_nf_data,only:c_uint8_t
use netcdf_nf_data,only:c_uint16_t
use netcdf_nf_data,only:c_uint32_t
use netcdf_nf_data,only:c_uint64_t
use netcdf_nf_data,only:c_uint128_t
use netcdf_nf_data,only:c_unsigned_char
use netcdf_nf_data,only:c_unsigned_short
use netcdf_nf_data,only:c_unsigned
use netcdf_nf_data,only:c_unsigned_long
use netcdf_nf_data,only:c_unsigned_long_long
use netcdf_nf_data,only:c_uintmax_t
use netcdf_nf_data,only:c_uint_fast8_t
use netcdf_nf_data,only:c_uint_fast16_t
use netcdf_nf_data,only:c_uint_fast32_t
use netcdf_nf_data,only:c_uint_fast64_t
use netcdf_nf_data,only:c_uint_fast128_t
use netcdf_nf_data,only:c_uint_least8_t
use netcdf_nf_data,only:c_uint_least16_t
use netcdf_nf_data,only:c_uint_least32_t
use netcdf_nf_data,only:c_uint_least64_t
use netcdf_nf_data,only:c_uint_least128_t
use netcdf_nf_data,only:c_f_procpointer
use netcdf_nf_data,only:selected_real_kind
use netcdf_nf_data,only:selected_int_kind
use netcdf_nf_data,only:rk4
use netcdf_nf_data,only:rk8
use netcdf_nf_data,only:ik1
use netcdf_nf_data,only:ik2
use netcdf_nf_data,only:ik4
use netcdf_nf_data,only:ik8
use netcdf_nf_data,only:cint1
use netcdf_nf_data,only:nfint1
use netcdf_nf_data,only:cint2
use netcdf_nf_data,only:nfint2
use netcdf_nf_data,only:cint
use netcdf_nf_data,only:nfint
use netcdf_nf_data,only:cint8
use netcdf_nf_data,only:nfint8
use netcdf_nf_data,only:nfreal
use netcdf_nf_data,only:c_enum
use netcdf_nf_data,only:kind
use netcdf_nf_data,only:nc_nat
use netcdf_nf_data,only:nc_byte
use netcdf_nf_data,only:nc_char
use netcdf_nf_data,only:nc_short
use netcdf_nf_data,only:nc_int
use netcdf_nf_data,only:nc_float
use netcdf_nf_data,only:nc_double
use netcdf_nf_data,only:nc_fill_char
use netcdf_nf_data,only:nc_fill_byte
use netcdf_nf_data,only:nc_fill_short
use netcdf_nf_data,only:nc_fill_int
use netcdf_nf_data,only:nc_fill_float
use netcdf_nf_data,only:nc_fill_double
use netcdf_nf_data,only:nc_nowrite
use netcdf_nf_data,only:nc_write
use netcdf_nf_data,only:nc_clobber
use netcdf_nf_data,only:nc_noclobber
use netcdf_nf_data,only:nc_fill
use netcdf_nf_data,only:nc_nofill
use netcdf_nf_data,only:nc_lock
use netcdf_nf_data,only:nc_share
use netcdf_nf_data,only:nc_strict_nc3
use netcdf_nf_data,only:nc_64bit_offset
use netcdf_nf_data,only:nc_64bit_data
use netcdf_nf_data,only:nc_cdf5
use netcdf_nf_data,only:nc_sizehint_default
use netcdf_nf_data,only:nc_align_chunk
use netcdf_nf_data,only:nc_format_classic
use netcdf_nf_data,only:nc_format_64bit
use netcdf_nf_data,only:nc_format_64bit_offset
use netcdf_nf_data,only:nc_format_64bit_data
use netcdf_nf_data,only:nc_format_cdf5
use netcdf_nf_data,only:nc_diskless
use netcdf_nf_data,only:nc_mmap
use netcdf_nf_data,only:nc_inmemory
use netcdf_nf_data,only:nc_unlimited
use netcdf_nf_data,only:nc_global
use netcdf_nf_data,only:nc_max_dims
use netcdf_nf_data,only:nc_max_attrs
use netcdf_nf_data,only:nc_max_vars
use netcdf_nf_data,only:nc_max_name
use netcdf_nf_data,only:nc_max_var_dims
use netcdf_nf_data,only:nc_noerr
use netcdf_nf_data,only:nc2_err
use netcdf_nf_data,only:nc_syserr
use netcdf_nf_data,only:nc_exdr
use netcdf_nf_data,only:nc_ebadid
use netcdf_nf_data,only:nc_ebfile
use netcdf_nf_data,only:nc_eexist
use netcdf_nf_data,only:nc_einval
use netcdf_nf_data,only:nc_eperm
use netcdf_nf_data,only:nc_enotindefine
use netcdf_nf_data,only:nc_eindefine
use netcdf_nf_data,only:nc_einvalcoords
use netcdf_nf_data,only:nc_emaxdims
use netcdf_nf_data,only:nc_enameinuse
use netcdf_nf_data,only:nc_enotatt
use netcdf_nf_data,only:nc_emaxatts
use netcdf_nf_data,only:nc_ebadtype
use netcdf_nf_data,only:nc_ebaddim
use netcdf_nf_data,only:nc_eunlimpos
use netcdf_nf_data,only:nc_emaxvars
use netcdf_nf_data,only:nc_enotvar
use netcdf_nf_data,only:nc_eglobal
use netcdf_nf_data,only:nc_enotnc
use netcdf_nf_data,only:nc_ests
use netcdf_nf_data,only:nc_emaxname
use netcdf_nf_data,only:nc_eunlimit
use netcdf_nf_data,only:nc_enorecvars
use netcdf_nf_data,only:nc_echar
use netcdf_nf_data,only:nc_eedge
use netcdf_nf_data,only:nc_estride
use netcdf_nf_data,only:nc_ebadname
use netcdf_nf_data,only:nc_erange
use netcdf_nf_data,only:nc_enomem
use netcdf_nf_data,only:nc_evarsize
use netcdf_nf_data,only:nc_edimsize
use netcdf_nf_data,only:nc_etrunc
use netcdf_nf_data,only:nc_eaxistype
use netcdf_nf_data,only:nc_edap
use netcdf_nf_data,only:nc_ecurl
use netcdf_nf_data,only:nc_eio
use netcdf_nf_data,only:nc_enodata
use netcdf_nf_data,only:nc_edapsvc
use netcdf_nf_data,only:nc_edas
use netcdf_nf_data,only:nc_edds
use netcdf_nf_data,only:nc_edatadds
use netcdf_nf_data,only:nc_edapurl
use netcdf_nf_data,only:nc_edapconstraint
use netcdf_nf_data,only:nc_etranslation
use netcdf_nf_data,only:nc_fatal
use netcdf_nf_data,only:nc_verbose
use netcdf_nf_data,only:nc_format_netcdf4
use netcdf_nf_data,only:nc_format_netcdf4_classic
use netcdf_nf_data,only:nc_netcdf4
use netcdf_nf_data,only:nc_classic_model
use netcdf_nf_data,only:nc_long
use netcdf_nf_data,only:nc_ubyte
use netcdf_nf_data,only:nc_ushort
use netcdf_nf_data,only:nc_uint
use netcdf_nf_data,only:nc_int64
use netcdf_nf_data,only:nc_uint64
use netcdf_nf_data,only:nc_string
use netcdf_nf_data,only:nc_vlen
use netcdf_nf_data,only:nc_opaque
use netcdf_nf_data,only:nc_enum
use netcdf_nf_data,only:nc_compound
use netcdf_nf_data,only:nc_fill_ubyte
use netcdf_nf_data,only:nc_fill_ushort
use netcdf_nf_data,only:nc_fill_uint
use netcdf_nf_data,only:nc_fill_int64
use netcdf_nf_data,only:nc_chunk_seq
use netcdf_nf_data,only:nc_chunk_sub
use netcdf_nf_data,only:nc_chunk_sizes
use netcdf_nf_data,only:nc_endian_native
use netcdf_nf_data,only:nc_endian_little
use netcdf_nf_data,only:nc_endian_big
use netcdf_nf_data,only:nc_chunked
use netcdf_nf_data,only:nc_notcontiguous
use netcdf_nf_data,only:nc_contiguous
use netcdf_nf_data,only:nc_nochecksum
use netcdf_nf_data,only:nc_fletcher32
use netcdf_nf_data,only:nc_noshuffle
use netcdf_nf_data,only:nc_shuffle
use netcdf_nf_data,only:nc_independent
use netcdf_nf_data,only:nc_collective
use netcdf_nf_data,only:nc_mpiio
use netcdf_nf_data,only:nc_mpiposix
use netcdf_nf_data,only:nc_pnetcdf
use netcdf_nf_data,only:nc_szip_ec_option_mask
use netcdf_nf_data,only:nc_szip_nn_option_mask
use netcdf_nf_data,only:nc_ehdferr
use netcdf_nf_data,only:nc_ecantread
use netcdf_nf_data,only:nc_ecantwrite
use netcdf_nf_data,only:nc_ecantcreate
use netcdf_nf_data,only:nc_efilemeta
use netcdf_nf_data,only:nc_edimmeta
use netcdf_nf_data,only:nc_eattmeta
use netcdf_nf_data,only:nc_evarmeta
use netcdf_nf_data,only:nc_enocompound
use netcdf_nf_data,only:nc_eattexists
use netcdf_nf_data,only:nc_enotnc4
use netcdf_nf_data,only:nc_estrictnc3
use netcdf_nf_data,only:nc_enotnc3
use netcdf_nf_data,only:nc_enopar
use netcdf_nf_data,only:nc_eparinit
use netcdf_nf_data,only:nc_ebadgrpid
use netcdf_nf_data,only:nc_ebadtypid
use netcdf_nf_data,only:nc_etypdefined
use netcdf_nf_data,only:nc_ebadfield
use netcdf_nf_data,only:nc_ebadclass
use netcdf_nf_data,only:nc_emaptype
use netcdf_nf_data,only:nc_elatefill
use netcdf_nf_data,only:nc_elatedef
use netcdf_nf_data,only:nc_edimscale
use netcdf_nf_data,only:nc_enogrp
use netcdf_nf_data,only:nc_estorage
use netcdf_nf_data,only:nc_ebadchunk
use netcdf_nf_data,only:nc_enotbuilt
use netcdf_nf_data,only:nc_ediskless
use netcdf_nf_data,only:nc_ecantextend
use netcdf_nf_data,only:nc_empi
use netcdf_nf_data,only:nc_efilter
use netcdf_nf_data,only:nc_ercfile
use netcdf_nf_data,only:nc_enullpad
use netcdf_nf_data,only:nc_einmemory
use netcdf_nf_data,only:nc_enofilter
use netcdf_nf_data,only:nc_enczarr
use netcdf_nf_data,only:nc_es3
use netcdf_nf_data,only:nc_eempty
use netcdf_nf_data,only:nc_eobject
use netcdf_nf_data,only:nc_enoobject
use netcdf_nf_data,only:nc_eplugin
use netcdf_nf_data,only:nc_noquantize
use netcdf_nf_data,only:nc_quantize_bitgroom
use netcdf_nf_data,only:nf_nat
use netcdf_nf_data,only:nf_byte
use netcdf_nf_data,only:nf_int1
use netcdf_nf_data,only:nf_char
use netcdf_nf_data,only:nf_short
use netcdf_nf_data,only:nf_int2
use netcdf_nf_data,only:nf_int
use netcdf_nf_data,only:nf_float
use netcdf_nf_data,only:nf_real
use netcdf_nf_data,only:nf_double
use netcdf_nf_data,only:nf_fill_char
use netcdf_nf_data,only:iachar
use netcdf_nf_data,only:nf_fill_byte
use netcdf_nf_data,only:nf_fill_short
use netcdf_nf_data,only:nf_fill_int
use netcdf_nf_data,only:nf_fill_float
use netcdf_nf_data,only:nf_fill_real
use netcdf_nf_data,only:nf_fill_real4
use netcdf_nf_data,only:nf_fill_double
use netcdf_nf_data,only:nf_fill_real8
use netcdf_nf_data,only:nf_nowrite
use netcdf_nf_data,only:nf_write
use netcdf_nf_data,only:nf_clobber
use netcdf_nf_data,only:nf_noclobber
use netcdf_nf_data,only:nf_fill
use netcdf_nf_data,only:nf_nofill
use netcdf_nf_data,only:nf_lock
use netcdf_nf_data,only:nf_share
use netcdf_nf_data,only:nf_strict_nc3
use netcdf_nf_data,only:nf_64bit_offset
use netcdf_nf_data,only:nf_sizehint_default
use netcdf_nf_data,only:nf_align_chunk
use netcdf_nf_data,only:nf_format_classic
use netcdf_nf_data,only:nf_format_64bit
use netcdf_nf_data,only:nf_diskless
use netcdf_nf_data,only:nf_mmap
use netcdf_nf_data,only:nf_inmemory
use netcdf_nf_data,only:nf_unlimited
use netcdf_nf_data,only:nf_global
use netcdf_nf_data,only:nf_max_dims
use netcdf_nf_data,only:nf_max_attrs
use netcdf_nf_data,only:nf_max_vars
use netcdf_nf_data,only:nf_max_name
use netcdf_nf_data,only:nf_max_var_dims
use netcdf_nf_data,only:nf_noerr
use netcdf_nf_data,only:nf2_err
use netcdf_nf_data,only:nf_syserr
use netcdf_nf_data,only:nf_exdr
use netcdf_nf_data,only:nf_ebadid
use netcdf_nf_data,only:nf_ebfile
use netcdf_nf_data,only:nf_eexist
use netcdf_nf_data,only:nf_einval
use netcdf_nf_data,only:nf_eperm
use netcdf_nf_data,only:nf_enotindefine
use netcdf_nf_data,only:nf_eindefine
use netcdf_nf_data,only:nf_einvalcoords
use netcdf_nf_data,only:nf_emaxdims
use netcdf_nf_data,only:nf_enameinuse
use netcdf_nf_data,only:nf_enotatt
use netcdf_nf_data,only:nf_emaxatts
use netcdf_nf_data,only:nf_ebadtype
use netcdf_nf_data,only:nf_ebaddim
use netcdf_nf_data,only:nf_eunlimpos
use netcdf_nf_data,only:nf_emaxvars
use netcdf_nf_data,only:nf_enotvar
use netcdf_nf_data,only:nf_eglobal
use netcdf_nf_data,only:nf_enotnc
use netcdf_nf_data,only:nf_ests
use netcdf_nf_data,only:nf_emaxname
use netcdf_nf_data,only:nf_eunlimit
use netcdf_nf_data,only:nf_enorecvars
use netcdf_nf_data,only:nf_echar
use netcdf_nf_data,only:nf_eedge
use netcdf_nf_data,only:nf_estride
use netcdf_nf_data,only:nf_ebadname
use netcdf_nf_data,only:nf_erange
use netcdf_nf_data,only:nf_enomem
use netcdf_nf_data,only:nf_evarsize
use netcdf_nf_data,only:nf_edimsize
use netcdf_nf_data,only:nf_etrunc
use netcdf_nf_data,only:nf_eaxistype
use netcdf_nf_data,only:nf_edap
use netcdf_nf_data,only:nf_ecurl
use netcdf_nf_data,only:nf_eio
use netcdf_nf_data,only:nf_enodata
use netcdf_nf_data,only:nf_edapsvc
use netcdf_nf_data,only:nf_edas
use netcdf_nf_data,only:nf_edds
use netcdf_nf_data,only:nf_edatadds
use netcdf_nf_data,only:nf_edapurl
use netcdf_nf_data,only:nf_edapconstraint
use netcdf_nf_data,only:nf_etranslation
use netcdf_nf_data,only:nf_fatal
use netcdf_nf_data,only:nf_verbose
use netcdf_nf_data,only:nf_noquantize
use netcdf_nf_data,only:nf_quantize_bitgroom
use netcdf_nf_data,only:nf_long
use netcdf_nf_data,only:nf_ubyte
use netcdf_nf_data,only:nf_ushort
use netcdf_nf_data,only:nf_uint
use netcdf_nf_data,only:nf_int64
use netcdf_nf_data,only:nf_uint64
use netcdf_nf_data,only:nf_string
use netcdf_nf_data,only:nf_vlen
use netcdf_nf_data,only:nf_opaque
use netcdf_nf_data,only:nf_enum
use netcdf_nf_data,only:nf_compound
use netcdf_nf_data,only:nf_fill_ubyte
use netcdf_nf_data,only:nf_fill_uint1
use netcdf_nf_data,only:nf_fill_ushort
use netcdf_nf_data,only:nf_fill_uint2
use netcdf_nf_data,only:nf_fill_uint
use netcdf_nf_data,only:nf_fill_int64
use netcdf_nf_data,only:nf_format_netcdf4
use netcdf_nf_data,only:nf_format_netcdf4_classic
use netcdf_nf_data,only:nf_format_64bit_data
use netcdf_nf_data,only:nf_netcdf4
use netcdf_nf_data,only:nf_hdf5
use netcdf_nf_data,only:nf_classic_model
use netcdf_nf_data,only:nf_chunk_seq
use netcdf_nf_data,only:nf_chunk_sub
use netcdf_nf_data,only:nf_chunk_sizes
use netcdf_nf_data,only:nf_endian_native
use netcdf_nf_data,only:nf_endian_little
use netcdf_nf_data,only:nf_endian_big
use netcdf_nf_data,only:nf_chunked
use netcdf_nf_data,only:nf_notcontiguous
use netcdf_nf_data,only:nf_contiguous
use netcdf_nf_data,only:nf_nochecksum
use netcdf_nf_data,only:nf_fletcher32
use netcdf_nf_data,only:nf_noshuffle
use netcdf_nf_data,only:nf_shuffle
use netcdf_nf_data,only:nf_independent
use netcdf_nf_data,only:nf_collective
use netcdf_nf_data,only:nf_mpiio
use netcdf_nf_data,only:nf_mpiposix
use netcdf_nf_data,only:nf_pnetcdf
use netcdf_nf_data,only:nf_szip_ec_option_mask
use netcdf_nf_data,only:nf_szip_nn_option_mask
use netcdf_nf_data,only:nf_ehdferr
use netcdf_nf_data,only:nf_ecantread
use netcdf_nf_data,only:nf_ecantwrite
use netcdf_nf_data,only:nf_ecantcreate
use netcdf_nf_data,only:nf_efilemeta
use netcdf_nf_data,only:nf_edimmeta
use netcdf_nf_data,only:nf_eattmeta
use netcdf_nf_data,only:nf_evarmeta
use netcdf_nf_data,only:nf_enocompound
use netcdf_nf_data,only:nf_eattexists
use netcdf_nf_data,only:nf_enotnc4
use netcdf_nf_data,only:nf_estrictnc3
use netcdf_nf_data,only:nf_enotnc3
use netcdf_nf_data,only:nf_enopar
use netcdf_nf_data,only:nf_eparinit
use netcdf_nf_data,only:nf_ebadgrpid
use netcdf_nf_data,only:nf_ebadtypid
use netcdf_nf_data,only:nf_etypdefined
use netcdf_nf_data,only:nf_ebadfield
use netcdf_nf_data,only:nf_ebadclass
use netcdf_nf_data,only:nf_emaptype
use netcdf_nf_data,only:nf_elatefill
use netcdf_nf_data,only:nf_elatedef
use netcdf_nf_data,only:nf_edimscale
use netcdf_nf_data,only:nf_enogrp
use netcdf_nf_data,only:nf_estorage
use netcdf_nf_data,only:nf_ebadchunk
use netcdf_nf_data,only:nf_enotbuilt
use netcdf_nf_data,only:nf_ediskless
use netcdf_nf_data,only:nf_ecantextend
use netcdf_nf_data,only:nf_empi
use netcdf_nf_data,only:nf_efilter
use netcdf_nf_data,only:nf_ercfile
use netcdf_nf_data,only:nf_enullpad
use netcdf_nf_data,only:nf_einmemory
use netcdf_nf_data,only:nf_enofilter
use netcdf_nf_data,only:nf_enczarr
use netcdf_nf_data,only:nf_es3
use netcdf_nf_data,only:nf_eempty
use netcdf_nf_data,only:nf_eobject
use netcdf_nf_data,only:nf_enoobject
use netcdf_nf_data,only:nf_eplugin
use netcdf_nf_data,only:ncbyte
use netcdf_nf_data,only:ncchar
use netcdf_nf_data,only:ncshort
use netcdf_nf_data,only:nclong
use netcdf_nf_data,only:ncfloat
use netcdf_nf_data,only:ncdouble
use netcdf_nf_data,only:ncrdwr
use netcdf_nf_data,only:nccreate
use netcdf_nf_data,only:ncexcl
use netcdf_nf_data,only:ncindef
use netcdf_nf_data,only:ncnsync
use netcdf_nf_data,only:nchsync
use netcdf_nf_data,only:ncndirty
use netcdf_nf_data,only:nchdirty
use netcdf_nf_data,only:ncfill
use netcdf_nf_data,only:ncnofill
use netcdf_nf_data,only:nclink
use netcdf_nf_data,only:ncnowrit
use netcdf_nf_data,only:ncwrite
use netcdf_nf_data,only:ncclob
use netcdf_nf_data,only:ncnoclob
use netcdf_nf_data,only:ncunlim
use netcdf_nf_data,only:ncglobal
use netcdf_nf_data,only:maxncop
use netcdf_nf_data,only:maxncdim
use netcdf_nf_data,only:maxncatt
use netcdf_nf_data,only:maxncvar
use netcdf_nf_data,only:maxncnam
use netcdf_nf_data,only:maxvdims
use netcdf_nf_data,only:ncnoerr
use netcdf_nf_data,only:ncebadid
use netcdf_nf_data,only:ncenfile
use netcdf_nf_data,only:nceexist
use netcdf_nf_data,only:nceinval
use netcdf_nf_data,only:nceperm
use netcdf_nf_data,only:ncenotin
use netcdf_nf_data,only:nceindef
use netcdf_nf_data,only:ncecoord
use netcdf_nf_data,only:ncemaxds
use netcdf_nf_data,only:ncename
use netcdf_nf_data,only:ncemaxat
use netcdf_nf_data,only:ncebadty
use netcdf_nf_data,only:ncebadd
use netcdf_nf_data,only:nceunlim
use netcdf_nf_data,only:ncemaxvs
use netcdf_nf_data,only:ncenotvr
use netcdf_nf_data,only:nceglob
use netcdf_nf_data,only:ncnotnc
use netcdf_nf_data,only:ncestc
use netcdf_nf_data,only:ncentool
use netcdf_nf_data,only:ncfoobar
use netcdf_nf_data,only:ncsyserr
use netcdf_nf_data,only:ncfatal
use netcdf_nf_data,only:ncverbos
use netcdf_nf_data,only:filchar
use netcdf_nf_data,only:filbyte
use netcdf_nf_data,only:filshort
use netcdf_nf_data,only:fillong
use netcdf_nf_data,only:filfloat
use netcdf_nf_data,only:fildoub
use netcdf_nf_interfaces,only:nf_inq_libvers
use netcdf_nf_interfaces,only:nf_strerror
use netcdf_nf_interfaces,only:nf_issyserr
use netcdf_nf_interfaces,only:nf_create
use netcdf_nf_interfaces,only:nf_create_par
use netcdf_nf_interfaces,only:nf__create
use netcdf_nf_interfaces,only:nf__create_mp
use netcdf_nf_interfaces,only:nf_open
use netcdf_nf_interfaces,only:nf_open_par
use netcdf_nf_interfaces,only:nf__open
use netcdf_nf_interfaces,only:nf__open_mp
use netcdf_nf_interfaces,only:nf_open_mem
use netcdf_nf_interfaces,only:nf_var_par_access
use netcdf_nf_interfaces,only:nf_inq_path
use netcdf_nf_interfaces,only:nf_set_fill
use netcdf_nf_interfaces,only:nf_set_default_format
use netcdf_nf_interfaces,only:nf_redef
use netcdf_nf_interfaces,only:nf_enddef
use netcdf_nf_interfaces,only:nf__enddef
use netcdf_nf_interfaces,only:nf_sync
use netcdf_nf_interfaces,only:nf_abort
use netcdf_nf_interfaces,only:nf_close
use netcdf_nf_interfaces,only:nf_delete
use netcdf_nf_interfaces,only:nf_delete_mp
use netcdf_nf_interfaces,only:nf_set_base_pe
use netcdf_nf_interfaces,only:nf_inq_base_pe
use netcdf_nf_interfaces,only:nf_def_dim
use netcdf_nf_interfaces,only:nf_inq_dim
use netcdf_nf_interfaces,only:nf_inq_dimid
use netcdf_nf_interfaces,only:nf_inq_dimlen
use netcdf_nf_interfaces,only:nf_inq_dimname
use netcdf_nf_interfaces,only:nf_rename_dim
use netcdf_nf_interfaces,only:nf_inq
use netcdf_nf_interfaces,only:nf_inq_ndims
use netcdf_nf_interfaces,only:nf_inq_nvars
use netcdf_nf_interfaces,only:nf_inq_natts
use netcdf_nf_interfaces,only:nf_inq_unlimdim
use netcdf_nf_interfaces,only:nf_inq_format
use netcdf_nf_interfaces,only:nf_def_var
use netcdf_nf_interfaces,only:nf_inq_varndims
use netcdf_nf_interfaces,only:nf_inq_var
use netcdf_nf_interfaces,only:nf_inq_vardimid
use netcdf_nf_interfaces,only:nf_inq_varid
use netcdf_nf_interfaces,only:nf_inq_varname
use netcdf_nf_interfaces,only:nf_inq_vartype
use netcdf_nf_interfaces,only:nf_inq_varnatts
use netcdf_nf_interfaces,only:nf_rename_var
use netcdf_nf_interfaces,only:nf_copy_var
use netcdf_nf_interfaces,only:nf_inq_att
use netcdf_nf_interfaces,only:nf_inq_atttype
use netcdf_nf_interfaces,only:nf_inq_attlen
use netcdf_nf_interfaces,only:nf_inq_attid
use netcdf_nf_interfaces,only:nf_inq_attname
use netcdf_nf_interfaces,only:nf_copy_att
use netcdf_nf_interfaces,only:nf_rename_att
use netcdf_nf_interfaces,only:nf_del_att
use netcdf_nf_interfaces,only:nf_put_var1_text
use netcdf_nf_interfaces,only:nf_put_var1_int1
use netcdf_nf_interfaces,only:nf_put_var1_int2
use netcdf_nf_interfaces,only:nf_put_var1_int
use netcdf_nf_interfaces,only:nf_put_var1_real
use netcdf_nf_interfaces,only:nf_put_var1_double
use netcdf_nf_interfaces,only:nf_get_var1_text
use netcdf_nf_interfaces,only:nf_get_var1_int1
use netcdf_nf_interfaces,only:nf_get_var1_int2
use netcdf_nf_interfaces,only:nf_get_var1_int
use netcdf_nf_interfaces,only:nf_get_var1_real
use netcdf_nf_interfaces,only:nf_get_var1_double
use netcdf_nf_interfaces,only:nf_put_var_text_a
use netcdf_nf_interfaces,only:nf_put_var_int1
use netcdf_nf_interfaces,only:nf_put_var_int2
use netcdf_nf_interfaces,only:nf_put_var_int
use netcdf_nf_interfaces,only:nf_put_var_real
use netcdf_nf_interfaces,only:nf_put_var_double
use netcdf_nf_interfaces,only:nf_get_var_text_a
use netcdf_nf_interfaces,only:nf_get_var_int1
use netcdf_nf_interfaces,only:nf_get_var_int2
use netcdf_nf_interfaces,only:nf_get_var_int
use netcdf_nf_interfaces,only:nf_get_var_real
use netcdf_nf_interfaces,only:nf_get_var_double
use netcdf_nf_interfaces,only:nf_put_vars_text_a
use netcdf_nf_interfaces,only:nf_put_vars_int1
use netcdf_nf_interfaces,only:nf_put_vars_int2
use netcdf_nf_interfaces,only:nf_put_vars_int
use netcdf_nf_interfaces,only:nf_put_vars_real
use netcdf_nf_interfaces,only:nf_put_vars_double
use netcdf_nf_interfaces,only:nf_get_vars_text_a
use netcdf_nf_interfaces,only:nf_get_vars_int1
use netcdf_nf_interfaces,only:nf_get_vars_int2
use netcdf_nf_interfaces,only:nf_get_vars_int
use netcdf_nf_interfaces,only:nf_get_vars_real
use netcdf_nf_interfaces,only:nf_get_vars_double
use netcdf_nf_interfaces,only:nf_put_varm_text_a
use netcdf_nf_interfaces,only:nf_put_varm_int1
use netcdf_nf_interfaces,only:nf_put_varm_int2
use netcdf_nf_interfaces,only:nf_put_varm_int
use netcdf_nf_interfaces,only:nf_put_varm_real
use netcdf_nf_interfaces,only:nf_put_varm_double
use netcdf_nf_interfaces,only:nf_get_varm_text_a
use netcdf_nf_interfaces,only:nf_get_varm_int1
use netcdf_nf_interfaces,only:nf_get_varm_int2
use netcdf_nf_interfaces,only:nf_get_varm_int
use netcdf_nf_interfaces,only:nf_get_varm_real
use netcdf_nf_interfaces,only:nf_get_varm_double
use netcdf_nf_interfaces,only:nf_put_vara_text_a
use netcdf_nf_interfaces,only:nf_put_vara_int1
use netcdf_nf_interfaces,only:nf_put_vara_int2
use netcdf_nf_interfaces,only:nf_put_vara_int
use netcdf_nf_interfaces,only:nf_put_vara_int64
use netcdf_nf_interfaces,only:nf_put_vara_real
use netcdf_nf_interfaces,only:nf_put_vara_double
use netcdf_nf_interfaces,only:nf_get_vara_text_a
use netcdf_nf_interfaces,only:nf_get_vara_int1
use netcdf_nf_interfaces,only:nf_get_vara_int2
use netcdf_nf_interfaces,only:nf_get_vara_int
use netcdf_nf_interfaces,only:nf_get_vara_int64
use netcdf_nf_interfaces,only:nf_get_vara_real
use netcdf_nf_interfaces,only:nf_get_vara_double
use netcdf_nf_interfaces,only:nf_put_att_text_a
use netcdf_nf_interfaces,only:nf_put_att_int1
use netcdf_nf_interfaces,only:nf_put_att_int2
use netcdf_nf_interfaces,only:nf_put_att_int
use netcdf_nf_interfaces,only:nf_put_att_int64
use netcdf_nf_interfaces,only:nf_put_att_real
use netcdf_nf_interfaces,only:nf_put_att_double
use netcdf_nf_interfaces,only:nf_get_att_text_a
use netcdf_nf_interfaces,only:nf_get_att_int1
use netcdf_nf_interfaces,only:nf_get_att_int2
use netcdf_nf_interfaces,only:nf_get_att_int
use netcdf_nf_interfaces,only:nf_get_att_int64
use netcdf_nf_interfaces,only:nf_get_att_real
use netcdf_nf_interfaces,only:nf_get_att_double
use netcdf_nf_interfaces,only:nf_put_var1
use netcdf_nf_interfaces,only:nf_get_var1
use netcdf_nf_interfaces,only:nf_put_vars
use netcdf_nf_interfaces,only:nf_get_vars
use netcdf_nf_interfaces,only:nf_put_vara
use netcdf_nf_interfaces,only:nf_get_vara
use netcdf_nf_interfaces,only:nccre
use netcdf_nf_interfaces,only:ncopn
use netcdf_nf_interfaces,only:ncddef
use netcdf_nf_interfaces,only:ncdid
use netcdf_nf_interfaces,only:ncvdef
use netcdf_nf_interfaces,only:ncvid
use netcdf_nf_interfaces,only:nctlen
use netcdf_nf_interfaces,only:ncsfil
use netcdf_nf_interfaces,only:nf90_open_mem
use netcdf_nf_interfaces,only:nf_put_var_text
use netcdf_nf_interfaces,only:nf_get_var_text
use netcdf_nf_interfaces,only:nf_put_vars_text
use netcdf_nf_interfaces,only:nf_get_vars_text
use netcdf_nf_interfaces,only:nf_put_varm_text
use netcdf_nf_interfaces,only:nf_get_varm_text
use netcdf_nf_interfaces,only:nf_put_vara_text
use netcdf_nf_interfaces,only:nf_get_vara_text
use netcdf_nf_interfaces,only:nf_put_att_text
use netcdf_nf_interfaces,only:nf_get_att_text
use netcdf4_nf_interfaces,only:nf_inq_ncid
use netcdf4_nf_interfaces,only:nf_inq_grps
use netcdf4_nf_interfaces,only:nf_inq_grpname
use netcdf4_nf_interfaces,only:nf_inq_grpname_full
use netcdf4_nf_interfaces,only:nf_inq_grpname_len
use netcdf4_nf_interfaces,only:nf_inq_grp_parent
use netcdf4_nf_interfaces,only:nf_inq_grp_full_ncid
use netcdf4_nf_interfaces,only:nf_inq_grp_ncid
use netcdf4_nf_interfaces,only:nf_inq_varids
use netcdf4_nf_interfaces,only:nf_inq_dimids
use netcdf4_nf_interfaces,only:nf_inq_typeids
use netcdf4_nf_interfaces,only:nf_inq_typeid
use netcdf4_nf_interfaces,only:nf_def_grp
use netcdf4_nf_interfaces,only:nf_rename_grp
use netcdf4_nf_interfaces,only:nf_def_compound
use netcdf4_nf_interfaces,only:nf_insert_compound
use netcdf4_nf_interfaces,only:nf_insert_array_compound
use netcdf4_nf_interfaces,only:nf_inq_type
use netcdf4_nf_interfaces,only:nf_inq_compound
use netcdf4_nf_interfaces,only:nf_inq_compound_name
use netcdf4_nf_interfaces,only:nf_inq_compound_size
use netcdf4_nf_interfaces,only:nf_inq_compound_nfields
use netcdf4_nf_interfaces,only:nf_inq_compound_field
use netcdf4_nf_interfaces,only:nf_inq_compound_fieldname
use netcdf4_nf_interfaces,only:nf_inq_compound_fieldindex
use netcdf4_nf_interfaces,only:nf_inq_compound_fieldoffset
use netcdf4_nf_interfaces,only:nf_inq_compound_fieldtype
use netcdf4_nf_interfaces,only:nf_inq_compound_fieldndims
use netcdf4_nf_interfaces,only:nf_inq_compound_fielddim_sizes
use netcdf4_nf_interfaces,only:nf_def_vlen
use netcdf4_nf_interfaces,only:nf_inq_vlen
use netcdf4_nf_interfaces,only:nf_inq_user_type
use netcdf4_nf_interfaces,only:nf_def_enum
use netcdf4_nf_interfaces,only:nf_inq_enum
use netcdf4_nf_interfaces,only:nf_inq_enum_ident
use netcdf4_nf_interfaces,only:nf_def_opaque
use netcdf4_nf_interfaces,only:nf_inq_opaque
use netcdf4_nf_interfaces,only:nf_def_var_chunking
use netcdf4_nf_interfaces,only:nf_inq_var_chunking
use netcdf4_nf_interfaces,only:nf_def_var_deflate
use netcdf4_nf_interfaces,only:nf_inq_var_deflate
use netcdf4_nf_interfaces,only:nf_def_var_szip
use netcdf4_nf_interfaces,only:nf_inq_var_szip
use netcdf4_nf_interfaces,only:nf_def_var_quantize
use netcdf4_nf_interfaces,only:nf_inq_var_quantize
use netcdf4_nf_interfaces,only:nf_def_var_zstandard
use netcdf4_nf_interfaces,only:nf_inq_var_zstandard
use netcdf4_nf_interfaces,only:nf_def_var_fletcher32
use netcdf4_nf_interfaces,only:nf_inq_var_fletcher32
use netcdf4_nf_interfaces,only:nf_def_var_endian
use netcdf4_nf_interfaces,only:nf_inq_var_endian
use netcdf4_nf_interfaces,only:nf_def_var_filter
use netcdf4_nf_interfaces,only:nf_inq_var_filter
use netcdf4_nf_interfaces,only:nf_put_var1_int64
use netcdf4_nf_interfaces,only:nf_put_vars_int64
use netcdf4_nf_interfaces,only:nf_put_varm_int64
use netcdf4_nf_interfaces,only:nf_put_var_int64
use netcdf4_nf_interfaces,only:nf_get_var1_int64
use netcdf4_nf_interfaces,only:nf_get_vars_int64
use netcdf4_nf_interfaces,only:nf_get_varm_int64
use netcdf4_nf_interfaces,only:nf_get_var_int64
use netcdf4_nf_interfaces,only:nf_set_chunk_cache
use netcdf4_nf_interfaces,only:nf_get_chunk_cache
use netcdf4_nf_interfaces,only:nf_set_var_chunk_cache
use netcdf4_nf_interfaces,only:nf_get_var_chunk_cache
use netcdf4_nf_interfaces,only:nf_insert_enum
use netcdf4_nf_interfaces,only:nf_inq_enum_member
use netcdf4_nf_interfaces,only:nf_put_att
use netcdf4_nf_interfaces,only:nf_get_att
use netcdf4_nf_interfaces,only:nf_put_vlen_element
use netcdf4_nf_interfaces,only:nf_get_vlen_element
use netcdf4_nf_interfaces,only:nf_free_vlen
use netcdf4_nf_interfaces,only:nf_free_vlens
use netcdf4_nf_interfaces,only:nf_free_string
use netcdf4_nf_interfaces,only:nf_put_var
use netcdf4_nf_interfaces,only:nf_get_var
use netcdf4_nf_interfaces,only:nf_def_var_fill
use netcdf4_nf_interfaces,only:nf_inq_var_fill
end
