!mod$ v1 sum:df016c0d2a01d490
!need$ fe3180dd7f22d4c1 n parkind1
module yoecumf
use parkind1,only:jpim
use parkind1,only:jprb
type::tecumf
real(8)::entrorg
real(8)::gmoc1
real(8)::gmoc2
real(8)::gmoc3
real(8)::gmoctau
real(8)::gmoen1
real(8)::gmoen2
real(8)::gmotau1
real(8)::gmotau2
logical(4)::lgmo
real(8)::entrtest
real(8)::entr_rh
real(8)::entshalp
real(8)::entstpc1
real(8)::entstpc2
real(8)::entstpc3
real(8)::entrdd
real(8)::detrpen
real(8)::rmfcfl
real(8)::rmflia
real(8)::rmfsoluv
real(8)::rmfsoltq
real(8)::rmfsolct
real(8)::rmfsolrhs
real(8)::rmfadvw
real(8)::rmfadvwdd
real(8)::rmfcmin
real(8)::rmfdeps
real(8)::rdepths
real(8)::rprcon
real(8)::rtaua
real(8)::rcapdcycl
real(8)::rtau0
real(8)::rcapqadv
real(8)::rmincape
real(8)::rcpecons
real(8)::rcvrfactor
real(8)::rcucov
real(8)::rtaumel
real(8)::rhebc
real(8)::ruvper
real(8)::rbase0
real(8)::rmincin
real(8)::rxmin
real(8)::rtaulim
real(8)::rtaufac
real(8)::rdxmin
real(8)::rdxmax
logical(4)::lmfpen
logical(4)::lmfscv
logical(4)::lmfmid
logical(4)::lmfdd
logical(4)::lmfdudv
logical(4)::lmfdsnow
logical(4)::lmfwetb
logical(4)::lmfglac
logical(4)::lscvliq
logical(4)::lnewtau
logical(4)::lmfenthcons
logical(4)::lmfuvdis
logical(4)::lmfsmooth
logical(4)::lmfwstar
logical(4)::lmfcuca
logical(4)::lmfprofp
integer(4)::njkt1
integer(4)::njkt2
integer(4)::njkt3
integer(4)::njkt4
integer(4)::njkt5
integer(4)::njkt6
integer(4)::njkt7
integer(4)::njkt8
contains
procedure,pass::print=>print_configuration
end type
contains
subroutine print_configuration(self,kdepth,koutno)
class(tecumf),intent(in)::self
integer(4),intent(in)::kdepth
integer(4),intent(in)::koutno
end
end
