!mod$ v1 sum:fe30d16384671131
!need$ fe3180dd7f22d4c1 n parkind1
!need$ 99f7ec52259902ea n yomhook
module yoecldp
use parkind1,only:jpim
use parkind1,only:jprb
use yomhook,only:lhook
use yomhook,only:dr_hook
use yomhook,only:jphook
use yomhook,only:yomhook$yomhook$dr_hook_default8=>dr_hook_default8
integer(4),parameter::nclv=5_4
integer(4),parameter::ncldql=1_4
integer(4),parameter::ncldqi=2_4
integer(4),parameter::ncldqr=3_4
integer(4),parameter::ncldqs=4_4
integer(4),parameter::ncldqv=5_4
integer(4),parameter::nprectypes=12_4
type::tecldp
real(8)::ramid
real(8)::rcldiff
real(8)::rcldiff_convi
real(8)::rclcrit
real(8)::rclcrit_sea
real(8)::rclcrit_land
real(8)::rkconv
real(8)::rprc1
real(8)::rprc2
real(8)::rcldmax
real(8)::rpecons
real(8)::rvrfactor
real(8)::rprecrhmax
real(8)::rtaumel
real(8)::ramin
real(8)::rlmin
real(8)::rkooptau
real(8)::rssicefactor
real(8)::rcldtopp
real(8)::rlcritsnow
real(8)::rsnowlin1
real(8)::rsnowlin2
real(8)::ricehi1
real(8)::ricehi2
real(8)::riceinit
real(8)::rvice
real(8)::rvrain
real(8)::rvsnow
real(8)::rthomo
real(8)::rcovpmin
real(8)::rccn
real(8)::rnice
real(8)::rccnom
real(8)::rccnss
real(8)::rccnsu
real(8)::rcldtopcf
real(8)::rdepliqrefrate
real(8)::rdepliqrefdepth
real(8)::rcl_overlapliqice
real(8)::rcl_effrime
real(8)::rxfallspeedrain
real(8)::rxfallspeedice
real(8)::rtau_cld_tlad
real(8)::rcl_kkaac
real(8)::rcl_kkbac
real(8)::rcl_kkaau
real(8)::rcl_kkbauq
real(8)::rcl_kkbaun
real(8)::rcl_kk_cloud_num_sea
real(8)::rcl_kk_cloud_num_land
real(8)::rcl_inhomogaut
real(8)::rcl_inhomogacc
logical(4)::lcloud_inhomog
real(8)::rcl_ai
real(8)::rcl_bi
real(8)::rcl_ci
real(8)::rcl_di
real(8)::rcl_x1i
real(8)::rcl_x2i
real(8)::rcl_x3i
real(8)::rcl_x4i
real(8)::rcl_const1i
real(8)::rcl_const2i
real(8)::rcl_const3i
real(8)::rcl_const4i
real(8)::rcl_const5i
real(8)::rcl_const6i
real(8)::rcl_const7i
real(8)::rcl_lambda1i
real(8)::rcl_lambda2i
real(8)::rcl_apb1
real(8)::rcl_apb2
real(8)::rcl_apb3
real(8)::rcl_as
real(8)::rcl_bs
real(8)::rcl_cs
real(8)::rcl_ds
real(8)::rcl_x1s
real(8)::rcl_x2s
real(8)::rcl_x3s
real(8)::rcl_x4s
real(8)::rcl_const1s
real(8)::rcl_const2s
real(8)::rcl_const3s
real(8)::rcl_const4s
real(8)::rcl_const5s
real(8)::rcl_const6s
real(8)::rcl_const7s
real(8)::rcl_const8s
real(8)::rcl_lam1s
real(8)::rcl_lam2s
real(8)::rdenswat
real(8)::rdensref
real(8)::rcl_ar
real(8)::rcl_br
real(8)::rcl_cr
real(8)::rcl_dr
real(8)::rcl_x1r
real(8)::rcl_x2r
real(8)::rcl_x4r
real(8)::rcl_x1r_mp
real(8)::rcl_x2r_mp
real(8)::rcl_x4r_mp
real(8)::rcl_ka273
real(8)::rcl_cdenom1
real(8)::rcl_cdenom2
real(8)::rcl_cdenom3
real(8)::rcl_schmidt
real(8)::rcl_dynvisc
real(8)::rcl_const1r
real(8)::rcl_const2r
real(8)::rcl_const3r
real(8)::rcl_const4r
real(8)::rcl_const7r
real(8)::rcl_const8r
real(8)::rcl_lam1r
real(8)::rcl_lam2r
real(8)::rcl_lam1r_mp
real(8)::rcl_lam2r_mp
real(8)::rcl_const5r
real(8)::rcl_const6r
real(8)::rcl_fzrab
real(8)::rcl_fzrbb
real(8)::rcl_const9r
real(8)::rcl_const10r
real(8)::rcl_eff_racw
integer(4)::nptype_sev2wmo(1_8:12_8)
logical(4)::lcldextra
logical(4)::lcldbudget
logical(4)::lcldbudc
logical(4)::lcldbudl
logical(4)::lcldbudi
logical(4)::lcldbudt
logical(4)::lcldbud_timeint
logical(4)::lcldbud_vertint
integer(4)::nssopt
integer(4)::ncldtop
integer(4)::naeclbc
integer(4)::naecldu
integer(4)::naeclom
integer(4)::naeclss
integer(4)::naeclsu
integer(4)::nclddiag
integer(4)::naercld
logical(4)::laerliqautolsp
logical(4)::laerliqautocp
logical(4)::laerliqautocpb
logical(4)::laerliqcoll
logical(4)::laericesed
logical(4)::laericeauto
real(8)::nshapep
real(8)::nshapeq
integer(4)::nbeta
real(8)::rbeta(0_8:100_8)
real(8)::rbetap1(0_8:100_8)
contains
procedure,pass::print=>print_configuration
end type
contains
subroutine print_configuration(self,kdepth,koutno)
class(tecldp),intent(in)::self
integer(4),intent(in)::kdepth
integer(4),intent(in)::koutno
end
end
