!mod$ v1 sum:eb04696016e1f4f0
!need$ fe3180dd7f22d4c1 n parkind1
!need$ 0bde2ac47243ead2 i iso_c_binding
module yoephy
use parkind1,only:jprb
use parkind1,only:jpim
use,intrinsic::iso_c_binding,only:c_associated
use,intrinsic::iso_c_binding,only:c_funloc
use,intrinsic::iso_c_binding,only:c_funptr
use,intrinsic::iso_c_binding,only:c_f_pointer
use,intrinsic::iso_c_binding,only:c_loc
use,intrinsic::iso_c_binding,only:c_null_funptr
use,intrinsic::iso_c_binding,only:c_null_ptr
use,intrinsic::iso_c_binding,only:c_ptr
use,intrinsic::iso_c_binding,only:c_sizeof
use,intrinsic::iso_c_binding,only:operator(==)
use,intrinsic::iso_c_binding,only:operator(/=)
use,intrinsic::iso_c_binding,only:c_int8_t
use,intrinsic::iso_c_binding,only:c_int16_t
use,intrinsic::iso_c_binding,only:c_int32_t
use,intrinsic::iso_c_binding,only:c_int64_t
use,intrinsic::iso_c_binding,only:c_int128_t
use,intrinsic::iso_c_binding,only:c_int
use,intrinsic::iso_c_binding,only:c_short
use,intrinsic::iso_c_binding,only:c_long
use,intrinsic::iso_c_binding,only:c_long_long
use,intrinsic::iso_c_binding,only:c_signed_char
use,intrinsic::iso_c_binding,only:c_size_t
use,intrinsic::iso_c_binding,only:c_intmax_t
use,intrinsic::iso_c_binding,only:c_intptr_t
use,intrinsic::iso_c_binding,only:c_ptrdiff_t
use,intrinsic::iso_c_binding,only:c_int_least8_t
use,intrinsic::iso_c_binding,only:c_int_fast8_t
use,intrinsic::iso_c_binding,only:c_int_least16_t
use,intrinsic::iso_c_binding,only:c_int_fast16_t
use,intrinsic::iso_c_binding,only:c_int_least32_t
use,intrinsic::iso_c_binding,only:c_int_fast32_t
use,intrinsic::iso_c_binding,only:c_int_least64_t
use,intrinsic::iso_c_binding,only:c_int_fast64_t
use,intrinsic::iso_c_binding,only:c_int_least128_t
use,intrinsic::iso_c_binding,only:c_int_fast128_t
use,intrinsic::iso_c_binding,only:c_float
use,intrinsic::iso_c_binding,only:c_double
use,intrinsic::iso_c_binding,only:c_long_double
use,intrinsic::iso_c_binding,only:c_float_complex
use,intrinsic::iso_c_binding,only:c_double_complex
use,intrinsic::iso_c_binding,only:c_long_double_complex
use,intrinsic::iso_c_binding,only:c_bool
use,intrinsic::iso_c_binding,only:c_char
use,intrinsic::iso_c_binding,only:c_null_char
use,intrinsic::iso_c_binding,only:c_alert
use,intrinsic::iso_c_binding,only:c_backspace
use,intrinsic::iso_c_binding,only:c_form_feed
use,intrinsic::iso_c_binding,only:c_new_line
use,intrinsic::iso_c_binding,only:c_carriage_return
use,intrinsic::iso_c_binding,only:c_horizontal_tab
use,intrinsic::iso_c_binding,only:c_vertical_tab
use,intrinsic::iso_c_binding,only:c_float128
use,intrinsic::iso_c_binding,only:c_float128_complex
use,intrinsic::iso_c_binding,only:c_uint8_t
use,intrinsic::iso_c_binding,only:c_uint16_t
use,intrinsic::iso_c_binding,only:c_uint32_t
use,intrinsic::iso_c_binding,only:c_uint64_t
use,intrinsic::iso_c_binding,only:c_uint128_t
use,intrinsic::iso_c_binding,only:c_unsigned_char
use,intrinsic::iso_c_binding,only:c_unsigned_short
use,intrinsic::iso_c_binding,only:c_unsigned
use,intrinsic::iso_c_binding,only:c_unsigned_long
use,intrinsic::iso_c_binding,only:c_unsigned_long_long
use,intrinsic::iso_c_binding,only:c_uintmax_t
use,intrinsic::iso_c_binding,only:c_uint_fast8_t
use,intrinsic::iso_c_binding,only:c_uint_fast16_t
use,intrinsic::iso_c_binding,only:c_uint_fast32_t
use,intrinsic::iso_c_binding,only:c_uint_fast64_t
use,intrinsic::iso_c_binding,only:c_uint_fast128_t
use,intrinsic::iso_c_binding,only:c_uint_least8_t
use,intrinsic::iso_c_binding,only:c_uint_least16_t
use,intrinsic::iso_c_binding,only:c_uint_least32_t
use,intrinsic::iso_c_binding,only:c_uint_least64_t
use,intrinsic::iso_c_binding,only:c_uint_least128_t
use,intrinsic::iso_c_binding,only:c_f_procpointer
type::tephy
logical(4)::lephys
logical(4)::lecond
logical(4)::lecumf
logical(4)::ledcld
logical(4)::leevap
logical(4)::legwdg
logical(4)::legwwms
logical(4)::leozoc
logical(4)::leqngt
logical(4)::leradi
logical(4)::leradimpl
logical(4)::lerads
logical(4)::lesice
logical(4)::lesurf
logical(4)::levdif
logical(4)::lagphy
logical(4)::lepcld
logical(4)::leo3ch
logical(4)::lo3ch_safe
logical(4)::lo3ch_oldver
logical(4)::lo3ch_bms
logical(4)::lo3ch_hlo
character(4_4,1)::co3chem
logical(4)::lneeonline
logical(4)::lwetonline
logical(4)::lbud23
logical(4)::lpptiles
logical(4)::lbudcycle
logical(4)::lextratend
logical(4)::lemethox
logical(4)::lecurr
logical(4)::lesurftraj
logical(4)::lvdftrac
logical(4)::lvdfnewtrac
logical(4)::lmftrac
logical(4)::lmfscav
logical(4)::lemwave
logical(4)::legbrad
logical(4)::leraingg
logical(4)::lesmos
logical(4)::lesmap
logical(4)::leocwa
logical(4)::leocco
logical(4)::leocsa
logical(4)::leocla
logical(4)::levgen
logical(4)::lessro
logical(4)::leflake
logical(4)::leocml
logical(4)::leobc
logical(4)::leobcmax
real(8)::reobcmax
logical(4)::leobcice
logical(4)::leoclake
logical(4)::leolakesst
logical(4)::locmltke
logical(4)::leclipqt0
logical(4)::leclipcldt0
logical(4)::lductdia
logical(4)::ldiagturb_ec
logical(4)::ldiagturbgrad_ec
logical(4)::lblend
logical(4)::lslphy
logical(4)::lesn09
logical(4)::lelaiv
logical(4)::lectessel
logical(4)::leags
logical(4)::lefarquhar
logical(4)::leoptsurf
logical(4)::lec4map
logical(4)::leairco2coup
logical(4)::lelight
logical(4)::lvextrdynacc
real(8)::rthrfrti
real(8)::rcimin
real(8)::rlaiint
integer(4)::npraccl
integer(4)::nlimode
logical(4)::lglightco
logical(4)::leclim10d
logical(4)::lesnml
logical(4)::leurban
integer(4)::nsnmlws
logical(4)::lbfasco2
integer(4)::nco2climyy1
integer(4)::nco2climyy2
integer(4)::nco2climn1
integer(4)::nco2climn2
integer(4)::nco2climfrq
integer(4)::nalbedoscheme
integer(4)::nemissscheme
real(8)::ralfminpsn
real(8)::rnorthml
real(8)::rsouthml
real(8)::rwestml
real(8)::reastml
logical(4)::invml
logical(4)::lfpos_ec_phys=.false._4
logical(4)::lfpos_acc_reset
logical(4)::lrad_cloud_inhomog
type(c_ptr)::ysurf
contains
procedure,pass::print=>print_configuration
end type
type(tephy),pointer::yrephy
intrinsic::null
contains
subroutine print_configuration(self,kdepth,koutno)
class(tephy),intent(in)::self
integer(4),intent(in)::kdepth
integer(4),intent(in)::koutno
end
end
