!mod$ v1 sum:67b29aa9476ac84e
!need$ fe3180dd7f22d4c1 n parkind1
module yomct0
use parkind1,only:jpim
use parkind1,only:jprb
integer(4),parameter::jpnpst=960_4
integer(4)::nconf
integer(4)::nfpos
logical(4)::lr3d
logical(4)::lr2d
logical(4)::lrshw
logical(4)::lrveq
integer(4)::nopt_memory
integer(4)::nopt_memory_ad
logical(4)::lallopr
logical(4)::lfdbop
logical(4)::lecfpos
logical(4)::lgrbop
logical(4)::lfbdap
logical(4)::larpegef
logical(4)::larpegef_trajhr
logical(4)::larpegef_trajbg
logical(4)::larpegef_rdgp_init
logical(4)::larpegef_rdgp_trajhr
logical(4)::larpegef_rdgp_trajbg
character(120_4,1)::cndispp
character(128_4,1)::cfpncf
character(120_4,1)::cfdirlst
character(120_4,1)::cnppath
character(120_4,1)::cscript_ppserver
character(120_4,1)::cscript_lamrtc
logical(4)::lnf
logical(4)::lsmssig
character(25_4,1)::cevent
character(25_4,1)::cmeter
logical(4)::lopdis
character(16_4,1)::cnmexp
logical(4)::lbackg
logical(4)::lspbsbal
logical(4)::lminim
logical(4)::liolevg
integer(4)::nundefld
logical(4)::lrefout
logical(4)::lrefgen
integer(4)::nquad
integer(4)::n2dini
integer(4)::n3dini
integer(4)::nsppr
integer(4)::nfrpos
integer(4)::nfrcorm
integer(4)::nfrco
integer(4)::nfrhis
integer(4)::nfrsfxhis
integer(4)::nfrmasscon
integer(4)::nfrgdi
integer(4)::nfrsdi
integer(4)::nfrdhfg
integer(4)::nfrdhfz
integer(4)::nfrdhfd
integer(4)::nfrdhp
integer(4)::n6bins
integer(4)::nposts(0_8:960_8)
integer(4)::npostsmin(0_8:960_8)
integer(4)::nhists(0_8:960_8)
integer(4)::nhistsmin(0_8:960_8)
integer(4)::nsfxhists(0_8:960_8)
integer(4)::nsfxhistsmin(0_8:960_8)
integer(4)::nmasscons(0_8:960_8)
integer(4)::ngdits(0_8:960_8)
integer(4)::nsdits(0_8:960_8)
integer(4)::ndhfgts(0_8:960_8)
integer(4)::ndhfzts(0_8:960_8)
integer(4)::ndhfdts(0_8:960_8)
integer(4)::ndhpts(0_8:960_8)
logical(4)::l4dvar
logical(4)::lcanari
integer(4)::ntasks_canari
logical(4)::lguess
logical(4)::lobs
logical(4)::lsimob
logical(4)::lobsc1
logical(4)::lscreen
logical(4)::lscreen_openmp
logical(4)::l_split_screen
logical(4)::l_screen_call
logical(4)::lmonitoring
logical(4)::lobsref
logical(4)::lifsmin
logical(4)::lifstraj
integer(4)::ncntvar
logical(4)::loldpp
integer(4)::nstepini
integer(4)::ninterptraj
integer(4)::ninterpincr
logical(4)::linflat
logical(4)::linflp9
logical(4)::linflf1
logical(4)::l_oops
logical(4)::l_oops_verbose_norms
logical(4)::lecmwf
logical(4)::lelam
logical(4)::lrplane
logical(4)::larome
logical(4)::lcallsfx
logical(4)::lsfxlsm
logical(4)::lconserv
logical(4)::lcorwat
logical(4)::lsfcflx
real(8)::rextshf
real(8)::rextlhf
logical(4)::lrough
real(8)::rextz0m
real(8)::rextz0h
logical(4)::lcouplo4
logical(4)::lcouplo4_env
logical(4)::lsforc
logical(4)::lsforcs
logical(4)::lwrspeca_gp
logical(4)::lsuspeca_gp
logical(4)::lwrspeca_gp_uv
logical(4)::lsuspeca_gp_uv
logical(4)::lgrib_api
integer(4)::niter_adtest
logical(4)::lread_orography_first
end
