!mod$ v1 sum:63d2912c9610bc6f
!need$ fe3180dd7f22d4c1 n parkind1
module yomcst
use parkind1,only:jprb
type::tcst
real(8)::rpi
real(8)::rclum
real(8)::rhpla
real(8)::rkbol
real(8)::rnavo
real(8)::rday
real(8)::rdayi
real(8)::rhour
real(8)::rea
real(8)::repsm
real(8)::rsiyea
real(8)::rsiday
real(8)::romega
real(8)::ra
real(8)::rg
real(8)::r1sa
real(8)::deg2rad
real(8)::rsigma
real(8)::ri0
real(8)::r
real(8)::rmd
real(8)::rmv
real(8)::rmo3
real(8)::rd
real(8)::rv
real(8)::rcpd
real(8)::rcpv
real(8)::rcvd
real(8)::rcvv
real(8)::rkappa
real(8)::retv
real(8)::rmco2
real(8)::rmch4
real(8)::rmn2o
real(8)::rmco
real(8)::rmhcho
real(8)::rmno2
real(8)::rmso2
real(8)::rmso4
real(8)::rmcfc11
real(8)::rmcfc12
real(8)::rmhcfc22
real(8)::rmccl4
real(8)::rcw
real(8)::rcs
real(8)::ratm
real(8)::rtt
real(8)::rlvtt
real(8)::rlstt
real(8)::rlvzer
real(8)::rlszer
real(8)::rlmlt
real(8)::rdt
real(8)::restt
real(8)::rgamw
real(8)::rbetw
real(8)::ralpw
real(8)::rgams
real(8)::rbets
real(8)::ralps
real(8)::ralpd
real(8)::rbetd
real(8)::rgamd
real(8)::rk1
real(8)::rk2
real(8)::rk3
real(8)::rgnsssat
real(8)::rgnssear
real(8)::rawgs
real(8)::rewgs
real(8)::rfwgs
real(8)::rgequ
real(8)::rgrat
real(8)::rkssom
end type
real(8),protected::rpi
real(8),protected::rclum
real(8),protected::rhpla
real(8),protected::rkbol
real(8),protected::rnavo
real(8),protected::rday
real(8),protected::rdayi
real(8),protected::rhour
real(8),protected::rea
real(8),protected::repsm
real(8),protected::rsiyea
real(8),protected::rsiday
real(8),protected::romega
real(8),protected::ra
real(8),protected::ra_earth
real(8),protected::rg
real(8),protected::r1sa
real(8),protected::deg2rad
real(8),protected::rad2deg
real(8),protected::rsigma
real(8),protected::ri0
real(8),protected::r
real(8),protected::rmd
real(8),protected::rmv
real(8),protected::rmo3
real(8),protected::rd
real(8),protected::rv
real(8),protected::rcpd
real(8),protected::rcpv
real(8),protected::rcvd
real(8),protected::rcvv
real(8),protected::rkappa
real(8),protected::retv
real(8),protected::rmco2
real(8),protected::rmch4
real(8),protected::rmn2o
real(8),protected::rmco
real(8),protected::rmhcho
real(8),protected::rmno2
real(8),protected::rmso2
real(8),protected::rmso4
real(8),protected::rmcfc11
real(8),protected::rmcfc12
real(8),protected::rmhcfc22
real(8),protected::rmccl4
real(8),protected::rcw
real(8),protected::rcs
real(8),protected::ratm
real(8),protected::rtt
real(8),protected::rlvtt
real(8),protected::rlstt
real(8),protected::rlvzer
real(8),protected::rlszer
real(8),protected::rlmlt
real(8),protected::rdt
real(8),protected::restt
real(8),protected::rgamw
real(8),protected::rbetw
real(8),protected::ralpw
real(8),protected::rgams
real(8),protected::rbets
real(8),protected::ralps
real(8),protected::ralpd
real(8),protected::rbetd
real(8),protected::rgamd
real(8),protected::rundef2
character(8_4,1),parameter::csnan="\000\000\000\000\000\000\364\177"
intrinsic::char
real(8),protected::rsnan
real(8),protected::rk1
real(8),protected::rk2
real(8),protected::rk3
real(8),protected::rgnsssat
real(8),protected::rgnssear
real(8),protected::rawgs
real(8),protected::rewgs
real(8),protected::rfwgs
real(8),protected::rgequ
real(8),protected::rgrat
real(8),protected::rkssom
logical(4),protected::l_has_been_setup
type(tcst),target::yrcst
contains
subroutine tcst_init(ydcst)
type(tcst),intent(in)::ydcst
end
subroutine setup_constants(kulout,kprintlev)
integer(4),intent(in)::kulout
integer(4),intent(in)::kprintlev
end
subroutine rvequalsrd()
end
end
