!mod$ v1 sum:5f747a7ce3877eca
!need$ 3eeb045851482ce7 n yomswe
!need$ fe3180dd7f22d4c1 n parkind1
module yomdyn
use parkind1,only:jpim
use parkind1,only:jprb
use yomswe,only:tswe
integer(4),parameter::jpsldimk=4_4
type::tdyn
real(8)::reps1
real(8)::reps2
real(8)::repsm1
real(8)::repsm2
real(8)::repsp1
real(8)::hdirvor
real(8)::hdirdiv
real(8)::hdirt
real(8)::hdirq
real(8)::hdiro3
real(8)::hdirpd
real(8)::hdirvd
real(8)::hdirsp
real(8)::hrdirvor
real(8)::hrdirdiv
real(8)::hrdirt
real(8)::hrdirq
real(8)::hrdiro3
real(8)::hrdirpd
real(8)::hrdirvd
real(8)::hrdirsp
real(8)::rrdxtau
real(8)::rdampvor
real(8)::rdampdiv
real(8)::rdampt
real(8)::rdampq
real(8)::rdampo3
real(8)::rdamppd
real(8)::rdampvd
real(8)::rdampsp
logical(4)::lnewhd
real(8)::rexpdh
real(8)::frandh
real(8)::slevdh
real(8)::slevdh1
real(8)::slevdh2
real(8)::slevdh3
integer(4)::nsrefdh
real(8)::ratio_hdi_top
integer(4)::nprofilehd
real(8)::rprofhdbt
real(8)::rprofhdtp
real(8)::rprofhdmx
real(8)::rprofhdex
logical(4)::lrdispe_ec
real(8),allocatable::rdivor(:,:)
real(8),allocatable::rdidiv(:,:)
real(8),allocatable::rditg(:,:)
real(8),allocatable::rdigfl(:,:,:)
real(8),allocatable::rdipd(:,:)
real(8),allocatable::rdivd(:,:)
real(8),allocatable::rdisp(:)
real(8),allocatable::rdhi(:,:,:)
real(8),allocatable::rdhivor(:,:,:)
real(8),allocatable::rdhidiv(:,:,:)
real(8),allocatable::rdhispd(:,:,:)
real(8),allocatable::rdhisvd(:,:,:)
real(8),allocatable::rdhinhx(:,:,:)
real(8),allocatable::rdhit(:,:,:)
real(8),allocatable::rdhigflq(:,:,:)
real(8),allocatable::rdhigflo3(:,:,:)
real(8),allocatable::rdhigfll(:,:,:)
real(8),allocatable::rdhigfli(:,:,:)
real(8),allocatable::rdhip(:,:,:)
real(8),allocatable::rdhsvor(:,:,:)
real(8),allocatable::rdhsdiv(:,:,:)
real(8),allocatable::rdhssvd(:,:,:)
real(8),allocatable::rdhsnhx(:,:,:)
logical(4)::lstrhd
real(8)::hdtime_strhd
real(8)::klsponge
logical(4)::lm0damp
real(8)::rbegsponge
logical(4)::ltop_vor
integer(4)::ntop_vor_trunc
integer(4)::ntop_vor_bot
real(8),allocatable::rsavedp(:,:,:,:)
real(8)::slhda0
real(8)::slhda0t
real(8)::slhdb
real(8)::slhdbt
real(8)::slhdd00
real(8)::slhdd00t
real(8)::slhddiv
real(8)::slhdratddiv
real(8)::slhdhor
real(8)::slhd_p_low
real(8)::slhd_p_high
logical(4)::lslhdheat
logical(4)::lslhdsponge
real(8)::hdsrvor
real(8)::hdsrdiv
real(8)::hdsrvd
real(8)::hrdsrvor
real(8)::hrdsrdiv
real(8)::hrdsrvd
real(8)::rdampvors
real(8)::rdampdivs
real(8)::rdampvds
real(8)::rdamphds
real(8)::rexpdhs
real(8)::slevdhs
real(8)::slevdhs1
real(8)::slevdhs2
real(8)::sdred
real(8),allocatable::rdsvor(:,:)
real(8),allocatable::rdsdiv(:,:)
real(8),allocatable::rdsvd(:,:)
real(8),allocatable::rdhs(:,:,:)
real(8),allocatable::slhd_mask_u(:)
real(8),allocatable::slhd_mask_t(:)
real(8)::zslhdp1
real(8)::zslhdp3
integer(4)::nlev_sponge
logical(4)::lrfric
logical(4)::lrfricisotr
real(8),allocatable::rcordit(:)
real(8),allocatable::rcordih(:)
real(8),allocatable::rcordif(:)
real(8)::vmax1
real(8)::vmax2
real(8)::rmax_d3
logical(4)::lbound_d3
real(8),allocatable::rkrf(:)
integer(4)::nmaxlevrf
real(8)::rrfz1
real(8)::rrfplm
real(8)::rrftau
real(8)::rtemrb
integer(4)::nrubc
logical(4)::lgwfric
integer(4)::nlev_gwfric
real(8)::rgwfric_max
real(8)::rgwfric_plm
real(8),allocatable::rgwfric(:)
logical(4)::lsidg
logical(4)::ldyn_staban
logical(4)::lrhdi_lastiterpc
logical(4)::lsidyn_verbose
real(8)::betadt
real(8)::rbt
real(8)::rbts2
real(8)::refgeo
real(8)::sipr
real(8)::sipra
real(8)::sitr
real(8)::sitra
real(8)::sitrub
real(8)::siprub
real(8)::sitime
real(8)::sirprg
real(8)::sirprn
real(8)::sislp
real(8)::sifrg
real(8)::sifra
real(8)::sitvar
integer(4)::nsiter
integer(4)::ncurrent_iter
integer(4)::niterhelm
integer(4)::nopt_sitr
integer(4)::nopt_sipr
integer(4)::nopt_sislp
integer(4)::nsznisnax
real(8),allocatable::sitram(:)
real(8),allocatable::sitrm(:)
real(8),allocatable::sialph(:)
real(8),allocatable::silnpr(:)
real(8),allocatable::sidelp(:)
real(8),allocatable::sirdel(:)
real(8),allocatable::sitlah(:)
real(8),allocatable::sitlaf(:)
real(8),allocatable::sidphi(:)
real(8),allocatable::sialph_nh(:)
real(8),allocatable::silnpr_nh(:)
real(8),allocatable::sidelp_nh(:)
real(8),allocatable::sirdel_nh(:)
real(8),allocatable::sitlah_nh(:)
real(8),allocatable::sitlaf_nh(:)
real(8),allocatable::sidphi_nh(:)
real(8),allocatable::siwf2h(:)
real(8),allocatable::siwh2f(:,:)
real(8),allocatable::sigfl(:)
real(8),allocatable::sigfm(:)
real(8),allocatable::sitfl(:)
real(8),allocatable::sitfm(:)
real(8),allocatable::sighl(:)
real(8),allocatable::sighm(:)
real(8),allocatable::sib(:,:)
real(8),allocatable::simo(:,:)
real(8),allocatable::simi(:,:)
real(8),allocatable::sivp(:)
real(8),allocatable::sivp2(:)
real(8),allocatable::sipd(:)
real(8),allocatable::sipe(:)
real(8),allocatable::sipf(:)
logical(4)::llonem
logical(4)::llpartop
logical(4)::ll_call_spcimpf
logical(4)::lloneblock_gpuway
integer(4),allocatable::sinisnax(:)
real(8),allocatable::silapdi(:)
real(8),allocatable::silapin(:)
real(8),allocatable::siheg(:,:,:)
real(8),allocatable::siheg2(:,:,:)
real(8),allocatable::sihegb(:,:,:)
real(8),allocatable::sihegb2(:,:,:)
real(8),allocatable::sifac(:,:)
real(8),allocatable::sifaci(:,:)
real(8),allocatable::sibq(:,:)
real(8),allocatable::simitra(:,:)
real(8),allocatable::simotra(:,:)
real(8),allocatable::sifacitra(:,:)
real(8),allocatable::sihegtra(:,:)
real(8),allocatable::siheg2tra(:,:,:)
real(8),allocatable::sihegbtra(:,:)
real(8),allocatable::sihegb2tra(:,:,:)
integer(4),allocatable::sihegind(:)
real(8),allocatable::sibqtra(:,:)
real(8),allocatable::siza(:)
real(8),allocatable::sizc(:)
real(8),allocatable::sipis(:)
real(8),allocatable::sitgr(:,:)
real(8),allocatable::sitac(:)
real(8)::vnorm
real(8)::slope_max
real(8)::psurf_max
real(8)::psurf_min
integer(4)::nvlag
integer(4)::nwlag
integer(4)::ntlag
integer(4)::nspdlag
integer(4)::nsvdlag
integer(4)::nsplthoi
logical(4)::lsplthoigfl
integer(4)::nsldimk
integer(4)::nitmp
real(8)::vetaon
real(8)::vetaox
logical(4)::lsettlsvf
logical(4)::lsetfstat
logical(4)::lsettlsvf_diff
real(8)::rw2tlff
real(8)::ralpha
real(8)::ralpha_top
integer(4)::nlev_zalpha
integer(4)::neder
real(8)::rbetak(1_8:3_8,1_8:10_8)
logical(4)::lwenobc
integer(4)::nqmhoislt
logical(4)::lsldp_rk
logical(4)::lsldp_curv
logical(4)::lsldp_curv_fix
logical(4)::lrhs_curv
logical(4)::lrhs_curv_fix
logical(4)::lsldp_xyz
logical(4)::lsldp_save
real(8)::vesl
real(8)::xidt
logical(4)::lqmw
logical(4)::lqmhw
logical(4)::lqmt
logical(4)::lqmht
logical(4)::lqmp
logical(4)::lqmhp
logical(4)::lqmpd
logical(4)::lqmhpd
logical(4)::lqmvd
logical(4)::lqmhvd
logical(4)::lvweno_w
logical(4)::lvweno_t
logical(4)::lvweno_sp
logical(4)::lvweno_spd
logical(4)::lvweno_svd
real(8)::weno_alpha_w
real(8)::weno_alpha_t
real(8)::weno_alpha_sp
real(8)::weno_alpha_spd
real(8)::weno_alpha_svd
logical(4)::ladvf
logical(4)::limpf
logical(4)::l2tlff
real(8)::rcmslp0
integer(4)::ncomp_cvgq
logical(4)::lsvtsm
real(8)::rpres_svtsm
real(8)::rpres_settlsvf
integer(4)::nflevsf
real(8)::rscale
real(8)::rscaleoff
real(8)::rintopt
real(8)::rrintopt
logical(4)::lhdiffm
logical(4)::lspecvis
integer(4)::ndiffact
logical(4)::lgpstress
real(8)::rclstress
real(8)::rclpole
integer(4)::nvsepc
integer(4)::nvsepl
logical(4)::lfindvsep
logical(4)::lmascor
logical(4)::lmasdry
logical(4)::lgpmascor
integer(4)::ngpmascor
real(8)::gpmassi
real(8)::gmassi
real(8)::gmass0
real(8)::gmassinc
logical(4)::lnodryflx
real(8),allocatable::sibi(:,:)
real(8)::resgp
real(8)::resgm
logical(4)::lnhhy_solver_gp
logical(4)::lnhhy_solver_sp
logical(4)::lnhqe_solver_gp
logical(4)::lnhqe_solver_sp
logical(4)::lreset_blend_si
integer(4)::nstop_blend
integer(4)::nstart_blend
real(8)::rnhqe_deltam
real(8),allocatable::rnhhy_deltam(:)
type(tswe)::yrswe
character(8_4,1)::claitri_type="NONE    "
character(8_4,1)::claitri_weno_type="NONE    "
real(8),allocatable::rgamma_weno(:,:)
contains
procedure,pass::print=>print_configuration
end type
contains
subroutine print_configuration(self,kdepth,koutno)
class(tdyn),intent(in)::self
integer(4),intent(in)::kdepth
integer(4),intent(in)::koutno
end
end
