!mod$ v1 sum:7b0b1303958b4b9f
!need$ fe3180dd7f22d4c1 n parkind1
module yommddh
use parkind1,only:jpim
use parkind1,only:jprb
integer(4),parameter::jpdhnox=10000_4
integer(4),parameter::jpdhxpu=5_4
type::tmddh
integer(4)::ndhkd
integer(4)::ndhnpu
integer(4)::ndhbpu(1_8:5_8)
integer(4)::ndhbpx
integer(4)::ndhnom
integer(4)::ndhddx
integer(4)::ndhidh
integer(4)::ndhcs
integer(4)::ndhcv
integer(4)::ndhcvsu
integer(4)::ndhcssu
integer(4)::ndhcvsun
integer(4)::ndhcvsul
integer(4)::ndhvv
integer(4)::ndhfvd
integer(4)::ndhfvp
integer(4)::ndhvs
integer(4)::ndhfsd
integer(4)::ndhfsp
integer(4)::ndhffs
integer(4)::ndhvfs
integer(4)::nfsvar_aero
integer(4)::nfsflx_aero
integer(4)::ndhvtls
integer(4)::ndhftls
integer(4)::ndhvtss
integer(4)::ndhftss
integer(4)::ndhvtts
integer(4)::ndhftts
integer(4)::ndhvtis
integer(4)::ndhftis
integer(4)::ndhvsss
integer(4)::ndhfsss
integer(4)::ndhviis
integer(4)::ndhfiis
integer(4)::ndhvwls
integer(4)::ndhfwls
integer(4)::ndhthk
integer(4)::ndhvhk
integer(4)::ndhfhkd
integer(4)::ndhfhkp
integer(4)::ndhtmc
integer(4)::ndhvmc
integer(4)::ndhfmcd
integer(4)::ndhfmcp
integer(4)::ndhten
integer(4)::ndhven
integer(4)::ndhfend
integer(4)::ndhfenp
integer(4)::ndhavd
integer(4)::ndhbvd
integer(4)::ndhavp
integer(4)::ndhbvp
integer(4)::ndhahkd
integer(4)::ndhbhkd
integer(4)::ndhahkp
integer(4)::ndhbhkp
integer(4)::ndhamcd
integer(4)::ndhbmcd
integer(4)::ndhamcp
integer(4)::ndhbmcp
integer(4)::ndhaend
integer(4)::ndhbend
integer(4)::ndhaenp
integer(4)::ndhbenp
integer(4)::ndhzpr
real(8)::fnoddh(1_8:11_8,1_8:10000_8)
real(8)::bdeddh(1_8:10_8,1_8:10000_8)
real(8)::hdsfgl
integer(4),allocatable::nddhla(:)
integer(4),allocatable::nddhpu(:,:)
integer(4),allocatable::nddhi(:)
integer(4),allocatable::nlrddh(:,:)
integer(4),allocatable::nurddh(:,:,:)
integer(4),allocatable::nlxddh(:)
integer(4),allocatable::nuxddh(:,:)
real(8),allocatable::hdsfla(:)
real(8),allocatable::hdsfdu(:,:)
real(8),allocatable::hdsf(:)
integer(4)::ndimhdgfl
integer(4)::ndimsigmv
integer(4)::msiddh_u1
integer(4)::msiddh_v1
integer(4)::msiddh_t1
integer(4)::msiddh_pd1
integer(4)::msiddh_vd1
integer(4)::msiddh_u0
integer(4)::msiddh_v0
integer(4)::msiddh_t0
integer(4)::msiddh_pd0
integer(4)::msiddh_vd0
integer(4)::msiddh_u9
integer(4)::msiddh_v9
integer(4)::msiddh_t9
integer(4)::msiddh_pd9
integer(4)::msiddh_vd9
integer(4)::mhdddh_u
integer(4)::mhdddh_v
integer(4)::mhdddh_t
integer(4)::mhdddh_q
integer(4)::mhdddh_pd
integer(4)::mhdddh_vd
integer(4)::mhdddh_nhx
integer(4)::mslddh_u
integer(4)::mslddh_v
integer(4)::mslddh_t
integer(4)::mslddh_pd
integer(4)::mslddh_vd
integer(4)::mslddh_nhx
character(200_4,1)::cfpathddh
integer(4)::nfields3d_auto
integer(4)::nfields3d_offset
integer(4)::nfieldsmax
integer(4)::nfields2d_auto
integer(4)::nfields2d_offset
end type
end
