!mod$ v1 sum:7384249014dc3f05
!need$ fe3180dd7f22d4c1 n parkind1
module yompertpar
use parkind1,only:jpim
use parkind1,only:jprb
type::tpertpar
logical(4)::lpertpar=.false._4
integer(4)::nseed_mbr
logical(4)::lpert_rmfdeps=.false._4
real(8)::rmfdeps_max
real(8)::rmfdeps_min
logical(4)::lpert_rprcon=.false._4
real(8)::rprcon_max
real(8)::rprcon_min
logical(4)::lpert_entrorg=.false._4
real(8)::entrorg_max
real(8)::entrorg_min
logical(4)::lpert_detrpen=.false._4
real(8)::detrpen_max
real(8)::detrpen_min
logical(4)::lpert_rtaufac=.false._4
real(8)::rtaufac_max
real(8)::rtaufac_min
logical(4)::lpert_cuduv=.false._4
real(8)::cudu_mod
real(8)::cudv_mod
real(8)::cuduv_max
real(8)::cuduv_min
logical(4)::lpert_gcvre=.false._4
real(8)::gcvre_max
real(8)::gcvre_min
logical(4)::lpert_gcvez=.false._4
real(8)::gcvez_max
real(8)::gcvez_min
logical(4)::lpert_gcvuv=.false._4
real(8)::gcvuv_max
real(8)::gcvuv_min
logical(4)::lpert_akn=.false._4
real(8)::akn_max
real(8)::akn_min
logical(4)::lpert_ald=.false._4
real(8)::ald_max
real(8)::ald_min
logical(4)::lpert_alphat=.false._4
real(8)::alphat_max
real(8)::alphat_min
logical(4)::lpert_almave=.false._4
real(8)::almave_max
real(8)::almave_min
logical(4)::lpert_tfvl=.false._4
real(8)::tfvl_min
real(8)::tfvl_max
logical(4)::lpert_tfvr=.false._4
real(8)::tfvr_min
real(8)::tfvr_max
logical(4)::lpert_tfvs=.false._4
real(8)::tfvs_min
real(8)::tfvs_max
logical(4)::lpert_tfvi=.false._4
real(8)::tfvi_min
real(8)::tfvi_max
logical(4)::lpert_rautefr=.false._4
real(8)::rautefr_min
real(8)::rautefr_max
logical(4)::lpert_rautefs=.false._4
real(8)::rautefs_min
real(8)::rautefs_max
logical(4)::lpert_rqicrmin=.false._4
real(8)::rqicrmin_min
real(8)::rqicrmin_max
logical(4)::lpert_rqicrmax=.false._4
real(8)::rqicrmax_min
real(8)::rqicrmax_max
logical(4)::lpert_rqlcr=.false._4
real(8)::rqlcr_min
real(8)::rqlcr_max
logical(4)::lpert_raccef=.false._4
real(8)::raccef_min
real(8)::raccef_max
logical(4)::lpert_rrimef=.false._4
real(8)::rrimef_min
real(8)::rrimef_max
logical(4)::lpert_raggef=.false._4
real(8)::raggef_min
real(8)::raggef_max
logical(4)::lpert_revasx=.false._4
real(8)::revasx_min
real(8)::revasx_max
logical(4)::lpert_rdtfac=.false._4
real(8)::rdtfac_min
real(8)::rdtfac_max
logical(4)::lpert_rhcrit1=.false._4
real(8)::rhcrit1_min
real(8)::rhcrit1_max
logical(4)::lpert_grhcmod=.false._4
real(8)::grhcmod_min
real(8)::grhcmod_max
logical(4)::lpert_gwdcd=.false._4
real(8)::gwdcd_min
real(8)::gwdcd_max
logical(4)::lpert_gwdse=.false._4
real(8)::gwdse_min
real(8)::gwdse_max
logical(4)::lpert_hobst=.false._4
real(8)::hobst_min
real(8)::hobst_max
logical(4)::lpert_rratsea=.false._4
real(8)::rratsea_min
real(8)::rratsea_max
logical(4)::lpert_rratland=.false._4
real(8)::rratland_min
real(8)::rratland_max
logical(4)::lpert_rratdri=.false._4
real(8)::rratdri_max
real(8)::rratdri_min
logical(4)::lpert_rcadecor=.false._4
real(8)::rcadecor_max
real(8)::rcadecor_min
logical(4)::lpert_rcbdecor=.false._4
real(8)::rcbdecor_max
real(8)::rcbdecor_min
logical(4)::lpert_rsigma2=.false._4
real(8)::rsigma2_max
real(8)::rsigma2_min
logical(4)::lpert_rfacdice=.false._4
real(8)::rfacdice_max
real(8)::rfacdice_min
logical(4)::lpert_xrimax=.false._4
real(8)::xrimax_min
real(8)::xrimax_max
logical(4)::lpert_xfracz0=.false._4
real(8)::xfracz0_min
real(8)::xfracz0_max
logical(4)::lpert_otadjs=.false._4
real(8)::otadjs_min
real(8)::otadjs_max
logical(4)::lpert_xentr=.false._4
real(8)::xentr_min
real(8)::xentr_max
logical(4)::lpert_xatpert=.false._4
real(8)::xatpert_min
real(8)::xatpert_max
logical(4)::lpert_xbtpert=.false._4
real(8)::xbtpert_min
real(8)::xbtpert_max
logical(4)::lpert_xdtpert=.false._4
real(8)::xdtpert_min
real(8)::xdtpert_max
logical(4)::lpert_xaw=.false._4
real(8)::xaw_min
real(8)::xaw_max
logical(4)::lpert_xbw=.false._4
real(8)::xbw_min
real(8)::xbw_max
logical(4)::lpert_rkfbtau=.false._4
real(8)::rkfbtau_min
real(8)::rkfbtau_max
logical(4)::lpert_rkfbnbx=.false._4
real(8)::rkfbnbx_min
real(8)::rkfbnbx_max
logical(4)::lpert_xpertflux=.false._4
real(8)::xpertflux_max
real(8)::xpertflux_min
end type
end
