!mod$ v1 sum:7b9903af3d86dda7
!need$ af34b429417f3ba9 n yomdprecips
!need$ 1df8f63181ab8b6b n yomdvisi
!need$ 507c078dbe4be540 n yomcape
!need$ 656db1b3c37b5086 n yomdwet
!need$ 8a93b8df34d9f590 n yomrpp
!need$ fe3180dd7f22d4c1 n parkind1
module yomphy
use parkind1,only:jpim
use yomdprecips,only:tdprecips
use yomdvisi,only:tdvisi
use yomcape,only:tcape
use yomdwet,only:tdwet
use yomrpp,only:trpp
integer(4),parameter::jphyec=1_4
integer(4),parameter::jphymf=2_4
integer(4),parameter::jphyaro=3_4
integer(4),parameter::jpbp002=4_4
type::tphy
integer(4)::nbiter
integer(4)::niterfl
integer(4)::ndpsfi
logical(4)::lmphys
logical(4)::lreasur
logical(4)::lcape
logical(4)::lcvgqd
logical(4)::lcvgqm
logical(4)::lcvgqp
logical(4)::lcondwt
logical(4)::lcvdd
logical(4)::lcvpgy
logical(4)::lcvpp
logical(4)::ldifcexp
logical(4)::ldifcons
logical(4)::ldifql
logical(4)::ldistur
logical(4)::lneige
logical(4)::lrnumx
logical(4)::lrnuexp
logical(4)::lrtruebbc
logical(4)::lrtruedir
logical(4)::lacpanmx
logical(4)::lclsatur
logical(4)::lvoigt
logical(4)::lglaciers
logical(4)::lvfull
logical(4)::lslc
logical(4)::lraylu
logical(4)::lrews
logical(4)::lrprox
logical(4)::lrmix
logical(4)::lrstab
logical(4)::lrstaer
logical(4)::lrtpp
logical(4)::lrtdl
logical(4)::lraypl
logical(4)::lrrgust
logical(4)::lo3abc
logical(4)::lo3fl
logical(4)::lecshal
logical(4)::lecdeep
logical(4)::lnebnxr
logical(4)::lneb_fp
logical(4)::lqxrtgh
logical(4)::lhucn
logical(4)::lfpcor
logical(4)::lnoias
logical(4)::lglt
logical(4)::lnewd
logical(4)::lprocld
logical(4)::levapp
logical(4)::lcollec
logical(4)::ladjcld
logical(4)::lsedsta
logical(4)::lsedlag
logical(4)::lsedcl
logical(4)::lfsvar
logical(4)::lfsfix
logical(4)::la0mps
logical(4)::larpmps
logical(4)::l3mt
logical(4)::lgpcmt
logical(4)::lentch
logical(4)::lcddevpro
logical(4)::laerosea
logical(4)::laerolan
logical(4)::laerosoo
logical(4)::laerodes
logical(4)::laerovol
logical(4)::laerosul
logical(4)::laeromass2d
logical(4)::laerommr3d
logical(4)::laerommr
logical(4)::laeronrt
logical(4)::lrelaxt
logical(4)::lrelaxw
logical(4)::lssd
logical(4)::lpble
logical(4)::lblvar
logical(4)::lz0hsrel
logical(4)::lz0snowh
logical(4)::lmlh
logical(4)::lnodifqc
logical(4)::lncvpgy
logical(4)::lsqrml
logical(4)::lab12
logical(4)::lfvgice3
logical(4)::levaplop
logical(4)::lcp06
logical(4)::lcvshcu
logical(4)::lcvgq
logical(4)::lpec
logical(4)::ludevol
logical(4)::lcddcsd
integer(4)::nclomix
integer(4)::nfsig
logical(4)::lhlradupd
integer(4)::ndprecperiod
integer(4)::ndprecperiod2
logical(4)::ldprecips
logical(4)::ldprecips2
type(tdprecips)::yrdprecips
type(tdvisi)::yrdvisi
type(tdwet)::yrdwet
character(20_4,1)::cgmixlen
character(20_4,1)::cgturs
character(20_4,1)::cgtrg
logical(4)::lprgml
logical(4)::lcvra
logical(4)::lcvtdk
logical(4)::ldayd
logical(4)::lcvpro
logical(4)::lgrapro
logical(4)::lcddpro
logical(4)::lcvcsd
logical(4)::lusl
logical(4)::lnsdo
logical(4)::lect
logical(4)::lefb
logical(4)::lfluso
logical(4)::lectq1
logical(4)::lectrep
logical(4)::lptke
logical(4)::lcoefktke
logical(4)::lcoefksurf
logical(4)::lcoefk_msc
logical(4)::lcoefk_f1
logical(4)::lcoefk_toms
logical(4)::lcoefk_ths1
logical(4)::lcoefk_ris
logical(4)::lcoefk_pl
logical(4)::lcoefk_ml
logical(4)::lcoefk_ptte
logical(4)::lcoefk_flx
logical(4)::lcoefk_scq
logical(4)::lafgd_a
logical(4)::lgwd
logical(4)::lgwdc
logical(4)::lnorgwd
logical(4)::lhmto
logical(4)::lnebco
logical(4)::lnebn
logical(4)::lnebr
logical(4)::lptopc
logical(4)::lozone
logical(4)::lray
logical(4)::lrayfm
logical(4)::lrmu0m
logical(4)::lrayfm15
logical(4)::lrrmes
logical(4)::lsfhyd
logical(4)::lsnv
logical(4)::lsolv
logical(4)::lfgel
logical(4)::lstra
logical(4)::lstras
logical(4)::lstrapro
logical(4)::lnewstat
logical(4)::lthermo
logical(4)::lvdif
logical(4)::lcvlis
logical(4)::lcvcas
logical(4)::lscmf
logical(4)::lvgsn
logical(4)::lphcdpi
logical(4)::lnebgr
logical(4)::lnebgy
logical(4)::lcvrav3
logical(4)::lcvppkf
logical(4)::lcvturb
logical(4)::lnebric
logical(4)::ledkf
logical(4)::ledmfi
logical(4)::ledmfs
logical(4)::lectfl
logical(4)::lectfl0
logical(4)::lectprodcvp
integer(4)::nphyrep
logical(4)::lcamod
logical(4)::lcomod
logical(4)::lphspsh
logical(4)::lsmnimbt
logical(4)::lsmtps
logical(4)::lsmgcdev
logical(4)::lxrcdev
logical(4)::lrkcdev
logical(4)::lsmith_cdev
logical(4)::lrcvott
logical(4)::lnebcv
logical(4)::lnebins
integer(4)::ndiffneb
integer(4)::nimelit
integer(4)::nray
integer(4)::nsorayfr
integer(4)::nthrayfr
integer(4)::nrautoev
integer(4)::nsmtbot
integer(4)::nsmdneb
integer(4)::nprac
integer(4)::nprri
integer(4)::nphy
integer(4)::ncallrad
integer(4)::nlend
integer(4)::ntend_diag_pos
integer(4)::ntend_diag_freq_reset
logical(4)::lnebect
logical(4)::lcvgqkf
logical(4)::lacdifus
logical(4)::l2micro
integer(4)::nsole
logical(4)::lajucv
logical(4)::lsmoothmelt
logical(4)::lgcheckmv
logical(4)::lchecksurf
logical(4)::lgchecknan
logical(4)::ledr
logical(4)::lwindfarm
logical(4)::lbmred
integer(4)::npblh_mxl
integer(4)::npblh_diag
logical(4)::lapl_arpege=.false._4
logical(4)::lapl_alaro=.false._4
type(tcape)::yrcape
type(trpp)::yrrpp
end type
type(tphy),pointer::yrphy
intrinsic::null
end
