!mod$ v1 sum:be8e9cec133ce3fd
!need$ fe3180dd7f22d4c1 n parkind1
module yomphy0
use parkind1,only:jpim
use parkind1,only:jprb
type::tadvprs
logical(4)::llmelts
logical(4)::llfreez
logical(4)::llevapx
real(8)::zeps
real(8)::znu1
real(8)::znu2
real(8)::ztau1
real(8)::ztau2
real(8)::zsigma1
real(8)::zsigma2
real(8)::zfventr1
real(8)::zfventr2
real(8)::zfvents1
real(8)::zfvents2
real(8)::zfvelr
real(8)::zfvels
real(8)::ztmelt
real(8)::zrhow
real(8)::znrhow
real(8)::zdvisc
real(8)::zsqtvis
real(8)::zcdarv
real(8)::zrhoref
real(8)::zexp1
real(8)::zexp4
real(8)::zexp6
real(8)::zpref
real(8)::zcoeff1
real(8)::zcoeff2
real(8)::zcoeff2b
real(8)::zcoeff3
real(8)::zcoeff4
real(8)::zcoeff5
real(8)::zcoeff6
end type
type::tphy0
real(8)::tym(1_8:5_8)
integer(4)::npclo1
integer(4)::npclo2
real(8)::a0ml_au
real(8)::a0ml_at
real(8)::a0ml_bu
real(8)::a0ml_bt
real(8)::aercs1
real(8)::aercs3
real(8)::aercs5
real(8)::adjtau
real(8)::almav
real(8)::bedifv
real(8)::ecmnp
real(8)::edb
real(8)::edc
real(8)::edd
real(8)::evap
real(8)::font
real(8)::galp
real(8)::gcismin
real(8)::gevavf
real(8)::gccsv
real(8)::gcvads
real(8)::gcvbeta
real(8)::gcvimpt
real(8)::gcvomge
real(8)::gcvomgq
real(8)::gcvomgs
real(8)::gcvturb
real(8)::gcvomdps
real(8)::gcvomgsx
real(8)::gcvrhmin
real(8)::gcvrhmax
real(8)::gcvomca
real(8)::gcvomcc
real(8)::gddeva
real(8)::gddsde
real(8)::gddfrevs
real(8)::gddinhom
real(8)::grcvpp
real(8)::gwdamp
real(8)::gwdbc
real(8)::gwdcco
real(8)::gwdcd
real(8)::gwdlt
real(8)::gwdse
real(8)::gwdprof
real(8)::gwdvali
real(8)::hobst
real(8)::hucoe
real(8)::hutil
real(8)::hutil1
real(8)::hutil2
real(8)::qsmin
real(8)::qsmodc
real(8)::qsnebc
real(8)::qsnebs
real(8)::qssusc
real(8)::qssuss
real(8)::qssusv
real(8)::qsusxc
real(8)::qsusxs
real(8)::rphi0
real(8)::rphir
real(8)::qxral
real(8)::qxral_adj
real(8)::qxrdel
real(8)::qxrhx
real(8)::qxrr
real(8)::qxrtgh
real(8)::qxrcdil
real(8)::rcin
real(8)::rcvevap
real(8)::rdecrd
real(8)::rdecrd1
real(8)::rdecrd2
real(8)::rdecrd3
real(8)::rdecrd4
real(8)::rdecrdred
real(8)::rdtfac
real(8)::revapn
real(8)::revgsl
real(8)::rgelsfon
real(8)::rflchce
real(8)::rtcape
real(8)::sco
real(8)::sensl
real(8)::snnbco
real(8)::spnbco
real(8)::sxnbco
real(8)::tca
real(8)::tct
real(8)::tcw
real(8)::tentr
real(8)::tentrx
real(8)::tudgp
real(8)::tddgp
real(8)::turb
real(8)::tvf
real(8)::uhdifv
real(8)::usdmlt
real(8)::usuprc
real(8)::usuric
real(8)::vchrnk
real(8)::vkarmn
real(8)::vz0cm
real(8)::vziustar0
real(8)::xnbmax
real(8)::aecls3
real(8)::aecls4
real(8)::ald
real(8)::akn
real(8)::alphat
real(8)::alphae
real(8)::eps
real(8)::etacut
real(8)::adisi
real(8)::adise
real(8)::ectmin
real(8)::ectmax
real(8)::ahclpv
real(8)::ricrlm
real(8)::rmulacvg
real(8)::xblm
real(8)::xminlm
real(8)::xmaxlm
real(8)::xwsalm
real(8)::xwsblm
real(8)::gcvalfa
real(8)::gcvpsi
real(8)::gcvpsie
real(8)::usurice
real(8)::usuricl
real(8)::qssc
real(8)::usurid
real(8)::gcvnu
real(8)::usuride
real(8)::gcvmlt
real(8)::utilgust
real(8)::rrgamma
real(8)::rrscale
real(8)::gpblhk0
real(8)::gpblhra
real(8)::wmxov
real(8)::acbrphim
real(8)::almave
real(8)::almavx
real(8)::arsch
real(8)::arscq
real(8)::arsc1
real(8)::arsb2
real(8)::ricret
real(8)::sttbmin
real(8)::ucwstar
real(8)::udect
real(8)::upretmin
real(8)::upretmax
real(8)::ushearm
real(8)::rautefr
real(8)::rrautcs
real(8)::rautefs
real(8)::rautsbet
real(8)::rautefg
real(8)::revasx
real(8)::revasxr
real(8)::revasxs
real(8)::revasxg
real(8)::rnintr
real(8)::rnints
real(8)::rnintg
real(8)::rqlcr
real(8)::rspcrr
real(8)::rqicrmax
real(8)::rqicrmin
real(8)::rqlcv
real(8)::rqicvmax
real(8)::rqicvmin
real(8)::rqicrt1
real(8)::rqicrt2
real(8)::rqicrsn
real(8)::rqcrns
real(8)::raccef
real(8)::raggef
real(8)::rrimef
real(8)::rhcrit1
real(8)::rhcrit2
real(8)::retamin
real(8)::rfacnsm
real(8)::tfvl
real(8)::tfvld
real(8)::tfvi
real(8)::tfvr
real(8)::tfvs
real(8)::grhcmod
real(8)::rhcexpdx
real(8)::nuptke
real(8)::tkemult
real(8)::c_epsilon
real(8)::c3tkefree
real(8)::etke_ctheta
real(8)::etke_rifc_maf
real(8)::etke_rifc
real(8)::etke_r
real(8)::etke_olam
real(8)::etke_lam0
real(8)::etke_lam1
real(8)::etke_lam2
real(8)::etke_lam3
real(8)::etke_lam4
real(8)::etke_ka1
real(8)::etke_ka2
real(8)::etke_ka3
real(8)::ent_lambda
real(8)::etke_cg01
real(8)::etke_cg02
real(8)::etke_cg03
real(8)::etke_beta_eps
real(8)::etke_gamma_eps
real(8)::etke_gamd
real(8)::etke_talph
real(8)::etke_alph0
real(8)::etke_entrx
real(8)::etke_entrn
real(8)::etke_klm
real(8)::etke_taulm
real(8)::etke_c0shear
real(8)::etke_dtheta_s1
real(8)::etke_dtheta_s2
real(8)::etke_lblt1
real(8)::etke_lblt2
real(8)::etke_hutls
real(8)::etke_lutls
real(8)::etke_r1sim
real(8)::etke_r2sim
real(8)::etke_gb08a
real(8)::etke_gb08b
real(8)::etke_min
real(8)::etke_crit
real(8)::etke_delta
real(8)::etke_rifgr
real(8)::efb_az0
real(8)::efb_ur
real(8)::refb_1
real(8)::refb_2
real(8)::refb_3
real(8)::rpblh_up
real(8)::tudbu
real(8)::tddbu
real(8)::tudfr
real(8)::tddfr
real(8)::gcvalmx
real(8)::gcvtaude
real(8)::gcvachi
real(8)::gcvbee
real(8)::gcveex
real(8)::ecmnpi
real(8)::grrmina
real(8)::gddbeta
real(8)::gdddp
real(8)::gddfxm
real(8)::gddwpf
real(8)::gddevf
real(8)::tentrd
real(8)::gddalbu
real(8)::gddfrac
real(8)::gddendymx
real(8)::gddfp(1_8:3_8)
real(8)::gddtausig
real(8)::gpeiphi
real(8)::gpetau
real(8)::gpefdc
real(8)::genvsrh
real(8)::gcvkskv
real(8)::gcvalbu
real(8)::gcvendy1
real(8)::gcvendy2
real(8)::gcvendymx
real(8)::gcvidpbas
real(8)::gcvtausig
real(8)::gtrgdpmix
real(8)::gtrgdphimn
real(8)::gtrgpuslmn
real(8)::gtrgkck9
real(8)::gtrgain
real(8)::gtrthrs
real(8)::gtrthck
real(8)::gtrbrc
real(8)::gtrkgain
real(8)::gtrkthrs
real(8)::gtrkthck
real(8)::gcvcatau
real(8)::gcathrcap
real(8)::gcathrmoc
real(8)::gcathrcnd
real(8)::gcaomcnd
real(8)::nweight
real(8)::ncatau
real(8)::ncapemax
real(8)::ncvgmax
real(8)::rnegat
real(8)::rnlcurv
real(8)::edk
real(8)::xklm
real(8)::agre1
real(8)::agrericr
real(8)::ajbumin
real(8)::rcoflm
real(8)::tentrvl
real(8)::trentrv
real(8)::gcvgamma
logical(4)::lkesc
real(8)::agre2
real(8)::agref
real(8)::alfx
real(8)::alfx_lr
real(8)::alfx_hr
real(8)::tctc
real(8)::tvfc
real(8)::gamap1
real(8)::rkdn
real(8)::vvn
real(8)::vvx
real(8)::fentrt
real(8)::fqlic
real(8)::fnebc
real(8)::fevapc
real(8)::rdphic
real(8)::rwbf1
real(8)::rwbf2
real(8)::rcpcoef1
real(8)::rcpcoef2
real(8)::rcpcoef3
real(8)::sclespr
real(8)::sclesps
real(8)::hucred
real(8)::hucredra
real(8)::fsprain
real(8)::effcoll
real(8)::rsmdnebx
real(8)::rsmdtx
integer(4)::nsmtpa
integer(4)::nsmtpb
real(8)::rkfbtau
real(8)::rkfbnbx
real(8)::gcvhmin
real(8)::gcvresn
real(8)::gcvresx
real(8)::gmirh
real(8)::rlmlh1
real(8)::rprth
real(8)::rsmoothmelt
logical(4)::ladvlim
logical(4)::lgddd
logical(4)::lcvresdyn
logical(4)::lcvmicc
real(8)::gmukedd
real(8)::gnhdtat
real(8)::gnhdsmos
real(8)::gnhdsmot
real(8)::gnhdev
logical(4)::lgvvex
logical(4)::lcvuvm
integer(4)::ncventr
integer(4)::ncvsig
integer(4)::ncvclos
integer(4)::ncvqli
real(8)::gcventrn
real(8)::gcventrx
real(8)::adoe
real(8)::rfrac_entr_n
real(8)::rfrac_entr_x
real(8)::gcventr_min
real(8)::thpcmt
real(8)::aj1peps
real(8)::aj1meps
integer(4)::najiter
real(8)::gaeps
real(8)::gcvez
real(8)::gcvtrmin
logical(4)::lcvfevv
real(8)::gcvfevv
logical(4)::lcvcontau
real(8)::gcvtexc
real(8)::gcvwexc
logical(4)::lcvnauv
real(8)::gcvfrr
real(8)::gcvpnh
real(8)::gcvorged
logical(4)::lcvimpt
real(8)::gcvtaurem
real(8)::gcloea
real(8)::gcloeb
real(8)::gfrae
real(8)::gcvadet
real(8)::gcvcinc
real(8)::gsdmin
real(8)::gsdmax
real(8)::galmin
real(8)::galmax
real(8)::gsdamin
real(8)::gsdamax
real(8)::gexpkd
logical(4)::lcveod
real(8)::gremin
real(8)::gremax
real(8)::gchi0
real(8)::gfsurf
real(8)::gshell
real(8)::gfric
real(8)::guddd
real(8)::gsiga
real(8)::gnhdsmow
real(8)::gdepth
real(8)::galtau
real(8)::gkeddre
real(8)::gnhacc
real(8)::gtdcl
real(8)::gsinhd
real(8)::gsinhr
real(8)::gcvfner
real(8)::gcvfneo
real(8)::gcvfnep1
real(8)::gcvfnep2
real(8)::grbcc
real(8)::gtopdepth
real(8)::gcvtsmo
real(8)::rkdx
logical(4)::lcapcin
logical(4)::lcorsedim
real(8)::gnhdtau
real(8)::grso
real(8)::grth
real(8)::grfcs
real(8)::gcvre
real(8)::gcvfmax
real(8)::glight
logical(4)::lsbuo
real(8)::greddi
real(8)::greddl
real(8)::greddr
real(8)::gredds
logical(4)::lcvtadv
logical(4)::lcvds
real(8)::gcvuv
real(8)::gcvgaw
real(8)::gcvgax
real(8)::gcheckmv_tmin
real(8)::gcheckmv_tmax
real(8)::gcheckmv_qvmin
real(8)::gcheckmv_qvmax
logical(4)::lgproni1
integer(4)::nproni
real(8)::gproni
real(8)::rnebcx
real(8)::glightt1
real(8)::glightt2
real(8)::glightt3
real(8)::reflrhc
real(8)::teqh
real(8)::reflkuo
real(8)::reflcape
real(8)::teqk
real(8)::teqc
real(8)::reps
real(8),allocatable::rhuc(:)
real(8),allocatable::rqsmod(:)
real(8),allocatable::rsurf(:)
real(8),allocatable::rn1d(:)
real(8),allocatable::rrc1d(:)
real(8),allocatable::rsrc1d(:)
real(8)::rcoefrain(1_8:2_8)
real(8)::rcoefsnow(1_8:2_8)
type(tadvprs)::yradvprcs
end type
type(tphy0),pointer::yrphy0
intrinsic::null
end
