!mod$ v1 sum:8a93b8df34d9f590
!need$ fe3180dd7f22d4c1 n parkind1
module yomrpp
use parkind1,only:jprb
use parkind1,only:jpim
type::trpp
logical(4)::lrpp
logical(4)::linfluent
logical(4)::lusesetran_rpp
integer(4)::nseed_rpp
logical(4)::lrcriauti
real(8)::rcriauti_min
real(8)::rcriauti_max
real(8)::rcriauti_best
real(8)::rcriauti_sigma
integer(4)::rcriauti_scheme
logical(4)::lrcriautc
real(8)::rcriautc_min
real(8)::rcriautc_max
real(8)::rcriautc_best
real(8)::rcriautc_sigma
integer(4)::rcriautc_scheme
logical(4)::lvsigqsat
real(8)::vsigqsat_min
real(8)::vsigqsat_max
real(8)::vsigqsat_best
real(8)::vsigqsat_sigma
integer(4)::vsigqsat_scheme
logical(4)::lxlini
real(8)::xlini_min
real(8)::xlini_max
real(8)::xlini_best
real(8)::xlini_sigma
integer(4)::xlini_scheme
logical(4)::lxctd
real(8)::xctd_min
real(8)::xctd_max
real(8)::xctd_best
real(8)::xctd_sigma
integer(4)::xctd_scheme
logical(4)::lxctp
real(8)::xctp_min
real(8)::xctp_max
real(8)::xctp_best
real(8)::xctp_sigma
integer(4)::xctp_scheme
logical(4)::lxcep
real(8)::xcep_min
real(8)::xcep_max
real(8)::xcep_best
real(8)::xcep_sigma
integer(4)::xcep_scheme
logical(4)::lxced
real(8)::xced_min
real(8)::xced_max
real(8)::xced_best
real(8)::xced_sigma
integer(4)::xced_scheme
logical(4)::lxphi_lim
real(8)::xphi_lim_min
real(8)::xphi_lim_max
real(8)::xphi_lim_best
real(8)::xphi_lim_sigma
integer(4)::xphi_lim_scheme
logical(4)::lxcet
real(8)::xcet_min
real(8)::xcet_max
real(8)::xcet_best
real(8)::xcet_sigma
integer(4)::xcet_scheme
logical(4)::lxrimax
real(8)::xrimax_max
real(8)::xrimax_min
real(8)::xrimax_best
real(8)::xrimax_sigma
integer(4)::xrimax_scheme
logical(4)::lxfracz0
real(8)::xfracz0_min
real(8)::xfracz0_max
real(8)::xfracz0_best
real(8)::xfracz0_sigma
integer(4)::xfracz0_scheme
logical(4)::lxcmf
real(8)::xcmf_min
real(8)::xcmf_max
real(8)::xcmf_best
real(8)::xcmf_sigma
integer(4)::xcmf_scheme
logical(4)::lxabuo
real(8)::xabuo_min
real(8)::xabuo_max
real(8)::xabuo_best
real(8)::xabuo_sigma
integer(4)::xabuo_scheme
logical(4)::lxbdetr
real(8)::xbdetr_min
real(8)::xbdetr_max
real(8)::xbdetr_best
real(8)::xbdetr_sigma
integer(4)::xbdetr_scheme
logical(4)::lcloud_inhom_decorr_scaling
real(8)::cloud_inhom_decorr_scaling_min
real(8)::cloud_inhom_decorr_scaling_max
real(8)::cloud_inhom_decorr_scaling_best
real(8)::cloud_inhom_decorr_scaling_sigma
integer(4)::cloud_inhom_decorr_scaling_scheme
logical(4)::lxentr_dry
real(8)::xentr_dry_min
real(8)::xentr_dry_max
real(8)::xentr_dry_best
real(8)::xentr_dry_sigma
integer(4)::xentr_dry_scheme
logical(4)::lrcadecor
real(8)::rcadecor_min
real(8)::rcadecor_max
real(8)::rcadecor_best
real(8)::rcadecor_sigma
integer(4)::rcadecor_scheme
logical(4)::lrcbdecor
real(8)::rcbdecor_min
real(8)::rcbdecor_max
real(8)::rcbdecor_best
real(8)::rcbdecor_sigma
integer(4)::rcbdecor_scheme
end type
end
