!mod$ v1 sum:1c3674ec2f8fa814
!need$ c4d8718d6e800cb5 n field_1rm_factory_module
!need$ 510aff658ef3077b n field_2rm_factory_module
!need$ 5f27705ce69c90f2 n field_3rm_factory_module
!need$ 9a87cdff1c93a7d2 n field_4rm_factory_module
!need$ 96763907cf3dcd42 n field_5rm_factory_module
!need$ 863fa7c06d7b267d n field_1rd_factory_module
!need$ 0fc153f9a6bc4201 n field_2rd_factory_module
!need$ 91671fc0e02f46af n field_3rd_factory_module
!need$ af8063fff9933652 n field_4rd_factory_module
!need$ 4487b7dd1d2caea0 n field_5rd_factory_module
!need$ 15ae3dd103ee38e6 n field_1im_factory_module
!need$ 527eec8a48eccd5d n field_2im_factory_module
!need$ 4f44dc92e67a0167 n field_3im_factory_module
!need$ 883902ef9d2fb5f3 n field_4im_factory_module
!need$ 2efa2a1f438aea75 n field_5im_factory_module
!need$ b6b350069c07cbe0 n field_1lm_factory_module
!need$ 2f7329ec9ed5ecb6 n field_2lm_factory_module
!need$ 6d46ac852fdbe548 n field_3lm_factory_module
!need$ ebf45d12f2d53cd6 n field_4lm_factory_module
!need$ fb1b55233dec61ee n field_5lm_factory_module
!need$ 68d55a4911fee962 n host_alloc_module
module field_factory_module
use host_alloc_module,only:host_pool
use field_1rm_factory_module,only:field_new
use field_2rm_factory_module,only:field_new
use field_3rm_factory_module,only:field_new
use field_4rm_factory_module,only:field_new
use field_5rm_factory_module,only:field_new
use field_1rd_factory_module,only:field_new
use field_2rd_factory_module,only:field_new
use field_3rd_factory_module,only:field_new
use field_4rd_factory_module,only:field_new
use field_5rd_factory_module,only:field_new
use field_1im_factory_module,only:field_new
use field_2im_factory_module,only:field_new
use field_3im_factory_module,only:field_new
use field_4im_factory_module,only:field_new
use field_5im_factory_module,only:field_new
use field_1lm_factory_module,only:field_new
use field_2lm_factory_module,only:field_new
use field_3lm_factory_module,only:field_new
use field_4lm_factory_module,only:field_new
use field_5lm_factory_module,only:field_new
use field_1rm_factory_module,only:field_delete
use field_2rm_factory_module,only:field_delete
use field_3rm_factory_module,only:field_delete
use field_4rm_factory_module,only:field_delete
use field_5rm_factory_module,only:field_delete
use field_1rd_factory_module,only:field_delete
use field_2rd_factory_module,only:field_delete
use field_3rd_factory_module,only:field_delete
use field_4rd_factory_module,only:field_delete
use field_5rd_factory_module,only:field_delete
use field_1im_factory_module,only:field_delete
use field_2im_factory_module,only:field_delete
use field_3im_factory_module,only:field_delete
use field_4im_factory_module,only:field_delete
use field_5im_factory_module,only:field_delete
use field_1lm_factory_module,only:field_delete
use field_2lm_factory_module,only:field_delete
use field_3lm_factory_module,only:field_delete
use field_4lm_factory_module,only:field_delete
use field_5lm_factory_module,only:field_delete
use field_1rm_factory_module,only:field_resize
use field_2rm_factory_module,only:field_resize
use field_3rm_factory_module,only:field_resize
use field_4rm_factory_module,only:field_resize
use field_5rm_factory_module,only:field_resize
use field_1rd_factory_module,only:field_resize
use field_2rd_factory_module,only:field_resize
use field_3rd_factory_module,only:field_resize
use field_4rd_factory_module,only:field_resize
use field_5rd_factory_module,only:field_resize
use field_1im_factory_module,only:field_resize
use field_2im_factory_module,only:field_resize
use field_3im_factory_module,only:field_resize
use field_4im_factory_module,only:field_resize
use field_5im_factory_module,only:field_resize
use field_1lm_factory_module,only:field_resize
use field_2lm_factory_module,only:field_resize
use field_3lm_factory_module,only:field_resize
use field_4lm_factory_module,only:field_resize
use field_5lm_factory_module,only:field_resize
interface field_new
end interface
interface field_delete
end interface
interface field_resize
end interface
contains
subroutine field_host_pool_delete()
end
end
