FC=/perm/sor/install/rocm/10004/bin/amdflang -c -fPIC -fconvert=big-endian -Qunused-arguments -fopenmp -Wl,-z,execstack --offload-arch=gfx942 -O1 -g
#FC=/perm/sor/install/rocm/8873/bin/amdflang -c -fPIC -fconvert=big-endian -Qunused-arguments -fopenmp -Wl,-z,execstack --offload-arch=gfx942 -O1 -g
