MODULE UTIL_FIELD_VARIABLES_COPY_MOD
USE FIELD_VARIABLES_MOD, ONLY : FIELD_VARIABLES
INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_FIELD_VARIABLES
END INTERFACE

CONTAINS
SUBROUTINE ACDC_COPY_FIELD_VARIABLES (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_VARIABLE_2RB_MOD
USE UTIL_VARIABLE_3RB_MOD
IMPLICIT NONE
TYPE (FIELD_VARIABLES), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
INTEGER :: J1
LOGICAL :: LAERAOT, LAERLISI, LAERO, LAEROCLIM, LAEROUT, LCHEM, LEDRP, LEMIS3D, LERA40, LEXT
LOGICAL :: LEZDIAG, LFORC, LGFL_PTR, LGHG, LLIMA, LNOGW, LSLDIA, LUVP
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF)
  !$OMP TARGET UPDATE TO (SELF)
ENDIF
CALL ACDC_COPY_VARIABLE_3RB (SELF%U, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%V, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%T, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%DIV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%VOR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SPD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SVD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CSPDNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CSPNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CSVDPT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CTNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CTPT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CUNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CUPT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CVNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CVPT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CVWVNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%DPHI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%EDOT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%GW, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%NHX, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%NHY, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SGRTL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SGRTM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SPDNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SPDNL_SI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SPNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SPNL_SI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SVDNL_SI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%TNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%TNL_SI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%UNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%UNL_SI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%VNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%VNL_SI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%VWVNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CURHS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CVRHS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CTRHS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CSPDRHS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CSVDRHS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%NHXNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CNHXNL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_U, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_V, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_T, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_SPD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_SVD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_NHX, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_SP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_CP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_UP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_VP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%PCF_TP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%SP, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%SPNL2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%PREHYDS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%DBBC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%CSPPT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%CSPNL2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%CSPRHS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%GWS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%PCF_BBC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%PCF_DPHI, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_2RB (SELF%PCF_GWS, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%Q, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%I, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%L, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%IMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%LMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%HLMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%HIMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%LCONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%ICONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%RCONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SCONV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%IRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%LRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%S, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%R, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%G, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%H, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%TKE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%TTE, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%EFB1, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%EFB2, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%EFB3, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%A, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%AMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%WMFC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%HLCFMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%HICFMF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%O3, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SRC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%MXL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SHTUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%FQTUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%FSTUR, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CPF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SPF, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CVGQ, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%QVA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LGHG = ALLOCATED (SELF%GHG)
IF (LGHG) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%GHG)
  !$OMP TARGET UPDATE TO (SELF%GHG)
  DO J1 = LBOUND (SELF%GHG, 1), UBOUND (SELF%GHG, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%GHG (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%GHG)
ENDIF

LCHEM = ALLOCATED (SELF%CHEM)
IF (LCHEM) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%CHEM)
  !$OMP TARGET UPDATE TO (SELF%CHEM)
  DO J1 = LBOUND (SELF%CHEM, 1), UBOUND (SELF%CHEM, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%CHEM (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%CHEM)
ENDIF

LAERO = ALLOCATED (SELF%AERO)
IF (LAERO) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%AERO)
  !$OMP TARGET UPDATE TO (SELF%AERO)
  DO J1 = LBOUND (SELF%AERO, 1), UBOUND (SELF%AERO, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%AERO (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%AERO)
ENDIF

CALL ACDC_COPY_VARIABLE_3RB (SELF%LRCH4, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LFORC = ALLOCATED (SELF%FORC)
IF (LFORC) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%FORC)
  !$OMP TARGET UPDATE TO (SELF%FORC)
  DO J1 = LBOUND (SELF%FORC, 1), UBOUND (SELF%FORC, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%FORC (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%FORC)
ENDIF

LEZDIAG = ALLOCATED (SELF%EZDIAG)
IF (LEZDIAG) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%EZDIAG)
  !$OMP TARGET UPDATE TO (SELF%EZDIAG)
  DO J1 = LBOUND (SELF%EZDIAG, 1), UBOUND (SELF%EZDIAG, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%EZDIAG (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%EZDIAG)
ENDIF

LERA40 = ALLOCATED (SELF%ERA40)
IF (LERA40) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%ERA40)
  !$OMP TARGET UPDATE TO (SELF%ERA40)
  DO J1 = LBOUND (SELF%ERA40, 1), UBOUND (SELF%ERA40, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%ERA40 (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%ERA40)
ENDIF

LNOGW = ALLOCATED (SELF%NOGW)
IF (LNOGW) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%NOGW)
  !$OMP TARGET UPDATE TO (SELF%NOGW)
  DO J1 = LBOUND (SELF%NOGW, 1), UBOUND (SELF%NOGW, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%NOGW (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%NOGW)
ENDIF

LEMIS3D = ALLOCATED (SELF%EMIS3D)
IF (LEMIS3D) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%EMIS3D)
  !$OMP TARGET UPDATE TO (SELF%EMIS3D)
  DO J1 = LBOUND (SELF%EMIS3D, 1), UBOUND (SELF%EMIS3D, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%EMIS3D (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%EMIS3D)
ENDIF

LEDRP = ALLOCATED (SELF%EDRP)
IF (LEDRP) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%EDRP)
  !$OMP TARGET UPDATE TO (SELF%EDRP)
  DO J1 = LBOUND (SELF%EDRP, 1), UBOUND (SELF%EDRP, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%EDRP (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%EDRP)
ENDIF

LSLDIA = ALLOCATED (SELF%SLDIA)
IF (LSLDIA) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%SLDIA)
  !$OMP TARGET UPDATE TO (SELF%SLDIA)
  DO J1 = LBOUND (SELF%SLDIA, 1), UBOUND (SELF%SLDIA, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%SLDIA (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%SLDIA)
ENDIF

LAERAOT = ALLOCATED (SELF%AERAOT)
IF (LAERAOT) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%AERAOT)
  !$OMP TARGET UPDATE TO (SELF%AERAOT)
  DO J1 = LBOUND (SELF%AERAOT, 1), UBOUND (SELF%AERAOT, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%AERAOT (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%AERAOT)
ENDIF

LAERLISI = ALLOCATED (SELF%AERLISI)
IF (LAERLISI) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%AERLISI)
  !$OMP TARGET UPDATE TO (SELF%AERLISI)
  DO J1 = LBOUND (SELF%AERLISI, 1), UBOUND (SELF%AERLISI, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%AERLISI (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%AERLISI)
ENDIF

LAEROUT = ALLOCATED (SELF%AEROUT)
IF (LAEROUT) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%AEROUT)
  !$OMP TARGET UPDATE TO (SELF%AEROUT)
  DO J1 = LBOUND (SELF%AEROUT, 1), UBOUND (SELF%AEROUT, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%AEROUT (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%AEROUT)
ENDIF

LAEROCLIM = ALLOCATED (SELF%AEROCLIM)
IF (LAEROCLIM) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%AEROCLIM)
  !$OMP TARGET UPDATE TO (SELF%AEROCLIM)
  DO J1 = LBOUND (SELF%AEROCLIM, 1), UBOUND (SELF%AEROCLIM, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%AEROCLIM (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%AEROCLIM)
ENDIF

LUVP = ALLOCATED (SELF%UVP)
IF (LUVP) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%UVP)
  !$OMP TARGET UPDATE TO (SELF%UVP)
  DO J1 = LBOUND (SELF%UVP, 1), UBOUND (SELF%UVP, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%UVP (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%UVP)
ENDIF

CALL ACDC_COPY_VARIABLE_3RB (SELF%PHYCTY, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%RSPEC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%SDSAT, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%CVV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%RKTH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%RKTQV, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%RKTQC, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%UOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%UAL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%DOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%DAL, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%UEN, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%MO, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

CALL ACDC_COPY_VARIABLE_3RB (SELF%UNEBH, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLIMA = ALLOCATED (SELF%LIMA)
IF (LLIMA) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%LIMA)
  !$OMP TARGET UPDATE TO (SELF%LIMA)
  DO J1 = LBOUND (SELF%LIMA, 1), UBOUND (SELF%LIMA, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%LIMA (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%LIMA)
ENDIF

CALL ACDC_COPY_VARIABLE_3RB (SELF%FSD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LEXT = ALLOCATED (SELF%EXT)
IF (LEXT) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%EXT)
  !$OMP TARGET UPDATE TO (SELF%EXT)
  DO J1 = LBOUND (SELF%EXT, 1), UBOUND (SELF%EXT, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%EXT (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%EXT)
ENDIF

CALL ACDC_COPY_VARIABLE_3RB (SELF%THRAD, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LGFL_PTR = ALLOCATED (SELF%GFL_PTR)
IF (LGFL_PTR) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%GFL_PTR)
  !$OMP TARGET UPDATE TO (SELF%GFL_PTR)
  DO J1 = LBOUND (SELF%GFL_PTR, 1), UBOUND (SELF%GFL_PTR, 1)
    CALL ACDC_COPY_VARIABLE_3RB (SELF%GFL_PTR (J1), LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)
  ENDDO
  !$OMP TARGET ENTER DATA MAP (TO: SELF%GFL_PTR)
ENDIF

END SUBROUTINE
END MODULE
! version = 3f26e477b27e049c8571210a41f2909f127213d3
! from = /tmp/IAL-bundle/build.GPUGFX942_O1_ROCM10004_OPENMPI5.0.7/ial_dp/field_variables_mod.F90
! time = 1770302595
