SUBROUTINE SPCHOR_STRHD1ACC (YDGEOMETRY, YDMODEL, KSTA, KEND, PSPVOR, PSPDIV&
&, PSPT, PSPSPD, PSPSVD, PSPSNHX, PSPQ, PSPO3, PSPL, PSPI, PSPSP, LDACC)
USE TYPE_MODEL,ONLY:MODEL
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB
USE YOMHOOK,ONLY:LHOOK, DR_HOOK, JPHOOK
USE YOMMP0,ONLY:MYSETV

IMPLICIT NONE

TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (INOUT)::YDMODEL
INTEGER (KIND=JPIM), INTENT (IN)::KSTA
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (INOUT)::PSPVOR (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPDIV (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPT (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPSPD (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPSVD (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPSNHX (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPQ (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPO3 (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPL (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPI (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPSP (KSTA:KEND)
LOGICAL, INTENT (IN)::LDACC


INTEGER (KIND=JPIM)::ILEV0
INTEGER (KIND=JPIM)::JLEV
INTEGER (KIND=JPIM)::JSP
LOGICAL::LL_NOHD
REAL (KIND=JPHOOK)::ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK ('SPCHOR_STRHD1ACC', 0, ZHOOK_HANDLE)


ILEV0=YDGEOMETRY%YRMP%NPTRLL (MYSETV)-1
LL_NOHD=(YDMODEL%YRML_DYN%YRDYNA%LNHQE_LASTSI.AND.YDMODEL%YRML_DYN%YRDYN%LNHQE_SOLVER_SP&
&).OR.(YDMODEL%YRML_DYN%YRDYNA%LNHHY.AND.YDMODEL%YRML_DYN%YRDYN%LNHHY_SOLVER_SP)
!$OMP TARGET TEAMS MAP(TOFROM:YDMODEL%YRML_DYN%YRDYN, YDGEOMETRY, PSPVOR, YDMODEL%YRML_DYN%YRDYN%SILAPIN, YDGEOMETRY%YRDIMV%NFLEVL) DEFAULT(SHARED)  IF (LDACC)
!$OMP DISTRIBUTE PARALLEL DO  COLLAPSE (2)

DO JSP=KSTA, KEND

  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
    PSPVOR (JLEV, JSP)=PSPVOR (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPIN (JSP)
  ENDDO

ENDDO

!$OMP END TARGET TEAMS



!$OMP TARGET TEAMS MAP(TOFROM:YDMODEL%YRML_DYN%YRDYN, YDGEOMETRY, PSPVOR, YDMODEL%YRML_DYN%YRDYN%SILAPDI, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
!$OMP DISTRIBUTE PARALLEL DO  COLLAPSE (2)

DO JSP=KSTA, KEND

  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
    PSPVOR (JLEV, JSP)=PSPVOR (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPDI (JSP)
  ENDDO

ENDDO

!$OMP END TARGET TEAMS
!$OMP TARGET TEAMS MAP(TOFROM:YDMODEL%YRML_DYN%YRDYN, YDGEOMETRY, PSPDIV, YDMODEL%YRML_DYN%YRDYN%SILAPIN, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
!$OMP DISTRIBUTE COLLAPSE (2)

DO JSP=KSTA, KEND

  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
    PSPDIV (JLEV, JSP)=PSPDIV (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPIN (JSP)
  ENDDO

ENDDO

!$OMP END TARGET TEAMS



!$OMP TARGET TEAMS MAP(TOFROM:YDMODEL%YRML_DYN%YRDYN, YDGEOMETRY, PSPDIV, YDMODEL%YRML_DYN%YRDYN%SILAPDI, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
!$OMP DISTRIBUTE COLLAPSE (2)

DO JSP=KSTA, KEND

  DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
    PSPDIV (JLEV, JSP)=PSPDIV (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPDI (JSP)
  ENDDO

ENDDO

!$OMP END TARGET TEAMS

IF (YDMODEL%YRML_GCONF%YRDIMF%LSPT) THEN
  !$OMP TARGET TEAMS MAP(TOFROM:YDMODEL%YRML_DYN%YRDYN, YDGEOMETRY, YDGEOMETRY, PSPT, PSPSP, YDMODEL%YRML_DYN%YRDYN%RCORDIT, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
  !$OMP DISTRIBUTE PARALLEL DO  COLLAPSE (2)

  DO JSP=KSTA, KEND

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
      PSPT (JLEV, JSP)=PSPT (JLEV, JSP)-YDMODEL%YRML_DYN%YRDYN%RCORDIT (ILEV0+JLEV)*PSPSP (JSP)
    ENDDO

  ENDDO

  !$OMP END TARGET TEAMS



ENDIF





IF (YDMODEL%YRML_GCONF%YRDIMF%LSPT) THEN
  !$OMP TARGET TEAMS MAP(TOFROM:YDGEOMETRY, YDMODEL%YRML_DYN%YRDYN, PSPT, PSPSP, YDMODEL%YRML_DYN%YRDYN%RCORDIT, YDGEOMETRY%YRDIMV%NFLEVL, YDMODEL%YRML_DYN%YRDYN%RCORDIT)  DEFAULT(SHARED) IF (LDACC)
  !$OMP DISTRIBUTE PARALLEL DO  COLLAPSE (2)

  DO JSP=KSTA, KEND

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
      PSPT (JLEV, JSP)=PSPT (JLEV, JSP)+YDMODEL%YRML_DYN%YRDYN%RCORDIT (ILEV0+JLEV)*PSPSP (JSP)
    ENDDO

  ENDDO

  !$OMP END TARGET TEAMS
ENDIF


IF (LHOOK) CALL DR_HOOK ('SPCHOR_STRHD1ACC', 1, ZHOOK_HANDLE)
END SUBROUTINE SPCHOR_STRHD1ACC
