SUBROUTINE SPCHOR_STRHD2ACC (YDGEOMETRY, YDMODEL, KSTA&
&, KEND, PSPVOR, PSPDIV, PSPSVD, PSPSNHX, LDACC)
USE TYPE_MODEL,ONLY:MODEL
USE GEOMETRY_MOD,ONLY:GEOMETRY
USE PARKIND1,ONLY:JPIM, JPRB

IMPLICIT NONE

TYPE (GEOMETRY), INTENT (IN)::YDGEOMETRY
TYPE (MODEL), INTENT (INOUT)::YDMODEL
INTEGER (KIND=JPIM), INTENT (IN)::KSTA
INTEGER (KIND=JPIM), INTENT (IN)::KEND
REAL (KIND=JPRB), INTENT (INOUT)::PSPVOR (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPDIV (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPSVD (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
REAL (KIND=JPRB), INTENT (INOUT)::PSPSNHX (YDGEOMETRY%YRDIMV%NFLEVL, KSTA:KEND)
LOGICAL, INTENT (IN)::LDACC

INTEGER (KIND=JPIM)::JSP
INTEGER (KIND=JPIM)::JLEV
LOGICAL::LL_NOHD


LL_NOHD=(YDMODEL%YRML_DYN%YRDYNA%LNHQE_LASTSI.AND.YDMODEL%YRML_DYN%YRDYN%LNHQE_SOLVER_SP&
&).OR.(YDMODEL%YRML_DYN%YRDYNA%LNHHY.AND.YDMODEL%YRML_DYN%YRDYN%LNHHY_SOLVER_SP)

IF (YDMODEL%YRML_DYN%YRDYNA%LSLHD_W) THEN
  !$OMP TARGET TEAMS MAP(PRESENT:YDGEOMETRY, YDMODEL%YRML_DYN%YRDYN, PSPVOR, YDMODEL%YRML_DYN%YRDYN%SILAPIN, YDGEOMETRY%YRDIMV%NFLEVL) DEFAULT(SHARED)  IF (LDACC)
  !$OMP DISTRIBUTE PARALLEL DO  COLLAPSE (2)

  DO JSP=KSTA, KEND

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
      PSPVOR (JLEV, JSP)=PSPVOR (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPIN (JSP)
    ENDDO

  ENDDO

  !$OMP END TARGET TEAMS

  !$OMP TARGET TEAMS MAP(PRESENT:YDGEOMETRY, YDMODEL%YRML_DYN%YRDYN, PSPVOR, YDMODEL%YRML_DYN%YRDYN%SILAPDI, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
  !$OMP DISTRIBUTE PARALLEL DO  COLLAPSE (2)

  DO JSP=KSTA, KEND

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
      PSPVOR (JLEV, JSP)=PSPVOR (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPDI (JSP)
    ENDDO

  ENDDO

  !$OMP END TARGET TEAMS
  !$OMP TARGET TEAMS MAP(PRESENT:YDGEOMETRY, YDMODEL%YRML_DYN%YRDYN, PSPDIV, YDMODEL%YRML_DYN%YRDYN%SILAPIN, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
  !$OMP DISTRIBUTE COLLAPSE (2)

  DO JSP=KSTA, KEND

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
      PSPDIV (JLEV, JSP)=PSPDIV (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPIN (JSP)
    ENDDO

  ENDDO

  !$OMP END TARGET TEAMS

  !$OMP TARGET TEAMS MAP(PRESENT:YDGEOMETRY, YDMODEL%YRML_DYN%YRDYN, PSPDIV, YDMODEL%YRML_DYN%YRDYN%SILAPDI, YDGEOMETRY%YRDIMV%NFLEVL)  DEFAULT(SHARED) IF (LDACC)
  !$OMP DISTRIBUTE COLLAPSE (2)

  DO JSP=KSTA, KEND

    DO JLEV=1, YDGEOMETRY%YRDIMV%NFLEVL
      PSPDIV (JLEV, JSP)=PSPDIV (JLEV, JSP)*YDMODEL%YRML_DYN%YRDYN%SILAPDI (JSP)
    ENDDO

  ENDDO

  !$OMP END TARGET TEAMS
ENDIF

END SUBROUTINE SPCHOR_STRHD2ACC
