SUBROUTINE ROUTINE(TAB1,KLEV,KSPEC,KSPEC0,LSOMME,TAB2)

IMPLICIT NONE

REAL(8), INTENT(INOUT) :: TAB1(KSPEC,KLEV)
REAL(8), INTENT(INOUT), OPTIONAL :: TAB2(KSPEC0,KLEV)
INTEGER(4), INTENT(IN) :: KLEV,KSPEC,KSPEC0
LOGICAL, INTENT(IN)    :: LSOMME

INTEGER(4) :: JLEV,JSP

#ifdef PRESENT_TAB2
!$OMP TARGET DATA MAP (PRESENT:TAB1,TAB2) 
#else
!$OMP TARGET DATA MAP (PRESENT:TAB1)
#endif

!$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO SIMD PRIVATE(JLEV)
DO JSP=1,KSPEC
  DO JLEV=1,KLEV
    TAB1(JSP,JLEV)=2*TAB1(JSP,JLEV)
  ENDDO
ENDDO
!$OMP END TARGET TEAMS DISTRIBUTE PARALLEL DO SIMD 

IF (LSOMME) THEN

  !$OMP TARGET TEAMS DISTRIBUTE PARALLEL DO SIMD PRIVATE(JLEV)
  DO JSP=1,KSPEC
    DO JLEV=1,KLEV
      TAB1(JSP,JLEV)=TAB1(JSP,JLEV)+TAB2(JSP,JLEV)
    ENDDO
  ENDDO
  !$OMP END TARGET TEAMS DISTRIBUTE PARALLEL DO SIMD

ENDIF

!$OMP END TARGET DATA

END SUBROUTINE ROUTINE
