PROGRAM TESTPRESENT

IMPLICIT NONE

INTEGER(4), PARAMETER :: KSPEC=64 
INTEGER(4), PARAMETER :: KSPEC0=64
INTEGER(4), PARAMETER :: KLEV=12 

INTEGER(4) :: JSP,JLEV

REAL(8) :: ZTAB1 (KSPEC,KLEV)
REAL(8) :: ZTAB2 (KSPEC0,KLEV)

INTERFACE
SUBROUTINE ROUTINE(TAB1,KLEV,KSPEC,KSPEC0,LSOMME,TAB2)
REAL(8), INTENT(INOUT) :: TAB1(KSPEC,KLEV)
REAL(8), INTENT(INOUT), OPTIONAL :: TAB2(KSPEC0,KLEV)
INTEGER(4), INTENT(IN) :: KLEV,KSPEC,KSPEC0
LOGICAL, INTENT(IN)    :: LSOMME
END SUBROUTINE ROUTINE
END INTERFACE

CALL RANDOM_NUMBER(ZTAB1)

!$OMP TARGET DATA MAP(TOFROM :ZTAB1)  

CALL ROUTINE(ZTAB1,KLEV,KSPEC,KSPEC0,.FALSE.)

!$OMP END TARGET DATA

END PROGRAM TESTPRESENT
