PROGRAM MAIN_ACTKE

IMPLICIT NONE

INTEGER, PARAMETER :: NPROMA = 32, NGPBLKS = 10000
INTEGER :: JLON, JBLK

!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP&PRIVATE (JBLK) &
!$OMP&NUM_TEAMS (NGPBLKS) &
!$OMP&THREAD_LIMIT (NPROMA)

DO JBLK = 1, NGPBLKS

!$OMP PARALLEL DO SIMD PRIVATE (JLON)

  DO JLON = 1, NPROMA
  
    CALL TT (JLON, JBLK)
  
  ENDDO

!$OMP END PARALLEL DO SIMD

ENDDO

!$OMP END TARGET TEAMS DISTRIBUTE

CONTAINS

SUBROUTINE TT (JLON, JBLK)

!$OMP DECLARE TARGET

USE ISO_C_BINDING, ONLY : C_PTR, C_SIZEOF

IMPLICIT NONE

INTEGER, INTENT (IN)::JLON
INTEGER, INTENT (IN)::JBLK

TYPE (C_PTR) :: CPTR1

INTEGER*8 :: ILOC1, ILOC0

IF (C_SIZEOF (CPTR1) /= 8) STOP 1
IF (C_SIZEOF (ILOC1) /= 8) STOP 1

ILOC0 = JLON-1 + NPROMA * (JBLK - 1)

CPTR1 = TRANSFER (ILOC0, CPTR1)
ILOC1 = TRANSFER (CPTR1, ILOC1)

IF (ILOC1 /= ILOC0) THEN
  PRINT *, ILOC1, ILOC0
ENDIF

ENDSUBROUTINE TT

END PROGRAM



