PROGRAM TEST_GANG

IMPLICIT NONE

INTEGER, PARAMETER :: JPRD = 8, JPIM = 4

INTEGER (KIND=JPIM), PARAMETER :: NPROMA = 32, NFLEVG = 15, NDIM = 3, NGPBLKS = 10
LOGICAL, PARAMETER :: LLPERSISTENT = .TRUE.

INTEGER (KIND=JPIM), PARAMETER :: ILB (4) = [1,0,1,1], IUB (4) = [NPROMA, NFLEVG, NDIM, NGPBLKS]
REAL (KIND=JPRD), ALLOCATABLE :: ZDATA4 (:,:,:,:)

INTEGER (KIND=JPIM) :: JDIM
INTEGER (KIND=JPIM) :: ISTEP
LOGICAL, PARAMETER :: LLVERBOSE = .TRUE.
CHARACTER*8 :: CLENV

INTEGER :: IERROR = 0

REAL (KIND=JPRD) :: ZCOEF (NDIM)

ABSTRACT INTERFACE 

SUBROUTINE FIELD_ABORT_FUNC_INTF (CDMESS)

CHARACTER (LEN=*), INTENT (IN) :: CDMESS

END SUBROUTINE

END INTERFACE

PROCEDURE (FIELD_ABORT_FUNC_INTF), POINTER :: FIELD_ABORT_FUNC


CALL GETENV ('GET_DEBUG_PRINT_CRC',      CLENV); 
CALL GETENV ('GET_DEBUG_PRINT_LOCATION', CLENV); 

ALLOCATE (ZDATA4 (ILB (1):IUB (1), ILB (2):IUB (2), ILB (3):IUB (3), ILB (4):IUB (4)))

DO JDIM = 1, NDIM
  ZCOEF (JDIM) = REAL (JDIM, JPRD)
ENDDO

DO ISTEP = 1, 2000
  CALL STEP
ENDDO

CALL DEL_YLF4

CONTAINS

SUBROUTINE TEST_GANG_ABORT (CDMESS)

CHARACTER (LEN=*), INTENT (IN) :: CDMESS

END SUBROUTINE

INTEGER (KIND=JPIM) FUNCTION IRAND (K1, K2)

INTEGER (KIND=JPIM) :: K1, K2

INTEGER*8, SAVE :: X = 2713

X = MODULO (16807_8 * X, 2147483647_8)

IRAND = K1 + MODULO (X, INT (K2-K1+1, 8))

END FUNCTION

SUBROUTINE SORTR8 (KDIM, KORD, PVAL)

INTEGER (KIND=JPIM) :: KDIM
INTEGER (KIND=JPIM) :: KORD (KDIM)
REAL (KIND=JPRD)    :: PVAL (KDIM)

INTEGER (KIND=JPIM) :: I, J, ITMP

DO I = 1, KDIM
  DO J = I+1, KDIM
    IF (PVAL (KORD (I)) > PVAL (KORD (J))) THEN
      ITMP = KORD (I)
      KORD (I) = KORD (J)
      KORD (J) = ITMP
    ENDIF
  ENDDO
ENDDO

END SUBROUTINE

SUBROUTINE STEP

INTEGER (KIND=JPIM) :: IFLD (NDIM)
INTEGER (KIND=JPIM) :: ICASE, ISIZE
INTEGER (KIND=JPIM) :: JFLD, JDIM, ITMP

REAL (KIND=JPRD) :: ZVAL (NDIM)

ISIZE = IRAND (1, NDIM)

DO JFLD = 1, NDIM
  IFLD (JFLD) = JFLD
  ZVAL (JFLD) = REAL (IRAND (0, 100000), JPRD) / REAL (100000, JPRD)
ENDDO


CALL SORTR8 (NDIM, IFLD, ZVAL)

  SELECT CASE (IRAND (1, 2))
    CASE (1)
      CALL NEW_OWNER_YLF4
    CASE (2)
      CALL NEW_WRAPPER_YLF4
    CASE DEFAULT
  END SELECT
  
  SELECT CASE (IRAND (1, 6))
    CASE (1)
      CALL SET_VIEW_YLF4
    CASE (2)
      CALL SET_DEVICE_YLF4
    CASE (3)
      CALL SET_HOST_YLF4
    CASE (4)
      CALL SET_VIEW_YLF3 ([(JFLD, JFLD = 1, NDIM)])
    CASE (5)
      CALL SET_DEVICE_YLF3 ([(JFLD, JFLD = 1, NDIM)])
    CASE (6)
      CALL SET_HOST_YLF3 ([(JFLD, JFLD = 1, NDIM)])
    CASE DEFAULT
  END SELECT
  
  SELECT CASE (IRAND (1, 134))
    CASE (1:10)
      CALL UPDATE_COEF
      CALL SET_VIEW_YLF4
    CASE (11:20)
      CALL GET_VIEW_YLF4
    CASE (21:30)
      CALL UPDATE_COEF (IFLD (1:ISIZE))
      CALL SET_VIEW_YLF3 (IFLD (1:ISIZE))
    CASE (31:40)
      CALL GET_VIEW_YLF3 (IFLD (1:ISIZE))
    CASE (41:50)
      CALL UPDATE_COEF
      CALL SET_HOST_YLF4
    CASE (51:60)
      CALL UPDATE_COEF
      CALL SET_DEVICE_YLF4
    CASE (61:70)
      CALL GET_HOST_YLF4
    CASE (71:80)
      CALL GET_DEVICE_YLF4
    CASE (81:90)
      CALL UPDATE_COEF (IFLD (1:ISIZE))
      CALL SET_HOST_YLF3 (IFLD (1:ISIZE))
    CASE (91:100)
      CALL UPDATE_COEF (IFLD (1:ISIZE))
      CALL SET_DEVICE_YLF3 (IFLD (1:ISIZE))
    CASE (101:110)
      CALL GET_DEVICE_YLF3 (IFLD (1:ISIZE))
    CASE (111:120)
      CALL GET_HOST_YLF3 (IFLD (1:ISIZE))
    CASE (121:130)
      CALL FAIL_VIEW_YLF4
    CASE (131:134)
      CALL DEL_YLF4
    CASE DEFAULT
  END SELECT 

END SUBROUTINE

SUBROUTINE UPDATE_COEF (KFLD)

INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN) :: KFLD (:)

INTEGER (KIND=JPIM) :: JDIM, JFLD

END SUBROUTINE

REAL (KIND=JPRD) FUNCTION FUNC (JLON_, JLEV_, JFLD_, JBLK_, PCOEF_)

INTEGER (KIND=JPIM) :: JLON_, JLEV_, JFLD_, JBLK_
REAL (KIND=JPRD) :: PCOEF_ (NDIM)

FUNC = 0.

END FUNCTION

SUBROUTINE NEW_OWNER_YLF4

END SUBROUTINE

SUBROUTINE NEW_WRAPPER_YLF4

END SUBROUTINE

SUBROUTINE SET_VIEW_YLF4

INTEGER (KIND=JPIM) :: JLON, JLEV, JFLD, JBLK
REAL (KIND=JPRD), POINTER :: ZPTR3 (:,:,:)

END SUBROUTINE

SUBROUTINE FAIL_VIEW_YLF4

INTEGER (KIND=JPIM) :: JLON, JLEV, JFLD, JBLK
REAL (KIND=JPRD), POINTER :: ZPTR3 (:,:,:)

FIELD_ABORT_FUNC => TEST_GANG_ABORT

!$OMP PARALLEL DO PRIVATE (ZPTR3, JBLK)
DO JBLK = 1, NGPBLKS
  DO JFLD = 1, NDIM
    DO JLEV = 0, NFLEVG
      DO JLON = 1, NPROMA
        ZPTR3 (JLON, JLEV, JFLD) = FUNC (JLON, JLEV, JFLD, JBLK, ZCOEF)
      ENDDO
    ENDDO
  ENDDO
ENDDO
!$OMP END PARALLEL DO


END SUBROUTINE

SUBROUTINE GET_VIEW_YLF4

INTEGER (KIND=JPIM) :: JLON, JLEV, JFLD, JBLK
REAL (KIND=JPRD), POINTER :: ZPTR3 (:,:,:)

END SUBROUTINE

SUBROUTINE SET_VIEW_YLF3 (KFLD)

INTEGER (KIND=JPIM), INTENT (IN) :: KFLD (:)

INTEGER (KIND=JPIM) :: JLON, JLEV, JFLD, JBLK, JDIM
REAL (KIND=JPRD), POINTER :: ZPTR2 (:,:)

END SUBROUTINE

SUBROUTINE GET_VIEW_YLF3 (KFLD)

INTEGER (KIND=JPIM), INTENT (IN) :: KFLD (:)

INTEGER (KIND=JPIM) :: JLON, JLEV, JFLD, JBLK, JDIM
REAL (KIND=JPRD), POINTER :: ZPTR2 (:,:)

END SUBROUTINE

SUBROUTINE SET_HOST_YLF4

REAL (KIND=JPRD), POINTER :: ZHOST4 (:,:,:,:)
INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD

END SUBROUTINE

SUBROUTINE SET_DEVICE_YLF4

REAL (KIND=JPRD), POINTER :: ZDEVICE4 (:,:,:,:)
INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD

END SUBROUTINE

SUBROUTINE DEL_YLF4

END SUBROUTINE

SUBROUTINE GET_HOST_YLF4

REAL (KIND=JPRD), POINTER :: ZHOST4 (:,:,:,:)

INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD

END SUBROUTINE

SUBROUTINE GET_DEVICE_YLF4

REAL (KIND=JPRD), POINTER :: ZDEVICE4 (:,:,:,:)

INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD

END SUBROUTINE

SUBROUTINE CHECK_DIMS_YLF4 (P4)

INTEGER (KIND=JPIM) :: JDIM

REAL (KIND=JPRD), POINTER :: P4 (:,:,:,:)

END SUBROUTINE

SUBROUTINE CHECK_DIMS_YLF3 (P3)

INTEGER (KIND=JPIM) :: JDIM

REAL (KIND=JPRD), POINTER :: P3 (:,:,:)

END SUBROUTINE

SUBROUTINE SET_HOST_YLF3 (KFLD)

INTEGER (KIND=JPIM), INTENT (IN) :: KFLD (:)

REAL (KIND=JPRD), POINTER :: ZHOST3 (:,:,:)
INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD, JDIM

END SUBROUTINE

SUBROUTINE SET_DEVICE_YLF3 (KFLD)

INTEGER (KIND=JPIM), INTENT (IN) :: KFLD (:)

REAL (KIND=JPRD), POINTER :: ZDEVICE3 (:,:,:)
INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD, JDIM

END SUBROUTINE

SUBROUTINE GET_DEVICE_YLF3 (KFLD)

INTEGER (KIND=JPIM), INTENT (IN) :: KFLD (:)

REAL (KIND=JPRD), POINTER :: ZDEVICE3 (:,:,:)
INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD, JDIM

END SUBROUTINE

SUBROUTINE GET_HOST_YLF3 (KFLD)

INTEGER (KIND=JPIM), INTENT (IN) :: KFLD (:)

REAL (KIND=JPRD), POINTER :: ZHOST3 (:,:,:)
INTEGER (KIND=JPIM) :: JBLK, JLEV, JLON, JFLD, JDIM

END SUBROUTINE

SUBROUTINE CHECK_STATUS

INTEGER (KIND=JPIM) :: JFLD

END SUBROUTINE

SUBROUTINE PLOG (CDNAME, KFLD)

CHARACTER (LEN=*), INTENT (IN) :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: KFLD (:)

INTEGER (KIND=JPIM) :: JDIM, JSPC

END SUBROUTINE

SUBROUTINE ABOR1_ACC (CDMESS)

CHARACTER (LEN=*), INTENT (IN) :: CDMESS

END SUBROUTINE

END PROGRAM 
