PROGRAM TEST_GANG

IMPLICIT NONE

ABSTRACT INTERFACE 
SUBROUTINE FIELD_ABORT_FUNC_INTF (CDMESS)
CHARACTER (LEN=*), INTENT (IN) :: CDMESS
END SUBROUTINE
END INTERFACE

PROCEDURE (FIELD_ABORT_FUNC_INTF), POINTER :: FIELD_ABORT_FUNC

FIELD_ABORT_FUNC => TEST_GANG_ABORT

CONTAINS

SUBROUTINE TEST_GANG_ABORT (CDMESS)
CHARACTER (LEN=*), INTENT (IN) :: CDMESS
END SUBROUTINE

SUBROUTINE FAIL_VIEW_YLF4
FIELD_ABORT_FUNC => TEST_GANG_ABORT
END SUBROUTINE

END PROGRAM 
