PROGRAM MAIN_SPNHSI

USE GEOMETRY_MOD , ONLY : GEOMETRY

USE UTIL_GEOMETRY_MOD

IMPLICIT NONE

TYPE(GEOMETRY)      :: YDGEOMETRY

INTEGER(KIND=4) :: KSTA,KEND

INTEGER :: JLEV, JLON
REAL(8), ALLOCATABLE :: ZSPHI(:,:)

KSTA=1
KEND=1598

ALLOCATE(YDGEOMETRY%YRVERT_GEOM%YRVETA%VFE_RDETAH(90))
YDGEOMETRY%YRVERT_GEOM%YRVETA%VFE_RDETAH(:)=1.0

CALL ACDC_COPY (YDGEOMETRY)

ALLOCATE(ZSPHI(KSTA:KEND,90))
ZSPHI(:,:)=0.

!$OMP TARGET DATA MAP(ALLOC: ZSPHI) MAP(PRESENT:YDGEOMETRY) 

WRITE (0,*) "before kernel in main_spnhsi"
CALL FLUSH(0)

!$OMP TARGET 
DO JLON = KSTA, KEND

  

  DO JLEV=1, 90
    
    ZSPHI (JLON, JLEV)=YDGEOMETRY%YRVERT_GEOM%YRVETA%VFE_RDETAH (JLEV)
    if ((jlon==1) .and. (jlev <=10)) write (0,*) "jlon jlev val",jlon,jlev,zsphi(jlon,jlev)
  
  ENDDO

ENDDO
!$OMP END TARGET 

WRITE (0,*) "after kernel in main_spnhsi"
CALL FLUSH(0)

!$OMP END TARGET DATA

CALL ACDC_WIPE (YDGEOMETRY)

END PROGRAM MAIN_SPNHSI 

