
MODULE TYPE_GEOMETRY

!USE YOMVERT    , ONLY : TVAB, TVETA, TVFE, TVERTICAL_GEOM
USE YOMVERT    , ONLY : TVERTICAL_GEOM

IMPLICIT NONE 

PRIVATE

TYPE, PUBLIC :: GEOMETRY
  LOGICAL          :: LNHX_GEOM
  TYPE(TVERTICAL_GEOM) :: YRVERT_GEOM

END TYPE GEOMETRY

END MODULE TYPE_GEOMETRY
