MODULE UTIL_TVERTICAL_GEOM_MOD

USE YOMVERT, ONLY : TVERTICAL_GEOM

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TVERTICAL_GEOM
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TVERTICAL_GEOM
END INTERFACE



CONTAINS

SUBROUTINE ACDC_COPY_TVERTICAL_GEOM (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TVETA_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF)
  !$OMP TARGET UPDATE TO (SELF)
ENDIF

CALL ACDC_COPY_TVETA (SELF%YRVETA, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TVERTICAL_GEOM (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TVETA_MOD
IMPLICIT NONE
TYPE (TVERTICAL_GEOM), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL ACDC_WIPE_TVETA (SELF%YRVETA, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$OMP TARGET EXIT DATA MAP (DELETE: SELF)
ENDIF
END SUBROUTINE





END MODULE
