MODULE UTIL_TVETA_MOD

USE YOMVERT, ONLY : TVETA

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_TVETA
END INTERFACE




INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_TVETA
END INTERFACE



CONTAINS


SUBROUTINE ACDC_COPY_TVETA (SELF, LDCREATED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVETA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LOGICAL :: LVFE_RDETAH

LVFE_RDETAH = ALLOCATED (SELF%VFE_RDETAH)
IF (LVFE_RDETAH) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF%VFE_RDETAH)
  !$OMP TARGET UPDATE TO (SELF%VFE_RDETAH)
  !$OMP TARGET ENTER DATA MAP (TO: SELF%VFE_RDETAH)
ENDIF

END SUBROUTINE







SUBROUTINE ACDC_WIPE_TVETA (SELF, LDDELETED, LDFIELDAPI)

IMPLICIT NONE
TYPE (TVETA), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LOGICAL :: LVFE_RDETAH

LVFE_RDETAH = ALLOCATED (SELF%VFE_RDETAH)
IF (LVFE_RDETAH) THEN
  !$OMP TARGET EXIT DATA MAP (RELEASE: SELF%VFE_RDETAH)
  !$OMP TARGET EXIT DATA MAP (DELETE: SELF%VFE_RDETAH)
ENDIF

END SUBROUTINE





END MODULE
