MODULE UTIL_GEOMETRY_MOD

USE TYPE_GEOMETRY, ONLY : GEOMETRY

INTERFACE ACDC_COPY
MODULE PROCEDURE ACDC_COPY_GEOMETRY
END INTERFACE

INTERFACE ACDC_WIPE
MODULE PROCEDURE ACDC_WIPE_GEOMETRY
END INTERFACE



CONTAINS

SUBROUTINE ACDC_COPY_GEOMETRY (SELF, LDCREATED, LDFIELDAPI)
USE UTIL_TVERTICAL_GEOM_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDCREATED, LDFIELDAPI
LOGICAL :: LLCREATED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF
LLCREATED = .FALSE.
IF (PRESENT (LDCREATED)) THEN
  LLCREATED = LDCREATED
ENDIF
IF (.NOT. LLCREATED) THEN
  !$OMP TARGET ENTER DATA MAP (ALLOC: SELF)
  !$OMP TARGET UPDATE TO (SELF)
ENDIF

CALL ACDC_COPY_TVERTICAL_GEOM (SELF%YRVERT_GEOM, LDCREATED=.TRUE., LDFIELDAPI=LDFIELDAPI)

END SUBROUTINE







SUBROUTINE ACDC_WIPE_GEOMETRY (SELF, LDDELETED, LDFIELDAPI)
USE UTIL_TVERTICAL_GEOM_MOD
IMPLICIT NONE
TYPE (GEOMETRY), INTENT (IN), TARGET :: SELF
LOGICAL, OPTIONAL, INTENT (IN) :: LDDELETED, LDFIELDAPI
LOGICAL :: LLDELETED
LOGICAL :: LLFIELDAPI
LLFIELDAPI = .FALSE.
IF (PRESENT (LDFIELDAPI)) THEN
  LLFIELDAPI = LDFIELDAPI
ENDIF

CALL ACDC_WIPE_TVERTICAL_GEOM (SELF%YRVERT_GEOM, LDDELETED=.TRUE., LDFIELDAPI=LDFIELDAPI)

LLDELETED = .FALSE.
IF (PRESENT (LDDELETED)) THEN
  LLDELETED = LDDELETED
ENDIF
IF (.NOT. LLDELETED) THEN
  !$OMP TARGET EXIT DATA MAP (DELETE: SELF)
ENDIF
END SUBROUTINE





END MODULE
