MODULE YOMVERT

IMPLICIT NONE

SAVE


!     ------------------------------------------------------------------

REAL(KIND=8)         :: VP00
REAL(KIND=8)         :: TOPPRES

!!TYPE TVAB
!!!  REAL(KIND=8), ALLOCATABLE :: VALH(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VBH(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VAH(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VC(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VAF(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VBF(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VDELA(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VDELB(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VRATH(:)
!!!  REAL(KIND=8), ALLOCATABLE :: VRATF(:)
!!!CONTAINS
!!!  PROCEDURE :: ALLOC=>ALLOCVAB
!!!  PROCEDURE :: DEALLOC=>DEALLOCVAB
!!!  PROCEDURE :: INIT=>INITVAB
!!END TYPE TVAB

!     ------------------------------------------------------------------

TYPE TVETA
!  REAL(KIND=8), ALLOCATABLE :: VETAH(:)
!  REAL(KIND=8), ALLOCATABLE :: VFE_ETAH(:)
!  REAL(KIND=8), ALLOCATABLE :: VETAF(:)
!  REAL(KIND=8), ALLOCATABLE :: VFE_ETAF(:)
  REAL(KIND=8), ALLOCATABLE :: VFE_RDETAH(:)
!  REAL(KIND=8), ALLOCATABLE :: VDETA_RATIO(:)
!  REAL(KIND=8), ALLOCATABLE :: VRDETAH(:)
!  REAL(KIND=8), ALLOCATABLE :: VWEI(:)
!  REAL(KIND=8), ALLOCATABLE :: VETA_H(:)
!  REAL(KIND=8), ALLOCATABLE :: VETA_LAITRIQM3D(:)
!CONTAINS
!  PROCEDURE :: ALLOC=>ALLOCVETA
!  PROCEDURE :: DEALLOC=>DEALLOCVETA
END TYPE TVETA

!!TYPE TVFE
!!!  REAL(KIND=8),ALLOCATABLE :: VFE_KNOT(:)
!!!  REAL(KIND=8),ALLOCATABLE :: RINTE(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RINTBF00 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RINTBF11 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERI(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERB(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERBF00 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERBF01 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERBF10 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERBF11 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERBH00 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERBH01 (:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDDERI(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDDERBF01(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RINTGW(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RDERGW(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RINTG(:,:)
!!!  REAL(KIND=8),ALLOCATABLE :: RINTC(:) 
!!END TYPE TVFE

TYPE TVERTICAL_GEOM
!  LOGICAL    :: LNONHYD_GEOM
  TYPE(TVETA):: YRVETA
END TYPE TVERTICAL_GEOM

END MODULE YOMVERT
