INTERFACE

SUBROUTINE ACTKE_OPENACC ( KIDIA, KLON, KLEV, YDSTACK)

USE FXTRAN_ACDC_STACK_MOD
IMPLICIT NONE
INTEGER, INTENT(IN)                  :: KIDIA
INTEGER, INTENT(IN)                  :: KLON
INTEGER, INTENT(IN)                  :: KLEV
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK

END SUBROUTINE ACTKE_OPENACC

END INTERFACE
