MODULE FXTRAN_ACDC_STACK_MOD

IMPLICIT NONE

INTEGER, PARAMETER :: JPIA = 8, JPIB = 8

TYPE FXTRAN_ACDC_STACK
  INTEGER (KIND=JPIA) :: L4
  INTEGER (KIND=JPIA) :: U4
  INTEGER (KIND=JPIA) :: L8
  INTEGER (KIND=JPIA) :: U8
END TYPE

CONTAINS

SUBROUTINE FXTRAN_ACDC_STACK_ALLOC (SELF, KPTR, KSIZE, KKIND)
!$omp declare target

TYPE (FXTRAN_ACDC_STACK) :: SELF
INTEGER (KIND=JPIA) :: KPTR
INTEGER (KIND=JPIB) :: KSIZE
INTEGER             :: KKIND

SELECT CASE (KKIND)
  CASE (4) 

    KPTR = SELF%L4
   
    SELF%L4 = SELF%L4 + 4 * KSIZE
   
    IF (SELF%L4 > SELF%U4) GOTO 999

  CASE (8) 

    KPTR = SELF%L8

    SELF%L8 = SELF%L8 + 8 * KSIZE

    IF (SELF%L8 > SELF%U8) GOTO 999

  CASE DEFAULT

    GOTO 999

END SELECT

RETURN

999 CONTINUE

END SUBROUTINE

END MODULE

