PROGRAM MAIN_ACTKE

#include "fxtran_acdc_stack.h"

USE FXTRAN_ACDC_STACK_MOD

IMPLICIT NONE

INTEGER                          :: KLON 
INTEGER                          :: KLEV 
#include "actke_openacc.intfb.h"

TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: NPROMA, JLON
INTEGER :: NGPBLKS, JBLK

!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP & PRIVATE (JBLK) &
!$OMP & NUM_TEAMS (NGPBLKS) &
!$OMP & THREAD_LIMIT (NPROMA)

    DO JBLK = 1, NGPBLKS

!$OMP PARALLEL DO SIMD PRIVATE (JLON, YLSTACK)

      DO JLON = 1, NPROMA

        CALL ACTKE_OPENACC ( JLON, KLON, KLEV, YDSTACK=YLSTACK)

      ENDDO

!$OMP END PARALLEL DO SIMD

    ENDDO

!$OMP END TARGET TEAMS DISTRIBUTE

END PROGRAM



