PROGRAM MAIN_ACTKE

USE FXTRAN_ACDC_STACK_MOD

IMPLICIT NONE

INTEGER                          :: KLON 
INTEGER                          :: KLEV 

INTERFACE
SUBROUTINE ACTKE_OPENACC ( KIDIA, KLON, KLEV, YDSTACK)
USE FXTRAN_ACDC_STACK_MOD
IMPLICIT NONE
INTEGER, INTENT(IN)                  :: KIDIA
INTEGER, INTENT(IN)                  :: KLON
INTEGER, INTENT(IN)                  :: KLEV
TYPE(FXTRAN_ACDC_STACK), INTENT (IN) :: YDSTACK
END SUBROUTINE ACTKE_OPENACC
END INTERFACE

TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: NPROMA, JLON
INTEGER :: NGPBLKS, JBLK

!$OMP TARGET TEAMS DISTRIBUTE &
!$OMP & PRIVATE (JBLK) &
!$OMP & NUM_TEAMS (NGPBLKS) &
!$OMP & THREAD_LIMIT (NPROMA)

    DO JBLK = 1, NGPBLKS

!$OMP PARALLEL DO SIMD PRIVATE (JLON, YLSTACK)

      DO JLON = 1, NPROMA

        CALL ACTKE_OPENACC ( JLON, KLON, KLEV, YDSTACK=YLSTACK)

      ENDDO

!$OMP END PARALLEL DO SIMD

    ENDDO

!$OMP END TARGET TEAMS DISTRIBUTE

END PROGRAM



