PROGRAM MAIN_SPNHSI


USE YOMDYN       , ONLY : TDYN, LOAD_TDYN
USE HIPFORT
USE HIPFORT_ROCBLAS
USE ISO_C_BINDING

IMPLICIT NONE

TYPE(TDYN)          :: YDDYN
TYPE(C_PTR)  :: HANDLE
INTEGER  ::IRESU

!!!!!loads object TDYN in CPU memory from file TDYN.CONST.DAT
CALL LOAD_TDYN (YDDYN  )

!!!!!beginning of object TDYN copy to GPU memory from CPU memory
!$OMP TARGET ENTER DATA MAP(ALLOC:YDDYN)
!$OMP TARGET UPDATE TO(YDDYN)

IF (ALLOCATED(YDDYN%RDIDIV)) THEN 
  WRITE (0,*) "RDIDIV ALLOCATED"
  !$OMP TARGET ENTER DATA MAP (ALLOC : YDDYN%RDIDIV)
  !$OMP TARGET UPDATE TO(YDDYN%RDIDIV)
  !$OMP TARGET ENTER DATA MAP(TO:YDDYN%RDIDIV)
ENDIF

IRESU = ROCBLAS_CREATE_HANDLE(HANDLE)
WRITE(0,*) "HANDLE CREATION RESULT : ",IRESU

END PROGRAM MAIN_SPNHSI 


