! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE YOMDYN

IMPLICIT NONE

SAVE

INTEGER(KIND=4),PARAMETER :: JPSLDIMK=4

TYPE :: TDYN

REAL(KIND=8) :: REPS1
REAL(KIND=8) :: REPS2
REAL(KIND=8) :: REPSM1
REAL(KIND=8) :: REPSM2
REAL(KIND=8) :: REPSP1
REAL(KIND=8) :: HDIRVOR
REAL(KIND=8) :: HDIRDIV
REAL(KIND=8) :: HDIRT
REAL(KIND=8) :: HDIRQ
REAL(KIND=8) :: HDIRO3
REAL(KIND=8) :: HDIRPD
REAL(KIND=8) :: HDIRVD
REAL(KIND=8) :: HDIRSP
REAL(KIND=8) :: HRDIRVOR
REAL(KIND=8) :: HRDIRDIV
REAL(KIND=8) :: HRDIRT
REAL(KIND=8) :: HRDIRQ
REAL(KIND=8) :: HRDIRO3
REAL(KIND=8) :: HRDIRPD
REAL(KIND=8) :: HRDIRVD
REAL(KIND=8) :: HRDIRSP
REAL(KIND=8) :: RRDXTAU
REAL(KIND=8) :: RDAMPVOR
REAL(KIND=8) :: RDAMPDIV
REAL(KIND=8) :: RDAMPT
REAL(KIND=8) :: RDAMPQ
REAL(KIND=8) :: RDAMPO3
REAL(KIND=8) :: RDAMPPD
REAL(KIND=8) :: RDAMPVD
REAL(KIND=8) :: RDAMPSP
LOGICAL :: LNEWHD
REAL(KIND=8) :: REXPDH
REAL(KIND=8) :: FRANDH
REAL(KIND=8) :: SLEVDH
REAL(KIND=8) :: SLEVDH1
REAL(KIND=8) :: SLEVDH2
REAL(KIND=8) :: SLEVDH3
INTEGER(KIND=4) :: NSREFDH
REAL(KIND=8) :: RATIO_HDI_TOP
INTEGER(KIND=4) :: NPROFILEHD
REAL(KIND=8) :: RPROFHDBT
REAL(KIND=8) :: RPROFHDTP
REAL(KIND=8) :: RPROFHDMX
REAL(KIND=8) :: RPROFHDEX
LOGICAL :: LRDISPE_EC
REAL(KIND=8),ALLOCATABLE:: RDIVOR(:,:)
REAL(KIND=8),ALLOCATABLE:: RDIDIV(:,:)
REAL(KIND=8),ALLOCATABLE:: RDITG(:,:)
REAL(KIND=8),ALLOCATABLE:: RDIGFL(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDIPD(:,:)
REAL(KIND=8),ALLOCATABLE:: RDIVD(:,:)
REAL(KIND=8),ALLOCATABLE:: RDISP(:)
REAL(KIND=8),ALLOCATABLE:: RDHI(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHIVOR(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHIDIV(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHISPD(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHISVD(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHINHX(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHIT(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHIGFL(:,:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHIP(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHSVOR(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHSDIV(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHSSVD(:,:,:)
REAL(KIND=8),ALLOCATABLE:: RDHSNHX(:,:,:)
LOGICAL :: LSTRHD
REAL(KIND=8) :: HDTIME_STRHD
REAL(KIND=8) :: KLSPONGE
LOGICAL :: LM0DAMP
REAL(KIND=8) :: RBEGSPONGE


LOGICAL :: LTOP_VOR
INTEGER(KIND=4) :: NTOP_VOR_TRUNC
INTEGER(KIND=4) :: NTOP_VOR_BOT

REAL(KIND=8),ALLOCATABLE:: RSAVEDP(:,:,:,:)

REAL(KIND=8) :: SLHDA0
REAL(KIND=8) :: SLHDA0T
REAL(KIND=8) :: SLHDB
REAL(KIND=8) :: SLHDBT
REAL(KIND=8) :: SLHDD00
REAL(KIND=8) :: SLHDD00T
REAL(KIND=8) :: SLHDDIV
REAL(KIND=8) :: SLHDRATDDIV
REAL(KIND=8) :: SLHDHOR
REAL(KIND=8) :: SLHD_P_LOW
REAL(KIND=8) :: SLHD_P_HIGH
LOGICAL :: LSLHDHEAT
LOGICAL :: LSLHDSPONGE
REAL(KIND=8) :: HDSRVOR
REAL(KIND=8) :: HDSRDIV
REAL(KIND=8) :: HDSRVD
REAL(KIND=8) :: HRDSRVOR
REAL(KIND=8) :: HRDSRDIV
REAL(KIND=8) :: HRDSRVD
REAL(KIND=8) :: RDAMPVORS
REAL(KIND=8) :: RDAMPDIVS
REAL(KIND=8) :: RDAMPVDS
REAL(KIND=8) :: RDAMPHDS
REAL(KIND=8) :: REXPDHS
REAL(KIND=8) :: SLEVDHS
REAL(KIND=8) :: SLEVDHS1
REAL(KIND=8) :: SLEVDHS2
REAL(KIND=8) :: SDRED
REAL(KIND=8),ALLOCATABLE:: RDSVOR(:,:)
REAL(KIND=8),ALLOCATABLE:: RDSDIV(:,:)
REAL(KIND=8),ALLOCATABLE:: RDSVD(:,:)
REAL(KIND=8),ALLOCATABLE:: RDHS(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SLHD_MASK_U(:)
REAL(KIND=8),ALLOCATABLE:: SLHD_MASK_T(:)
REAL(KIND=8) :: ZSLHDP1
REAL(KIND=8) :: ZSLHDP3
INTEGER(KIND=4) :: NLEV_SPONGE


LOGICAL :: LRFRIC
LOGICAL :: LRFRICISOTR

REAL(KIND=8),ALLOCATABLE:: RCORDIT(:)
REAL(KIND=8),ALLOCATABLE:: RCORDIH(:)
REAL(KIND=8),ALLOCATABLE:: RCORDIF(:)

REAL(KIND=8) :: VMAX1
REAL(KIND=8) :: VMAX2

REAL(KIND=8) :: RMAX_D3
LOGICAL :: LBOUND_D3

REAL(KIND=8),ALLOCATABLE:: RKRF(:) 
INTEGER(KIND=4) :: NMAXLEVRF
REAL(KIND=8) :: RRFZ1
REAL(KIND=8) :: RRFPLM
REAL(KIND=8) :: RRFTAU

REAL(KIND=8) :: RTEMRB
INTEGER(KIND=4) :: NRUBC

LOGICAL :: LGWFRIC
INTEGER(KIND=4) :: NLEV_GWFRIC
REAL(KIND=8) :: RGWFRIC_MAX
REAL(KIND=8) :: RGWFRIC_PLM
REAL(KIND=8),ALLOCATABLE :: RGWFRIC(:)


LOGICAL :: LSIDG
LOGICAL :: LDYN_STABAN
LOGICAL :: LRHDI_LASTITERPC
LOGICAL :: LSIDYN_VERBOSE

REAL(KIND=8) :: BETADT
REAL(KIND=8) :: RBT
REAL(KIND=8) :: RBTS2
REAL(KIND=8) :: REFGEO
REAL(KIND=8) :: SIPR
REAL(KIND=8) :: SIPRA
REAL(KIND=8) :: SITR
REAL(KIND=8) :: SITRA
REAL(KIND=8) :: SITRUB
REAL(KIND=8) :: SIPRUB
REAL(KIND=8) :: SITIME
REAL(KIND=8) :: SIRPRG
REAL(KIND=8) :: SIRPRN
REAL(KIND=8) :: SISLP
REAL(KIND=8) :: SIFRG
REAL(KIND=8) :: SIFRA
REAL(KIND=8) :: SITVAR

INTEGER(KIND=4) :: NSITER
INTEGER(KIND=4) :: NCURRENT_ITER
INTEGER(KIND=4) :: NITERHELM
INTEGER(KIND=4) :: NOPT_SITR
INTEGER(KIND=4) :: NOPT_SIPR
INTEGER(KIND=4) :: NOPT_SISLP
INTEGER(KIND=4) :: NSZNISNAX

REAL(KIND=8),ALLOCATABLE:: SITRAM(:)
REAL(KIND=8),ALLOCATABLE:: SITRM(:)

REAL(KIND=8),ALLOCATABLE:: SIALPH(:)
REAL(KIND=8),ALLOCATABLE:: SILNPR(:)
REAL(KIND=8),ALLOCATABLE:: SIDELP(:)
REAL(KIND=8),ALLOCATABLE:: SIRDEL(:)
REAL(KIND=8),ALLOCATABLE:: SITLAH(:)
REAL(KIND=8),ALLOCATABLE:: SITLAF(:)
REAL(KIND=8),ALLOCATABLE:: SIDPHI(:)

REAL(KIND=8),ALLOCATABLE:: SIALPH_NH(:)
REAL(KIND=8),ALLOCATABLE:: SILNPR_NH(:)
REAL(KIND=8),ALLOCATABLE:: SIDELP_NH(:)
REAL(KIND=8),ALLOCATABLE:: SIRDEL_NH(:)
REAL(KIND=8),ALLOCATABLE:: SITLAH_NH(:)
REAL(KIND=8),ALLOCATABLE:: SITLAF_NH(:)
REAL(KIND=8),ALLOCATABLE:: SIDPHI_NH(:)

REAL(KIND=8),ALLOCATABLE:: SIWF2H(:)
REAL(KIND=8),ALLOCATABLE:: SIWH2F(:,:)
REAL(KIND=8),ALLOCATABLE:: SIGFL(:)
REAL(KIND=8),ALLOCATABLE:: SIGFM(:)
REAL(KIND=8),ALLOCATABLE:: SITFL(:)
REAL(KIND=8),ALLOCATABLE:: SITFM(:)
REAL(KIND=8),ALLOCATABLE:: SIGHL(:)
REAL(KIND=8),ALLOCATABLE:: SIGHM(:)

REAL(KIND=8),ALLOCATABLE:: SIB(:,:)
REAL(KIND=8),ALLOCATABLE:: SIMO(:,:)
REAL(KIND=8),ALLOCATABLE:: SIMI(:,:)
REAL(KIND=8),ALLOCATABLE:: SIVP(:)
REAL(KIND=8),ALLOCATABLE:: SIVP2(:)
REAL(KIND=8),ALLOCATABLE:: SIPD(:)
REAL(KIND=8),ALLOCATABLE:: SIPE(:)
REAL(KIND=8),ALLOCATABLE:: SIPF(:)
INTEGER(KIND=4),ALLOCATABLE:: SINISNAX(:)
REAL(KIND=8),ALLOCATABLE:: SILAPDI(:)
REAL(KIND=8),ALLOCATABLE:: SILAPIN(:)
REAL(KIND=8),ALLOCATABLE:: SIHEG(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEG2(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEGB(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEGB2(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SIFAC(:,:)
REAL(KIND=8),ALLOCATABLE:: SIFACI(:,:)
REAL(KIND=8),ALLOCATABLE:: SIBQ(:,:)

REAL(KIND=8),ALLOCATABLE:: SIMITRA(:,:)
REAL(KIND=8),ALLOCATABLE:: SIMOTRA(:,:)
REAL(KIND=8),ALLOCATABLE:: SIFACITRA(:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEGTRA(:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEG2TRA(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEGBTRA(:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEGB2TRA(:,:,:)
REAL(KIND=8),ALLOCATABLE:: SIHEGIND(:)
REAL(KIND=8),ALLOCATABLE:: SIBQTRA(:,:)

REAL(KIND=8),ALLOCATABLE:: SIZA(:)
REAL(KIND=8),ALLOCATABLE:: SIZC(:)
REAL(KIND=8),ALLOCATABLE:: SIPIS(:)
REAL(KIND=8),ALLOCATABLE:: SITGR(:,:)
REAL(KIND=8),ALLOCATABLE:: SITAC(:)

REAL(KIND=8) :: VNORM
REAL(KIND=8) :: SLOPE_MAX
REAL(KIND=8) :: PSURF_MAX
REAL(KIND=8) :: PSURF_MIN
INTEGER(KIND=4) :: NVLAG
INTEGER(KIND=4) :: NWLAG
INTEGER(KIND=4) :: NTLAG
INTEGER(KIND=4) :: NSPDLAG
INTEGER(KIND=4) :: NSVDLAG
INTEGER(KIND=4) :: NSPLTHOI
LOGICAL :: LSPLTHOIGFL
INTEGER(KIND=4) :: NSLDIMK
INTEGER(KIND=4) :: NITMP
REAL(KIND=8) :: VETAON
REAL(KIND=8) :: VETAOX
LOGICAL :: LSETTLSVF
LOGICAL :: LSETFSTAT
LOGICAL :: LSETTLSVF_DIFF
REAL(KIND=8) :: RW2TLFF
REAL(KIND=8) :: RALPHA
REAL(KIND=8) :: RALPHA_TOP
INTEGER(KIND=4) :: NLEV_ZALPHA
INTEGER(KIND=4) :: NEDER
REAL(KIND=8)    :: RBETAK(1:3,1:10)
LOGICAL :: LWENOBC
INTEGER(KIND=4) :: NQMHOISLT
LOGICAL :: LSLDP_RK
LOGICAL :: LSLDP_CURV
LOGICAL :: LSLDP_CURV_FIX
LOGICAL :: LRHS_CURV
LOGICAL :: LRHS_CURV_FIX
LOGICAL :: LSLDP_XYZ
LOGICAL :: LSLDP_SAVE
REAL(KIND=8) :: VESL
REAL(KIND=8) :: XIDT
LOGICAL :: LQMW
LOGICAL :: LQMHW
LOGICAL :: LQMT
LOGICAL :: LQMHT
LOGICAL :: LQMP
LOGICAL :: LQMHP
LOGICAL :: LQMPD
LOGICAL :: LQMHPD
LOGICAL :: LQMVD
LOGICAL :: LQMHVD
LOGICAL :: LVWENO_W, LVWENO_T, LVWENO_SP, LVWENO_SPD, LVWENO_SVD
REAL(KIND=8) :: WENO_ALPHA_W, WENO_ALPHA_T, WENO_ALPHA_SP, WENO_ALPHA_SPD, WENO_ALPHA_SVD
LOGICAL :: LADVF
LOGICAL :: LIMPF
LOGICAL :: L2TLFF
REAL(KIND=8) :: RCMSLP0
INTEGER(KIND=4) :: NCOMP_CVGQ
LOGICAL :: LSVTSM
REAL(KIND=8) :: RPRES_SVTSM
REAL(KIND=8) :: RPRES_SETTLSVF
INTEGER(KIND=4) :: NFLEVSF
REAL(KIND=8) :: RSCALE
REAL(KIND=8) :: RSCALEOFF
REAL(KIND=8) :: RINTOPT
REAL(KIND=8) :: RRINTOPT

LOGICAL :: LHDIFFM
LOGICAL :: LSPECVIS
INTEGER(KIND=4) :: NDIFFACT
LOGICAL :: LGPSTRESS
REAL(KIND=8) :: RCLSTRESS
REAL(KIND=8) :: RCLPOLE

INTEGER(KIND=4) :: NVSEPC, NVSEPL
LOGICAL ::      LFINDVSEP

LOGICAL         :: LMASCOR
LOGICAL         :: LMASDRY

LOGICAL         :: LGPMASCOR

INTEGER(KIND=4) :: NGPMASCOR

REAL(KIND=8) :: GPMASSI

REAL(KIND=8) :: GMASSI
REAL(KIND=8) :: GMASS0
REAL(KIND=8) :: GMASSINC

LOGICAL         :: LNODRYFLX

REAL(KIND=8), ALLOCATABLE :: SIBI(:,:)
REAL(KIND=8) :: RESGP 
REAL(KIND=8) :: RESGM 
LOGICAL :: LNHHY_SOLVER_GP, LNHHY_SOLVER_SP
LOGICAL :: LNHQE_SOLVER_GP, LNHQE_SOLVER_SP
LOGICAL :: LRESET_BLEND_SI
INTEGER(KIND=4) :: NSTOP_BLEND, NSTART_BLEND
REAL(KIND=8) :: RNHQE_DELTAM
REAL(KIND=8), ALLOCATABLE :: RNHHY_DELTAM(:)

!---------------------------------------------------------------------



END TYPE TDYN

CONTAINS

SUBROUTINE LOAD_TDYN (SELF)
IMPLICIT NONE
TYPE (TDYN), INTENT (OUT), TARGET :: SELF
INTEGER :: KLUN=77
INTEGER :: IL1(1), IU1(1), IL2(2), IU2(2), IL3(3), IU3(3), IL4(4), IU4(4)
LOGICAL :: LRCORDIF, LRCORDIH, LRCORDIT, LRDHI, LRDHIDIV, LRDHIGFL, LRDHINHX, LRDHIP, LRDHISPD, LRDHISVD
LOGICAL :: LRDHIT, LRDHIVOR, LRDHS, LRDHSDIV, LRDHSNHX, LRDHSSVD, LRDHSVOR, LRDIDIV, LRDIGFL, LRDIPD
LOGICAL :: LRDISP, LRDITG, LRDIVD, LRDIVOR, LRDSDIV, LRDSVD, LRDSVOR, LRGAMMA_WENO, LRGWFRIC, LRKRF
LOGICAL :: LRNHHY_DELTAM, LRSAVEDP, LSIALPH, LSIALPH_NH, LSIB, LSIBI, LSIBQ, LSIBQTRA, LSIDELP, LSIDELP_NH
LOGICAL :: LSIDPHI, LSIDPHI_NH, LSIFAC, LSIFACI, LSIFACITRA, LSIGFL, LSIGFM, LSIGHL, LSIGHM, LSIHEG
LOGICAL :: LSIHEG2, LSIHEG2TRA, LSIHEGB, LSIHEGB2, LSIHEGB2TRA, LSIHEGBTRA, LSIHEGIND, LSIHEGTRA, LSILAPDI, LSILAPIN
LOGICAL :: LSILNPR, LSILNPR_NH, LSIMI, LSIMITRA, LSIMO, LSIMOTRA, LSINISNAX, LSIPD, LSIPE, LSIPF
LOGICAL :: LSIPIS, LSIRDEL, LSIRDEL_NH, LSITAC, LSITFL, LSITFM, LSITGR, LSITLAF, LSITLAF_NH, LSITLAH
LOGICAL :: LSITLAH_NH, LSITRAM, LSITRM, LSIVP, LSIVP2, LSIWF2H, LSIWH2F, LSIZA, LSIZC, LSLHD_MASK_T
LOGICAL :: LSLHD_MASK_U
REAL(KIND=8) :: ZTMP0
REAL(KIND=8), ALLOCATABLE :: ZTMP1 (:)
REAL(KIND=8), ALLOCATABLE :: ZTMP2 (:,:)
REAL(KIND=8), ALLOCATABLE :: ZTMP3 (:,:,:)
REAL(KIND=8), ALLOCATABLE :: ZTMP4 (:,:,:,:)
OPEN (KLUN, FILE='TDYN.CONST.DAT', FORM='UNFORMATTED')
READ (KLUN) ZTMP0
SELF%REPS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSM1 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSM2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REPSP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRT = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRQ = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRPD = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%HDIRSP = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRT = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRQ = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRPD = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDIRSP = ZTMP0
READ (KLUN) ZTMP0
SELF%RRDXTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPT = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPQ = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPO3 = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPPD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPSP = ZTMP0
READ (KLUN) SELF%LNEWHD
READ (KLUN) ZTMP0
SELF%REXPDH = ZTMP0
READ (KLUN) ZTMP0
SELF%FRANDH = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH1 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH2 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDH3 = ZTMP0
READ (KLUN) SELF%NSREFDH
READ (KLUN) ZTMP0
SELF%RATIO_HDI_TOP = ZTMP0
READ (KLUN) SELF%NPROFILEHD
READ (KLUN) ZTMP0
SELF%RPROFHDBT = ZTMP0
READ (KLUN) ZTMP0
SELF%RPROFHDTP = ZTMP0
READ (KLUN) ZTMP0
SELF%RPROFHDMX = ZTMP0
READ (KLUN) ZTMP0
SELF%RPROFHDEX = ZTMP0
READ (KLUN) SELF%LRDISPE_EC
READ (KLUN) LRDIVOR
IF (LRDIVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIVOR,1):UBOUND(SELF%RDIVOR,1), LBOUND(SELF%RDIVOR,2):UBOUND(SELF%RDIVOR,2)))
  READ (KLUN) ZTMP2
  SELF%RDIVOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIDIV
IF (LRDIDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIDIV,1):UBOUND(SELF%RDIDIV,1), LBOUND(SELF%RDIDIV,2):UBOUND(SELF%RDIDIV,2)))
  READ (KLUN) ZTMP2
  SELF%RDIDIV = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDITG
IF (LRDITG) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDITG (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDITG,1):UBOUND(SELF%RDITG,1), LBOUND(SELF%RDITG,2):UBOUND(SELF%RDITG,2)))
  READ (KLUN) ZTMP2
  SELF%RDITG = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIGFL
IF (LRDIGFL) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDIGFL (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDIGFL,1):UBOUND(SELF%RDIGFL,1), LBOUND(SELF%RDIGFL,2):UBOUND(SELF%RDIGFL,2), LBOUND(SELF%RDIGFL,3):UBOUND(SELF%RDIGFL,3)))
  READ (KLUN) ZTMP3
  SELF%RDIGFL = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDIPD
IF (LRDIPD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIPD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIPD,1):UBOUND(SELF%RDIPD,1), LBOUND(SELF%RDIPD,2):UBOUND(SELF%RDIPD,2)))
  READ (KLUN) ZTMP2
  SELF%RDIPD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDIVD
IF (LRDIVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDIVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDIVD,1):UBOUND(SELF%RDIVD,1), LBOUND(SELF%RDIVD,2):UBOUND(SELF%RDIVD,2)))
  READ (KLUN) ZTMP2
  SELF%RDIVD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDISP
IF (LRDISP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RDISP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RDISP,1):UBOUND(SELF%RDISP,1)))
  READ (KLUN) ZTMP1
  SELF%RDISP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRDHI
IF (LRDHI) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHI (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHI,1):UBOUND(SELF%RDHI,1), LBOUND(SELF%RDHI,2):UBOUND(SELF%RDHI,2), LBOUND(SELF%RDHI,3):UBOUND(SELF%RDHI,3)))
  READ (KLUN) ZTMP3
  SELF%RDHI = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIVOR
IF (LRDHIVOR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIVOR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIVOR,1):UBOUND(SELF%RDHIVOR,1), LBOUND(SELF%RDHIVOR,2):UBOUND(SELF%RDHIVOR,2), LBOUND(SELF%RDHIVOR,3):UBOUND(SELF%RDHIVOR,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIVOR = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIDIV
IF (LRDHIDIV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIDIV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIDIV,1):UBOUND(SELF%RDHIDIV,1), LBOUND(SELF%RDHIDIV,2):UBOUND(SELF%RDHIDIV,2), LBOUND(SELF%RDHIDIV,3):UBOUND(SELF%RDHIDIV,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIDIV = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHISPD
IF (LRDHISPD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHISPD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHISPD,1):UBOUND(SELF%RDHISPD,1), LBOUND(SELF%RDHISPD,2):UBOUND(SELF%RDHISPD,2), LBOUND(SELF%RDHISPD,3):UBOUND(SELF%RDHISPD,3)))
  READ (KLUN) ZTMP3
  SELF%RDHISPD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHISVD
IF (LRDHISVD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHISVD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHISVD,1):UBOUND(SELF%RDHISVD,1), LBOUND(SELF%RDHISVD,2):UBOUND(SELF%RDHISVD,2), LBOUND(SELF%RDHISVD,3):UBOUND(SELF%RDHISVD,3)))
  READ (KLUN) ZTMP3
  SELF%RDHISVD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHINHX
IF (LRDHINHX) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHINHX (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHINHX,1):UBOUND(SELF%RDHINHX,1), LBOUND(SELF%RDHINHX,2):UBOUND(SELF%RDHINHX,2), LBOUND(SELF%RDHINHX,3):UBOUND(SELF%RDHINHX,3)))
  READ (KLUN) ZTMP3
  SELF%RDHINHX = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIT
IF (LRDHIT) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIT (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIT,1):UBOUND(SELF%RDHIT,1), LBOUND(SELF%RDHIT,2):UBOUND(SELF%RDHIT,2), LBOUND(SELF%RDHIT,3):UBOUND(SELF%RDHIT,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIT = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHIGFL
IF (LRDHIGFL) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%RDHIGFL (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%RDHIGFL,1):UBOUND(SELF%RDHIGFL,1), LBOUND(SELF%RDHIGFL,2):UBOUND(SELF%RDHIGFL,2), LBOUND(SELF%RDHIGFL,3):UBOUND(SELF%RDHIGFL,3), LBOUND(SELF%RDHIGFL,4):UBOUND(SELF%RDHIGFL,4)))
  READ (KLUN) ZTMP4
  SELF%RDHIGFL = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) LRDHIP
IF (LRDHIP) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHIP (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHIP,1):UBOUND(SELF%RDHIP,1), LBOUND(SELF%RDHIP,2):UBOUND(SELF%RDHIP,2), LBOUND(SELF%RDHIP,3):UBOUND(SELF%RDHIP,3)))
  READ (KLUN) ZTMP3
  SELF%RDHIP = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSVOR
IF (LRDHSVOR) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSVOR (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSVOR,1):UBOUND(SELF%RDHSVOR,1), LBOUND(SELF%RDHSVOR,2):UBOUND(SELF%RDHSVOR,2), LBOUND(SELF%RDHSVOR,3):UBOUND(SELF%RDHSVOR,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSVOR = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSDIV
IF (LRDHSDIV) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSDIV (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSDIV,1):UBOUND(SELF%RDHSDIV,1), LBOUND(SELF%RDHSDIV,2):UBOUND(SELF%RDHSDIV,2), LBOUND(SELF%RDHSDIV,3):UBOUND(SELF%RDHSDIV,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSDIV = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSSVD
IF (LRDHSSVD) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSSVD (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSSVD,1):UBOUND(SELF%RDHSSVD,1), LBOUND(SELF%RDHSSVD,2):UBOUND(SELF%RDHSSVD,2), LBOUND(SELF%RDHSSVD,3):UBOUND(SELF%RDHSSVD,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSSVD = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LRDHSNHX
IF (LRDHSNHX) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHSNHX (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHSNHX,1):UBOUND(SELF%RDHSNHX,1), LBOUND(SELF%RDHSNHX,2):UBOUND(SELF%RDHSNHX,2), LBOUND(SELF%RDHSNHX,3):UBOUND(SELF%RDHSNHX,3)))
  READ (KLUN) ZTMP3
  SELF%RDHSNHX = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) SELF%LSTRHD
READ (KLUN) ZTMP0
SELF%HDTIME_STRHD = ZTMP0
READ (KLUN) ZTMP0
SELF%KLSPONGE = ZTMP0
READ (KLUN) SELF%LM0DAMP
READ (KLUN) ZTMP0
SELF%RBEGSPONGE = ZTMP0
READ (KLUN) SELF%LTOP_VOR
READ (KLUN) SELF%NTOP_VOR_TRUNC
READ (KLUN) SELF%NTOP_VOR_BOT
READ (KLUN) LRSAVEDP
IF (LRSAVEDP) THEN
  READ (KLUN) IL4
  READ (KLUN) IU4
  ALLOCATE (SELF%RSAVEDP (IL4(1):IU4(1), IL4(2):IU4(2), IL4(3):IU4(3), IL4(4):IU4(4)))
  ALLOCATE (ZTMP4(LBOUND(SELF%RSAVEDP,1):UBOUND(SELF%RSAVEDP,1), LBOUND(SELF%RSAVEDP,2):UBOUND(SELF%RSAVEDP,2), LBOUND(SELF%RSAVEDP,3):UBOUND(SELF%RSAVEDP,3), LBOUND(SELF%RSAVEDP,4):UBOUND(SELF%RSAVEDP,4)))
  READ (KLUN) ZTMP4
  SELF%RSAVEDP = ZTMP4
  DEALLOCATE (ZTMP4)
ENDIF
READ (KLUN) ZTMP0
SELF%SLHDA0 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDA0T = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDB = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDBT = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDD00 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDD00T = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDRATDDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHDHOR = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHD_P_LOW = ZTMP0
READ (KLUN) ZTMP0
SELF%SLHD_P_HIGH = ZTMP0
READ (KLUN) SELF%LSLHDHEAT
READ (KLUN) SELF%LSLHDSPONGE
READ (KLUN) ZTMP0
SELF%HDSRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HDSRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HDSRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDSRVOR = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDSRDIV = ZTMP0
READ (KLUN) ZTMP0
SELF%HRDSRVD = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVORS = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPDIVS = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPVDS = ZTMP0
READ (KLUN) ZTMP0
SELF%RDAMPHDS = ZTMP0
READ (KLUN) ZTMP0
SELF%REXPDHS = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDHS = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDHS1 = ZTMP0
READ (KLUN) ZTMP0
SELF%SLEVDHS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%SDRED = ZTMP0
READ (KLUN) LRDSVOR
IF (LRDSVOR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDSVOR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDSVOR,1):UBOUND(SELF%RDSVOR,1), LBOUND(SELF%RDSVOR,2):UBOUND(SELF%RDSVOR,2)))
  READ (KLUN) ZTMP2
  SELF%RDSVOR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDSDIV
IF (LRDSDIV) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDSDIV (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDSDIV,1):UBOUND(SELF%RDSDIV,1), LBOUND(SELF%RDSDIV,2):UBOUND(SELF%RDSDIV,2)))
  READ (KLUN) ZTMP2
  SELF%RDSDIV = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDSVD
IF (LRDSVD) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%RDSVD (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%RDSVD,1):UBOUND(SELF%RDSVD,1), LBOUND(SELF%RDSVD,2):UBOUND(SELF%RDSVD,2)))
  READ (KLUN) ZTMP2
  SELF%RDSVD = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LRDHS
IF (LRDHS) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%RDHS (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%RDHS,1):UBOUND(SELF%RDHS,1), LBOUND(SELF%RDHS,2):UBOUND(SELF%RDHS,2), LBOUND(SELF%RDHS,3):UBOUND(SELF%RDHS,3)))
  READ (KLUN) ZTMP3
  SELF%RDHS = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSLHD_MASK_U
IF (LSLHD_MASK_U) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SLHD_MASK_U (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SLHD_MASK_U,1):UBOUND(SELF%SLHD_MASK_U,1)))
  READ (KLUN) ZTMP1
  SELF%SLHD_MASK_U = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSLHD_MASK_T
IF (LSLHD_MASK_T) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SLHD_MASK_T (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SLHD_MASK_T,1):UBOUND(SELF%SLHD_MASK_T,1)))
  READ (KLUN) ZTMP1
  SELF%SLHD_MASK_T = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%ZSLHDP1 = ZTMP0
READ (KLUN) ZTMP0
SELF%ZSLHDP3 = ZTMP0
READ (KLUN) SELF%NLEV_SPONGE
READ (KLUN) SELF%LRFRIC
READ (KLUN) SELF%LRFRICISOTR
READ (KLUN) LRCORDIT
IF (LRCORDIT) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCORDIT (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RCORDIT,1):UBOUND(SELF%RCORDIT,1)))
  READ (KLUN) ZTMP1
  SELF%RCORDIT = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCORDIH
IF (LRCORDIH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCORDIH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RCORDIH,1):UBOUND(SELF%RCORDIH,1)))
  READ (KLUN) ZTMP1
  SELF%RCORDIH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LRCORDIF
IF (LRCORDIF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RCORDIF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RCORDIF,1):UBOUND(SELF%RCORDIF,1)))
  READ (KLUN) ZTMP1
  SELF%RCORDIF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%VMAX1 = ZTMP0
READ (KLUN) ZTMP0
SELF%VMAX2 = ZTMP0
READ (KLUN) ZTMP0
SELF%RMAX_D3 = ZTMP0
READ (KLUN) SELF%LBOUND_D3
READ (KLUN) LRKRF
IF (LRKRF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RKRF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RKRF,1):UBOUND(SELF%RKRF,1)))
  READ (KLUN) ZTMP1
  SELF%RKRF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) SELF%NMAXLEVRF
READ (KLUN) ZTMP0
SELF%RRFZ1 = ZTMP0
READ (KLUN) ZTMP0
SELF%RRFPLM = ZTMP0
READ (KLUN) ZTMP0
SELF%RRFTAU = ZTMP0
READ (KLUN) ZTMP0
SELF%RTEMRB = ZTMP0
READ (KLUN) SELF%NRUBC
READ (KLUN) SELF%LGWFRIC
READ (KLUN) SELF%NLEV_GWFRIC
READ (KLUN) ZTMP0
SELF%RGWFRIC_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%RGWFRIC_PLM = ZTMP0
READ (KLUN) LRGWFRIC
IF (LRGWFRIC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RGWFRIC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RGWFRIC,1):UBOUND(SELF%RGWFRIC,1)))
  READ (KLUN) ZTMP1
  SELF%RGWFRIC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) SELF%LSIDG
READ (KLUN) SELF%LDYN_STABAN
READ (KLUN) SELF%LRHDI_LASTITERPC
READ (KLUN) SELF%LSIDYN_VERBOSE
READ (KLUN) ZTMP0
SELF%BETADT = ZTMP0
READ (KLUN) ZTMP0
SELF%RBT = ZTMP0
READ (KLUN) ZTMP0
SELF%RBTS2 = ZTMP0
READ (KLUN) ZTMP0
SELF%REFGEO = ZTMP0
READ (KLUN) ZTMP0
SELF%SIPR = ZTMP0
READ (KLUN) ZTMP0
SELF%SIPRA = ZTMP0
READ (KLUN) ZTMP0
SELF%SITR = ZTMP0
READ (KLUN) ZTMP0
SELF%SITRA = ZTMP0
READ (KLUN) ZTMP0
SELF%SITRUB = ZTMP0
READ (KLUN) ZTMP0
SELF%SIPRUB = ZTMP0
READ (KLUN) ZTMP0
SELF%SITIME = ZTMP0
READ (KLUN) ZTMP0
SELF%SIRPRG = ZTMP0
READ (KLUN) ZTMP0
SELF%SIRPRN = ZTMP0
READ (KLUN) ZTMP0
SELF%SISLP = ZTMP0
READ (KLUN) ZTMP0
SELF%SIFRG = ZTMP0
READ (KLUN) ZTMP0
SELF%SIFRA = ZTMP0
READ (KLUN) ZTMP0
SELF%SITVAR = ZTMP0
READ (KLUN) SELF%NSITER
READ (KLUN) SELF%NCURRENT_ITER
READ (KLUN) SELF%NITERHELM
READ (KLUN) SELF%NOPT_SITR
READ (KLUN) SELF%NOPT_SIPR
READ (KLUN) SELF%NOPT_SISLP
READ (KLUN) SELF%NSZNISNAX
READ (KLUN) LSITRAM
IF (LSITRAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITRAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITRAM,1):UBOUND(SELF%SITRAM,1)))
  READ (KLUN) ZTMP1
  SELF%SITRAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITRM
IF (LSITRM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITRM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITRM,1):UBOUND(SELF%SITRM,1)))
  READ (KLUN) ZTMP1
  SELF%SITRM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIALPH
IF (LSIALPH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIALPH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIALPH,1):UBOUND(SELF%SIALPH,1)))
  READ (KLUN) ZTMP1
  SELF%SIALPH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILNPR
IF (LSILNPR) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SILNPR (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SILNPR,1):UBOUND(SELF%SILNPR,1)))
  READ (KLUN) ZTMP1
  SELF%SILNPR = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDELP
IF (LSIDELP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDELP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDELP,1):UBOUND(SELF%SIDELP,1)))
  READ (KLUN) ZTMP1
  SELF%SIDELP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIRDEL
IF (LSIRDEL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIRDEL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIRDEL,1):UBOUND(SELF%SIRDEL,1)))
  READ (KLUN) ZTMP1
  SELF%SIRDEL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAH
IF (LSITLAH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAH,1):UBOUND(SELF%SITLAH,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAF
IF (LSITLAF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAF,1):UBOUND(SELF%SITLAF,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDPHI
IF (LSIDPHI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDPHI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDPHI,1):UBOUND(SELF%SIDPHI,1)))
  READ (KLUN) ZTMP1
  SELF%SIDPHI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIALPH_NH
IF (LSIALPH_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIALPH_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIALPH_NH,1):UBOUND(SELF%SIALPH_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIALPH_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILNPR_NH
IF (LSILNPR_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SILNPR_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SILNPR_NH,1):UBOUND(SELF%SILNPR_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SILNPR_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDELP_NH
IF (LSIDELP_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDELP_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDELP_NH,1):UBOUND(SELF%SIDELP_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIDELP_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIRDEL_NH
IF (LSIRDEL_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIRDEL_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIRDEL_NH,1):UBOUND(SELF%SIRDEL_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIRDEL_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAH_NH
IF (LSITLAH_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAH_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAH_NH,1):UBOUND(SELF%SITLAH_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAH_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITLAF_NH
IF (LSITLAF_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITLAF_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITLAF_NH,1):UBOUND(SELF%SITLAF_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SITLAF_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIDPHI_NH
IF (LSIDPHI_NH) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIDPHI_NH (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIDPHI_NH,1):UBOUND(SELF%SIDPHI_NH,1)))
  READ (KLUN) ZTMP1
  SELF%SIDPHI_NH = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIWF2H
IF (LSIWF2H) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIWF2H (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIWF2H,1):UBOUND(SELF%SIWF2H,1)))
  READ (KLUN) ZTMP1
  SELF%SIWF2H = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIWH2F
IF (LSIWH2F) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIWH2F (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIWH2F,1):UBOUND(SELF%SIWH2F,1), LBOUND(SELF%SIWH2F,2):UBOUND(SELF%SIWH2F,2)))
  READ (KLUN) ZTMP2
  SELF%SIWH2F = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIGFL
IF (LSIGFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGFL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGFL,1):UBOUND(SELF%SIGFL,1)))
  READ (KLUN) ZTMP1
  SELF%SIGFL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGFM
IF (LSIGFM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGFM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGFM,1):UBOUND(SELF%SIGFM,1)))
  READ (KLUN) ZTMP1
  SELF%SIGFM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITFL
IF (LSITFL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITFL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITFL,1):UBOUND(SELF%SITFL,1)))
  READ (KLUN) ZTMP1
  SELF%SITFL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITFM
IF (LSITFM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITFM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITFM,1):UBOUND(SELF%SITFM,1)))
  READ (KLUN) ZTMP1
  SELF%SITFM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGHL
IF (LSIGHL) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGHL (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGHL,1):UBOUND(SELF%SIGHL,1)))
  READ (KLUN) ZTMP1
  SELF%SIGHL = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIGHM
IF (LSIGHM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIGHM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIGHM,1):UBOUND(SELF%SIGHM,1)))
  READ (KLUN) ZTMP1
  SELF%SIGHM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIB
IF (LSIB) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIB (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIB,1):UBOUND(SELF%SIB,1), LBOUND(SELF%SIB,2):UBOUND(SELF%SIB,2)))
  READ (KLUN) ZTMP2
  SELF%SIB = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMO
IF (LSIMO) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMO (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMO,1):UBOUND(SELF%SIMO,1), LBOUND(SELF%SIMO,2):UBOUND(SELF%SIMO,2)))
  READ (KLUN) ZTMP2
  SELF%SIMO = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMI
IF (LSIMI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMI,1):UBOUND(SELF%SIMI,1), LBOUND(SELF%SIMI,2):UBOUND(SELF%SIMI,2)))
  READ (KLUN) ZTMP2
  SELF%SIMI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIVP
IF (LSIVP) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIVP (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIVP,1):UBOUND(SELF%SIVP,1)))
  READ (KLUN) ZTMP1
  SELF%SIVP = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIVP2
IF (LSIVP2) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIVP2 (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIVP2,1):UBOUND(SELF%SIVP2,1)))
  READ (KLUN) ZTMP1
  SELF%SIVP2 = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIPD
IF (LSIPD) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIPD (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIPD,1):UBOUND(SELF%SIPD,1)))
  READ (KLUN) ZTMP1
  SELF%SIPD = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIPE
IF (LSIPE) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIPE (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIPE,1):UBOUND(SELF%SIPE,1)))
  READ (KLUN) ZTMP1
  SELF%SIPE = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIPF
IF (LSIPF) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIPF (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIPF,1):UBOUND(SELF%SIPF,1)))
  READ (KLUN) ZTMP1
  SELF%SIPF = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSINISNAX
IF (LSINISNAX) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SINISNAX (IL1(1):IU1(1)))
  READ (KLUN) SELF%SINISNAX
ENDIF
READ (KLUN) LSILAPDI
IF (LSILAPDI) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SILAPDI (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SILAPDI,1):UBOUND(SELF%SILAPDI,1)))
  READ (KLUN) ZTMP1
  SELF%SILAPDI = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSILAPIN
IF (LSILAPIN) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SILAPIN (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SILAPIN,1):UBOUND(SELF%SILAPIN,1)))
  READ (KLUN) ZTMP1
  SELF%SILAPIN = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIHEG
IF (LSIHEG) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEG (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEG,1):UBOUND(SELF%SIHEG,1), LBOUND(SELF%SIHEG,2):UBOUND(SELF%SIHEG,2), LBOUND(SELF%SIHEG,3):UBOUND(SELF%SIHEG,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEG = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEG2
IF (LSIHEG2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEG2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEG2,1):UBOUND(SELF%SIHEG2,1), LBOUND(SELF%SIHEG2,2):UBOUND(SELF%SIHEG2,2), LBOUND(SELF%SIHEG2,3):UBOUND(SELF%SIHEG2,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEG2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGB
IF (LSIHEGB) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEGB (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEGB,1):UBOUND(SELF%SIHEGB,1), LBOUND(SELF%SIHEGB,2):UBOUND(SELF%SIHEGB,2), LBOUND(SELF%SIHEGB,3):UBOUND(SELF%SIHEGB,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEGB = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGB2
IF (LSIHEGB2) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEGB2 (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEGB2,1):UBOUND(SELF%SIHEGB2,1), LBOUND(SELF%SIHEGB2,2):UBOUND(SELF%SIHEGB2,2), LBOUND(SELF%SIHEGB2,3):UBOUND(SELF%SIHEGB2,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEGB2 = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIFAC
IF (LSIFAC) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIFAC (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIFAC,1):UBOUND(SELF%SIFAC,1), LBOUND(SELF%SIFAC,2):UBOUND(SELF%SIFAC,2)))
  READ (KLUN) ZTMP2
  SELF%SIFAC = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIFACI
IF (LSIFACI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIFACI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIFACI,1):UBOUND(SELF%SIFACI,1), LBOUND(SELF%SIFACI,2):UBOUND(SELF%SIFACI,2)))
  READ (KLUN) ZTMP2
  SELF%SIFACI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIBQ
IF (LSIBQ) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIBQ (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIBQ,1):UBOUND(SELF%SIBQ,1), LBOUND(SELF%SIBQ,2):UBOUND(SELF%SIBQ,2)))
  READ (KLUN) ZTMP2
  SELF%SIBQ = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMITRA
IF (LSIMITRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMITRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMITRA,1):UBOUND(SELF%SIMITRA,1), LBOUND(SELF%SIMITRA,2):UBOUND(SELF%SIMITRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIMITRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIMOTRA
IF (LSIMOTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIMOTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIMOTRA,1):UBOUND(SELF%SIMOTRA,1), LBOUND(SELF%SIMOTRA,2):UBOUND(SELF%SIMOTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIMOTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIFACITRA
IF (LSIFACITRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIFACITRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIFACITRA,1):UBOUND(SELF%SIFACITRA,1), LBOUND(SELF%SIFACITRA,2):UBOUND(SELF%SIFACITRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIFACITRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIHEGTRA
IF (LSIHEGTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIHEGTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIHEGTRA,1):UBOUND(SELF%SIHEGTRA,1), LBOUND(SELF%SIHEGTRA,2):UBOUND(SELF%SIHEGTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIHEGTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIHEG2TRA
IF (LSIHEG2TRA) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEG2TRA (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEG2TRA,1):UBOUND(SELF%SIHEG2TRA,1), LBOUND(SELF%SIHEG2TRA,2):UBOUND(SELF%SIHEG2TRA,2), LBOUND(SELF%SIHEG2TRA,3):UBOUND(SELF%SIHEG2TRA,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEG2TRA = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGBTRA
IF (LSIHEGBTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIHEGBTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIHEGBTRA,1):UBOUND(SELF%SIHEGBTRA,1), LBOUND(SELF%SIHEGBTRA,2):UBOUND(SELF%SIHEGBTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIHEGBTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIHEGB2TRA
IF (LSIHEGB2TRA) THEN
  READ (KLUN) IL3
  READ (KLUN) IU3
  ALLOCATE (SELF%SIHEGB2TRA (IL3(1):IU3(1), IL3(2):IU3(2), IL3(3):IU3(3)))
  ALLOCATE (ZTMP3(LBOUND(SELF%SIHEGB2TRA,1):UBOUND(SELF%SIHEGB2TRA,1), LBOUND(SELF%SIHEGB2TRA,2):UBOUND(SELF%SIHEGB2TRA,2), LBOUND(SELF%SIHEGB2TRA,3):UBOUND(SELF%SIHEGB2TRA,3)))
  READ (KLUN) ZTMP3
  SELF%SIHEGB2TRA = ZTMP3
  DEALLOCATE (ZTMP3)
ENDIF
READ (KLUN) LSIHEGIND
IF (LSIHEGIND) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIHEGIND (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIHEGIND,1):UBOUND(SELF%SIHEGIND,1)))
  READ (KLUN) ZTMP1
  SELF%SIHEGIND = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIBQTRA
IF (LSIBQTRA) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIBQTRA (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIBQTRA,1):UBOUND(SELF%SIBQTRA,1), LBOUND(SELF%SIBQTRA,2):UBOUND(SELF%SIBQTRA,2)))
  READ (KLUN) ZTMP2
  SELF%SIBQTRA = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSIZA
IF (LSIZA) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIZA (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIZA,1):UBOUND(SELF%SIZA,1)))
  READ (KLUN) ZTMP1
  SELF%SIZA = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIZC
IF (LSIZC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIZC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIZC,1):UBOUND(SELF%SIZC,1)))
  READ (KLUN) ZTMP1
  SELF%SIZC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSIPIS
IF (LSIPIS) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SIPIS (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SIPIS,1):UBOUND(SELF%SIPIS,1)))
  READ (KLUN) ZTMP1
  SELF%SIPIS = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) LSITGR
IF (LSITGR) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SITGR (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SITGR,1):UBOUND(SELF%SITGR,1), LBOUND(SELF%SITGR,2):UBOUND(SELF%SITGR,2)))
  READ (KLUN) ZTMP2
  SELF%SITGR = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) LSITAC
IF (LSITAC) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%SITAC (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%SITAC,1):UBOUND(SELF%SITAC,1)))
  READ (KLUN) ZTMP1
  SELF%SITAC = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
READ (KLUN) ZTMP0
SELF%VNORM = ZTMP0
READ (KLUN) ZTMP0
SELF%SLOPE_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%PSURF_MAX = ZTMP0
READ (KLUN) ZTMP0
SELF%PSURF_MIN = ZTMP0
READ (KLUN) SELF%NVLAG
READ (KLUN) SELF%NWLAG
READ (KLUN) SELF%NTLAG
READ (KLUN) SELF%NSPDLAG
READ (KLUN) SELF%NSVDLAG
READ (KLUN) SELF%NSPLTHOI
READ (KLUN) SELF%LSPLTHOIGFL
READ (KLUN) SELF%NSLDIMK
READ (KLUN) SELF%NITMP
READ (KLUN) ZTMP0
SELF%VETAON = ZTMP0
READ (KLUN) ZTMP0
SELF%VETAOX = ZTMP0
READ (KLUN) SELF%LSETTLSVF
READ (KLUN) SELF%LSETFSTAT
READ (KLUN) SELF%LSETTLSVF_DIFF
READ (KLUN) ZTMP0
SELF%RW2TLFF = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPHA = ZTMP0
READ (KLUN) ZTMP0
SELF%RALPHA_TOP = ZTMP0
READ (KLUN) SELF%NLEV_ZALPHA
READ (KLUN) SELF%NEDER
ALLOCATE (ZTMP2(LBOUND(SELF%RBETAK,1):UBOUND(SELF%RBETAK,1), LBOUND(SELF%RBETAK,2):UBOUND(SELF%RBETAK,2)))
READ (KLUN) ZTMP2
SELF%RBETAK = ZTMP2
DEALLOCATE (ZTMP2)
READ (KLUN) SELF%LWENOBC
READ (KLUN) SELF%NQMHOISLT
READ (KLUN) SELF%LSLDP_RK
READ (KLUN) SELF%LSLDP_CURV
READ (KLUN) SELF%LSLDP_CURV_FIX
READ (KLUN) SELF%LRHS_CURV
READ (KLUN) SELF%LRHS_CURV_FIX
READ (KLUN) SELF%LSLDP_XYZ
READ (KLUN) SELF%LSLDP_SAVE
READ (KLUN) ZTMP0
SELF%VESL = ZTMP0
READ (KLUN) ZTMP0
SELF%XIDT = ZTMP0
READ (KLUN) SELF%LQMW
READ (KLUN) SELF%LQMHW
READ (KLUN) SELF%LQMT
READ (KLUN) SELF%LQMHT
READ (KLUN) SELF%LQMP
READ (KLUN) SELF%LQMHP
READ (KLUN) SELF%LQMPD
READ (KLUN) SELF%LQMHPD
READ (KLUN) SELF%LQMVD
READ (KLUN) SELF%LQMHVD
READ (KLUN) SELF%LVWENO_W
READ (KLUN) SELF%LVWENO_T
READ (KLUN) SELF%LVWENO_SP
READ (KLUN) SELF%LVWENO_SPD
READ (KLUN) SELF%LVWENO_SVD
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_W = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_T = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_SP = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_SPD = ZTMP0
READ (KLUN) ZTMP0
SELF%WENO_ALPHA_SVD = ZTMP0
READ (KLUN) SELF%LADVF
READ (KLUN) SELF%LIMPF
READ (KLUN) SELF%L2TLFF
READ (KLUN) ZTMP0
SELF%RCMSLP0 = ZTMP0
READ (KLUN) SELF%NCOMP_CVGQ
READ (KLUN) SELF%LSVTSM
READ (KLUN) ZTMP0
SELF%RPRES_SVTSM = ZTMP0
READ (KLUN) ZTMP0
SELF%RPRES_SETTLSVF = ZTMP0
READ (KLUN) SELF%NFLEVSF
READ (KLUN) ZTMP0
SELF%RSCALE = ZTMP0
READ (KLUN) ZTMP0
SELF%RSCALEOFF = ZTMP0
READ (KLUN) ZTMP0
SELF%RINTOPT = ZTMP0
READ (KLUN) ZTMP0
SELF%RRINTOPT = ZTMP0
READ (KLUN) SELF%LHDIFFM
READ (KLUN) SELF%LSPECVIS
READ (KLUN) SELF%NDIFFACT
READ (KLUN) SELF%LGPSTRESS
READ (KLUN) ZTMP0
SELF%RCLSTRESS = ZTMP0
READ (KLUN) ZTMP0
SELF%RCLPOLE = ZTMP0
READ (KLUN) SELF%NVSEPC
READ (KLUN) SELF%NVSEPL
READ (KLUN) SELF%LFINDVSEP
READ (KLUN) SELF%LMASCOR
READ (KLUN) SELF%LMASDRY
READ (KLUN) SELF%LGPMASCOR
READ (KLUN) SELF%NGPMASCOR
READ (KLUN) ZTMP0
SELF%GPMASSI = ZTMP0
READ (KLUN) ZTMP0
SELF%GMASSI = ZTMP0
READ (KLUN) ZTMP0
SELF%GMASS0 = ZTMP0
READ (KLUN) ZTMP0
SELF%GMASSINC = ZTMP0
READ (KLUN) SELF%LNODRYFLX
READ (KLUN) LSIBI
IF (LSIBI) THEN
  READ (KLUN) IL2
  READ (KLUN) IU2
  ALLOCATE (SELF%SIBI (IL2(1):IU2(1), IL2(2):IU2(2)))
  ALLOCATE (ZTMP2(LBOUND(SELF%SIBI,1):UBOUND(SELF%SIBI,1), LBOUND(SELF%SIBI,2):UBOUND(SELF%SIBI,2)))
  READ (KLUN) ZTMP2
  SELF%SIBI = ZTMP2
  DEALLOCATE (ZTMP2)
ENDIF
READ (KLUN) ZTMP0
SELF%RESGP = ZTMP0
READ (KLUN) ZTMP0
SELF%RESGM = ZTMP0
READ (KLUN) SELF%LNHHY_SOLVER_GP
READ (KLUN) SELF%LNHHY_SOLVER_SP
READ (KLUN) SELF%LNHQE_SOLVER_GP
READ (KLUN) SELF%LNHQE_SOLVER_SP
READ (KLUN) SELF%LRESET_BLEND_SI
READ (KLUN) SELF%NSTOP_BLEND
READ (KLUN) SELF%NSTART_BLEND
READ (KLUN) ZTMP0
SELF%RNHQE_DELTAM = ZTMP0
READ (KLUN) LRNHHY_DELTAM
IF (LRNHHY_DELTAM) THEN
  READ (KLUN) IL1
  READ (KLUN) IU1
  ALLOCATE (SELF%RNHHY_DELTAM (IL1(1):IU1(1)))
  ALLOCATE (ZTMP1(LBOUND(SELF%RNHHY_DELTAM,1):UBOUND(SELF%RNHHY_DELTAM,1)))
  READ (KLUN) ZTMP1
  SELF%RNHHY_DELTAM = ZTMP1
  DEALLOCATE (ZTMP1)
ENDIF
CLOSE (KLUN)
END SUBROUTINE LOAD_TDYN



END MODULE YOMDYN

