PROGRAM MAIN_ACDRAG  

USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

INTERFACE
SUBROUTINE ACDRAG_OPENACC 
!$OMP DECLARE TARGET
IMPLICIT NONE
END SUBROUTINE ACDRAG_OPENACC
END INTERFACE

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MAIN_ACDRAG',0,ZHOOK_HANDLE)

END PROGRAM MAIN_ACDRAG
