INTERFACE

SUBROUTINE ACDRAG_MANYBLOCKS ( KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, PDELP, PRDELP, KGPBLKS)
IMPLICIT NONE
INTEGER , INTENT (IN)::KLON
INTEGER , INTENT (IN)::KLEV
INTEGER , INTENT (IN)::KIDIA
INTEGER , INTENT (IN)::KFDIA
INTEGER , INTENT (IN)::KTDIA
REAL (KIND=8), INTENT (IN)::PDELP (:, :, :)
REAL (KIND=8), INTENT (IN)::PRDELP (:, :, :)
INTEGER, INTENT (IN) :: KGPBLKS
END SUBROUTINE ACDRAG_MANYBLOCKS

END INTERFACE
