
SUBROUTINE ACDRAG_MANYBLOCKS ( KIDIA, KFDIA, KLON, KTDIA&
&, KLEV, PDELP, PRDELP, KGPBLKS)
USE FXTRAN_ACDC_STACK_MOD

IMPLICIT NONE



INTEGER , INTENT (IN)::KLON  
INTEGER , INTENT (IN)::KLEV
INTEGER , INTENT (IN)::KIDIA
INTEGER , INTENT (IN)::KFDIA
INTEGER , INTENT (IN)::KTDIA
REAL (KIND=8), INTENT (IN)::PDELP (:, :, :) ! (KLON, KLEV)
REAL (KIND=8), INTENT (IN)::PRDELP (:, :, :) ! (KLON, KLEV)
INTEGER, INTENT (IN) :: KGPBLKS  

REAL(KIND=8) , DIMENSION (KLON,0:KLEV,KGPBLKS) :: ZWGHT 
POINTER (IP_ZWGHT_,ZWGHT)
REAL(KIND=8) , DIMENSION (KLON,KLEV,KGPBLKS) :: ZPOID 
POINTER (IP_ZPOID_,ZPOID)
REAL(KIND=8) , DIMENSION (KLON,KLEV,KGPBLKS) :: ZIPOI 
POINTER (IP_ZIPOI_,ZIPOI)

INTEGER :: JLON
INTEGER :: JLEV
INTEGER :: JBLK 

TYPE(FXTRAN_ACDC_STACK) :: YLSTACK

!$OMP TARGET DATA  &
!$OMP & MAP (TO: PDELP, PRDELP)

YLSTACK=FXTRAN_ACDC_STACK(0,0,0,0)
CALL FXTRAN_ACDC_STACK_INIT(YLSTACK,YFXTRAN_ACDC_STACK,1,1)

IP_ZWGHT_=YLSTACK%L8
YLSTACK%L8=YLSTACK%L8+8*SIZE(ZWGHT,KIND=8)
IF (YLSTACK%L8>YLSTACK%U8) WRITE (0,*) "ACDC_ABORT : ZWGHT"

IP_ZPOID_=YLSTACK%L8
YLSTACK%L8=YLSTACK%L8+8*SIZE(ZPOID,KIND=8)
IF (YLSTACK%L8>YLSTACK%U8)  WRITE (0,*) "ACDC_ABORT : ZPOID"

IP_ZIPOI_=YLSTACK%L8
YLSTACK%L8=YLSTACK%L8+8*SIZE(ZIPOI,KIND=8)
IF (YLSTACK%L8>YLSTACK%U8)  WRITE (0,*) "ACDC_ABORT : ZIPOI"

!$OMP TARGET DATA  &
!$OMP & MAP (TO:  ZIPOI, ZPOID, ZWGHT )

PRINT *, " KERNEL 1 "

!$OMP TARGET TEAMS DISTRIBUTE  &
!$OMP & PRIVATE (JBLK)  &
!$OMP & THREAD_LIMIT (KLON) 

DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD  &
  !$OMP & PRIVATE (JLEV, JLON) 

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZPOID (JLON, JLEV, JBLK)=PDELP (JLON, JLEV, JBLK)
  
    ENDDO

  ENDDO
!$OMP END PARALLEL DO SIMD
ENDDO
!$OMP END TARGET TEAMS DISTRIBUTE

PRINT *, " KERNEL 2 "

!$OMP TARGET TEAMS DISTRIBUTE  &
!$OMP & PRIVATE (JBLK)  &
!$OMP & THREAD_LIMIT (KLON) 

DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD  &
  !$OMP & PRIVATE (JLEV, JLON) 

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZIPOI (JLON, JLEV, JBLK)=PRDELP (JLON, JLEV, JBLK)
  
    ENDDO

  ENDDO
!$OMP END PARALLEL DO SIMD
ENDDO
!$OMP END TARGET TEAMS DISTRIBUTE

PRINT *, " KERNEL 3 "

!$OMP TARGET TEAMS DISTRIBUTE  &
!$OMP & PRIVATE (JBLK)  &
!$OMP & THREAD_LIMIT (KLON) 

DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD  &
  !$OMP & PRIVATE (JLEV, JLON) 

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZWGHT (JLON, JLEV, JBLK)=0.0
  
    ENDDO

  ENDDO
!$OMP END PARALLEL DO SIMD
ENDDO
!$OMP END TARGET TEAMS DISTRIBUTE

PRINT *, " KERNEL 1&2&3 "

!$OMP TARGET TEAMS DISTRIBUTE  &
!$OMP & PRIVATE (JBLK)  &
!$OMP & THREAD_LIMIT (KLON) 

DO JBLK = 1, KGPBLKS
  
  !$OMP PARALLEL DO SIMD  &
  !$OMP & PRIVATE (JLEV, JLON) 

  DO JLON = KIDIA, MERGE (KLON, KFDIA, JBLK < KGPBLKS)

    DO JLEV=KTDIA, KLEV
      
      ZPOID (JLON, JLEV, JBLK)=PDELP (JLON, JLEV, JBLK)
      ZIPOI (JLON, JLEV, JBLK)=PRDELP (JLON, JLEV, JBLK)
      ZWGHT (JLON, JLEV, JBLK)=0.0
  
    ENDDO

  ENDDO
!$OMP END PARALLEL DO SIMD
ENDDO
!$OMP END TARGET TEAMS DISTRIBUTE

!$OMP END TARGET DATA

!$OMP END TARGET DATA

PRINT *, " END OF KERNELS "

END SUBROUTINE ACDRAG_MANYBLOCKS
