MODULE FXTRAN_ACDC_STACK_MOD

!
! Copyright 2025 Meteo-France
! All rights reserved
! philippe.marguinaud@meteo.fr
!

IMPLICIT NONE

INTEGER, PARAMETER :: JPIA = 8, JPIB = 8

TYPE FXTRAN_ACDC_STACK_DATA
  REAL (KIND=4), POINTER :: ZDATA4 (:,:,:,:)
  REAL (KIND=8), POINTER :: ZDATA8 (:,:,:,:)
  INTEGER (KIND=JPIB) :: IALIGN
END TYPE

TYPE FXTRAN_ACDC_STACK
  INTEGER (KIND=JPIA) :: L4
  INTEGER (KIND=JPIA) :: U4
  INTEGER (KIND=JPIA) :: L8
  INTEGER (KIND=JPIA) :: U8
END TYPE

TYPE (FXTRAN_ACDC_STACK_DATA) :: YFXTRAN_ACDC_STACK

PRIVATE
PUBLIC :: FXTRAN_ACDC_STACK, YFXTRAN_ACDC_STACK, FXTRAN_ACDC_STACK_INIT

CONTAINS

SUBROUTINE FXTRAN_ACDC_STACK_INIT (SELF,YDSTACK_DATA, KBLOCK, KGPBLKS)

TYPE (FXTRAN_ACDC_STACK) :: SELF
TYPE (FXTRAN_ACDC_STACK_DATA), INTENT (IN) :: YDSTACK_DATA
INTEGER, INTENT (IN) :: KBLOCK, KGPBLKS

INTEGER (KIND=JPIA) :: IBASE4, IBASE8

INTEGER (KIND=JPIA) :: MALIGN, P, K
MALIGN (P, K) = ((P+K-1)/K) * K

IBASE4 = 0
IBASE8 = 0

SELF%L4 =   IBASE4 + LOC (YDSTACK_DATA%ZDATA4 (1,1,1,1)) + ((INT (KBLOCK, 8) - 1)    &
        * (SIZE (YDSTACK_DATA%ZDATA4,KIND=8) * KIND (YDSTACK_DATA%ZDATA4) - IBASE4)) &
        / INT (KGPBLKS, 8)
SELF%U4 =   IBASE4 + LOC (YDSTACK_DATA%ZDATA4 (1,1,1,1)) + ((INT (KBLOCK, 8)    )    &
        * (SIZE (YDSTACK_DATA%ZDATA4,KIND=8) * KIND (YDSTACK_DATA%ZDATA4) - IBASE4)) &
        / INT (KGPBLKS, 8)

SELF%L8 =   IBASE8 + LOC (YDSTACK_DATA%ZDATA8 (1,1,1,1)) + ((INT (KBLOCK, 8) - 1)    &
        * (SIZE (YDSTACK_DATA%ZDATA8,KIND=8) * KIND (YDSTACK_DATA%ZDATA8) - IBASE8)) &
        / INT (KGPBLKS, 8)
SELF%U8 =   IBASE8 + LOC (YDSTACK_DATA%ZDATA8 (1,1,1,1)) + ((INT (KBLOCK, 8)    )    &
        * (SIZE (YDSTACK_DATA%ZDATA8,KIND=8) * KIND (YDSTACK_DATA%ZDATA8) - IBASE8)) &
        / INT (KGPBLKS, 8)

SELF%L4 = MALIGN(SELF%L4, YDSTACK_DATA%IALIGN)
SELF%L8 = MALIGN(SELF%L8, YDSTACK_DATA%IALIGN)

END SUBROUTINE

END MODULE

