PROGRAM MAIN_ACDRAG  

USE FXTRAN_ACDC_STACK_MOD

IMPLICIT NONE
#include "acdrag_manyblocks.intfb.h"

REAL(KIND=8), DIMENSION(16, 70, 435) :: ZZDELP
REAL(KIND=8), DIMENSION(16, 70, 435) :: ZZRDELP

INTEGER :: NPROMA, NGPBLKS,KLEV,KLON
INTEGER :: KIDIA,KFDIA,KTDIA
TYPE(FXTRAN_ACDC_STACK) :: YLSTACK
INTEGER :: ISIZE4, ISIZE8

NPROMA=16
NGPBLKS=435
ISIZE4=200
ISIZE8=200
KTDIA=1
KLEV=70
KIDIA=1
KFDIA=16
KLON=16

CALL RANDOM_NUMBER(ZZDELP)
CALL RANDOM_NUMBER(ZZRDELP)

!$OMP TARGET DATA MAP(TOFROM: ZZDELP, ZZRDELP)

YFXTRAN_ACDC_STACK%IALIGN=8 
ALLOCATE(YFXTRAN_ACDC_STACK%ZDATA4(NPROMA,KLEV,ISIZE4,NGPBLKS))
ALLOCATE(YFXTRAN_ACDC_STACK%ZDATA8(NPROMA,KLEV,ISIZE8,NGPBLKS))

!$OMP TARGET ENTER DATA MAP(TO:YFXTRAN_ACDC_STACK,YFXTRAN_ACDC_STACK%ZDATA4,YFXTRAN_ACDC_STACK%ZDATA8)  

CALL ACDRAG_MANYBLOCKS(KIDIA,KFDIA,KLON,KTDIA,KLEV,&
      & ZZDELP, ZZRDELP,KGPBLKS=NGPBLKS)

!$OMP END TARGET DATA

END PROGRAM MAIN_ACDRAG
